### ISSUE TITLE
Error running "dotnet test" when "Microsoft.AspNetCore.Mvc" 1.1.0-preview1-final is included in dependencies

### ISSUE THREAD

**Issue by hbiarge** [xunit/xunit#1015]
Running dotnet test in a new net core class library with this project.json:

    {
      "version": "1.0.0-*",
      "testRunner": "xunit",
      "dependencies": {
        "dotnet-test-xunit": "2.2.0-preview2-build1029",
        "Microsoft.AspNetCore.Mvc": "1.1.0-preview1-final",
        "xunit": "2.2.0-beta3-build3402"
      },
      "frameworks": {
        "netcoreapp1.1": {
          "dependencies": {
            "Microsoft.NETCore.App": {
              "type": "platform",
              "version": "1.1.0-preview1-001100-00"
            }
          },
        "imports": [
           "dnxcore50",
           "portable-net45+win8"
        ]
      }
     }
    }

throws this error:

    Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
       at Xunit.Runner.DotNet.Program.GetAvailableRunnerReporters()
       at Xunit.Runner.DotNet.Program.Run(String[] args)
       at Xunit.Runner.DotNet.Program.Main(String[] args)

When you change the version of the "Microsoft.AspNetCore.Mvc" package to version 1.0.1 it works as expected again.

**Comment by tristal** [comment]
I fixed this by explicitly adding `"Microsoft.DotNet.InternalAbstractions": "1.0.0",` to my test projects `project.json`.

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable"
  },
  "dependencies": {
    "System.Runtime.Serialization.Primitives": "4.3.0-preview1-24530-04",
    "xunit": "2.2.0-beta3-build3402",
    "dotnet-test-xunit": "2.2.0-preview2-build1029",
    "Microsoft.AspNetCore.TestHost": "1.1.0-preview1-final",
    "Microsoft.DotNet.InternalAbstractions": "1.0.0",
    "My.Project": {
      "target": "project"
    }
  },
  "testRunner": "xunit",
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0-preview1-001100-00"
        }
      },
      "imports": [
        "dotnet5.4",
        "portable-net451+win8"
      ]
    }
  }
}
```

**Comment by MaximPopov** [comment]
I had a similar issue after adding "Microsoft.AspNetCore.SignalR.Server" package with version 0.2.0-preview2-22683 to my project. The problem is that "Microsoft.DotNet.InternalAbstractions" package is restored indirectly because "Microsoft.DotNet.DependencyModel" package version 1.0.0 depends on it. However, preview versions of "Microsoft.AspNetCore.Mvc" and "Microsoft.AspNetCore.SignalR.Server" packages (indirectly) depend on the newer "Microsoft.DotNet.DependencyModel" version (1.1.0) which doesn't depend on "Microsoft.DotNet.InternalAbstractions" anymore.

It seems like "Microsoft.DotNet.InternalAbstractions" package should be specified as a direct dependency in "dotnet-test-xunit" package metadata.

**Comment by hbiarge** [comment]
Ok @bradwilson so the recommended solution is reference the package `"Microsoft.DotNet.InternalAbstractions": "1.0.0"` for `project.json` projects and wait to VS 2017 and MsBuild tooling?

**Comment by bradwilson** [comment]
If that's what works... We have no intention of officially supporting Preview 2.1 tooling, because we're finished with `project.json`.
