### ISSUE TITLE
Where is xUnit API reference / in detail documentation? (it is question, not Issue)

### ISSUE THREAD

**Issue by ramin-rp** [xunit/xunit#1018]
Hello,
I like xUnit, but i can't find good documentation for it.
Where is API reference or detailed documentation for your library?

**Comment by newprint** [comment]
Unfortunately, it looks like there is no official API nor official documentation apart from what you can find on main page. 
I am forced to use samples in the repo + google.

**Comment by metasequoia** [comment]
+1

**Comment by bradwilson** [comment]
There is a documentation site: https://xunit.github.io/

However, there is no API documentation there. We ship the XML documentation in the ZIP file for Intellisense, but thus far have not worked on a system to automatically generate HTML from that XML.

**Comment by Neutrino-Sunset** [comment]
Not even a quickstart describing the concurrency, or setup/teardown semantics!

Worst. documentation. ever.

**Comment by bradwilson** [comment]
@neutrino-sunset Thank you for the constructive feedback.

FYI, both topics are already documented:
https://xunit.github.io/docs/shared-context.html
https://xunit.github.io/docs/running-tests-in-parallel.html

If you have any improvements to offer, we accept pull requests.

**Comment by cchamberlain** [comment]
Appreciate this project pushes good code styles over stale documentation. That being said, it would lower the bar to entry to have "the basics" documented in the documentation area of https://xunit.github.io.

If I get some time soon, will send a PR.

**Comment by borgdylan** [comment]
@bradwilson I'd recommend using monodoc to turn the xml doc file into something browsable.

**Comment by borgdylan** [comment]
For whoever has mono and therefor the ```mdoc``` command installed use the following (example for the asserts library)
```
mdoc update -i *.xml -o docs xunit.assert.dll
mdoc export-html -o docs-html docs
```

Open the ```index.html``` file inside the ```docs-html``` folder using your preferred browser.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by mishal153** [comment]
their tests may help understand/find the needed info. accuracy guaranteed

**Comment by maxalmonte14** [comment]
I think closing the issue is not the right solution but working on the problem. The xUnit documentation is really poor, and taking into account that this is the most used .NET testing framework it shouldn't be that way!

If we look at [PHPUnit documentation](https://phpunit.readthedocs.io/en/7.4/) for example, we find a lot of useful information, even a detailed list of every assertion available!

**Comment by bradwilson** [comment]
@maxalmonte14 In addition to being closed for age, it should also have been closed as being non-actionable. Issues need to be opened for specific, discrete bugs or tasks. "Please make X better" is too open ended to be usable.

As mentioned above, we welcome specific issues as well as PRs to improve the documentation (the docs site is [on Github](https://github.com/xunit/xunit.github.io/) as well).

**Comment by canterberry** [comment]
Not to sound too snarky here, but I think what we're all asking for is documentation that reveals the answer to the following fundamental question:

> :question: When I add the line `using Xunit;` to my code, what becomes available to me?

Such a document goes by many names: API Reference, Class Reference, or most libraries just call it "the docs", or the proverbial object of many an "RTFM" response.

**Examples:**
 * [.NET Core](https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-2.2)
 * [Mono](http://docs.go-mono.com/?link=N%3aSystem.Data)

I'm trying to learn about Xunit and to understand what `Assert` looks like. Rather than trial-and-error and inspecting oodles of "sample code" that exercise various portions of what it might do, trying to use it as if it were [MSTest's `Assert` class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.assert?view=mstest-net-1.2.0), I'd much rather just look at a document that illustrates "Here's what `Assert` does".

In the meantime, for others who find themselves here as the top Google search result for "Xunit API Reference", your best bet is to read through the Xunit source code itself. For convenience, here's what I think may be the implementation for [`Assert`](https://github.com/xunit/assert.xunit/blob/db11c08977f1ecf9b868317073d4255560547c45/Assert.cs).

**Comment by bradwilson** [comment]
The API documentation is contained in the XML doc comments (which ship with the library). They are surfaced via Intellisense.

Since this is not a convenient form for browsing, there is an open issue to get the API documentation added to the web site: https://github.com/xunit/xunit/issues/1902

**Comment by geronimus** [comment]
Will dive into the xml, since it seems to be the only docs the project is willing to provide.

However, please consider that many developers use vim, emacs, and other editors that don't implement Intellisense. We don't rely on Intellisense because we believe a good testing framework will catch any typos. So Intellisense shouldn't be necessary!

We crave simplicity in a complex world. We need programs to just be text files!

**Comment by tohagan** [comment]
Very disappointed to discover XUnit assertion docs are non-existent.   All it takes is a brief one line per method to  improve the situation.  Tempts me to port my old NUnit wrapper over to XUnit to fix this. See how easy it is ... 

- https://github.com/tohagan/ShouldBe#assertion-methods

**Comment by tohagan** [comment]
https://fluentassertions.com/ solves my problem.  Fully documented with support for xUnit.

**Comment by 18549** [comment]
> 
> 
> https://fluentassertions.com/ solves my problem. This solves the problem by wrapping the xUnit assertion API with BDD assertions that are fully documented and much nicer to use.

Any API promoting 10 deep dotted method chaining and classes with properties called 'And' needs burning. What kind of OOP is that supposed to be?

**Comment by bartelink** [comment]
As long as this nonsense doesn't make it into the core library and turn it from something with xmldoc into something needing a Friendly Manual or a 20 page README.me, it's all good ;)

**Comment by bradwilson** [comment]
>turn it from something with xmldoc into something needing a Friendly Manual or a 20 page README.me

We accept PRs for https://github.com/xunit/xunit.github.io

**Comment by krischik** [comment]
> been closed as being non-actionable.

It's absolutely actionable: **write better documentation.**

> The API documentation is contained in the XML doc comments

Which is useless without samples and explanation. Have a look at the Android documentation. That too is just JavaDoc documentation inside the code.

But it has examples, pictures, explanations. The Android documentation is useful.

**Comment by bartelink** [comment]
The Android documentation has the backing of a large number of full time devs and tech writers

and :fire: I bet they have a 1% less entitled user community that will 2% more frequently bring the change they seek

**Comment by bradwilson** [comment]
@krischick I will refer you to the post immediately above yours: we accept PRs.

**Comment by Ruud-cb** [comment]
Was pretty excited about xUnit to try since [this stackoverflow answer](https://stackoverflow.com/a/40220724/2901207) gave some good points, yet now discovering that xUnit doesn't even tell you how to do simple things is just... sad.

Let's not even go into details about more 'advanced' (while still being very much basic) on how to do things like fakes/mocking? "Use Moq for that" or anything similar to give developers an smooth ride is lacking, for more then 3 years already!

**Comment by bartelink** [comment]
@Ruud-cb you can be the change you wish to see and be a part of making these things happen. While the feedback is not entirely useless, it adds up to kicking sand in faces and running off in the end from where I'm sitting.

Ultimately the maintainers + (generally very limited) community around a project have hard choices to make in terms of how to balance the use of their time on open source projects (remember, this stuff does not pay bills - its a labour of love and a gift).

As a 11 year+ user of xUnit, I deeply appreciate Brad's (and Jim, but really Brad :D) demonstrated commitment to making the hard choices of how to best invest their finite time, and the courage to say no to doing anything half-assed (i.e. saying no to adding some features, not straying into providing guidance on subjective matters around testing).

**Comment by mikek65** [comment]
I went to the GitHub site referenced above and it says the repo has been archived and is read-only.  Does that mean PR's are not still accepted?  I'm also needing documentation but am willing to contribute as time allows, if I can.

**Comment by patrickbucher** [comment]
No official API doc? Seriously? I'm trying to get into TDD with C#, which is one of the most frustrating endeavors I've ever tried.

**Comment by tohagan** [comment]
> No official API doc? Seriously? I'm trying to get into TDD with C#, which is one of the most frustrating endeavors I've ever tried.

Checkout https://fluentassertions.com/ that wrappers xUnit.  Nice docs.

**Comment by NilsFantastic** [comment]
> No official API doc? Seriously? I'm trying to get into TDD with C#, which is one of the most frustrating endeavors I've ever tried.

I'm just going to answer this for future googlers: 

There is no online documentation but there are documentation in the source code of xUnit itself. 

You can see it by either:
1. Looking in the auto-complete for each specific function in visual studio
2. Decompiling the assert class and looking directly at the comments
3. Using a doc generator as discussed in this [stack over flow thread](https://stackoverflow.com/questions/9631980/c-doc-viewer-for-visualstudio)

This may be obvious to some people but It needs to be pointed out in this thread.

**Comment by 0bviouSquirre1** [comment]
As a brand-new user to xUnit, I don't have the experience or knowledge necessary to contribute anything yet, in large part because I cannot find any kind of documentation that could help get me to a place where I could make a contribution.

Having to install Yet Another Thing I Don't Understand (fluent assertions) just to make the Thing I Barely Understand somewhat usable is an incredibly daunting prospect for the newbie.

I just want to know why Assert.IsType<Player>(player) doesn't return true when I've literally just instantiated a Player object. Is this a Moq problem? I don't know, it's Yet Another Thing I Barely Understand that I've installed in the hopes that this stuff will Just Work one day.

If you want more contributions, it needs to be possible for new people to get spun up enough to contribute anything.

**Comment by bartelink** [comment]
re ☝️☝️

>You can see it by either: 

I would add

4. clone the repo and load the solution - there is no need to go decompiling things or using doc generators - use an IDE to navigate.

@0bviouSquirre1 

>I just want to know why Assert.IsType(player) doesn't return true when I've literally just instantiated a Player object. Is this a Moq problem? I don't know, it's Yet Another Thing I Barely Understand that I've installed in the hopes that this stuff will Just Work one day.

Taking a stab:

`Assert.IsType<T>` checks whether the type can be cast to the specified type. It's intended for use when checking an unknown `object`. It happens to return the dowcasted value for you to do further assertions on as desired.

If it cannot be downcast, it will have thrown already. It's possible that you are testing the `Mock<T>` holder/builder rather than the actual Mock Object - i.e. maybe you should be doing `Assert.IsType<X>(mockX.Object)` ?

_While some people watch this repo, the bottom line is that the Issues are for confirmed problems that are going to be solved in some clear way. Figuring out how to use it etc is best done either in the Discussions, or on Stackoverflow.com - there are way more people there. In both cases, it would be helpful to show what you are doing so people can get you unstuck quickly without having to guess what you are doing and what you've tried._

And you absolutely don't need Fluent Assertions. The built in ones are not fluent. You can argue that some things are missing, but in general that's by design - the intentional lack of corner case features in xUnit.net is absolutely a feature.

(Fluent assertions and the like obviously have plenty followers, and plenty positives; just flagging the fact that many people intentionally use the built in `Xunit` ones despite being aware of and having tried other assertion libraries)

**Comment by 0bviouSquirre1** [comment]
Wow, thank you! That was incredibly clear and helpful.

I only posted here to show support for the idea that this documentation is sorely needed, with my minor issue as an example. I wasn't expecting to receive actual help. I genuinely appreciate it.

**Comment by bradwilson** [comment]
>I just want to know why Assert.IsType(player) doesn't return true when I've literally just instantiated a Player object. Is this a Moq problem?

The answer is both "yes" and "no". 😁 

The Intellisense for `Assert.IsType` says this:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/16944/193898870-8891d4b3-ccc4-46e2-8cd8-fc351e04e736.png">

So this assertion is checking for _exact type_, not _compatible type_; the latter is handled by `Assert.IsAssignableFrom`:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/16944/193900910-25155bd7-381e-438c-b64a-ff9d8c55a9e8.png">

So why is this a Moq "problem"? Off the top of my head, there a couple ways it could go sideways:

1. You might have a `Mock<Player>` (which is not a `Player`)

If this is the case, as @bartelink notes above, calling `.Object` on the `Mock<Player>` will give you the instance of the mocked `Player` object. However, this puts you into the second situation:

2. The implementation of how mocking generally works is that it creates something that _derives_ from `Player` so that it can override the virtual methods.

`Assert.IsType` is wrong, because you don't have an object of _exactly_ the `Player` type, you have one that's derived from `Player`, so `Assert.IsAssignableFrom` is the right choice.

> I cannot find any kind of documentation that could help get me to a place where I could make a contribution

There is a project site at https://xunit.net/ with some documentation, but it currently does not contain the documentation that you see with Intellisense (that's only available in a compatible editor like Visual Studio or VS Code). There is an open issue for this: https://github.com/xunit/xunit/issues/1902

**Comment by davidcian** [comment]
Leaving my 2 cents here: yes, I can read the source code, and I am sometimes forced to do so. It's not convenient though, and I like to avoid doing this when I can. Adding documentation is what I would call very low-hanging fruit: a little would go a very long way.

Here's the main reason: sure, if I want to know how something works, I'll go read the source code. Question is, how do I figure out what is available and how to do things? Read through the entire source code? That is an utterly undefendable position.

Who should add the doc and whether doc should be added are also two very different issues: the dev team's position is rather confusing with respect to these two issues.

**Comment by bradwilson** [comment]
@davidcian As ever, we would gladly accept PRs to address this.

**Comment by fmelink** [comment]
This is still not fixed.

**Comment by sin-ack** [comment]
Here's my experience with the xUnit website as someone who has previously used frameworks like Pytest and is trying to learn how to do testing in .NET.

1. I open the xUnit website.
2. I look at the "Getting Started" section to orient myself on what things are called:
  - "Getting started with the .NET SDK command line" -> OK, that's cool I guess. Very basic (Fact, Theorem) and most of it is just IDE setup.
  - "Migrating from xUnit.net v2 for unit test authors and extensibility authors" -> I don't care about this, I've never used xUnit v2.
  - "What’s new in xUnit.net v3" -> Why should I care about this? I just learned of xUnit's existence.
  - "Microsoft Testing Platform support in v3" -> What is "Microsoft Testing Platform"? Why is this relevant to me as a new user trying to get started?
  - "Code Coverage with Microsoft Testing Platform" -> OK, cool, but I need to be able to write tests before I can check coverage.
  - "Query Filter Language" -> Very obtuse name for something that can just be called "Filtering tests".
  - "Serialization with IXunitSerializer and IXunitSerializable" -> Serializing what? Clicking on the link reveals it's for theory data (PBT/fixtures) but the link itself just adds more confusion.
  - "Writing a custom Runner Reporter for xUnit.net v3" -> How does this help me as a new user?
  - "NuGet packages for xUnit.v3" -> This one's fine I suppose, telling me what I else I should look into.

I can't find any information about:
- What assertions are available to me.
- How to do setup and teardown.

Which are the two most basic bits of information I need to be able to write tests.

Compare this to the homepage of Pytest:

- Immediate example of how to run stuff provided.
- Direct link below the example about how to write assertions.
- "Modular fixtures for managing small or parametrized long-lived test resources" -> Even if I don't know what the terminology means, it explains it to me so I know what I should click on.
- Link to how-to guides to do specific things.

I only learned that "Sharing context between tests" is what I want by reading this issue!

If you want something actionable, here it is: Please make the first links in the documentation things that are actually relevant to people who are *new* to the testing framework, so they can get started. None of the migration stuff is relevant to new users. There should definitely be links for the migration stuff too but having it be the second link in the "Getting Started" section is unhelpful.

**Comment by bradwilson** [comment]
@sin-ack Thanks for this feedback. The website is on the list for a long overdue restructuring (necessitated in part by including the API documentation).

**Comment by dadaPipes** [comment]
@bradwilson 

I read somewhere that you want to document multiple versions.

Given that .NET Framework 4.5 is quite outdated and no longer supported (support ended in January 2016), it would make more sense to focus on more recent and supported versions of the xUnit framework. 
I encountered issues with version v2-2.0 due to its reliance on this outdated framework.

How far back would you like the documentation to cover?

https://stackoverflow.com/questions/73648702/install-net-framework-4-5-targeting-pack

**Comment by bradwilson** [comment]
Multiple versions of xUnit.net, not multiple versions of .NET Framework. 😄 

I'm planning to start with just API version for released v3 binaries. Off the top of my head I think that includes `xunit.v3.assert.dll`, `xunit.v3.common.dll`, `xunit.v3.core.dll`, `xunit.v3.runner.common.dll`, and `xunit.v3.runner.utility.dll`.

**Comment by dadaPipes** [comment]
My bad. In my head it made sense 😄

I tried to document as far back as v2-2.0, but I ran in to some trouble, by not having installed .NET Framework 4.5. Then I saw the stackoverflow post, and thought that it would be overkill to document that far back.

Who is the documentation targeting ?
`assert` and `core` looks that they contain the things, that people have been asking for, **Asserts** and **Attributes** that is. If I'm not all wrong..

**Comment by dadaPipes** [comment]
@bradwilson 

[](https://github.com/[dadaPipes/Xunit-Proto](https://github.com/dadaPipes/Xunit-Proto))

It's possible to group Asserts under a 'fake' namespace so it is easier to navigate.
Same thing with other classes, but I am not so familiar with the source code and how it is best grouped.

The namespaces does not seem so important to document, given there are so few of them. What also makes it a pain to document in an easy way.

Anyways, this is my first take on the documentation.
Versioning should be possible, as you can see in 'v2' in the heading. But there are some issues when it comes to the generated metadata. I will file a bug report about it.

Reminder to myself:
post processor, append a XML template where there are no code examples.

Any particular way you want the classes to be grouped ?

**Comment by matushorvath** [comment]
It's pretty absurd to read this lengthy discussion where people argue whether having no API documentation for the most used .NET unit test framework is OK or not.
