### ISSUE TITLE
Trait attributes do  not end up as TestCategory elements in test results

### ISSUE THREAD

**Issue by hkoestin** [xunit/xunit#1052]
Hello,

I try to achieve something like the following: on test methods, I would like to specify traits, which reflect e.g. the test-case number on TFS, which this unit test is "implementing". When I then run and execute the tests on TFS, I would like to have the .TRX file reflecting these specified traits as TestCategory elements, to be able to display this column in VS test results or on TFS. However, these attributes are not transformed/mapped to the TRX file.

When I have MSTest unit tests in my tests, the TestCategory attribute becomes mapped into the TRX result file and later on can be displayed like the following:
![image](https://cloud.githubusercontent.com/assets/13849875/21174160/ca294636-c1db-11e6-8b40-da78f99a6e7d.png)

In the TRX file, the corresponding section can be found in the <TestDefinitions> section of the XML.
![image](https://cloud.githubusercontent.com/assets/13849875/21174188/f889adae-c1db-11e6-9bcf-60ac113a00d1.png)

After reading the following post on the ALM blog, I actually assumed, that the xUnit Trait attribute becomes mapped to the TestCategory attribute of MSTest and then is also available in the TRX file.
See: https://blogs.msdn.microsoft.com/visualstudioalm/2013/06/11/part-3-unit-testing-with-traits-and-code-coverage-in-visual-studio-2012-using-the-tfs-build-and-the-new-nuget-adapter-approach/
![image](https://cloud.githubusercontent.com/assets/13849875/21174252/4d02e36e-c1dc-11e6-8d53-75c04b658d14.png)

As it seems, this is not done. I checked some of the code of the test adapter of xUnit, but have not found anything, which would map the trait to a test-category item. Is this correct?

What I have tried/done so far:

The test case with the traits on it (just tried different ones to see, if it is working for some of them):
![image](https://cloud.githubusercontent.com/assets/13849875/21149393/a307a244-c15b-11e6-8eb9-8c5a236a4c23.png)

When I execute the tests using vstest on TFS, I get a TRX file afterwards, which I publish to the test results. This file however does not include any of the traits.

Is this as designed or is this simply missing the mapping?
Or am I missing some things?

Strangely enough, even though I followed your steps of how to run tests and upload results in TFS (see https://xunit.github.io/docs/getting-test-results-in-vsts.html), I do not see the xUnit Test Adapter to be chosen in the TRX file:

![image](https://cloud.githubusercontent.com/assets/13849875/21174350/eeab9bfc-c1dc-11e6-95d5-28f75baf1751.png)

On the build output of TFS I see xUnit.net taking over the execution:
![image](https://cloud.githubusercontent.com/assets/13849875/21174417/46728954-c1dd-11e6-8bdd-5577bd5af1a8.png)

Can somebody probably explain to me, what is happening here?

Thanks for any help regarding this!

Best regards,
Harald

**Comment by hkoestin** [comment]
By the way: I just found a nice post about "Traceability with Continuous Testing" on TFS 2017 and VSTS.
This would actually be something like I would like to achieve as well, but just not upgrading to TFS 2017 now.
https://blogs.msdn.microsoft.com/visualstudioalm/2016/08/02/traceability-with-continuous-testing/

**Comment by bradwilson** [comment]
I'm pretty sure their docs are wrong, and you should use `[Trait("TestCategory", "...")]`.

**Comment by hkoestin** [comment]
I am afraid, but it is not working with the "TestCategory" string either.

I applied the following attributes now to my test, and none of them end up in the TRX file.
![image](https://cloud.githubusercontent.com/assets/13849875/21216422/04456efa-c2a7-11e6-9df9-f7c2697de6a9.png)

In addition, I still have the MSTest Unit Test Adapter specified in the TRX file:
`adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter"`

However, on the test run itself on TFS, I can see the following command line arguments:
`/TestAdapterPath:"D:\TfsData\Build\DefaultAgent\_work\12\s\packages\xunit.runner.visualstudio.2.1.0\build\_common"`

I am using version 2.1.0.3179 of xunit.core. Does it work with this version?

**Comment by bradwilson** [comment]
I'm afraid you're going to have to ask the Visual Studio team what's needed. We push all traits to them through the API. It sounds like perhaps something is broken on their end.

**Comment by bradwilson** [comment]
Oops, wrong button. :-p

**Comment by hkoestin** [comment]
Thanks for the information.
Do you probably know where to forward this issue to?

Don't think that any of the dotnetcore projects on github is related to
this.

**Comment by bradwilson** [comment]
https://connect.microsoft.com/visualstudio

**Comment by hkoestin** [comment]
Short heads-up:
There is now the following thread on the MSDN forum: https://social.msdn.microsoft.com/Forums/vstudio/en-US/e5f85cb7-e003-4207-a8f0-31a2bfd09e9a

Also a related user-voices suggestion has been filed:
https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/17508760-vstest-console-not-support-add-attribute-of-xunit

**Comment by alexlazarciuc** [comment]
Hey guys,

Apologies for asking this here, but maybe you can help, although is not exactly the same topic..

When using Nunit you can specify to input some data in the XML when you run the tests, something like: TestContext.CurrentContext.Test.Properties.Add("Property", "Value");

Now, in Xunit, instead of properties we have traits. Is there something similar I can do and control which traits I want to add? Not the ones which are added automatically based on the tags I'm using in the feature files. For example, I'm taking a screenshot of a failed test, and I want to save the path of that screenshot in the xml, in order to parse it later. I'd like to add that path into a property / trait = value.

Hopefully you can give me some feedback on how to do it.. as I've spent almost 1 day to solve this.. The only success I had, was with ITestOutputHelper, but as I've said I'd like to add them in traits. :(

Thanks in advance,
Alex.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by akshaybheda** [comment]
Is it Fixed? I am still getting issues when running with adapter as well. I don't get Traits in the log file

**Comment by alexlazarciuc** [comment]
@akshaybheda not sure in fairness. Last time I've tried to use it it did not worked, so I switched xUnit to Nunit.

**Comment by hkoestin** [comment]
It seems that there is not much work done on this - frankly said none.
Since I could solve it on a different way now, I stayed with xUnit,
although I was also playing around with NUnit recently and love the new
features there. MSTest v2 does look promising too.

Am Do., 20. Dez. 2018 um 07:19 Uhr schrieb Alex Lazarciuc <
notifications@github.com>:

**Comment by akshaybheda** [comment]
What workaround did you find?

**Comment by hkoestin** [comment]
@akshaybheda I do now use the traceability matrix feature from TFS in conjunction with a hand-made PS script, which parses some information and publishes to TFS using the REST API for the test management.

Not that nice, but working.
And since the test base is too much to change to a different framework now, I was willing to pay the price.

Nevertheless, a solution on the xUnit FX for this would still be nice and very much welcome.

**Comment by puttagunta** [comment]
Sorry, for missing something on the resolution of this issue. Why is this closed? Any plans to reopen this? Also, have not seen anyone from the contributors, commenting on https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/17508760-vstest-console-not-support-add-attribute-of-xunit. If this is not the forum to ask, please direct me to a right forum. This is very much needed for us.

**Comment by sstcvetkov** [comment]
Any news?
I need to add my Traits to test results.
I also discovered that "Description" doesn't work too.

**Comment by cjjohansen** [comment]
This works of me now. So I believe it has been fixed
`       [Fact]
        [Trait("TestCategory","DontRunThisDomain")]
        public void Test1()
        {
            Assert.True(false);
        }`

**Comment by IanKemp** [comment]
In Visual Studio 2022 the magic way to make this work is by using an empty string as the "name" parameter to the `TraitAttribute` constructor, i.e:

```
[Trait("", "your-test-category")]
```

**Comment by jpero** [comment]
I have run into this recently myself.  I have tried both `dotnet test` and `dotnet vstest`.  I do see my traits showing up in the logs when using `--diag output.log`

**Comment by johncrim** [comment]
The workarounds listed above ("TestCategory" or "" name) don't work, or didn't work for me.

A workaround for this issue is to use the xunit test result XML, instead of the vstest/trx XML. The [xunit XML format](https://xunit.net/docs/format-xml-v2) includes traits for each test.

To do this:
1. Add the [XunitXml.TestLogger](https://www.nuget.org/packages/XunitXml.TestLogger) nuget package to each of your test projects
2. Run your tests using the xunit logger, eg:
`dotnet test --logger xunit`
or
`dotnet vstest ... /logger:xunit`

So, that give you traits in the output, it's just a different format that your test result reporting tool needs to handle.

FWIW the [Azure Pipelines PublishTestResults Task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2) publishes test results in this xunit format (yaaay!), but it doesn't display traits (boooo!).

**Comment by johncrim** [comment]
Hi @bradwilson  - in fact, trait key `"Category"` is what I went with, and it doesn't show up as a Tag in the Azure Pipelines test results UI. It looks like if I wrote my own `PublishTestResults`-like task I could use the REST API to set tags for tests, but so far this isn't important enough to me to justify that effort. Plus we'd like to migrate to Github actions, so that reduces the effort I'm willing to expend on an Azure Pipelines task.

I appreciate the suggestion.

Are you familiar with [CTRF - Common Test Report Format](https://ctrf.io/docs/intro)? It looks like a new (new to me) open-source effort at an all-language test result/report format. (Also [an XKCD punchline](https://xkcd.com/927))

It has xunit support, but it looks minimal at this point. The schema has tags (traits/key+value would be better, but better than nothing). If I put any effort into this, I think it would make sense to add trait support to their xunit reporter, and make it a direct logger from xunit instead of "log to trx, then translate trx to CTRF". Then any test result tooling UI written for CTRF would presumably work (there's something for Github Actions).

**Comment by bradwilson** [comment]
> Any thoughts on that?

I'll take a look. It's probably not too tough to get an additional output format supported here. We currently use XSL-T for our report generation, so generating JSON isn't a purely good fit, but I can look at see whether it will work as-is or whether it will require an additional reporter formatting path.
