### ISSUE TITLE
xunit.runner.visualstudio 2.2.0-beta5-build1225 does not set current directory for debugging tests

### ISSUE THREAD

**Issue by chuckries** [xunit/xunit#1093]
Using Visual Studio 2017 RC with .NET Core.

1. File -> New Project -> .NET Core -> xUnit Text Project (.NET Core)
2. Copy the following code into UnitTest1.cs:
```cs
    public class UnitTest1
    {
        private readonly ITestOutputHelper _output;

        public UnitTest1(ITestOutputHelper output)
        {
            _output = output;
        }

        [Fact]
        public void Test1()
        {
            _output.WriteLine(Directory.GetCurrentDirectory());
        }
    }
```

3. Run the test and view output.
4. Debug the test and view output.

Expected: output and thus current directory are the same in both cases: the output directory for my test project

Actual: When debugging the test the current directory is a VS directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE

**Comment by onovotny** [comment]
Is this in the VS Test Explorer, cmd line or both?

**Comment by chuckries** [comment]
I was doing this via VS Test Explorer. As for command line, I don't know how to "debug the test" from the cli.

**Comment by bradwilson** [comment]
Setting the current directory is something we only do for desktop class library projects, because that functionality is not available in .NET Standard 1.1, as you can see in the image below.

https://github.com/xunit/xunit/blob/c91337c958bb68b63e6df23d159dbc090d48ead2/src/xunit.execution/Sdk/Frameworks/Runners/TestAssemblyRunner.cs#L187-L189

This at this moment, this is a "won't fix" situation.

![Directory class](https://cloud.githubusercontent.com/assets/16944/22858833/ac537480-f07d-11e6-8908-5730d99123cc.png)

**Comment by natemcmaster** [comment]
Related? https://github.com/microsoft/vstest/issues/311

**Comment by bradwilson** [comment]
@natemcmaster I don't think so.

**Comment by bradwilson** [comment]
Closed for age.
