### ISSUE TITLE
TheoryDiscoverer.CreateTestCasesForSkip does not always serialize 'skipReason'

### ISSUE THREAD

**Issue by natemcmaster** [xunit/xunit#1118]
We have a custom implementation of TheoryDiscoverer that calls TheoryDiscoverer.CreateTestCasesForSkip.
This method takes a final argument `string skipReason)`. This method is not passed down in the `XunitTestCase` instance.

https://github.com/xunit/xunit/blob/976289ebf4b0899ca4fbf6d034e1a8c74bad782c/src/xunit.execution/Sdk/Frameworks/TheoryDiscoverer.cs#L52-L53

This means the skip reason is lost during serialization/deserialization.

**Comment by bradwilson** [comment]
That's true, because `XunitTestCase` does not take skip reason as a parameter (it always gets it from the `[Fact]` attribute).

You should make your own test case which derives from `XunitTestCase`, and override `GetSkipReason`. The extensibility point there allows you make your own custom test case and pass the skip reason along.

**Comment by bradwilson** [comment]
This sample should help: https://github.com/xunit/samples.xunit/tree/master/DynamicSkipExample

**Comment by natemcmaster** [comment]
That's what we ended up doing. Any reason you wouldn't want to modify XunitTestCase to allow a skipreason in the constructor?

**Comment by bradwilson** [comment]
Closed for age.
