### ISSUE TITLE
Separate "Facts" in another DLL

### ISSUE THREAD

**Issue by juniorgasparotto** [xunit/xunit#1171]
Hello

I am trying to separate my "Facts" into a separate DLL from my test project, but the Visual Studio Do not recognize this project, is this possible?

The idea is to generate two test projects to test DOTNETCORE and another project with DOTNET45.

**Comment by bradwilson** [comment]
Since you're talking about .NET Core, my best recommendation is to start with the .NET Core unit test project template, then convert it to multi-targeting in your .csproj (that is, change `<TargetFramework>netcoreapp1.0</TargetFramework>` to `<TargetFrameworks>net452;netcoreapp1.0</TargetFrameworks>`). (Important: Note that it's plural, TargetFrameworks)

**Comment by juniorgasparotto** [comment]
I've tried this, but VisualStudio always chooses the netcoreapp1.1 target and bypasses the net45, is it possible for it to test on both?

**Comment by bradwilson** [comment]
The command line will run both. Visual Studio's UI will only run the first one. Unfortunately, this is a limitation of the VS UI (and has nothing to do with xUnit.net; it's the same thing with NUnit and MSTest). ☹️

**Comment by juniorgasparotto** [comment]
Got it,

Thank you very much for the answers.

[]s
