### ISSUE TITLE
error CS0017: Program has more than one entry point defined.

### ISSUE THREAD

**Issue by NotMyself** [xunit/xunit#1172]
I have a small single project console app called [DotNetCoreKoans](https://github.com/NotMyself/DotNetCoreKoans). It has embedded xunit tests in the project. After running `dotnet migrate` I can no longer build the project. I get the following error:

```
Engine\Program.cs(8,27,8,31): error CS0017: Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point.
```
Incase it is not clear what my project looks like here is a screenshot showing the test location and my program.cs where my main method is.

![image](https://cloud.githubusercontent.com/assets/73120/24086241/3e000648-0cc9-11e7-96f2-4e9ef41c4cad.png)

**Comment by onovotny** [comment]
.NET Core test projects are exe's. They just provide the main method for you... You might be able to add `<OutputType>Exe</OutputType>` but I'm not sure that'll work....

**Comment by bradwilson** [comment]
That's a mandate right now from VSTest. I don't think it'll be required for `dotnet xunit`, but I can't make that guarantee yet.

**Comment by NotMyself** [comment]
Thanks @bradwilson I'll come up with something until that releases. @onovotny I submitted a bug to vstest. Really weird that they would inject a static void Main into a console application like that and just let it fail to build.

**Comment by NotMyself** [comment]
@bradwilson did you see the resolution to this over in Microsoft/vstest#636 ? Looks like there is a flag you can set in your csproj to disable this silly behavior.

**Comment by bradwilson** [comment]
I honestly have no idea why they did that in the first place. My work showed it to be completely unnecessary now (obviously, since you can provide your own entry point, you don't need theirs).

It used to be that a unit test project in DNX had to be an executable, because of the architecture of that system (the runner was literally an entry point to the program, so that you can write your own Main and accept command line arguments). That hasn't been true since they changed to VSTest. It's possible that they're just doing it out of habit rather than any technical need.

**Comment by bradwilson** [comment]
There are [some things I'm injecting into the project](https://github.com/xunit/xunit/blob/5490508ff9ce3641ca1509c187046b136ae0c148/src/dotnet-xunit/Program.cs#L56-L66) to get it to generate the artifacts I need (with tons of nods to Nate McMaster who is like my guidebook for .NET Core). Maybe VSTest should take this strategy rather than flipping the project into an executable.

```xml
<Project>
  <PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <CopyNuGetImplementations>true</CopyNuGetImplementations>
    <DebugType Condition=""'$(TargetFrameworkIdentifier)' != '.NETCoreApp'"">Full</DebugType>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateDependencyFile>true</GenerateDependencyFile>
  </PropertyGroup>
</Project>
```

**Comment by bradwilson** [comment]
Closing this as external, because (a) there's a workaround, and (b) it's not our bug.

**Comment by Hassan-Ali123** [comment]
I also have this issue in a Window form project. Please help if someone can!

**Comment by bradwilson** [comment]
Please don't respond to closed issues. Open a new one, and provide a repro project (otherwise it'll be closed). Thanks!

**Comment by danielfedelesumg** [comment]
https://andrewlock.net/fixing-the-error-program-has-more-than-one-entry-point-defined-for-console-apps-containing-xunit-tests/

**Comment by danielfedelesumg** [comment]
> I also have this issue in a Window form project. Please help if someone can!

https://andrewlock.net/fixing-the-error-program-has-more-than-one-entry-point-defined-for-console-apps-containing-xunit-tests/
