### ISSUE TITLE
Documentation seems to be missing

### ISSUE THREAD

**Issue by EamonNerbonne** [xunit/xunit#118]
I've been trying to look up how to do data-driven testing, and I can't seem to find any documentation about xUnit's attributes and assertions anywhere on github.  There are a few links back to codeplex, but there doesn't seem to be an index there either, so if there are relevant pages there, I don't know how to find them; codeplex's doc homepage is just a pointer back to github.

I hope I'm not just being blind!  xUnit.net would be much easier to use if the docs were easy to find.

**Comment by cherrydev** [comment]
So, you seem to have accepted the fact that there isn't proper documentation for xUnit, but then immediately closed the issue.  I would argue that you might get more contributions to the documentation if you left this issue open.

**Comment by bradwilson** [comment]
I closed the issue because there is a _different_ place to contribute to the documentation, and provided a link here to that other place.

**Comment by cherrydev** [comment]
I completely understand what you're saying, and yet, there are a number of issues already on THIS issue tracker that are tagged "documentation".  The issue tracker on the github.io project is basically empty, perhaps indicating that that is not where users of xunit go to discuss documentation.

**Comment by bradwilson** [comment]
The documentation site is brand new.

**Comment by cherrydev** [comment]
Didn't realize that, okay.

**Comment by EamonNerbonne** [comment]
The new documentation site looks like a great start - if I come across anything I can easily fix, I'll be sure to make PR.  However, at the moment I'm not working on any xUnit-using projects (which is related to the fact that docs previously were hard to find), but that might change shortly :-).

**Comment by hVostt** [comment]
no documentation :(

**Comment by bradwilson** [comment]
@hVostt Do you have any constructive suggestions on what documentation you think is missing?

**Comment by Verequus** [comment]
I'd say, a Quick Start Guide and what features do exist in the first place and how to use them.  Finding Asserts merely, because you use intellisense, is not enough. People have complained about missing documentation for years and nothing seems to have been changed. The hurdle is so unnecessarily steep.

**Comment by bradwilson** [comment]
@Verequus Please open an PR with any documentation you'd like added to [the site](https://xunit.github.io/). https://github.com/xunit/xunit.github.io/

**Comment by Verequus** [comment]
PR = pull request? I'm not sure how this is supposed to work, since I have nothing created for you to merge. But if you want to know what I am missing, it is simple:

Which APIs exist?
How can they be used?
What is the intention of their use?

The examples lack simple detail. Even the lowly Assert doesn't include all possibilities, which pop up in the Intellisense.
