### ISSUE TITLE
xUnit's Unique ID can include a version string, rendering it inadequate for correlating test results over time

### ISSUE THREAD

**Issue by blfrantz** [xunit/xunit#1208]
We would like to be able to use xUnit's UniqueId to correlate results for the same test over time.  This is currently problematic due to the fact that the input to the UniqueId can contain assembly version information, which results in the UniqueId changing when it arguably shouldn't.

This is explained in the comment for the "Name" field in [IAssemblyInfo.cs](https://github.com/xunit/abstractions.xunit/blob/master/src/xunit.abstractions/Reflection/IAssemblyInfo.cs), which is used as an input to the hash generated by GetUniqueID() in [TestMethodTestCase.cs](https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/Frameworks/TestMethodTestCase.cs).

Is there a good reason for including the fully qualified name (which includes the version) in the hash, and if not, can we modify it to exclude this information to prevent unexpected revs of the UniqueId?

**Comment by gamercubed** [comment]
I've noticed another issue with xUnit's GetUniqueID() method - it doesn't include the method's Generic Types in the hash, causing it to produce the same UniqueId for different test cases.  I'd like to modify this method to fix these issues for our team, and then submit a pull request to get them into the mainline.  Ideally, I'd like to get my approach approved first so that if this does get included in a future release, there's a good chance its UniqueIds will match ours when we upgrade.

Here's what I have so far which seemed like a low-impact change that addresses both issues.  Please let me know if there's a better way (for one thing, could we remove TestMethod.Method.Name and TestMethodArguments from the stream since they're already part of DisplayName?):

[TestMethodTestCase.cs](https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/Frameworks/TestMethodTestCase.cs)
`        protected virtual string GetUniqueID()
        {
            using (var stream = new MemoryStream())
            {
                var assemblyName = TestMethod.TestClass.TestCollection.TestAssembly.Assembly.Name;

                //Get just the assembly name (without version info) when obtained by reflection
                IReflectionAssemblyInfo assembly = TestMethod.TestClass.TestCollection.TestAssembly.Assembly as IReflectionAssemblyInfo;
                if (assembly != null)
                {
                    assemblyName = assembly.Assembly.GetName().Name;
                }

                Write(stream, assemblyName);
                Write(stream, TestMethod.TestClass.Class.Name);
                Write(stream, TestMethod.Method.Name);

                if (TestMethodArguments != null)
                    Write(stream, SerializationHelper.Serialize(TestMethodArguments));

                Write(stream, DisplayName); // Largely duplicates most of the information above, but can contain additional information we want to capture (such as generic type names)

                stream.Position = 0;

                var hash = new byte[20];
                var data = stream.ToArray();

                var hasher = new Sha1Digest();
                hasher.BlockUpdate(data, 0, data.Length);
                hasher.DoFinal(hash, 0);

                return BytesToHexString(hash);
            }
        }`

**Comment by gamercubed** [comment]
I've found another issue with GetUniqueID and this is one that I can't yet explain.  It looks like in some cases, theory tests' arguments (which should be serializable) don't impact the UniqueId.  For example, the following two test names (taken from the results file, where they apparently did serialize correctly) have the same UniqueId:

- CreateIRange_GivenSameMinAndMax_ReturnsEmptyRange&amp;lt;Double, DoubleDescriptor&amp;gt;(value: 1, descriptor: DoubleDescriptor)
- CreateIRange_GivenSameMinAndMax_ReturnsEmptyRange&amp;lt;Double, DoubleDescriptor&amp;gt;(value: 1.5, descriptor: DoubleDescriptor)

**Comment by bradwilson** [comment]
A few thoughts.

1. The `UniqueID` property exists solely to compare test cases, especially as it applies to serialization. It came into being solely to support the architecture of VSTest, which does discovery in one process and execution in another. We have never intended for it to have any use other than that, and in fact do not routinely expose the unique ID to test authors (for example, they do not appear in the test reports).
2. We would be unable to change the definition of `ITestAssembly.Name` as this is a contract that has existed since 2.0. If we did support this, we'd have to strip the version number out of that name.
3. We have never supported overloaded tests (that is, two tests with the same method name). This breaks too many things in our design to be easily supported. When it works, it's accidental and not guaranteed to always work in the future. Please use different method names for each test.

**Comment by gamercubed** [comment]
Thanks.  Some follow-ups: 

1. I realize we're wanting to use the UniqueID in a way it wasn't intended, but if these changes maintain existing functionality while also making it more suitable to this usecase, is there a reason to reject them?  I've made the changes in my second comment locally and they don't break any tests.
2. Yeah, I figured there may be risks to changing the ITestAssembly.Name itself, which is why I ended up making all my changes inside GetUniqueID (see second comment).  Can you think of a reason this approach wouldn't work?
3. The case I'm describing that isn't handled by the current GetUniqueID is where a _generic_ test method (e.g. MyTest<T>()) that is run different ways with different type parameters (T) doesn't generate different UniqueIDs because the type input isn't included in the hash.  This seems like a bug, no?  The way I'm fixing it is to just add the DisplayName to the hash because it does include the type names (this is admittedly redundant since it re-adds the method name and [possibly truncated] arguments though I don't see any problem with that and it's easier than turning the generic type names into a string again).

I'm happy to submit a pull request (with the change above, or whatever you'd suggest instead) if you agree this preserves the original intent of the UniqueID while making it more useful for those like us who'd like to use it as a more consistent test identifier across runs.  What do you think?

**Comment by bradwilson** [comment]
1. So long as it doesn't break our usage, I'm okay with that change.
2. See above. :)
3. I see. I didn't understand this (I thought you were describing different methods with different types). It should be trivial to add serialization of the type names into the unique ID.

**Comment by blfrantz** [comment]
Thanks!  I've submitted a PR: https://github.com/xunit/xunit/pull/1241
