### ISSUE TITLE
Unseal InlineDataAttribute

### ISSUE THREAD

**Issue by krwq** [xunit/xunit#1225]
I'd like to create:
NonNetfxInlineDataAttribute which would set `Skip = true` in the constructor if running on full .NET.

Since InlineDataAttribute is sealed I need to pass additional arg to each InlineData and do additional check in the beginning of each theory.

Unsealing InlineData would make it cleaner and easier.

**Comment by bradwilson** [comment]
This cannot be unsealed because it is discovered using reflection abstractions that may not include actual binaries (for example, discovery via source code AST).

Given how little code is here (https://github.com/xunit/xunit/blob/master/src/xunit.core/InlineDataAttribute.cs), you should be able to duplicate it yourself.

**Comment by krwq** [comment]
@bradwilson - sounds good, thank you!
