### ISSUE TITLE
Run tests from the same collection in parallel

### ISSUE THREAD

**Issue by smithybc** [xunit/xunit#1227]
It's my understanding that tests within the same collection cannot run in parallel. When you are running tests that share no state, for example, smoke tests or UI tests against an actual implementation, it's quite handy to be able to run them in parallel. Splitting tests into separate classes reduces cohesiveness and also introduces issues if you have one time setup for the fixture i.e using ICollectionFixture.

Is there a way to override the documented behaviour? Is it feasible to implement this?

**Comment by bradwilson** [comment]
The entire purpose for test collections is shared state (the collection fixture).

There is currently no way to override this, as it's a fundamental design decision.

**Comment by smithybc** [comment]
Are there any other suitable options?

**Comment by bradwilson** [comment]
The only options here would involve extensive extensibility changes (unlikely that someone would stumble into the solution without help from one of us who knows the APIs very well).

If another test framework already offers you the parallelization options you desire, that would be a lot less painful. ☹️

**Comment by jawn** [comment]
To anyone who needs this.

Here's a description of how to use NUnit 3 to have parallel test execution for a single data driven test method: https://dev.to/franndotexe/parallel-test-execution-within-the-context-of-mstestv2-nunit3-and-vstestconsole-3f39

**Comment by DS-AdamMilazzo** [comment]
It's reasonable that tests from the same collection don't run in parallel, but why do collections have to line up with entire classes or assemblies? It would be nice if we could do either of these, or both:

```C#
[assembly: CollectionBehavior(CollectionBehavior.CollectionPerTest)] // run all tests in parallel by default
```

```C#
[Fact, Collection("a")] // specify [Collection] on a test method
public void TestFunc() { ... }
```

**Comment by bartelink** [comment]
>[Fact, Collection("a")] // specify [Collection] on a test method

@DS-AdamMilazzo but the collection args are fed into the class ctor, so this would get very confusing quickly, no?

**Comment by DS-AdamMilazzo** [comment]
> @DS-AdamMilazzo but the collection args are fed into the class ctor, so this would get very confusing quickly, no?

Yes. I've never used collection arguments and wasn't aware of their existence, but if that's how they work then it makes sense that you can't specify a different collection for each test in a class.

That said, it's unclear why tests in a collection can't run in parallel, or why a collection can't be marked as parallelizable (especially if the collection aligns with a single class). If the class is instantiated, can't you call more than one method at a time?

**Comment by bartelink** [comment]
>That said, it's unclear why tests in a collection can't run in parallel, or why a collection can't be marked as parallelizable (especially if the collection aligns with a single class). If the class is instantiated, can't you call more than one method at a time?

The high level idea is that tests in the collection are sharing a Fixture, which is assumed to be stateful (inc async init and dispose) and not threadsafe.

A collection fixture is generally intended for use across test types (a class fixture does not require a collection definition). See https://xunit.net/docs/shared-context. In all cases, the general idea is that the framework manages the fixtures lifetime, and the concurrency aspect. It's also explicitly intended that it means there's a mutex across all tests that are 'in' that Collection; the poster child being if you have some database, registry area or something else that you want to dole out exclusive access to, you can represent that as Collection Fixture

If you have threadsafe state to share between states (and no interest in controlled disposal, then you could to that via an AsyncLazy)

Having said all that, while I doubt it would be a simple ask to implement, being able to tag a Collection Fixture with a 'thread safe' marker that opts out of this mutual exclusion is concievably useful where the construction or disposal might otherwise be messy to coordinate. The counterpoint is that it's largely an antipattern to be relying on async disposal.

I'd suggest perusing the feature proposals list to see if it's already been described, then having a good think about specific scenarios where this sort of mechanism might apply. Invariably IME if you pose each such example as a discussion question or a SO question, the chances are there's already a decent way to represent it without adding behaviors and/or special cases to the Fixtures mechanisms impl, tests and their documentation though.

**Comment by andrewshawcare** [comment]
Associating a collection with a class by default is an odd design choice. The atomic unit of parallelization should be the test, not an implicit collection defined by tests in a class.

Is the expectation that, if someone wants to run two tests in parallel (which might be related), that they create separate classes for each test?

**Comment by bradwilson** [comment]
> Is the expectation that, if someone wants to run two tests in parallel (which might be related), that they create separate classes for each test?

With the default behavior, yes.

Third parties can extend the system to change behavior like this. Example: https://github.com/xunit/samples.xunit/tree/main/v3/NamespaceParallelization
