### ISSUE TITLE
Question: Will MSBuild 15.x running on Mono/.NET Desktop be supported for running tests?

### ISSUE THREAD

**Issue by borgdylan** [xunit/xunit#1266]
I do know that xunit supports the "dotnet test" experience already but since the dotnet CLI does not support mono or desktop .NET I had to go with the standalone MSBuild route to be able to compile for desktop .NET/Mono/.NET Core. That however leaves without a testing story when running on Linux. I do remeber xunit running on my machine back in the DNX days. Will that be brought over to support MSBuild 15.x in general, maybe with some special target/task? Or is this already available and I just don't know about it?

**Comment by bradwilson** [comment]
We are shipping 2.3 beta 2 this week with a few things that will help you.

First, I would strongly recommend you use `dotnet xunit` over `dotnet test` because it offers better performance and more features. We have a [Getting Started page](https://xunit.github.io/docs/getting-started-dotnet-core.html) that shows how to do that.  This runner supports both desktop CLR and .NET Core.

In the forthcoming build, we [added a `-usemsbuild` switch](https://github.com/xunit/xunit/commit/39852115b45fcd9d6ad748a5df51a5efc975d269) to `dotnet xunit` which will use desktop MSBuild instead of `dotnet msbuild` when interacting with your `.csproj` file. We also [added a `-nobuild` switch](https://github.com/xunit/xunit/commit/2dad9bbc589758b393b7be94131ddb12eb830292) so that you can tell it not to rebuild your binaries (that's mostly for performance reasons, but if you're building ahead of time, we eliminated the need to re-build again). We also [fixed `dotnet xunit` so that it would invoke Mono](https://github.com/xunit/xunit/commit/6f83e40d5056ab68ea0ef1c210e177e97baf554a) for desktop CLR unit tests when running outside of Windows.

Once 2.3 beta 2 ships and you've tried it out, feel free to open issues if there are any remaining unaddressed issues for you.

**Comment by borgdylan** [comment]
Can it be invoked through some target/task ? I don't mind if the command line to use is complex. Dotnet cli interfered with my desktop msbuild install on Linux and so I'd like to avoid installing the cli if possible.

**Comment by borgdylan** [comment]
Or is there a dotnet-xunit executable in the nuget package? Like that I can build a target that executed the executable as msbuild 15 has properties that aids in finding the path to packages. I could share what I came up with.

**Comment by borgdylan** [comment]
The new msbuild also allows automatic import of msbuild targets having a specific name inside the build folder of the package. It makes consumption nice and easy.

**Comment by bradwilson** [comment]
There is no such thing as a stand-alone .NET Core console application executable. The `dotnet` CLI is absolutely required to be able to run anything on .NET Core.

**Comment by borgdylan** [comment]
The CLI and the "dotnet" hoster are different packages altogether. The CLI is just the tooling and is shipped separately. I do not install the CLI but do have the "dotnet" hoster/driver binary as well as the shared frameworks packages installed. I am able to run ```dotnet dotnet-xunit.dll``` for example. I just need to synthesize the direct path to xunit, that's all. It's the same story as with mono.

**Comment by borgdylan** [comment]
Also, standalone apps are possible when shipping the runtime with the app. In the case of xunit, I would not recommend that as most people would have the the .NET Core runtime (i,.e. dotnet bianry + shared framework) already installed.

**Comment by dasMulli** [comment]
btw, mono is also able run netcoreapp* executables ;)
Mono 5 will include the SDK in it's msbuild distribution, for mono 4.8 this is possible with [some hacks](https://gist.github.com/dasMulli/29c7d68f321cc5ac4a68407a6fd76d19) - but it can build sdk-based csproj files nicely.

And yes the CLI is required to run `dotnet xunit` as command - both because of the command resolver and because it generates a deps file for the command (at least for 2.0, this step will be an msbuild target as well).
However, the msbuild runner shouldn't need a CLI installed, only a muxer + shared fx to run `netcoreapp` targets.

**Comment by borgdylan** [comment]
For linux the sdk as well as msbuild have to installed separately. I've already done that and its working fine for me. When targeting netcoreapp, msbuild makes a deps file as well as those steps are now in the sdk itself. The CLI is just a glorified msbuild wrapper now so for me its just overhead,

**Comment by bradwilson** [comment]
It turns out we couldn't make this work effectively, because of the way .NET Core (or, really, does not) adequately support a plug-in model. MSBuild can still be used to launch the console runner or `dotnet xunit` as appropriate.
