### ISSUE TITLE
dotnet-xunit support for Reference

### ISSUE THREAD

**Issue by winterlimelight** [xunit/xunit#1268]
When I run my test project with `dotnet xunit` I get one test failing that does not fail with `dotnet test`.
This test uses a directly referenced dll:
```xml
 <ItemGroup>
    <Reference Include="..\..\src\lib\DocumentFormat.OpenXml.dll" />
...
    <PackageReference Include="xunit" Version="2.2.0-beta5-build3474" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-beta5-build1225" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta1-build3642" />
  </ItemGroup>
```
and the error message is:
`System.IO.FileNotFoundException : Could not load file or assembly 'DocumentFormat.OpenXml, Version=0.0.1.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17'. The system cannot find the file specified.`

The DocumentFormat.OpenXml.dll assembly is in the bin folder with the test assembly

Does dotnet-xunit support project `Reference`? If it does is there some way of getting more information about the failure (already tried -verbose)?

**Comment by bradwilson** [comment]
My guess is that `<Reference>` isn't showing up in your dependency graph (i.e., the `.deps.json` file that .NET Core uses to figure out what to load and from where). Question is... why?

**Comment by bradwilson** [comment]
## Short answer
What you're trying to do appears to be a new feature of the .NET Core SDK 2.0 Preview 1. This will not working on previous versions of the .NET Core SDK (anything from 1.x).

_Note that the version of the SDK tooling is separate from the version of .NET Core that you may be targeting._

## Longer answer
Here's what I did to reproduce it:

1. Create a `netstandard1.1` class library named `MathLib`, which included a single class which adds two numbers. I did this so that the library in question would have no dependencies.
2. I ran `dotnet restore` and `dotnet build` on this library.
3. Create a `netstandard1.1` unit test library named `MathLib.Tests`.
4. I hand copied the DLL from step 2 into a `lib` folder
5. I added `<Reference Include="lib\MathLib.dll" />`
6. I wrote unit tests against the math library, including a passing and failing test
7. I ran `dotnet restore` and `dotnet xunit` on the unit tests.

With the 2.0 tooling, everything ran as expected:

```
  PS> dotnet --version
2.0.0-preview1-005977

  PS> dotnet xunit
[...]
xUnit.net Console Runner (64-bit .NET Core 4.6.25211.01)
  Discovering: MathLib.Tests
  Discovered:  MathLib.Tests
  Starting:    MathLib.Tests
    Class1.Failing [FAIL]
      Assert.Equal() Failure
      Expected: 5
      Actual:   4
      Stack Trace:
        C:\Dev\1\MathLib.Tests\Tests.cs(16,0): at Class1.Failing()
  Finished:    MathLib.Tests
=== TEST EXECUTION SUMMARY ===
   MathLib.Tests  Total: 2, Errors: 0, Failed: 1, Skipped: 0, Time: 0.133s
```

With the 1.0.4 tooling, everything fails:

```
  PS> dotnet --version
1.0.4

  PS> dotnet xunit
[...]
xUnit.net Console Runner (64-bit .NET Core 4.6.25211.01)
  Discovering: MathLib.Tests
  Discovered:  MathLib.Tests
  Starting:    MathLib.Tests
    Class1.Passing [FAIL]
      System.IO.FileNotFoundException : Could not load file or assembly 'MathLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      Stack Trace:
           at Class1.Passing()
    Class1.Failing [FAIL]
      System.IO.FileNotFoundException : Could not load file or assembly 'MathLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      Stack Trace:
           at Class1.Failing()
  Finished:    MathLib.Tests
=== TEST EXECUTION SUMMARY ===
   MathLib.Tests  Total: 2, Errors: 0, Failed: 2, Skipped: 0, Time: 0.122
```

And here are the files in question:

### MathLib\MathLib.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.1</TargetFramework>
  </PropertyGroup>

</Project>
```

### MathLib\Adder.cs

```csharp
namespace MathLib
{
    public class Adder
    {
        public int Go(int x, int y) => x + y;
    }
}
```

### MathLib.Tests\MathLib.Tests.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="lib\MathLib.dll" />
    <PackageReference Include="xunit" Version="2.3.0-beta2-build3683" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta2-build3683" />
  </ItemGroup>

</Project>
```

### MathLib.Tests\Tests.cs

```csharp
using Xunit;

public class Class1
{
    [Fact]
    public void Passing()
    {
        var adder = new MathLib.Adder();
        Assert.Equal(6, adder.Go(4, 2));
    }

    [Fact]
    public void Failing()
    {
        var adder = new MathLib.Adder();
        Assert.Equal(5, adder.Go(2, 2));
    }
}
```

**Comment by winterlimelight** [comment]
Thanks for investigating - I'll follow this up a bit more tomorrow. But I would note that `dotnet --version`  comes back as 1.0.1 for me, so not sure about it being Core preview 2.0 related. I will try upgrading to 1.0.4 though.

**Comment by bradwilson** [comment]
I think maybe you're missing my point: this will not work with any 1.x SDK (not 1.0.1, nor 1.0.4) tools. You must use the 2.0 SDK tools, which are currently at Preview 1 and just shipped a few days ago.
