### ISSUE TITLE
Horrible test run performance in vstest unless {appdomain: denied} is specified

### ISSUE THREAD

**Issue by jessehouwing** [xunit/xunit#1290]
We have a number of tests that slow down to a crawl when specifying a runsettings file on the vstest command line. Running without code coverage and running without specifying a runsettings file the tests execute in 27 seconds.

When specifying a runsettings the test execution takes 20 minutes.
[runsettings.zip](https://github.com/xunit/xunit/files/1008999/runsettings.zip)

Adding a xunit.runner.json and setting { "appDomain": "denied" } solves all perf issues, regardless of which runettings file I specify.

This is with VS 2017u2, Vs2017u3-preview1 ad xunit 2.2.0

**Comment by bradwilson** [comment]
We have no control over the cost associated with code coverage.

**Comment by froitag** [comment]
I experienced the very same performance problem with VSTest and /EnableCodeCoverage on our Visual Studio Team Services (VSTS) build server. 

I can confirm, that disabling AppDomains solves the problem (although it raises further issues with assembly loading etc.).

However, I can also confirm that using xunit.runner.visualstudio 2.2.0 solves this problem, too! I assume this is related to the AppDomain improvements in 2.2 as briefly mentioned in [#758](https://github.com/xunit/xunit/issues/758#issuecomment-179673392).

If someone else experiences this problem on VSTS although using xunit 2.2.0, I can recommend to look for outdated xunit.runner.visualstudio references in your projects. In our case it turned out that the build agent restored an outdated xunit.runner.visualstudio 2.1 from an obsolete project in the repository. Somehow, the outdated version took precedence over the new one and all tests were running with 2.1 although all other projects referenced 2.2. I have yet to figure out how to talk VSTS out of this behavior ;)

**Comment by bradwilson** [comment]
Significant performance improvements have happened in 2.2 and 2.3. Performance work is ongoing and doesn't need an open issue.
