### ISSUE TITLE
How to run tests as 64 bit process from VS Test Explorer?

### ISSUE THREAD

**Issue by jawn** [xunit/xunit#1304]
Given a xunit project with platform target Any CPU and targetting .NET Framework 4.5.2
Installed xunit.runner.visualstudio v2.2.0

When I build and run my unit tests with the VS Test Explorer, they run in 32 bit.
When I build and run my unit tests with the Resharper unit test explorer, they run in 64 bit

Is there a way to force running the xunit tests via the VS Test explorer in 64 bit?
Note: when I set the platform target to 64 bit, the tests no longer appear in the Visual Studio Test Explorer after rebuilding.

Detailed configuration:
- Visual Studio Enterprise 2017 with latest updates
- .NET Framework 4.x
- xunit 2.2.0
- xunit.runner.visualstudio v2.2.0
- ReSharper 2017 latest

**Comment by xied75** [comment]
On VS Menu, Test -> Test Settings -> Default Processor Architecture -> X64

**Comment by serup** [comment]
do you know if it is possible to make the visual studio automatic change the default processor architecture settings, to fit according to the runtime chosen? 

I ran into this issue when testing in different environments x86 and x64, and somehow x86 continuesly failed - due to the fact that the default processor architecture was set to x64, and that should ofcourse also be changed when choosing the x86 platform

**Comment by bradwilson** [comment]
I'm not aware of anything. This is really a question for the VSTest team.

**Comment by mbalex99** [comment]
How do you do this in Visual Studio for Mac?
