### ISSUE TITLE
No CodeLens support for tests in nested classes

### ISSUE THREAD

**Issue by GeorgDangl** [xunit/xunit#1322]
This issue is related to #1140, but that one has been closed and marked as fixed.

I'm facing the problem that xUnit tests don't get the CodeLens when they're in nested classes:
![xunitcodelens](https://user-images.githubusercontent.com/10274404/27004079-7219a7a6-4e03-11e7-96df-95a39fb28154.PNG)

I'm running Visual Studio 2017 with the latest update (15.2.26430.13, not preview) and the following references:
```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170618-03" />
<PackageReference Include="xunit" Version="2.3.0-beta4-build3710" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta4-build3710" />
<DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta4-build3710" />
```

It is also configured as test project via:
```xml
<ItemGroup>
  <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
</ItemGroup>
```

The target framework for the test project is `netcoreapp1.1`. I'm usually structuring my tests in a base class per class to test and parent classes for each method, e.g.:
```csharp
public class AccountCountrollerTests
{
  public class Login
  {
    [Fact]
    public void OkWithUsernameInsteadOfEmail()
    {
      // ...
    }
  }

  public class Logout
  {
    // ...
  }
}
```

The Test Explorer is fine and I'm able to run single tests in nested classes. It's just not showing up in CodeLens. I've tried to create nested classes in the xUnit Integration Test Project with the same result.

**Comment by ryangribble** [comment]
I see this issue has been open 1+ month so just wanted to add a "me too!".

Just confirming this is also reproducible for me.  In [octokit.net](github.com/octokit/octokit.net) we structure all our tests as nested classes (one per method) and code lens information has been missing ever since going to VS2017.  Today I decided to see why they were missing, updated all the nuget references to the latest versions etc and still found no luck.  Then I saw this issue and proved that if I create a dummy test in the parent class, CodeLens shows up, so it's just the fact that we have all nested class tests that was causing issues for us

**Comment by ryangribble** [comment]
I dug around in the xunit visual studio code, including the previous fix for code lens but unfortunately I'm not sure how/where to "fix" the issue for nested classes. I assume it has something to do with needing to include the full namespace and recursive parent classes names in the test discovery code, but the ITypeInfo doesn't have enough detail to do that I don't think. Any tips/pointers on how to fix this?

**Comment by bradwilson** [comment]
ReflectionTypeInfo.Name already does this.

**Comment by ryangribble** [comment]
Although it doesn't include the namespace, which seems to be shown in the visual studio test runner... Although maybe that's just the display name? 

I guess the tip I need is HOW does visual studio know to show the code lens info... Looking at your previous fix it seemed to be setting the testname property to include class and method name... I assume this is to match "something" (what visual studio thinks about a particular method in a file in the code editor?). 

I guess the question is what does visual studio "think" about the nested class test methods and how can we get xunit to provide testcase name that aligns to that?

**Comment by bradwilson** [comment]
Right, that's probably because you have `method` as the default display name.

We take the method name (after doing some... evilness related to async methods) and send it to a service inside Visual Studio, which identifies the source file & line. I will see if I can reproduce this myself, as it may turn out to be a bug in Visual Studio. They did completely re-write the testing engine in 2017... ;)

**Comment by GeorgDangl** [comment]
With the latest Visual Studio 2017 15.3 Update, this issue seems to be resolved. I'm using the following dependencies:

```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170106-08" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta3-build3705" />
<PackageReference Include="xunit" Version="2.3.0-beta3-build3705" />
```

@ryangribble, please confirm if VS 2017 15.3 fixes the issue for you, too, and I'll close the issue.

**Comment by ryangribble** [comment]
Yep it's now working for me.  I updated to VS2017 15.3 and it still wasn't working, but I was still running non pre-releases packages.

After some experimentation I found that I only needed the `xunit.runner.visualstudio` package to be updated, and code lens is now showing up.

These are the dependencies that are working (although I am going to roll with the latest pre-release of xunit itself as well)

```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta4-build3742" />
```
