### ISSUE TITLE
[xunit.analyzers] Consider warning when Theory parameter is unused

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1373]
Sometimes, people convert from `[Fact]` to `[Theory]` but forget to replace the hard-coded values with variables. I recall commenting on a corefx PR of @hughbe's some time ago where he made this mistake, but I can't find it now (there are too many of them :)).

Would it be a good idea to warn when the parameter of a theory is unused, e.g.

```cs
[Theory]
[InlineData(2)]
public void ZeroIsAdditiveIdentity(int n)
{
    Assert.Equal(2, AddZero(2));
}
```

? /cc @marcind

**Comment by marcind** [comment]
Yes, that sounds like a great idea for an analyzer.

On Jul 21, 2017 19:45, "James Ko" <notifications@github.com> wrote:

Sometimes, people convert from [Fact] to [Theory] but forget to replace the
hard-coded values with variables. I recall commenting on a corefx PR of
@hughbe <https://github.com/hughbe>'s some time ago where he made this
mistake, but I can't find it now (there are too many of them :)).

Would it be a good idea to warn when the parameter of a theory is unused,
e.g.

[Theory]
[InlineData(2)]public void ZeroIsAdditiveIdentity(int n)
{
    Assert.Equal(2, AddZero(2));
}

? /cc @marcind <https://github.com/marcind>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xunit/xunit/issues/1373>, or mute the thread

**Comment by hughbe** [comment]
That's a great idea, can't count the number of times I've done that!

**Comment by jamesqo** [comment]
@marcind I will grab this issue, assuming you haven't already started working on this.
