### ISSUE TITLE
Support for theory test using generics

### ISSUE THREAD

**Issue by svejdo1** [xunit/xunit#1378]
There seems to be a demand for some support for generic test methods. Something like:

```
[Theory]
[Generics(typeof(int), typeof(double))]
public void TestMethod<T>();

[Theory]
// some data attributes
[Generics(typeof(int), typeof(double))]
public void TestMethod<T1,T2>(int foo, int bar);
```

etc. While completly posible to replace this with non-generic variant

```
[Theory]
// some data attributes
public void TestMethod(Type t1);

[Theory]
// some data attributes
public void TestMethod(Type t1, Typ2 t2, int foo, int bar);
```

Related:
https://stackoverflow.com/questions/39570641/xunit-theory-test-using-generics/45178208

**Comment by bradwilson** [comment]
I would like to see a real world scenario where this would be useful (simply testing `typeof(T)` is not such a case, because clearly you could just pass the `Type` as a parameter instead of generic).

**Comment by svejdo1** [comment]
Suppose method/class like: `MyMethod<T>();` you need to test with both ` double` and ` int` .
Usually you'd go like:
```
void TestMyMethodInt() {
   MyMethod<int>();
}

void TestMyMethodDouble() {
   MyMethod<double>();
}
```
This seems shorter:
```
[Generics(typeof(int),typeof(double)]
void TestMyMethod<T>()
```

**Comment by bradwilson** [comment]
I'm sorry, but this still fails the real world test for me.

Provide an implementation of `MyMethod<T>()` which neither takes any data nor returns any, but still meaningfully uses `T`.

I suspect that this is such an edge case that we will probably not support it, even if you can come up with a case where it makes sense. Rarely would you ever see a properly designed API where T cannot be implied, but also MUST be passed via generic instead of a type, for the simple reason that such an API is broken unless you know T at compile time. In that scenario, my suggestion would be to fix the API, not the testing framework.

**Comment by colin-young** [comment]
What about this (working and tested with `xunit 2.2.0 netcoreapp1.1`)?

```
public static IList<object[]> TestData => new List<object[]>
        {
            new object[] { (Func<int, int>)((i) => i), 1, 1 },
            new object[] { (Func<int, string>)((i) => i.ToString()), 1, "1" },
            new object[] { (Func<string, int>)((i) => int.Parse(i)), "1", 1 }
        };

        [Theory]
        [MemberData(nameof(TestData))]
        public void TestMemberData<TInput, TOutput>(Func<TInput, TOutput> f, 
            TInput input, 
            TOutput expected)
        {
            TOutput result = f.Invoke(input);
            result.Should().Be(expected);
        }
```

If you're really just trying to make sure you can call `MyMethod<T>()` without getting an exception, you could just use the input/output as "examples," e.g. (_not_ tested, but I'm guessing it should work):

```
...
new object[] {(Func<TInput>)(() => MyClass<TInput>()), 1.0},
new object[] {(Func<TInput>)(() => MyClass<TInput>()), "1"}
...
public void TestMemberData<TInput>(Func<TInput> f, TInput input)
{
    f.Invoke();
}
```

**Comment by bradwilson** [comment]
Not planning to implement this.

**Comment by skolima** [comment]
Type inference works for this @naasking :

```
[Theory]
[MemberData(nameof(TypesToCheck))]
public void ShouldBeAbleToSerialize<T>(T item)
{// test serialization}

public static IEnumerable<object[]> TypesToCheck()
{
  yield return new object[] { CreateSampleData<SomeTypeToCheck>() };
}
```

**Comment by sidm1983** [comment]
@bradwilson I believe I have a real-world scenario for you in this case. I have recently implemented the following extension method:
```csharp
public static byte[] ComputeHashHex<T>(this string input, Encoding encoding = null) where T : HashAlgorithm, new()
{
    var inputBytes = (encoding ?? Encoding.UTF8).GetBytes(input ?? string.Empty);
    byte[] hashBytes;
    using(var hashImpl = new T())
    {
        hashBytes = hashImpl.ComputeHash(inputBytes);
    }
    return string.Concat(hashBytes.Select(x => x.ToString("x2")));
}

//Usages
"hello world".ComputeHash<SHA256Managed>(); //Outputs: "b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9"
"This string needs to be hashed".ComputeHash<SHA512Managed>(); //Outputs: "309ecc489c12d6eb4cc40f50c902f2b4d0ed77ee511a7c7a9bcd3ca86d4cd86f989dd35bc5ff499670da34255b45b0cfd830e81f605dcf7dc5542e93ae9cd76f"
```
As you can see, I am passing in a generic type parameter `<T>` that has no equivalent parameter in the method's parameter list (and therefore nothing can be inferred about `<T>` from the parameters) and I have put a restriction on `<T>` which only allows it to be a derived type of the `System.Security.Cryptography.HashAlgorithm` class (`HashAlgorithm` is an abstract class) and it must define an empty constructor. In this case, all of its derived classes (e.g. `SHA256Managed`, `SHA512Managed`, etc.) meet this constraint and can be used, however, we don't need to pass in an actual live instance as a parameter in this case, because the extension method above will instantiate the type itself and use it to compute the hash of the input string (as can be seen by this statement: `using(var hashImpl = new T())`).

Now to the unit testing aspect. At the moment, here is what my test method looks like:
```csharp
[Theory]
[ClassData(typeof(HashHexTestData))]
public void ComputeHashHexTests<T>(string input, T hashAlgorithm, Encoding encoding, string expectedHashHex) where T : HashAlgorithm, new()
{
    var actualHashHex = input.ComputeHashHex<T>(encoding);
    output.WriteLine($"{hashAlgorithm.GetType().Name} hash hex of \"{input}\": {actualHashHex}");
    Assert.Equal(expectedHashHex, actualHashHex);
}
```
And here is the definition of the `HashHexTestData` class:
```csharp
public class HashHexTestData : IEnumerable<object[]>
{
    public IEnumerator<object[]> GetEnumerator()
    {
        yield return new object[] { "hello world", new SHA256Managed(), Encoding.UTF8, "b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9" };
        yield return new object[] { "hello world", new SHA512Managed(), Encoding.UTF8, "309ecc489c12d6eb4cc40f50c902f2b4d0ed77ee511a7c7a9bcd3ca86d4cd86f989dd35bc5ff499670da34255b45b0cfd830e81f605dcf7dc5542e93ae9cd76f" };
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```
Notice that my test method passes in a generic `<T>` type parameter which also has a matching parameter `T hashAlgorithm` in the parameter list. I have done this workaround intentionally in order to invoke type inference for `<T>` in this case. The `T hashAlgorithm` parameter is not actually needed. You can see that I am not even passing it to the `ComputeHashHex<T>` method during the test. However, because the compiler spits out a warning for unused parameters, I decided to fake it and use the `hashAlgorithm` parameter to output some text to the console using `ITestOutputHelper` as can be seen by the `output.WriteLine($"{hashAlgorithm.GetType().Name}...");` statement in the test method.

Is there a better way to test this method without having to pass in a redundant `T hashAlgorithm` parameter just so it invokes type inference for `<T>`?

I am hoping I will eventually be able to have a test method with a signature like this:
```csharp
public void ComputeHashHexTests<T>(string input, Encoding encoding, string expectedHashHex) where T : HashAlgorithm, new()
{
   ...
}
```
And then be able to pass it an object array like this from my test data class (or something similar):
```csharp
yield return new object[] { typeof(SHA256Managed), "hello world", Encoding.UTF8, "b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9" };
```
Would love to hear your thoughts on this. Thank you.

**Comment by Sgtmoustache** [comment]
> Not planning to implement this.

Was looking forward for this feature. :(

**Comment by bradwilson** [comment]
>Would love to hear your thoughts on this.

The value here is still quite low, with an obvious work-around: provide the `HashAlgorithm` instances as member data instead of writing `new T()` inside the test.

**Comment by JennelleMaierPie** [comment]
Here's my real world example for why I'd like InlineData to support generics.  I'm testing a method that returns different Types based on the error code received.

If this format were supported, it would make the tests cases very legible:
```csharp
[Theory]
[InlineData<NotFoundObjectResult>(ErrorCode.RecordNotFound, StatusCodes.Status404NotFound)]
[InlineData<UnprocessableEntityObjectResult>(ErrorCode.InvalidStatus, StatusCodes.Status422UnprocessableEntity)]
public async Task MediatorReturnsError_ConvertToObjectResult<TObjectResult>(ErrorCode errorCode, int expectedStatusCode) where TObjectResult : ObjectResult
{
    //Arrange
    //Act
    var result = //invocation
    //Assert
    var objectResult = Assert.IsType<TObjectResult>(result);
    Assert.Equal(expectedStatusCode, objectResult.StatusCode);
}
```

**Comment by cr4bb** [comment]
I wanted to do something like this for testing exception serialization/deserialization:
```csharp
[Theory]
[InlineData(typeof(SomeTypeOfException))]
[InlineData(typeof(SomeOtherTypeOfException))]
public async void ExceptionsSerializeAndDeserializeCorrectly<TException>(TException input) where TException : Exception, new()
{
    var exception = new TException();

    var serializedException = Serialize(exception);
    var deserializedException = Deserialize<TException>(serializedException);
    
    await Assert.ThrowsAsync<TException>(() => throw deserializedException);
}
```

But this fails to compile with `The value is not convertible to the method parameter 'input' of type 'TException'.`

The workaround I implemented with help from this thread is:
```csharp
public static IEnumerable<object[]> ExceptionsToTest()
{
    yield return new object[] { new SomeTypeOfException() };
    yield return new object[] { new SomeOtherTypeOfException() };
}

[Theory]
[MemberData(nameof(ExceptionsToTest))]
public async void ExceptionsSerializeAndDeserializeCorrectly<TException>(TException exception) where TException : Exception
{
    var serializedException = Serialize(exception);
    var deserializedException = Deserialize<TException>(serializedException);
    
    await Assert.ThrowsAsync<TException>(() => throw deserializedException);
}
```

Perhaps not quite as succinct as the former, but still clear in its intent.

**Comment by harish-venkataramanan-cko** [comment]
I was able to give this a shot and it worked using c# 11 generic attributes

```
internal class ValueObjectDataAttribute<TValueObjectType, TValueType> : DataAttribute
    where TValueObjectType : IValueObject<TValueObjectType, TValueType>
{
    private readonly TValueType _value;

    public ValueObjectDataAttribute(TValueType value) =>
        _value = value;

    public override IEnumerable<object[]> GetData(MethodInfo testMethod)
    {
        yield return new object[]
       {
              <any way of using generics to create the objects, if possible use static abstract interface members to avoid 
              reflection if you need a factory :) > };
        }
}
```

you can then use it in your tests like below

```
[Theory]
    [ValueObjectData<StringBasedValueObject, string>("Samplename")]
    public void SimpleSerialization_Succeeds_For_ValueObjects<TValueObjectType, TValueType>(TValueObjectType expectedValueObject)
    {
        string json = JsonConvert.SerializeObject(expectedValueObject);
        TValueObjectType? actualValueObject = JsonConvert.DeserializeObject<TValueObjectType>(json);
        actualValueObject.ShouldBeEquivalentTo(expectedValueObject);
    }
```

**Comment by JoHohner** [comment]
My use case for this are static abstract interface members. I want to test a generic method that uses only the statics of the generic type. To call this I need a generic theory, but not an instance of the type. I prefer to use InlineData, but this doesn't work with the necessity to pass an instance of the generic.

**Comment by ilya-chumakov** [comment]
Based on the previous snippets, this is how I got strong-typed generic test methods working in `xunit.v3`. The only limitation is `new()` constraint on a generic parameter:

```cs
class InlineType<TTestParam> : DataAttribute where TTestParam : new()
{
    public override ValueTask<IReadOnlyCollection<ITheoryDataRow>> GetData(
        MethodInfo testMethod,
        DisposalTracker disposalTracker) => new([new TheoryDataRow(new TTestParam())]);

    public override bool SupportsDiscoveryEnumeration() => true;
}


[Theory]
[InlineType<Foo>]
[InlineType<Bar>]
public Task Arrange_Act_Assert<TEntity>(TEntity _) where TEntity : new()
{
    return DoSomethingAsync<TEntity>();
}
```

Additional type constraints can be added on both attribute and method level, or even by declaring an attribute subtype:

```cs
class InlineEntityType<TTestParam> : InlineType<TTestParam> where TTestParam : SomeBaseType, new();
```

Thanks guys.

**Comment by fterrani** [comment]
Hi @bradwilson.

Personally, I would also be interested in this feature for readability reasons.

Regarding my use case, the system I'm working on allows to execute CRUD operations on various kinds of entities which can have either an integer or GUID as their primary key. For basic CRUD tests, several assertions are identical no matter which entity and key types are used. It would have been interesting for me to reuse these tests instead of copying-pasting them to simply change entity type, key type and the test key value.

I've read the whole issue and I feel like this feature's value mainly resides in an hypothetic syntactic sugar that would (in my humble opinion) improve readability if well designed, assuming something like the following is possible:

```csharp

// ** WARNING ** quick, dirty, UNTESTED draft!
// Based on XUnit 2 code. Casting and generic call would be "outsourced" to the framework?
// Developer is still obviously responsible for providing valid data.
public class InlineDataAttribute<T1> : DataAttribute
{
    private readonly object[] _data;

    public InlineDataAttribute(params object[] data) => _data = data;

    public override IEnumerable<object[]> GetData(MethodInfo testMethod) => new[] { _data };
}

public class InlineDataAttribute<T1, T2> : DataAttribute
{
    private readonly object[] _data;

    public InlineDataAttribute(params object[] data) => _data = data;

    public override IEnumerable<object[]> GetData(MethodInfo testMethod) => new[] { _data };
}

// ... and additional classes for <T1, T2, T3>, <T1, T2, T3, T4>...
```

That being said, I also learnt about type inference using `[*Data]` attributes to work around this limitation by reading this issue. While current docs does [demonstrate how to use `[InlineData]`](https://xunit.net/docs/getting-started/v3/getting-started#write-your-first-theory), I think that a section devoted to `[ClassData]`, `[MemberData]` and `[InlineData]` with usage examples of these would be useful. Another section showing how to implement generic tests using methods shown in this issue would also be very valuable, at least to provide a recommendation.

What do you think?

*P.S.: For those wondering, `[InlineData]` cannot be used sometimes due to [CS0182](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/parameter-argument-mismatch), hence the interest of `[MemberData]` and `[ClassData]` I guess.*
