### ISSUE TITLE
Analyzers that error when MemberData references data with mismatched arity/type

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1391]
Suggested by a user on Reddit: https://www.reddit.com/r/csharp/comments/6rigmd/what_are_some_common_mistakes_you_make_with/dl674oa/

- If the member `MemberData` references is a `TheoryData`, then we can easily check the arity and types of the `TheoryData` to see whether they match the method.

  - Note: This will have to deal with `params` support, default parameters, etc.

- If the `MemberData` references an `IEnumerable<object[]>`, then it will be harder to verify this. However, it may still be feasible when the `object[]`s are created via `new object[] { ... }` literals directly inside the referenced method. See my response to the Reddit comment above.

**Comment by marcind** [comment]
Related to https://github.com/xunit/xunit/issues/1244

**Comment by jamesqo** [comment]
@marcind Do you think it'd be best if I put this in `MemberDataShouldReferenceValidMember` or made a new analyzer for this? There already seems to be a lot of code in that analyzer.

**Comment by marcind** [comment]
I've been working on refactoring the argument type to parameter matching logic from [InlineDataMustMatchTheoryParameters](https://github.com/xunit/xunit.analyzers/blob/master/src/xunit.analyzers/InlineDataMustMatchTheoryParameters.cs) into something reusable that would be applicable here. I'm about halfway through that, but don't have an ETA on when I'll be done. You would likely be repeating that effort so not sure if it's worth it.

Btw, I originally put all that code in one analyzer because there was a lot of shared logic and my intuition told me it would be more efficient to have it execute once for all rules vs once for each rule in that group. My decision process for determining what goes together vs separate is a balancing act between having the analyzers reuse calculated metadata at runtime vs how likely it is that someone would disable all or a subset of the analyzers. It's not scientific, just a best guess; it probably changes over time too based on how tired I am.

**Comment by bradwilson** [comment]
This is now covered by [xUnit1039](https://xunit.net/xunit.analyzers/rules/xUnit1039) (for type matching) and [xUnit1040](https://xunit.net/xunit.analyzers/rules/xUnit1040) (for nullability matching).
