### ISSUE TITLE
Consider analyzer to convert async void to async Task test methods

### ISSUE THREAD

**Issue by marcind** [xunit/xunit#1405]
XUnit supports `async void` test methods correctly via a custom synchronization context. However users occasionally report that as a potential problem because the prevailing (and correct in most cases) guidance is to avoid `async void` unless absolutely necessary. Should we consider having an analyzer/code fix to convert `async void` to `async Task`?

/cc @bradwilson @onovotny

**Comment by bradwilson** [comment]
You only have to look at the xUnit.net source itself to see whether I would use such a rule. 😉 

My problem with this as an analyzer is that there is nothing wrong with the behavior per se in the context of xUnit.net. If people want a generalized rule to warn about `async void` (in places where it's not appropriate), that doesn't really feel like something we should be writing.

I have personally never given guidance to avoid `async void` in xUnit.net. It is 100% purely stylistic. I'm not against stylistic rules, but if you implement this one, you should offer its opposite, too.

**Comment by jamesqo** [comment]
@bradwilson I was the one who originally had this idea in #1390, before @marcind gave it its own issue. I posted this because a Reddit user [claimed](https://www.reddit.com/r/csharp/comments/6rigmd/what_are_some_common_mistakes_you_make_with/dl5dkx9/) there were performance issues related to `async void`. I haven't personally run into such issues myself, however. If it really is "100% stylistic" and neither is faster than the other, then I'm in favor of having both (void -> Task and Task -> void) codefixes or none, too.

**Comment by ErikSchierboom** [comment]
The [official Async/Await best practices](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx) state the following:

> Prefer async Task methods over async void methods

The list one exception where `async void` should be used instead of `async Task`: asynchronous event handlers. They also list some reasons on why `async Task` is preferrable to `async void`, such as improved exception handling and composability. I don't necessarily think these arguments are very strong in the context of xUnit, but I do think there is something to be said for conforming to the official guidelines.

**Comment by bradwilson** [comment]
> I don't necessarily think these arguments are very strong in the context of xUnit

Not strong at all.

> I do think there is something to be said for conforming to the official guidelines.

Regardless on your feelings one way or another, I don't believe that it's the responsibility of xUnit.net to enforce `async Task` over `async void`, because _**this guidance has nothing specificially to do with xUnit.net**_. At best, that rule belongs to some other general analyzer set.

**Comment by ErikSchierboom** [comment]
> At best, that rule belongs to some other general analyzer set.

Agreed. Should we close this issue then?

**Comment by jamesqo** [comment]
@ErikSchierboom It still makes sense to have such an analyzer for stylistic reasons. For example, there should be no reason for someone to mix `async Task` and `async void` in the same file:

```cs
[Fact] public async Task Test1() { ... }

[Fact] public async void Test2() { ... }
```

This might end up happening if different people working on the same project have different preferences. We should encourage the developer to use either all `async Task` or `async void` within a class.

**Comment by ErikSchierboom** [comment]
Well, the point @bradwilson is making is that it is not the responsibility of xUnit to ensures that. And I agree.

**Comment by jamesqo** [comment]
@ErikSchierboom This is specific to xUnit.net. A general analyzer for async shouldn't suggest that an `async void` method be converted to `async Task` just because all of the other methods in the class return `async Task`. For xUnit.net, however, there is no difference between the two, so it makes sense to enforce consistency.

**Comment by marcind** [comment]
I believe there are other, more important/interesting analyzers to implement, not to mention bugs in the existing ones. I'm going to close this issue for now. We can revisit once there's nothing else left to be done.

**Comment by jamesqo** [comment]
@marcind OK, sounds like a fine plan to me.

**Comment by bbrandt** [comment]
FYI, the [VSTHRD100](https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD100.md#vsthrd100-avoid-async-void-methods) analyzer makes this suggestion and can update all instances across a project or solution for you.
![image](https://github.com/xunit/xunit/assets/602767/ee04852d-95f7-4940-8b0a-05f929573940)

**Comment by davkean** [comment]
Just as FYI, for folks landing here, things have changed a bit since above, `async void` is now flagged in v2 projects, v3 has dropped support entirely: https://github.com/xunit/xunit/issues/2573#issuecomment-2080379408.
