### ISSUE TITLE
Assert.True/False on the negation of an expression should be flipped to Assert.False/True

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1435]
Given something like `Assert.True(!expr)` or `Assert.False(!expr)`, we should offer a diagnostic/codefix to change it to `Assert.False(expr)` / `Assert.True(expr)`, respectively. This will compose quite nicely with other analyzers which convert `True` / `False` assertions to something else. For example, `True(!col.Contains(item))` gets fixed to `False(col.Contains(item))`, then another codefix is offered for `DoesNotContain(item, col)`.

We should not check for `!=` expressions, because that should be handled by another analyzer that converts `==` to `Equal` and `!=` to `NotEqual`. (btw @marcind why does `True(x.Equals(y))` only warn when x/y are `string`s and not for other types?)

**Comment by marcind** [comment]
`Assert.True(!expr)` codefix sounds fine. The diagnostic should probably be an `Info` not `Warning`. In this particular case it would be fine to include the overloads that include a message parameter.

I don't think there should be an analyzer for `!=` or `==` comparisons. The semantics (and implementations) of how `==` and `Object.Equals` should interoperate are convoluted enough, offering this as a refactoring might cause perfectly fine tests to break.

Similarly I'm hesitant to have a generic `Assert.True(x.Equals(y))` diagnostic because there are plenty of cases when you might want to be testing the `Equals` implementation itself. Having this rule for strings is fine because the type is sealed. An argument could be made that other types (e.g. primitives like `Int32`, maybe any struct, etc) could be covered, though I'm vary of how large the list would grow.

**Comment by bradwilson** [comment]
Available in `1.5.0-pre.16`.
