### ISSUE TITLE
Compile-time argument validation for Assert methods

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1436]
This idea came to me when I was thinking about `Assert.Contains` and `DoesNotContain`. I made a PR for those functions recently, and I was surprised when I found out they [didn't accept null comparers](https://github.com/xunit/assert.xunit/blob/master/CollectionAsserts.cs#L108) in contrast to the BCL, which treats `null` the same as `EqualityComparer<T>.Default`. It's plausible (esp. since xUnit uses a custom equality comparer by default) someone could write

```cs
Assert.Contains(item, col, null);
Assert.DoesNotContain(item, col, null);
```

expecting to get the behavior of the default equality comparer.

My original idea was to write an analyzer to check just those 2 parameters for a null literal. But if we implement that, then we can also check all of the other arguments in the `Assert` API that should be non-null too, for little extra effort.

**Comment by jamesqo** [comment]
Related: Consider offering a codefix for the above snippets to

```cs
Assert.Contains(item, col, EC<T>.Default);
Assert.DoesNotContain(item, col, EC<T>.Default);
```

**Comment by marcind** [comment]
I'm fine having an analyzer that detects a null literal being passed as the comparer parameter into `Contains` and `DoesNotContain`. I think the codefix should offer to just drop the parameter instead of offering `EqualityComparer<T>.Default` as that would result in terser, more readable code that still behaves exactly the same.

Not sure what you mean by the following:
> But if we implement that, then we can also check all of the other arguments in the Assert API that should be non-null too, for little extra effort.

If the proposal is to also flag `Assert.Contains(item, null)` then I wonder if it's taking things a little too far. I want to consider the likelihood that someone actually writes a bad pattern before creating an analyzer for every conceivable invalid call.

**Comment by bradwilson** [comment]
In the case of null values (which this is about), enabling nullable reference type support in the assertion library is the correct solution to this now, so I'm going to close this.
