### ISSUE TITLE
Error when running beta5 under macOS/Unix

### ISSUE THREAD

**Issue by ErikSchierboom** [xunit/xunit#1443]
I'm busy upgrading the xUnit packages to the beta5 release for the [Cake](https://github.com/cake-build/cake) library. All works well under Windows, but on macOS and Unix I get the following error:

<pre>
Cake.Common.Tests  Total: 3428, Errors: 0, Failed: 0, Skipped: 77, Time: 4.624s
Locating binaries for framework netcoreapp1.0...
Running .NET Core tests for framework netcoreapp1.0...

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'xunit.runner.utility.netcoreapp10, Version=2.3.0.3769, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. The system cannot find the file specified.

   at Xunit.ConsoleClient.Program..ctor()
   at Xunit.ConsoleClient.Program.Main(String[] args)
An error occurred when executing task 'Run-Unit-Tests'.
</pre>

Any idea how this could happen?

For a repro, checkout my `update-xunit` branch in my `cake`  fork: https://github.com/ErikSchierboom/cake/tree/update-xunit To verify the behavior, run `build.sh` on macOS or Unix. You can also checkout out the build result of [the PR](https://github.com/cake-build/cake/pull/1778).

**Comment by ErikSchierboom** [comment]
Addendum: the code used to work, which you can verify by reverting back to 2.3.0-beta2-build3683.

**Comment by bradwilson** [comment]
Working on reproducing the issue, just wanted to let you know that your build script blows through an early error:

![Missing .NET SDK 1.0.4](https://user-images.githubusercontent.com/16944/30523553-1b969686-9b98-11e7-9a46-82086a542299.png)

It does eventually error out again and fail. Anyway, just an aside. :)

**Comment by bradwilson** [comment]
(Some of those errors may be because you assume nobody will re-write the `md` alias, which I have done. You should probably only use built-in commands when writing build scripts, unless you also control the execution environment.)

**Comment by bradwilson** [comment]
It appears that this is an issue related to you installing the .NET SDK into a local `.dotnet` folder rather than the global `C:\Program Files\dotnet` location.

I'm not 100% sure yet, but I suspect the reason is that we are shelling out to run `dotnet.exe` with your test project as the current folder that's causing the failure. It no longer sees the `.dotnet` folder, since the working directory is a couple folders down, which is causing it to use a different SDK, thus causing the failure. If this is the case, I'm not sure whether it's a bug or expected behavior that `dotnet.exe` does not traverse the tree upwards in search of a `.dotnet` folder to find SDKs in.

I didn't have problems running the tests once I'd globally installed the 1.0.4 SDK:

![Run success](https://user-images.githubusercontent.com/16944/30523851-ea95eff4-9b9d-11e7-95d2-617babc7a67b.png)

Thoughts, @natemcmaster?

**Comment by bradwilson** [comment]
Sorry, I'm deleting the previous message, because I think I don't really understand the problem yet.

**Comment by bradwilson** [comment]
Okay, I don't understand why, but the problem is that you left the `xunit.runner.visualstudio` packages at beta 2. Once I upgrade those to beta 5 as well, `dotnet xunit` starts working correctly.

I have *zero* clue why this is, though.

**Comment by ErikSchierboom** [comment]
Thanks a lot for looking into this! It is indeed now working, although I also don't have a clue why that fixes it.
