### ISSUE TITLE
Running Theory test using ClassData attributes gives error when I use two dimensional array instead of List

### ISSUE THREAD

**Issue by RassulYunussov** [xunit/xunit#1456]
I have a simple Point class
```csharp
class Point
{
    int x;
    int y;
    Point(int x,int y)
    {
        this.x = x;
        this.y = y;
    }
}
```

In my test i use next classdata:

```csharp
    public class PointDataClass : IEnumerable<object[]>
    {
        private readonly Point[][] _data = new Point[][]
        {
            new Point[] {new Point(1,2),new Point(2,3)},
            new Point[] {new Point(1,2),new Point(2,3)}
        };
        
        public IEnumerator<object[]> GetEnumerator()
        {
           return (IEnumerator<object[]>)_data.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
           return GetEnumerator();
        }
    }
```

And it produces an error:

```
Failed   mylibtests.MyFirstTest.TestPointsClassData
Error Message:
 System.InvalidCastException : Unable to cast object of type 'SZArrayEnumerator' to type 'System.Collections.Generic.IEnumerator`1[System.Object[]]'.
```

And when I use List<Point[]> instead of two dimensional array, error disappears. 

```csharp
        private readonly List<Point[]> _data = new List<Point[]>
        {
            new Point[] {new Point(1,2),new Point(2,3)},
            new Point[] {new Point(1,2),new Point(2,3)}
        };
```

**Comment by bradwilson** [comment]
The problem is that we expected `IEnumerable<object[]>` or something that's compatible with it. A two-dimensional array is not the same thing as a List of arrays; it is just an array with two dimensions, and is therefore not compatible with `IEnumerable<object[]>`. `List<T>`, on the other hand, does implement `IEnumerable<T>`, and because of [covariance](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/) with `IEnumerable<T>` as well as arrays, then you get `IEnumerable<Point[]>` being type-compatible with `IEnumerable<object[]>`.

This is why it works with `List<>`, but not `[,]`.

That said, you're probably best off just using `TheoryData<>` as your base class:

```csharp
public class PointData : TheoryData<Point, Point> {
    public PointData() {
        Add(new Point(1, 2), new Point(2, 3));
        Add(new Point(1, 2), new Point(2, 3));
    }
}
```

This already correctly implements `IEnumerable<object[]>` for you, and offers type safe data operations.
