### ISSUE TITLE
Visual Studio 2017 CodeLens doesn't show xunit test status

### ISSUE THREAD

**Issue by djohnst10** [xunit/xunit#1474]
In Visual Studio 2017 Professional (15.3.5), CodeLens doesn't show the test status reliably.

When writing a test class, the first test method in the class will have the testing indicators after the first build is done. The test status will allow you to run or debug the test method.

The Test Explorer will show the every test and allows you to run all tests or only the tests you select. The Test Explorer remains reliable in all of the following scenarios when the test status fails,

If you rename the test method, the test indicator remains but won't allow you to run or debug the test method. Clicking Run or Debug will cause the message "Discovering tests..." to flash briefly with no other apparent action.

If you add a second method to the test class, the second method shows no test status at all at any time.

![image](https://user-images.githubusercontent.com/2738319/31031394-61520c5e-a526-11e7-9221-f8b17ba1d601.png)

If Visual Studio is closed and the solution is reopened, none of the test methods, even ones that did show their status before, show their test status.

If you add another test class the pattern is repeated: the first method's test status works until it is renamed, the other test methods' test statuses are completely missing.

The attached demo solution uses the .NET Framework 4.6.1 and xunit 2.2.0. The test project also references xunit.runner.visualstudio 2.2.0 and xunit.analyzers 0.7.0.

The main solution I work on at work uses .NET 4.7 and I've seen the same issues.

I've also tried the latest beta of xunit (2.3.0-beta5-build3769) and xunit.runner.visualstudio (2.3.0-beta5-build3769) and the same issues persist.

I've also tried removing xunit.analyzers but that doesn't seem to make a difference.

[XUnitCodeLensIssues.zip](https://github.com/xunit/xunit/files/1345407/XUnitCodeLensIssues.zip)

**Comment by bradwilson** [comment]
There is a known issue with 2.2 that CodeLens stops working when .NET 4.7 is installed on the machine (whether you're using it or not).

I believe the issue is fixed in 2.3 RC 1, which is not out yet. When I use the latest build from our [MyGet CI feed](https://myget.org/gallery/xunit) (`2.3.0-rc1-build3797`), everything works as expected: existing tests and newly added tests show up correctly in CodeLens:

![Visual Studio 2017](https://user-images.githubusercontent.com/16944/31034660-d5c5b2dc-a519-11e7-8e1e-67f621115e6d.png)

We will be releasing RC 1 to NuGet soon.

**Comment by djohnst10** [comment]
I just updated the repo project I provided and our solution at work to use 2.3.0-rc1-build3797 and it does fix the problem.

I look forward to an official RC1 release soon.
