### ISSUE TITLE
Not found assembly.

### ISSUE THREAD

**Issue by sergius1che** [xunit/xunit#1477]
## Hello
**I have example project:** [xUnitIssue](https://github.com/sergius1che/xUnitIssue)

I run tests: `C:\...\xunitVsDapper>dotnet xunit`
I get an error:
```
xunitVsDapper.Class1.Test1 [FAIL]
      System.IO.FileNotFoundException : Could not load file or assembly 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Не удается найти указанный файл.
```
**Run at:**
Windows 10 x64, dotnet version 2.0.0
**xUnit version:** 
2.3.0-rc1-build3809

How do I run tests from the console?

**Comment by bradwilson** [comment]
This is the problem:

```xml
  <ItemGroup>
    <Reference Include="getDbVersion">
      <HintPath>..\getDbVersion\bin\Debug\netcoreapp2.0\getDbVersion.dll</HintPath>
    </Reference>
  </ItemGroup>
```

You're using a DLL reference without importing any of its dependencies. Why are you doing this? The more appropriate way would be to use a project reference, which automatically brings in all the dependencies:

```xml
  <ItemGroup>
    <ProjectReference Include="..\getDbVersion\getDbVersion.csproj" />
  </ItemGroup>
```

Once you've done that, the tests start running.

Alternatively, if you're intent on using a DLL reference instead of a project reference, you will need to manually add all the dependent references from `getDbVersion.csproj` and make sure you keep them in sync. Frankly, this is a huge pain, and it's why project references exist in the first place. 😄
