### ISSUE TITLE
dotnet xunit fails to load dependent DLLs, but dotnet test succeeds

### ISSUE THREAD

**Issue by Aaronontheweb** [xunit/xunit#1509]
Currently in the process of debugging https://github.com/akkadotnet/akka.net/issues/3150

When I work on the following .CSPROJ within the solution: https://github.com/akkadotnet/akka.net/tree/dev/src/contrib/persistence/Akka.Persistence.Sqlite.Tests

`dotnet xunit` is able to execute the unit tests just fine for the .NET 4.5.2 target, but when it comes time to execute the .NET Core 1.1 target the runner is unable to find the `sqlite.dll` dependency, which is referenced in a child project's NuGet dependencies.

```
        [ERROR][10/13/2017 4:49:26 PM][Thread 0175][akka://SqliteCurrentEventsByPersistenceIdSpec/system/akka.persistence.journal.sqlite] Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
        Cause: [akka://SqliteCurrentEventsByPersistenceIdSpec/system/akka.persistence.journal.sqlite#2004861133]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
           at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
           at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
           at Microsoft.Data.Sqlite.SqliteConnection.Open()
```

This issue occurred rather suddenly this week after we upgraded to 2.3.0. The part that confuses me is that if we run the same specifications on .NET Core using `dotnet test` instead of `dotnet xunit`, everything runs fine and the tests all pass.

Any idea what's occurring here?

**Comment by bradwilson** [comment]
Please try with the latest 2.4 beta 1 build from our [CI builds on MyGet](https://myget.org/gallery/xunit), as this is likely already fixed (and planned for 2.3.1). Let me know if you're still having issues even with the latest build.

**Comment by Aaronontheweb** [comment]
Thanks @bradwilson, I'll give that a try - might be related to https://github.com/xunit/xunit/issues/1490

**Comment by jp7677** [comment]
@bradwilson I'm seeing the same FileNotFoundException here https://github.com/jp7677/hellocoreclr/tree/master/test/HelloCoreClrApp.Test
since I moved to 2.3.0 final. Everything is fine with `dotnet test` and was fine with the latest 2.3 beta. I have tested locally with 2.4.0-beta from nuget and that fixes the FileNotFoundException indeed. Thanks, looking forward to 2.3.1.

Please note though that even with 2.4.0-beta I'm still seeing test failures that are successful with dotnet test and the latest 2.3 beta. The exception looks like:
```
 System.MissingMethodException : Method not found: 'Void Newtonsoft.Json.JsonWriter.set_AutoCompleteOnClose(Boolean)'.
      Stack Trace:
           at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.CreateJsonWriter(TextWriter writer)
           at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
           at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.<WriteResponseBodyAsync>d__9.MoveNext()
```
I wonder if this is related to that commit: https://github.com/xunit/xunit/commit/e79a5abbe343eac2c9648ae676d4b5c2f219c162

**Comment by bradwilson** [comment]
@jp7677 Your problem is a dup of (the bottom half of) #1060.

**Comment by AleksanderKrolasik** [comment]
I have similar problem. Tests passes when I run them from visual studio but fails when run by xunit.console. I import dll using DllImport. Tests fails with message:

System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

Cant solve the problem.

**Comment by bradwilson** [comment]
> An attempt was made to load a program with an incorrect format. 

This usually means that the image you're trying to load is wrong for some reason: wrong bitness (i.e., 32-bit instead of 64-bit) or the wrong CPU (i.e., ARM instead of Intel).

**Comment by bradwilson** [comment]
> And second thing, when I use FreeLibrary, tests stops

Open a new issue with a repro project, please.

**Comment by adamrodger** [comment]
It's the same if you try to read a file (e.g. NLog config) from the current directory. It looks like `dotnet-xunit` changes the current working directory from `MyProject/bin/Debug/netcoreapp1.1` to the directory of xUnit itself. When I run my integration tests I get:

```
System.IO.FileNotFoundException : Could not find file 'C:\Users\<username>\.nuget\packages\dotnet-xunit\2.3.1\tools\netcoreapp1.0\nlog.config'
```

...because my code just tries to access `nlog.config` from the current directory as a relative path (e.g. `File.ReadAllText("nlog.config")`. When I run `dotnet test` then it works fine.

**Comment by adamrodger** [comment]
From looking at the source code, there's a few places where it does:

```csharp
#if NET452
    Directory.SetCurrentDirectory(Path.GetDirectoryName(TestAssembly.Assembly.AssemblyPath));
#endif
```

e.g. https://github.com/xunit/xunit/blob/c7140cbc14a0d190931add88c2c0be9f3f2de440/src/xunit.execution/Sdk/Frameworks/Runners/TestAssemblyRunner.cs#L185-187

Using this, I changed my project to run as `net452` instead of `netcoreapp1.1` and now everything works correctly. It looks like the current directory is only broken when running on .Net Core instead of .Net Framework.

**Comment by bradwilson** [comment]
Original issue is fixed. If there are still outstanding things, please open new issues.

**Comment by adamrodger** [comment]
Raised #1579
