### ISSUE TITLE
xunit1026 fixer is incomplete and will often cause runner exceptions

### ISSUE THREAD

**Issue by dougbu** [xunit/xunit#1513]
`RemoveMethodParameterFix` is not a complete fix for xunit1026 in many (most?) cases. Suggest not offering that fix, providing an alternative that offers a simpler suppression, or perhaps extending xUnit to include a first-class approach that can be used in a fix.

For one thing, the fix is incomplete and will cause exceptions when the runner discovers the theory's data set doesn't match the parameter list. For another, even a more complete fix hits a wall when xUnit extensions generate the data set, the data set is broadly shared, or the theory method has multiple `[MemberData(...)]` attributes.

Example slightly more complete fixers would remove values from `[InlineData(...)]` attributes or drop the user on the right `TheoryDataSet<...>` property (when one exists). Not sure either is possible or particularly general.

My simpler suppression suggestion is to add `GC.KeepAlive(parameter3); // Mark parameter as used.` to the start of a theory method originally similar to
``` c#
[Theory]
[TestDataSet(
    typeof(HttpTestData), "LegalQueryStringParameterNames",
    typeof(HttpTestData), "LegalQueryStringParameterValues",
    typeof(CommonUnitTestDataSets), "EmptyStrings")]
public void TestMethod(string parameter1, string parameter2, string parameter3)
{
    // Use other parameters but not parameter3...
}
```

The above addition is simpler than adding new subset datasets, which would require extensions to `TestDataSetAttribute` in the above case.

----

A data set filtering approach may be workable. But, I don't know whether such filtering could be hooked into the xUnit test data discovery process.

For example, xUnit might offer a new `[IgnoreDataValue(int column)]` attribute. In the above example, it could be used like
``` c#
[Theory]
[TestDataSet(
    typeof(HttpTestData), "LegalQueryStringParameterNames",
    typeof(HttpTestData), "LegalQueryStringParameterValues",
    typeof(CommonUnitTestDataSets), "EmptyStrings")]
[IgnoreDataValue(3)] // 2 if user should consider the value index zero-based.
public void TestMethod(string parameter1, string parameter2)
{
    // Do stuff
}
```

Of course, if the remaining values in the data set include duplicates, should de-dupe them.

**Comment by marcind** [comment]
A lot going on in this suggestion.

> `RemoveMethodParameterFix` is not a complete fix for xunit1026 in many (most?) cases. Suggest not offering that fix, providing an alternative that offers a simpler suppression, or perhaps extending xUnit to include a first-class approach that can be used in a fix.

The fix is complete in the scope of a particular theory method. The user does not have to apply the fix, VS already provides a way to suppress a rule (so no need for `GC.KeepAlive(param)` or anything else like that). It's fine to add new features to xUnit but the analyzers are targeting the behaviors that exist in current and (to certain extent) previous versions of xUnit.

I've been meaning to offer better analysis for Theory parameter matching for `MemberData`, esp. when the referenced member returns a `TheoryData<>`. But even for the typical `yield return` case the data generator could be analyzed, though with some effort.

> Example slightly more complete fixers would remove values from `[InlineData(...)]` attributes or drop the user on the right `TheoryDataSet<...>` property (when one exists). Not sure either is possible or particularly general.

Note that `InlineData` already has analyzers that detect if the values don't align with the test method parameters. Not sure what `TheoryDataSet` (or `TestDataSet` from the exampoe) is but it's not my intention to accommodate every possible way xunit can be extended. If extensions are in play that conflict with a rule, that rule can be disabled/ignored.

Regarding "slightly more complete fixers" I'd like to keep the code focused and doing one thing: if applying one fixer causes other rules to trigger, those should be resolved with their own fixers. I'd like to avoid building composite fixers that try to fix everything up about the project. I recognize that does mean in some cases a user might go through multiple passes of analyzing and applying fixes until no more analysis messages show up, but that's a deliberate design choice.

> For example, xUnit might offer a new `[IgnoreDataValue(int column)]` attribute.

If and when that happens, the analyzer/fix should be updated to take it into account.

**Comment by dougbu** [comment]
@marcind thanx for the detailed comments. Appreciate your point about avoiding composite fixers in particular.

> VS already provides a way to suppress a rule (so no need for `GC.KeepAlive(param)` or anything else like that).

VS uppressions are either hidden away from the relevant code or a knot of verbosity. `GC.KeepAlive(param)` was designed for the purpose of informing the compiler something is used. IOW it's purpose-built for suppressing xunit1026.

> in some cases a user might go through multiple passes of analyzing and applying fixes

This sounds idyllic compared to the current situation where just one fixer exists to followup on the xunit1026 fixer's changes. Users who apply the xunit1026 fixer to theory methods without `[InlineData(...)]` fix a warning but cause runtime failures.

> If and when that happens, &hellip;

My suggestions were otherwise focused on analyzers and fixers. But, this is the xUnit issue list and if `[IgnoreDataValue(...)]` is the only actionable bit here, so be it.

Does the framework have a place to hook something like that in?

**Comment by marcind** [comment]
Let's break this down. Looks like the issue arrises because you have a situation where a single data set is being used by multiple theories, some of which do not use/care about all the fields from the data set objects. In my opinion the best thing to do is to create projections of that dataset that have semantically appropriate fields for the specific classes of theories, but I agree that XUnit does have some friction at the moment to express such projections. I'd suggest you open a separate issue to explore ways of improving this.

Now, onto the analyzer. Let's say you really want to use a single data set and have a theory that's using a subset of the fields.

The existing `#pragma`-based suppression mechanism will do the trick (and is already offered by VS as one potential way to resolve the issue) but it is a pretty coarse solution as it can mask other parameters that are being unused (at least given the typical formatting of method parameters all on one line).

We could offer another fix that better targets a specific parameter. `GC.KeepAlive` is one option although I'm not a fan as it's documented purpose is not to provide suggestions to the compiler but rather influence the behavior of the garbage collector (hence why it is a method on the `GC` object). If I was reading a test method with that call in it I'd be pretty confused. All the same, having a fix that injects `GC.KeepAlive(theParam); // Ignore xUnit1026 rule` at the end of the method could be done.

An alternative would be to have a convention whereby parameters prefixed with `_` are ignored for purposes of this rule. This convention is used in the typescript compiler to opt out of the `ignoreUnusedParameters` option firing a compilation error and it aligns (somewhat) with the standing convention of using `_` as the name of an irrelevant lambda function parameter in C# and other languages. The downside to this is that being a convention, not everyone will be familiar with what it means and they might find a method parameter that starts with an underscore weird too.

**Comment by dougbu** [comment]
Filed the separate issue (#1517)

Small nit:
> it is a pretty coarse solution as it can mask other parameters that are being unused (at least given the typical formatting of method parameters all on one line)

At least with the VS 2017 version I've got, the suppression inserts newlines and places the `#pragma` lines around just the offending parameter. So, the suppression is verbose but not coarse.

**Comment by marcind** [comment]
As per the comments in https://github.com/xunit/xunit/issues/1561#issuecomment-372961831 I'm closing this as "won't fix".
