### ISSUE TITLE
InlineData attribute with decimal is not working properly with 12-15 decimals

### ISSUE THREAD

**Issue by RicardoLans** [xunit/xunit#1529]
I need some help on the following unit test.
```
[Theory]
[InlineData(700, 0.03, 8, 860.911705797409)]
[InlineData(700, 0.03, 9, "886,73905697133127")]
[InlineData(700, 0.03, 10, "913,341228680471208")]
public void Handle_ValidInputs_ReturnsCorrectResult(decimal val1, decimal val2, decimal val3, decimal expected)
{
    //Act
    var result = Calc(val1, val2, val3);

    //Assert
    Assert.NotNull(result);
    Assert.Equal(expected, result, 15);
}
```

here is my Calc function:
```
public decimal Calc(decimal val1, decimal val2, decimal val3)
{
    var result = val1;

    var exponent = (val3 - 1);
    while (exponent > 0)
    {
        result = result * (1 + val2);
        exponent -= 1;
    }

    return result;
}
```

The problem I have atm is that in the last 2 lines of the InlineData i have to put the decimals in "string" notation else the Assert.Equal fails with the following:

```
Message: Assert.Equal() Failure
Expected: 913,341228680471 (rounded from 913,341228680471)
Actual:   913,341228680471208 (rounded from 913,341228680471208100)
```
And
```
Message: Assert.Equal() Failure
Expected: 886,739056971331 (rounded from 886,739056971331)
Actual:   886,739056971331270 (rounded from 886,7390569713312700)
```

The funny thing is though that I am using in the Assert.Equal that it needs to check for max precision and that is 15. But the expected value in the InlineData cannot exceed precision 12 withouth usage of the string notation...

I can work with the string notation but I am curious why InlineData does not support decimals with precision 15 while the Assert does support it.

**Comment by bradwilson** [comment]
`860.911705797409` is not a `decimal`, it's a `double`. This data type has limited precision and accuracy (in particular, you're hitting the [15 digit precision offered to doubles](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/double)).

Normally the answer would be "use a `decimal` value"; unfortunately, [`decimal` is not a type that's compatible with attributes](https://stackoverflow.com/questions/507528/use-decimal-values-as-attribute-params-in-c), so that option isn't available to you with your current code.

You have (at least) two choices:

1. Continue to use strings, and rely on the automatic data conversion;
2. Use a data provider other than `InlineData` (for example, `MemberData`) that doesn't have the same attribute restrictions.

**Comment by RicardoLans** [comment]
@bradwilson thank you for explaining that the InlineData is converted to a double instead of decimal. That explains a lot.

I have reworked my unit test to make use of the MemberData attribute and now its working like a charm with the decimal values up to precision 15, since that is the max precision for decimal in the Assert.Equal method.

**Comment by voroninp** [comment]
Yet for xUnit 2.4.1  when I specify "1.0" in `InlineData` I get error:

> xUnit1010	The value is not convertible to the method parameter 'amount' of type 'decimal?'.

What am I missing?
