### ISSUE TITLE
xUnit1026 should not be raised for parameters named with a starting _

### ISSUE THREAD

**Issue by jp7677** [xunit/xunit#1561]
Let say we have the following test:

```
[Theory]
[SomeMemberData]
public async Task MyTest(string somevalue, string _)
{
 ..
}
```
xunit.analyzers would (technically) correctly throw an xUnit1026 warning: Theory method 'MyTest' on test class 'MyClass' does not use parameter '_'.

I think this warning should not be thrown in this case due to the name being _ and commonly seen as the "discarded operator".

**Comment by marcind** [comment]
Also related: https://github.com/xunit/xunit/issues/1513

**Comment by jp7677** [comment]
@marcind While your issue is indeed related I would prefer such an exception to the rule only for parameters where the full name is _, not for everything that starts with an underscore.

Do you mind reverting the title to the original one?

**Comment by marcind** [comment]
What if you have 2 such parameters that you wish be ignored?

**Comment by jp7677** [comment]
Fair point, though not sure if it justifies a specific xunit convention.

**Comment by marcind** [comment]
One could argue that no convention is justified since you could put an appropriate `#pragma` around the offending parameter(s) to suppress the analyzer. Why have a convention for only 1 parameter?

**Comment by jp7677** [comment]
Well, your solution would include my one. I would say your call.

**Comment by marcind** [comment]
@kentcb what is that link meant to illustrate?

**Comment by kentcb** [comment]
Only that I treat an identifier consisting solely of underscores as a discard. So if you have multiple parameters you wish to discard, you'd just do:
```C#
[Theory]
...
public void foo(int used, int _, int __)
{
}
```

**Comment by ErikSchierboom** [comment]
In like the suggestion by @kentcb. The default discard identifier is a single underscore `_`, but if you would want to have multiple discards (e.g. when using them as parameters), I like the suggestion by @kentcb to use multiple underscores. Just looking if a parameter is prefixed with an underscore could perhaps lead to situations where people somehow use an underscore to start parameters with (although that is not very likely).

**Comment by jamesqo** [comment]
As the person who implemented this analyzer, here's my 2c: what's wrong with `#pragma warning disable` / `#pragma warning restore`? ("It looks ugly" is not an excuse.)

Also, there would be little benefit if we supported this feature, since only a few people (namely, the people reading this thread) would be aware it even exists.

**Comment by jp7677** [comment]
Ignoring _ would be somewhat in line with https://blogs.msdn.microsoft.com/mazhou/2017/06/27/c-7-series-part-4-discards/
I prefer the solution mentioned by @kentcb and @ErikSchierboom for multiple ignores. I would not bluntly ignore everything that starts with an underscore.

I would love to have this feature due to https://youtrack.jetbrains.com/issue/RIDER-11176
My work-around for this rider issue was to introduce a field in the member data that just serves like an index. Obviously I want to ignore this index field in my actual tests. Using pragma is usable, but would unfortunately result in a lot of pragma statements in my current project. Doing so would encourage to disable this warning on a project level which is what I prefer to avoid.

**Comment by jamesqo** [comment]
> Doing so would encourage to disable this warning on a project level which is what I prefer to avoid.

If you have a good reason to disable the warning, there's nothing wrong with doing so. It's just one warning out of the tens offered by this project.

Anyway, I think there's a way we can satisfy both of us here. I assume you have something like this set up for the workaround right now:

```cs
public static IEnumerable<object[]> Data()
{
    yield return new[] { "ReallyLongString1", 1 };
    yield return new[] { "ReallyLongString2", 2 };
}

[Theory, MemberData("Data")]
public void Test(string str, int index)
{
}
```

If that's the case, then just change it to this:

```cs
public static IEnumerable<object[]> Data()
{
    yield return new[] { ("ReallyLongString1", 1) };
    yield return new[] { ("ReallyLongString2", 2) };
}

[Theory, MemberData("Data")]
public void Test((string str, int index) pair)
{
    var (str, _) = pair;
}
```

I understand that it's undesirable to have a lot of pragmas around. However, I don't think we should be introducing new conventions in our project because of a bug in another project. Does the above workaround sound acceptable to you?

**Comment by jp7677** [comment]
Thank you for your suggestion and sample. We are already doing something similar.

I fully agree that there shouldn't be a new convention for a bug in another tool, though that said discarding underscore seems already accepted in c# land, Rider and ReSharper do so as well (irony ;) ). and to be honest I had already expected that the analyzer would work like this. Hence my suggestion here.

Dunno what the reasoning for other people here is.

**Comment by ErikSchierboom** [comment]
My reasoning is that the single underscore is already being treated as a discard option in newer versions of C#, so I figured it might be what people expect when defining a parameter with that identifier.

**Comment by marcind** [comment]
Right, but the difference is that the discard identifier feature in C# allows for any number of such identifiers, all named `_`, whereas that would not be the case here since the compiler would complain about duplicate names.

**Comment by ErikSchierboom** [comment]
That is correct. What is your suggested route of action for this issue?

**Comment by marcind** [comment]
Honestly I'm inching closer and closer to "close as won't fix". The right pragma will work for any number of parameters and be ugly enough to maybe discourage what I see as an anti pattern anyway.

**Comment by wachulski** [comment]
I understand C# 7.0 brings discards to the table for 3 main reasons:
* outs in Try-like methods
* pattern matching (match type, disregards value)
* Value Tuple deconstructions

What's the purpose of discards for unit tests params? In @jamesqo's example parameter discard acts like a deconstrucion. IMO this can be done by an intermediate projection of Data computed by narrowing down original Data collection. Or a dedicated test data structure. Then it's more about encouraging people not to reuse test data rather than having large common test data structures and tricky discards here and there.

**Comment by bradwilson** [comment]
@wachulski The only justification I've seen so far is reusing test data, for test methods which only need some of the data. Example: your test data generates `string firstName, string lastName, string fullName`; some tests use all three, and some tests don't need them all.

I'm not 100% convinced this is a great reuse (and frankly, I'd be using test data transformers in this case rather than ignored parameters).

**Comment by wachulski** [comment]
Huh, @bradwilson I tried to convey exactly what you wrote. My _intermediate projection of Data computed by narrowing down original Data collection_ is your _test data transformers_ 😄

**Comment by marcind** [comment]
After much (and delayed) introspection, I'm closing this as "won't fix". I see discards in theory parameters as an anti pattern for both performance and test intent readability reasons. The existing workarounds are sufficient, IMHO: the warning can be suppressed per violation or disabled altogether in a project, or the test code can be rewritten.
