### ISSUE TITLE
Analyzer xUnit1019 is being fired incorrectly in arrays.

### ISSUE THREAD

**Issue by kidchenko** [xunit/xunit#1567]
xUnitAnalyzer  xUnit1019 is triggering a false positive for arrays.

Steps to Reproduce:

- Create a test method using `Theory` attribute
- Add `MemberData` attribute to the test method method
- In the first parameter of `MemberData` pass the name of one property that is an `object[]`
- The xUnit analyzer erroneously triggers error saying that the `Member must return something compatible with IEnumerable<object[]> with the test data`. This is a false positive since `object[]` are compatible with `IEnumerable<object[]>`

Example:

```csharp
[Theory, MemberData("myArray")]
public void MyTest(int value1, int value2)
{
    Assert.Equal(value1, 100);
    Assert.Equal(value2, 100);
}
public static readonly object[] myArray= { 
    new object[]{ 100, 100 }
};

```
![image](https://user-images.githubusercontent.com/5432753/32650135-3973ad8a-c62f-11e7-80a0-b97e38184149.png)

## Expected behavior

The analyzer should not be triggered because in .NET `Array` implements `IEnumerable`

From the .NET Documentation

> In the .NET Framework version 2.0, the Array class implements the System.Collections.Generic.IList<T>, System.Collections.Generic.ICollection<T>, and System.Collections.Generic.IEnumerable<T> generic interfaces.

If I suppress the analyzer the test pass, proving that this type of construction is valid.

![image](https://user-images.githubusercontent.com/5432753/32650672-3a9a6396-c631-11e7-9f43-84e5a829d0e0.png)

**Comment by marcind** [comment]
Interesting. The analyzer fires because the declared type of the field is `object[]`, whereas the runtime type is `object[][]`. I'm guessing if you changed the declared type to `object[][]` the analyzer would stop firing. (Note that it is not true that `object[]` is assignable to `IEnumerable<object[]>`).

So the analyzer is doing the right thing in the sense that it's going off of the declared type. The experience could be improved if this analyzer (or maybe another one) looked at the assigned type, realized the declared type was underscpecified and offered a refactoring to update the declared type.

Btw, what's that underline in the second screenshot?

**Comment by kidchenko** [comment]
Thank you for your feedback. I changed my declared type to `object[][]` and it worked as expected. 

> (Note that it is not true that object[] is assignable to IEnumerable<object[]>). Sorry, was a mistake. The correct I believe is: `object[]` should be `IEnumerable<object>` and `object[][]` should be `IEnumerable<object[]>`.

I also think that `looked at the assigned type, realized the declared type was underscpecified and offered a refactoring to update the declared type.` is a cool improvement.

The underline in the second screenshot is SonarQube analyzers asking me to `Encapsulate the field` using a property:

![image](https://user-images.githubusercontent.com/5432753/32715140-9599a000-c883-11e7-8eeb-15408e4933c8.png)
