### ISSUE TITLE
XUnit should not use different assembly names for each target framework, as this can cause load failures

### ISSUE THREAD

**Issue by dsplaisted** [xunit/xunit#1594]
XUnit uses different assembly names for each target framework.  For example:

https://github.com/xunit/xunit/blob/1953782eac3d537fbf6826df7b62b308bf456567/src/xunit.runner.utility.nuspec#L36-L49

This causes errors loading assemblies when you have a framework-specific app referencing a .NET Standard project which references an xunit package.  For example:

```
simpleharness.exe -> xunit.performance.api.dll -> xunit.runner.utility.dotnet.dll
(net461)             (netstandard1.5)             (netstandard1.1)
```

In this case, the middle project will be compiled against `xunit.runner.utility.dotnet.dll`, but when `simpleharness.exe` is built, what will be deployed is `xunit.runner.utility.net452.dll`, which means that at runtime it will fail to find the `dotnet` version of the dll it was compiled against.

When compiling the same code for different target frameworks and putting it in a NuGet package, the assembly name should be the same for each version.  So in this case all the versions should just be named `xunit.runner.utility.dll`.

Fixing this would normally be a breaking change, as assemblies compiled against a previous assembly name won't work with a new assembly name.  If you don't want it to break like this, you could continue to also ship the old assembly names, which would just type forward to the new ones.

**Comment by bradwilson** [comment]
Those assemblies have different features and different API sets. They have different names purposefully.

What you want to do is not supported. You need to provide a separate build of xunit.performance.api.dll for each runner utility that you intend to support.

Frankly, at this point, it's probably appropriate for us to remove the netstandard runner utility library anyway, since we don't support running netstandard tests. Runners must make forthright declarations about which platform they're for anyway. We should instead ship one for each concrete supported platform.

**Comment by bradwilson** [comment]
Alternatively, ship the runner utility library inside your NuGet package rather than relying upon a NuGet package dependency. All our runners ship the appropriate runner utility library inside. Example:

https://github.com/xunit/xunit/blob/1953782eac3d537fbf6826df7b62b308bf456567/src/xunit.runner.console.nuspec#L1-L32
