### ISSUE TITLE
xUnit.Core v2.3.1 sets IsTestProject build property blocking consuming projects to be packed

### ISSUE THREAD

**Issue by mishra14** [xunit/xunit#1624]
xUnit.Core v2.3.1 package contains `build/xunit.core.props` and `buildMultitargeting/xunit.core.props`.

As part of https://github.com/xunit/xunit/commit/6ef433fe9a45469a3763efd6e8188bb627c4ef10, the props file was changed to set `IsTestProject`. This breaks package consumers from being able to pack their projects as part of NuGet pack [logic](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L33).

To fix this, the props file should contain another property to allow consuming projects to be packed - 

`<IsPackable>true</IsPackable>`

**Comment by mishra14** [comment]
If this is an unintentional change and needs to be fixed, I have raised a PR for this - https://github.com/xunit/xunit/pull/1625

cc: @bradwilson

**Comment by onovotny** [comment]
Why would a project consuming `xunit.core` need to be packed? It's a unit test project?

**Comment by mishra14** [comment]
Users can have their own scenarios for packing a project which have been working till now. An [example](https://developercommunity.visualstudio.com/content/problem/186365/build-of-nuget-package-on-compile-stops-working-if.html).

The root issue is that xUnit should not prevent consuming projects from being packed. Further, this is a breaking change in behavior from v 2.2.0 to v2.3.1.

@onovotny what is the reason that xUnit should explicitly prevent consuming projects from being packed?

**Comment by bradwilson** [comment]
Users can override this, since .props files are effectively included before their own properties. This change should be unnecessary.

> The root issue is that xUnit should not prevent consuming projects from being packed.

This value is set by VSTest, so even if we removed it, it would still end up being set as soon as you include Microsoft.Net.SDK.Test. This value is set at the guidance of the VSTest team that unit test projects should not be packable by default (guidance we agree with).

**Comment by mishra14** [comment]
Fair enough. I will close the issue and PR.

**Comment by dasMulli** [comment]
@mishra14 about this.. why does NuGet "know" about `IsTestProject`? That's hardly NuGet's concern..

**Comment by mishra14** [comment]
@dasMulli Thats a good point. NuGet pack was changed in this [commit](https://github.com/NuGet/NuGet.Client/commit/407e5969ec3f04c6461d1b42f819f42ee38e97b1). @natemcmaster can answer that better.

**Comment by dasMulli** [comment]
It makes sense that certain project types don't support packing, but it seems there are 2 different approaches here:

1. web sdk defaults `IsPackable` to false
2. Nuget uses `IsTestProject` to determine default for `IsPackable`

would like to see a proper decision on who should own the project modes.. e.g. xunit and/or test SDK should default `IsPackable` instead of NuGet since they own the project/application model.

**Comment by natemcmaster** [comment]
This was the thinking when we did this: https://github.com/NuGet/NuGet.Client/pull/1170#issuecomment-279033654

**Comment by phatcher** [comment]
Can I request a re-think on this, I have a project which is the common test infrastructure within the solution and so doesn't reference Microsoft.NET.Test.Sdk since there's only helper methods there.

I then needed to share this with another business project and it took me a couple of hours to figure out why it wasn't producing a nuget package.  

As other comments have said it complicates producing other libraries that use xunit and actual test projects which reference Microsoft.NET.Test.Sdk will already be set to IsTestProject.
