### ISSUE TITLE
xUnit2000 behavior should account for named arguments

### ISSUE THREAD

**Issue by sharwell** [xunit/xunit#1636]
Analyzer version 0.8.0

#### Code:

```csharp
Assert.Equal(actual: int.Parse("3"), expected: 3);
Assert.Equal(actual: 3, expected: int.Parse("3"));
```

#### Expected result:

No warning on the first assertion.
xUnit2000 reported on the second assertion.

#### Actual result:

xUnit2000 is reported on the first assertion, saying the literal should appear first.
No warning on the second assertion.

#### Rationale:

xUnit2000 is intended to catch cases where the *expected* and *actual* values have been unintentionally swapped. Normally this is based on argument positions. However, when named arguments are used, xUnit2000 should analyze the value for `expected` instead of simply looking at the first argument.

**Comment by tiesmaster** [comment]
Next up, this issue ;) I already looked at this briefly, back in April, and the fix is really easy, but I found out that the diagnostic title/message wouldn't make sense anymore, since we're not talking about first vs second arguments anymore, since named arguments are being used in this scenario, but "argument named 'expected'".

@marcind @sharwell Any suggestion how to handle that?

I see these options:
 * Keep the title as is? (might be confusing)
 * Make use of a different title/message for this specific scenario (but needlessly complicating the analyzer in this case, probably)
 * Or, rephrase the title/message a bit, so it states something like,
   * for title: "Expected value should be first, or the argument named 'expected'"
   * for the message: "The literal or constant value 123 should be the first, or named argument 'expected' in the call to 'Assert.Equal(expected, actual)' in method 'TestMethod' on type 'TestClass'."
