### ISSUE TITLE
Duplicate UniqueId's with tests

### ISSUE THREAD

**Issue by onovotny** [xunit/xunit#1640]
The following tests are generating the same unique id despite having different parameters.
https://github.com/xunit/xunit/blob/master/test/test.xunit.runner.utility/Extensibility/DefaultRunnerReporterWithTypesMessageHandlerTests.cs#L112-L131

```json
{
    "testCaseTitle": "DefaultRunnerReporterWithTypesMessageHandlerTests+OnMessage_ITestAssemblyDiscoveryStarting.LogsMessage(diagnosticMessages: False, expectedResult: \"[Imp] =>   Discovering: testAssembly\")",
    "automatedTestName": "DefaultRunnerReporterWithTypesMessageHandlerTests+OnMessage_ITestAssemblyDiscoveryStarting.LogsMessage",
    "automatedTestId": "dce66a819b1d2a17ad10d31d20bbbaede76cae28"
}, {
    "testCaseTitle": "DefaultRunnerReporterWithTypesMessageHandlerTests+OnMessage_ITestAssemblyDiscoveryStarting.LogsMessage(diagnosticMessages: True, expectedResult: \"[Imp] =>   Discovering: testAssembly (app domain =\"...)",
    "automatedTestName": "DefaultRunnerReporterWithTypesMessageHandlerTests+OnMessage_ITestAssemblyDiscoveryStarting.LogsMessage",
    "automatedTestId": "dce66a819b1d2a17ad10d31d20bbbaede76cae28"
}
```

**Comment by bradwilson** [comment]
The issue is: IDs are unique for test cases, but not for individual tests.

What's happening is that you're running with theory pre-enumeration turned off. This yields one test case per theory, rather than one test case per data row. This one test case yields multiple results, because the data is enumerated at runtime, and each test case can (legally) emit more than one test result. For theories, when data serialization fails, or when pre-enumeration is turned off, a [special test case](https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/Frameworks/XunitTheoryTestCase.cs) is returned, and internally during execution it enumerates the data, and reports one result per data row against the single test case).

So, this behavior is working as designed. The unique IDs are, in fact, unique _**per test case**_ rather than _**per test**_, as might've been assumed here.
