### ISSUE TITLE
Using dotnet --no-build option to test .NET Standard libraries

### ISSUE THREAD

**Issue by eduherminio** [xunit/xunit#1658]
I'm using XUnit to test a .NET Standard library, whose .dll after being compiled is placed in `\bin\Release\netstandard2.0\XXX.dll`.
I intend to test it using `dotnet test XXX.csproj -c Release --no-build`, which expects the compiled .dll to be in `\bin\Release\netcoreapp2.0\XXX.dll`.

Is there any workaround so that I can use `--no-build` option?

**Comment by bradwilson** [comment]
netstandard test libraries are not supported. You must choose a support platform (see the [table here](https://xunit.github.io/#runners) for a list). For `dotnet test` (aka, VSTest), that means either desktop CLR (`net452` or later), or .NET Core (`netcoreapp1.0` or later).

**Comment by drobertson123** [comment]
Are we going to see support for netstandard coming in the future? Is it on the roadmap?

**Comment by bradwilson** [comment]
There's nothing **_we_** can do to make this happen.

The way the .NET build tools today work, the target _platform_ of the code must be known ahead of time to make the code executable. `netstandard` is not a platform; it's a platform-agnostic framework, and therefore cannot be made to be directly executable. This is why all the code you eventually need to run--whether it be an ASP.NET Core app, or a console app, or a UWP app--must at the end of the day be targeting a platform, and not just a framework. `netstandard` can be used for class libraries, because somewhere at the end of the chain, they will be consumed by an application that targets a platform. Your unit test libraries are directly executable; in the most technical sense, by the rules of the build system, they are a form of application, and therefore they, too, must target a platform, not just a framework.

It is unlikely that the .NET build system will change in regards to this requirement anytime in the near future.

**Comment by eduherminio** [comment]
Or both @drobertson123, see for instance [this test .csproj](https://github.com/eduherminio/FileParser/blob/master/FileParserSolution/FileParserTest/FileParserTest.csproj).
That implies having to compile the library against each one of the target platforms chosen in the test project.

Referring back to my original question, `--no-build` option of `dotnet test ` can't be used when testing pure .NET Standard libraries (by pure I mean without any other `TargetFrameworks` than `netstandard` defined) , since they aren't pre-compiled during build process against any specific platform.

Am I right, @bradwilson?

**Comment by bradwilson** [comment]
@eduherminio It is correct to say that `--no-build` will be of no help trying to get `netstandard` test projects to run, because they are not supported (neither with `dotnet test` nor `dotnet xunit`).
