### ISSUE TITLE
Debugging Theory with non-serializable data in DataMember launches debug of all tests cases

### ISSUE THREAD

**Issue by SuperJMN** [xunit/xunit#1679]
Hey guys, working with **Theories** and **DataMembers** (and homologous).

Since the test data "cannot" be serialized, every time I wan to debug a test case, instead of debugging the specified case, it launches ALL of them under the **Theory**.

I looks for a fix for some time and found a guy that has a very clever fix. Please, check this out.

https://stackoverflow.com/a/43968005/1025407

I cannot understand how this isn't included in the official xUnit.

What's your opinion on it? Is there a better way than using this little piece of goodness? :) Could you please implement the [code](https://github.com/DjvuNet/DjvuNet/tree/master/DjvuNet.Shared.Tests/xunit) into the official xUnit?

Bit thanks, and contratulations for this wonderful testing framework :)

**Comment by bradwilson** [comment]
This is expected behavior.

**Comment by bradwilson** [comment]
The implementation of this "work-around" does not validate that the data set is stable, and therefore can give unexpected results.

**Comment by SuperJMN** [comment]
Sorry, @bradwilson, but I don't understand why the behavior I expect (and a wide range of other devs) isn't the actual behavior. I know that no everything can be serialized, but at least it should cover the 90% of the use cases.

For instance, this class

public class MyTestData 
{
      public int { get; set; }
}

doesn't implement the `IXunitSerializable` interface, but it is, in any case, serializable.

I think forcing the explicit implementation is more harmful than beneficial.


Isn't there any other way to make the test explorers (both ReSharper and Visual Studio's build-in) be able to debug different tests properly?

Big thanks in advance :)

**Comment by douglasg14b** [comment]
Unfortunately the forced use of `IXunitSerializable` causes more maintenance problems than it solves with the magic string usage for property names, especially when the members are already serializeable.  This is causing devs to try and create workarounds for the cludgy or unwanted behavior...

**Comment by danstur** [comment]
@bradwilson Could you explain the actual problem here? Enabling diagnostics messages for long running tests, means we also get messages about this behavior, but both the ReSharper and vstest.console test runners behave just as I'd expect (i.e. you can debug single test variations, errors in single tests get correctly attributed).

What's the possible bug this diagnostic is warning about? And what does "the data set is stable" mean here and how would unstable data sets lead to incorrect results?

**Comment by bradwilson** [comment]
This is a stable data set:

```csharp
public static IEnumerable<object[]> MyData()
{
    yield return new object[] { 1 };
    yield return new object[] { 5 };
    yield return new object[] { 9 };
}
```

Every time you call it, you get back the exact same values, in the exact same quantity, and in the exact same order. If any of those things isn't true (different values, different number of values, different order), then the data set is unstable. For example:

```csharp
public static IEnumerable<object[]> MyData()
{
    var random = new System.Random();
    yield return new object[] { random.Next() };
    yield return new object[] { random.Next() };
    yield return new object[] { random.Next() };
}
```

That returns the same number of elements every time, but they are random (different) for each run, so the data set is unstable.

**Comment by danstur** [comment]
@bradwilson Thank you for the answer. So since you can't serialize the data, you have to recreate it for tests and for display purposes - meaning that the test data might not be the same as the displayed data.

The workaround here often requires duplicating production code so it can be extended for test purposes, which is suboptimal. Googling around, I find pretty much nobody actually doing this. Since test data is usually stable few people probably fall into this trap. 

What do you think about a way to either globally disable this particular diagnostic (least amount of effort) or locally declare that the data is stable and that the diagnostic should be suppressed? 

Diagnostics are great to detect long-running unit tests, but Visual Studio showing a text box every time due to this issue makes them hard to use.

**Comment by bradwilson** [comment]
@danstur I'm not sure what diagnostic you're talking about.

**Comment by danstur** [comment]
@bradwilson Oh that's the only reason I care about this.
Create a xunit.runner.json containing
```json
{
  "$schema": "https://xunit.github.io/schema/current/xunit.runner.schema.json",
  "diagnosticMessages": true
}
```
and then use the ReSharper test runner to execute the following test (weirdly enough this only seems to happen with the Full Framework, but not when using netcoreapp2.2) :
```csharp
    public sealed class Test
    {
        [Theory]
        [MemberData(nameof(GetData))]
        public void Foo(Foo a, Foo b)
        {
            a.Bar.Should().Be(b.Bar); // fluent assertions, doesn't matter really.
        }

        public static IEnumerable<object[]> GetData()
        {
            yield return new object[] {new Foo(1), new Foo(2)};
            yield return new object[] {new Foo(3), new Foo(4)};
        }
    }

    public sealed class Foo
    {
        public Foo(int bar)
        {
            Bar = bar;
        }

        public int Bar { get; }
    }
```

Both tests are executed and the result is as expected (first one green, second one fails). The "problem" is the following message box that appears:
![image](https://user-images.githubusercontent.com/34061111/57041713-3186f100-6c63-11e9-8530-dd96730c1be5.png)

(The built-in visual studio test runner just writes the diagnostic to the console where it's not particularly disturbing, if rather ugly).

**Comment by bradwilson** [comment]
Set `DisableDiscoveryEnumeration` on the data attribute that contains the non-serializable data.

**Comment by lemonlion** [comment]
@bradwilson , from what you said, the issue is unpredictable behaviour in classes/records that specifically implement a non repeatable serializable pattern of behaviour in their properties.  This is fair enough, however I feel the user should be able to mark objects they're using as serializable explicitly when they know they are consistently serializable, and do so by mechanisms that are more flexible than inheriting from IXunitSerializable.  For example:

For this given record:

```
record Foo(string Bar1, string Bar2);
```

It would be good to be able to implement one of these patterns:

```
[Theory]
[MemberData(nameof(GetData))]
public void MyTestUsingASerializableInlineAttribute([Serializable] Foo a, [Serializable] Foo b)
{ .... }
```
or

```
[Theory(AllInputsSerializable = true)]
[MemberData(nameof(GetData))]
public void MyTestUsingAFlagInTheoryConstructor(Foo a, Foo b)
{ .... }
```

Either of the above options above gives the user far more flexibility, while still making them assert explicitly that there is no issue reliably serializing their objects in an automated manner.  This is far preferable to having to make Foo implement IXunitSerializable, as that solution is not practical for pre-existing objects, or in the example above where you're declaring a simple one line ordered record.
