### ISSUE TITLE
Unable to set target platform for test runner

### ISSUE THREAD

**Issue by Nihlus** [xunit/xunit#1686]
When using `dotnet xunit`, I'm unable to set the target platform that the tests should run under. For example, if I have tests compiled for `Release|x64`, I am unable to get `dotnet xunit` to execute those tests without relying on environment variables.

The configuration can be set by the `-configuration` switch, but I haven't found any way to set a corresponding platform target.

When using `dotnet test`, I can specify this by using `/property:PlatformTarget=x64` in varying combinations with `/property:Platform=AnyCPU`.

**Comment by bradwilson** [comment]
Platform target cannot be specified with .NET Core, because it is dictated by the bitness of the dotnet.exe that you use to launch the command. There are both 32- and 64-bit versions of the .NET SDK, and you must choose to run the `dotnet` command from the correct executable (32-bit in `C:\Program Files (x86)\dotnet`, 64-bit in `C:\Program Files\dotnet`).
