### ISSUE TITLE
Support operating on binaries additionally to projects with 3.0

### ISSUE THREAD

**Issue by ViktorHofer** [xunit/xunit#1768]
When making xunit 3.0 a global tool, is it possible to support operating on the produced binaries instead of on the project like today with `dotnet test` or `dotnet-xunit`?

EDIT: Does that work today with dotnet-xunit somehow?

**Comment by bradwilson** [comment]
It's unclear whether there will be a global tool for 3.0, because the current plan of record is to make unit tests executable (you will run them with `dotnet run`, not `dotnet test` or `dotnet xunit`).

If there is a global tool, it's sole job would be to allow running multiple projects in parallel and collating the results.

**Comment by ViktorHofer** [comment]
The global tool aspect doesn't really matter here. The question was more about if tests will be executable without a project file to invoke the test runner which you confirmed that I will be possible. Thanks.

**Comment by bradwilson** [comment]
Well...yes and no.

What you think of as a 'stand alone runner' (for example, `xunit.console.exe`) will not really be part of the design of 3.0. The tests will run themselves; linking in xUnit.net will bring in the runner code that's applicable to your target platform, and the result will be directly executable (generating a `.exe` file on desktop CLR, or via `dotnet run` on .NET Core).

**Comment by ViktorHofer** [comment]
Ok thanks for the clarification. That matches what we (dotnet/corefx/coreclr) need and are missing today.
