### ISSUE TITLE
3.0: Improve error messages w/ UWP SDK is not installed

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1819]
When running `build.ps1`, package restore fails if UWP SDK isn't installed:

`xunit.runner.utility\xunit.runner.utility.csproj : error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project.`

Suggestion from @onovotny:

>C:\Program Files (x86)\Windows Kits\10\bin
>look for the sdk version there
>the `TargetPlatformVersion` is the one used for compiling
>even if the TPMV is lower
>more specifically, to ensure the uwp component of the sdk is installed, looking for this could work C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\XamlCompiler

**Comment by Gnbrkm41** [comment]
Oh, well, that was confusing....

Could I ask which version of SDKs do I need, specifically?

**Comment by bradwilson** [comment]
Paging @onovotny...

**Comment by onovotny** [comment]
That project still relies on the original 10240 SDK as the target platform version. I would suggest that the target platform version be raised (that affects what SDK is used, not the minimum supported OS is). I'd also suggest that the minimum be 16299 given support cycles. https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet

**Comment by KirillOsenkov** [comment]
@clairernovotny I've changed 
https://github.com/xunit/xunit/blob/56476a9691bb061661190b183733c5d8a2c6ef4d/src/Directory.Build.props#L18-L19
to 10.0.16299.0 but still hitting the same build error (`The target "_GetRestoreSettingsPerFramework" does not exist in the project`). Any idea what I'm doing wrong? Also filed https://github.com/microsoft/msbuild/issues/5473 because I'm seeing MSBuild weirdness in this scenario too.

Thanks!

**Comment by KirillOsenkov** [comment]
I have a fix available: https://github.com/xunit/xunit/pull/2115

The problem that caused `The target "_GetRestoreSettingsPerFramework" does not exist in the project.` was this MSBuild.Sdk.Extras issue: https://github.com/novotnyllc/MSBuildSdkExtras/issues/127 which was fixed in 1.6.61.
