### ISSUE TITLE
Example of using multiple assemblies

### ISSUE THREAD

**Issue by devdigital** [xunit/xunit#186]
Hi, do you have an example of using multiple assemblies (wildcard pattern) either with the command line tool or the MSBuild task? Thanks.

**Comment by tomap** [comment]
Hi,

Adding more example in the documentation would be great.
It took me some time to figure out how it worked to run tests in parallel for multiple assemblies:

Here is a command line example:

xunit.console.x86.exe -parallel all pathTo\myDll.Tests.dll pathTo\myDll2.Tests.dll
or with a fake path:
xunit.console.x86.exe -parallel all c:\project\myDll.Tests.dll c:\project\myDll2.Tests.dll

note that if you have spaces in your path, you need to add quotes:

xunit.console.x86.exe -parallel all "c:\my project\myDll.Tests.dll" "c:\my project\myDll2.Tests.dll"

Then, the tricky part is running all that inside OpenCover :) :

OpenCover.exe "-target:xunit.console.x86.exe" "-targetargs:-parallel all -xml \"c:\my project\out.xml\" \"c:\my project\myDll.Tests.dll\" \"c:\my project\myDll2.Tests.dll\""

I am not sure how to do that last command in MSBuild without using <Exec /> task.

**Comment by bradwilson** [comment]
Moved here: https://github.com/xunit/xunit.github.io/issues/8 and here: https://github.com/xunit/xunit.github.io/issues/9

**Comment by yokomizor** [comment]
I could not find the new issues. I am looking for an example of how to run multiple assemblies with console runner.

**Comment by cirelli94** [comment]
I can't find any solution neither documentation. Anyone understood how to do this?

**Comment by reduckted** [comment]
For anyone who ends up here trying to work out how to run multiple assemblies with the console runner, it's quite easy, and it's all documented (but not all in the one place).

@tomap's example above is basically correct, but I think the console runner has changed since then because the arguments must now be in a different order.

You just specify each assembly that you want to test as arguments. If you want to configure parallelization, those arguments go _at the end_:

```
xunit.console.exe "c:\my project\a.tests.dll" "c:\my project\b.tests.dll" -parallel all
```

For reference, _[Run tests with the xUnit.net console runner](https://xunit.github.io/docs/getting-started-desktop.html#run-tests)_ states the following:

> The console runner has several command line options, which include options for parallelization, test filtering, and result reporting. **To learn more about the console runner options, run the console runner with no command line options.**

Running the console runner with no arguments outputs the following:

```
usage: xunit.console <assemblyFile> [configFile] [assemblyFile [configFile]...] [options] [reporter] [resultFormat filename [...]]
...
-parallel option   : set parallelization based on option
                   :   none        - turn off all parallelization
                   :   collections - only parallelize collections
                   :   assemblies  - only parallelize assemblies
                   :   all         - parallelize assemblies & collections
```
