### ISSUE TITLE
3.0: Coverage tool

### ISSUE THREAD

**Issue by HamedFathi** [xunit/xunit#1878]
Ut would be great if you support test coverage as embedded feature like Jest in Javascript world.

**Comment by bradwilson** [comment]
Out of curiosity: why? Existing tools (for example, [coverlet](https://github.com/tonerdo/coverlet)) work with xUnit.net already. Endorsing one (or worse, writing our own) seems both unnecessary and divisive.

Should we instead try to find ways for third party code coverage tools to easier integrate with us? What form would you want to see that take?

**Comment by HamedFathi** [comment]
Honestly, I tried xUnit and Coverlet. Both work great but I am looking for a solution to make their test output together.

As I asked this from you today about Xunit test output, my problem is integration between report results.

Suppose you have a project with xUnit and another one with xUnit and Coverlet.

How to integrate their test results in a specific style like JSON, XML or ...
I asked it to have the same result output for doing something like [Allure Test Report
](http://allure.qatools.ru/).

I am looking for a way to save xUnit and Coverlet output results in a web UI or .... as real-time.

The first problem is the uniformity of the structure of the report outputs.

**Comment by bradwilson** [comment]
It's unlikely that xUnit.net would generate a coverage report unless we directly integrated a coverage tool (and I'm not inclined to do that, because it's not a "business" I want to be in). I doubt there is a standardized format (XML or otherwise) that integrates both test results _and_ code coverage, but I can see how a post-processing tool would/could merge the two into a single HTML report. (I also don't think that we should be in that business.)

**Comment by HamedFathi** [comment]
Thanks for your clarification, let me close this.
