### ISSUE TITLE
AssemblyRunner with a dynamic assembly

### ISSUE THREAD

**Issue by nightroman** [xunit/xunit#1896]
Would it be possible to make `AssemblyRunner` working with dynamic assemblies?
As far as I understand, currently I only can specify an assembly by its path.

The use case is F# scripting with FSharp.Compiler.Services. The compiled
interactive session for a script or a set of scripts is effectively a dynamic
assembly. This assembly is exposed by the API. In "scripted scenarios" it would
be useful to define some tests in scripts, send their session dynamic assembly
to a `AssemblyRunner` and invoke tests without some usual hassle.

**Comment by bradwilson** [comment]
Depending on how you view this request, this is either already done or never getting done.

On the "already done" front: you can create an on-disk executable dynamically at runtime that is a v3 test project (and we do in fact do this for some of our acceptance testing, via [`CSharpAcceptanceTestV3Assembly`](https://github.com/xunit/xunit/blob/769ec5c44214da4a45082c38031d6829dd0a09b5/src/common.tests/Compilation/CSharpAcceptanceTestV3Assembly.cs) and [`FSharpAcceptanceTestV3Assembly`](https://github.com/xunit/xunit/blob/769ec5c44214da4a45082c38031d6829dd0a09b5/src/xunit.v3.runner.utility.tests/Compilation/FSharpAcceptanceTestV3Assembly.cs)). The code to do that would be slightly different, as we cannot rely on the NuGet packages to auto-fill the entry points, for example, which you would be able to do. Then `AssemblyRunner` would be able to run that by pointing it to the assembly on disk. (Our sample code only works for .NET Framework, mostly because I haven't spent the time to figure out what the equivalent .NET Core code would look like, especially for F#.)

On the "never getting done" front: there is no way to do an in-memory assembly and make this work in the context of v3, because the v3 architecture is designed around out-of-process executables.
