### ISSUE TITLE
Assert.Equals on two large arrays takes a long time

### ISSUE THREAD

**Issue by ericstj** [xunit/xunit#1907]
I noticed this when comparing 6GB worth of array data.  Assert.Equals takes a very long time: over 10 minutes.  Using Span.SequenceEqual instead is much faster: under 10s.  Here's a micro comparison on a 1MB array that shows a 220x difference.  Sample code attached. [xunitPerf.zip](https://github.com/xunit/xunit/files/2917368/xunitPerf.zip)

Method | Elapsed
------------ | -------------
Assert.Equal | 00:00:00.3534817
Span.SequenceEqual | 00:00:00.0015998

Not sure how many folks are doing assertions with large arrays, but you have an opportunity for an overload with better performance.

**Comment by hughbe** [comment]
This isn't so easy, as we use a custom equality converter to check if each element of the array is equal... I suppose we could special case for things like char/byte arrays?

**Comment by louis-z** [comment]
I just took a quick stab at it (mostly to get familiar with the xUnit codebase) and I too got a pretty impressive performance gain (about 250x faster) using @ericstj's test.

The way I did it was to overload the `Assert.Equal` and `Assert.NotEqual` methods for arrays of unmanaged type T and bypass `AssertEqualityComparer<T>` completely. I had to add a dependency on the System.Memory NuGet package and bump up the language version from 6 to 7.3.

Anyway if that's something that could be of interest, I could create a PR (well, 2 actually because of the use of submodules, right?).
