### ISSUE TITLE
Add Assert.ThrowsAsync() overloads that accepts a ValueTask-returning function

### ISSUE THREAD

**Issue by roji** [xunit/xunit#1919]
More and more async APIs are adopting ValueTask as their return type, to cut down on allocations. It's currently a bit tricky to test these APIs with `Assert.ThrowsAsync()`, which requires a function returning a Task. The workaround is to call `AsTask()` on the returned ValueTask.

It may be relevant to add overloads to other async assertion APIs, so this issue may be wider in scope.

**Comment by weitzhandler** [comment]
Can I PR?

**Comment by weitzhandler** [comment]
It might be hard to develop easily, because when you call a static function you have to specify all the type arguments if one of them can be inferred.

Since `ValueTask<T>` is a solid struct, and doesn't implement a non-generic `IValueTask`, you'll have to go `Assert.ThrowsAsync<ExpectedException, TaskResult>(() => myGenericValueTask);` which is in my vision worse than `AsTask()`.

**Comment by tony6636** [comment]
in my case, that works
`await Assert.ThrowsAsync<ArgumentException>(async () =>  await sut.Get(someArgument));`

the Get method returns the `ValueTask<>` object

**Comment by bradwilson** [comment]
Assert updates: https://github.com/xunit/assert.xunit/commit/74a60f5decc7ba9c9a23cdd64939a4c6503bf161
Core updates: 59683c16301613545fee22d20c70ff4939897cb7
