### ISSUE TITLE
Record Assertion Failures And Report At End

### ISSUE THREAD

**Issue by RehanSaeed** [xunit/xunit#1920]
Currently xUnit throws an exception when an assertion fails which causes the test to fail. It is often useful to have more than one assert in a test like so:

```csharp
[Fact]
public void SomeTest()
{
    var result = new Service().GetResult();
    
    Assert.Equal("Value1", result.Property1);
    Assert.Equal("Value2", result.Property2);
}
```

In the above scenario, if the first assertion fails, you don't know if the second one would have also failed. There are hacks to workaround this that other assertion libraries used like [Assert.Multiple](https://github.com/xunit/xunit/issues/1377) but a better solution would be if xUnit recorded failures and reported them at the end of the test.

There are some who philosophically disagree with having more than one assertion in a test. To them I say:

1. No matter what you think, this pattern is common in the wild and this feature would make peoples lives easier.
2. In the above test, I'm still testing one thing i.e. that the shape of the object is as I expect. I could write two tests for this but imagine if the result had a dozen properties, I'd have to write a dozen tests. It's not a scalable approach IMHO.
3. I don't want to have to use hacks like `Assert.Multiple` that introduce noise into my tests.
4. If this functionality was added, it could produce nicer errors.

**Comment by bradwilson** [comment]
As requested, this breaks the notion of how assertions work (both 1st and 3rd party): they're all based on throwing exceptions. Support for something like [Assert.Equivalent](https://github.com/xunit/xunit/issues/1604) might actually help in this particular case, because you'd be able to write something like:

```csharp
Assert.Equivalent(new { Property1 = "Value1", Property2 = "Value2" }, result);
```

That said, I think maybe there are other ways to accommodate this, albeit with slightly odd syntax, that won't break the existing assertion frameworks:

```csharp
[Fact]
public void SomeTest()
{
    var result = new Service().GetResult();

    Assert.INeedAnInterestingName(    
        () => Assert.Equal("Value1", result.Property1),
        () => Assert.Equal("Value2", result.Property2)
    );
}
```

By separating each assert into a separate lambda (which can be invoked by the framework in individual try/catch blocks), we could run them all and then aggregate the results. Then you're being fairly explicit about your desire to break the default model ("stop on first assertion failure), and you could also enable 3rd party assertion frameworks still:

```csharp
Assert.INeedAnInterestingName(    
    () => result.Property1.Should.Equal("Value1"),
    () => result.Property2.Should.Equal("Value2")
);
```

**Comment by RehanSaeed** [comment]
Your `INeedAnInterestingName` is what I mentioned above and is called [Assert.Multiple](https://github.com/nunit/docs/wiki/Multiple-Asserts) in NUnit.

I raised this because I thought 3.0 was more about moon landing style features. If not, then I'd be happy with `Assert.Multiple` even if it introduces a bit of extra noise to my tests.

I'll certainly think hard about using `Assert.Equivalent`, thanks for the tip. I don't think it will cover all cases but will get some of the way.

**Comment by tullo-x86** [comment]
[FluentAssertions](https://github.com/fluentassertions/fluentassertions) pulls this off using a disposable `AssertionScope` which captures failed assertions, and if any failed, throws them all at once:

```c#
using (new AssertionScope())
{
    someObj.StringValue.Should().Be("this specific string");
    someObj.Date.Should().BeOnOrBefore(DateTime.Now);
}
```

**Comment by bradwilson** [comment]
That technique only works with their own assertions, though (because it relies upon the assertions to not throw exceptions). That's fine for them, since they're not trying to generally solve the problem.

**Comment by mauriciogracia** [comment]
Asser.Multiple is in the roadmap !
