### ISSUE TITLE
What's the best way to compose fixtures?

### ISSUE THREAD

**Issue by candychiu** [xunit/xunit#196]
I organize my fixtures by funtionality, for example, Feature1Fixture, Feature2Fixture, etc.  I'd like to have a CompositeFixture or fixture collection that essentially runs the constructors of the fixtures in order for set up, then run the Dispose in reverse order for tear down.  

What's the best approach for this?  Thanks.

**Comment by bradwilson** [comment]
It's not our intent to provide a generalized solution, because we don't believe that there is a single solution that would serve everybody, nor is it required (since developers can easily achieve what they need within the existing framework).

**Comment by StevenLiekens** [comment]
> developers can easily achieve what they need within the existing framework

Well, no.

I have a fixture that builds an `IConfigurationRoot` which many of my integration tests depend on. The constructor is quite expensive (because of disk and network I/O) so I decided to share the fixture as a collection fixture.

<details>
<summary>Fixture</summary>

```csharp
public class ConfigurationFixture
{
    public ConfigurationFixture()
    {
        Configuration = new ConfigurationBuilder()
            .AddJsonFile("appsettings.json")
            .AddUserSecrets<ConfigurationFixture>()
            .Build();

        // 2-phase build, because the next part requires configuration of its own
        Configuration = new ConfigurationBuilder()
            .AddConfiguration(Configuration)
            .AddAzureKeyVault($"https://{Configuration["KeyVaultName"]}.vault.azure.net/")
            .Build();

    }

    public IConfigurationRoot Configuration { get; }

    public string ApiKey => Configuration["ApiKey"];

    public Uri BaseAddress => new Uri(Configuration["Authority"], UriKind.Absolute);
}
```
</details>

<details>
<summary>CollectionDefinition</summary>

```csharp
[CollectionDefinition("Configuration collection")]
public class ConfigurationCollection : ICollectionFixture<ConfigurationFixture>
{
}
```
</details>

Now what do I do if I want to use the collection fixture in a class fixture without `new`ing it up? There seems to be no way to make a class fixture participate in a collection and get collection fixtures injected as constructor arguments.

I'm worried that a Service Locator is the only solution here. I feel like xUnit.net could do more to help me out. @bradwilson
