### ISSUE TITLE
Analyzers assume strict Xunit attributes, not derived ones

### ISSUE THREAD

**Issue by kzu** [xunit/xunit#1963]
If you create a custom (say) `TheoryAttribute`-derived class, the analyzers that check the presence of `InlineData`, verify that `InlineData` matches method parameters, etc., don't work since they check for the [presence of the exact symbol](https://github.com/xunit/xunit.analyzers/blob/master/src/xunit.analyzers/TheoryMethodMustHaveTestData.cs#L20). Since it's at the symbol analysis phase, it could check whether the attributes or any of its base types equals `TheoryAttribute` instead.

**Comment by bradwilson** [comment]
After consideration and in concert with other issues, the general strategy is to only have analyzers apply in cases where we know with 100% certainty that the rules apply. This means that we generally don't run analyzers against 3rd party extensions since there's no way for us to know whether those extensions have changed the behavior in any meaningful way (and in fact, have had issues opened against our analyzers by third party libraries when we are overly aggressive about trying to enforce rules that may not be true when extensions are in use).

**Comment by kzu** [comment]
Ah, yeah, makes sense. Thanks!
