### ISSUE TITLE
Tests not discovered when inline data is an enum located in ASP.NET Core project

### ISSUE THREAD

**Issue by sandves** [xunit/xunit#1971]
Theory with inline data of type enum where the enum is defined in another project and the project is an ASP.NET Core project is not discovered/executed. It causes the IDE to hang and inifintely scan for tests. Sometimes it causes build errors because the IDE locks some of the files that the build process wants to overwrite.

I have tried multiple versions of Visual Studio (with and without Resharper), JetBrains Rider and dotnet cli. I have also asked my colleagues to clone the [demo project](https://github.com/sandves/bug-demo) and verify. The issue is reproducable and does not seem to be a problem with my setup.

I managed to get the tests working by adding a package reference to `Microsoft.AspNetCore.App` in the test project.

However, I do not think this is a good solution. Why should my unit test project have a dependency on all of the packages in `Microsoft.AspNetCore.App` when none of my tests has anything to do with web? It does not make sense to me. 

The issue is not present when the enum is defined in a dotnet core console project or class library.

I also made an identical test using NUnit and the `TestCase` attribute. This works as expected without adding a reference to `Microsoft.AspNetCore.App`. 

I believe this issue is a duplicate of #1903, but I was asked to open a new one.

**Comment by bradwilson** [comment]
>Why should my unit test project have a dependency on all of the packages in `Microsoft.AspNetCore.App` when none of my tests has anything to do with web?

This is a design flaw with the design of `Microsoft.AspNetCore.App` in that it's not a real package dependency, but a fake dependency that's fixed up with "magic".

Normally, when your test project references your production project, it inherits all the dependencies of that production project automatically. Unfortunately, because of the "magic" of `Microsoft.AspNetCore.App`, this inheritance does not apply, and you're force to add this reference by hand yourself.

There's nothing we can do about this. Your complaint is with the ASP.NET team for not making this dependency inherit like every other dependency does. Maybe this will be fixed in a later SDK, but given the design, I'm skeptical. /cc @damianedwards @davidfowl @terrajobst

**Comment by nguerrera** [comment]
The framework reference will flow (be "inherited") from web prokect to test project in .net core 3.0.

**Comment by bradwilson** [comment]
Sounds good to me!
