### ISSUE TITLE
Add float oriented Assert.Equal with precision

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1984]
I am halfway surprised given its maturity that there is not a ``float`` oriented *Assert.Equal* method. There is a [double](/xunit/assert.xunit/blob/92395f59e3ff47d6d5a1edeced9e99ccfef9fd37/EqualityAsserts.cs#L51) oriented method, there is even a [decimal](/xunit/assert.xunit/blob/92395f59e3ff47d6d5a1edeced9e99ccfef9fd37/EqualityAsserts.cs#L71) oriented method. I should think that comparison is somewhere along the lines of the ``double`` methods.

**Comment by bradwilson** [comment]
What's the value of adding a `float` version as opposed to just using the existing `double` version?

**Comment by mwpowellhtx** [comment]
@bradwilson Are we guaranteed there would not be precision errors converting ``float`` to ``double``?

**Comment by mwpowellhtx** [comment]
i.e. A [Duck search](https://duckduckgo.com/?q=stackoverflow+dotnet+floating+point+precision+errors+converting+float+to+double&ia=web), and [at least one SO article](https://stackoverflow.com/questions/53663632/converting-float-to-double-loses-precision-c-sharp).

**Comment by bradwilson** [comment]
That talked about formatting issues and the imprecision associated with floating points in general, not specifically about any kind of loss of precision.

**Comment by mwpowellhtx** [comment]
Or in this article, [Convert float to double](https://social.msdn.microsoft.com/Forums/vstudio/en-US/1fcf6486-807d-4dce-8aef-7fe5268b568d/convert-float-to-double).

**Comment by bradwilson** [comment]
I looked at doing this on today's live stream, and since we use `Math.Round`, it's not as simple as it appears. There are only `double` versions of `Math.Round` and not `float` versions, so it's not clear to me that we're not back in the same problem, only pushing the cast from `float` to `double` down a layer into our call to `Math.Round`.

Interested to hear alternate suggestions, so tagging this as a discussion item for now.

**Comment by mwpowellhtx** [comment]
Would it make sense to cast `float` to/from `decimal` for the [`Math.Round`](https://docs.microsoft.com/en-us/dotnet/api/system.math.round?view=netstandard-2.0)?

If not, it's cool, appreciate you at least looking into it further. It is not urgent for me at the moment, so if nothing else put it on the shelf in the event that a plausible solution pops up for further consideration.

**Comment by Romanx** [comment]
Was just catching up on the VOD on twitch and saw this issue. Another option that may be more "correct" would be to use [MathF](https://docs.microsoft.com/en-us/dotnet/api/system.mathf?view=netcore-3.1) for the round functionality although i'm not sure if it's available for your targets since its netstandard2.1.

**Comment by bradwilson** [comment]
> Would it make sense to cast `float` to/from `decimal` for the [`Math.Round`](https://docs.microsoft.com/en-us/dotnet/api/system.math.round?view=netstandard-2.0)?

No, because the range of valid decimal values is smaller than the range of valid float values.

> Was just catching up on the VOD on twitch and saw this issue. Another option that may be more "correct" would be to use [MathF](https://docs.microsoft.com/en-us/dotnet/api/system.mathf?view=netcore-3.1) for the round functionality although i'm not sure if it's available for your targets since its netstandard2.1.

Correct, we cannot use MathF.

**Comment by bradwilson** [comment]
Based on the discussion in https://github.com/xunit/xunit/issues/1293 I've added an item in the v3 roadmap to enable tolerance-based `Assert.Equal` for `double` (and deprecate the precision-based version). This should allow me to add a `float` based assertion as well, since our reliance on `Math.Round` will disappear.

**Comment by Xcodo** [comment]
@bradwilson I can take this and copy what I just did for doubles
