### ISSUE TITLE
3.0 Pass values to XUnit tests via command line

### ISSUE THREAD

**Issue by iamfreid** [xunit/xunit#2001]
Pass values to XUnit tests via command line.
Example:
xunit test.dll -params: Key=Value

**Comment by bartelink** [comment]
no have. use env vars is normal advice. remember there are maaany runners beyond xunit.console.exe

**Comment by iamfreid** [comment]
Duct tape. This does not look like a turnkey solution.

**Comment by bartelink** [comment]
Right, lets talk in bigger sentences ;) I've asked for similar in the past.

I was told then (and the fact that no other test framework has implemented such a mechanism is a key data point) that this is not a good idea in general or for xUnit.net in particular. Perhaps MSTest has something like it, but that's definitely not an automatic justification for it as a good idea.

The other point is - resharper, coderush, VS, VSCode etc would all have to build UIs for it etc.

Do you have a specific usecase in mind?

**Comment by bradwilson** [comment]
There is an alternative that will be available in v3, so I'm going to close this.

Because v3 tests are programs and not libraries, you will be able to provide any command line parsing you want by overriding the entrypoint and then extracting anything you like from the command line before passing it along to the in-process runner.
