### ISSUE TITLE
How to limit number of tests running in parallel when using async tests

### ISSUE THREAD

**Issue by mabead** [xunit/xunit#2003]
I am using XUnit 2.4.0 with .NET Core 2.2. I then create the following tests and limit the level of parallelism:

```csharp
using System.Threading.Tasks;
using Xunit;

[assembly: CollectionBehavior(MaxParallelThreads = 2)]

namespace XUnitTestProject1
{
    public class T1
    {
        [Fact]
        public async Task Test()
        {
            await Task.Delay(10000);
        }
    }

    public class T2 : T1 { }
    public class T3 : T1 { }
    public class T4 : T1 { }
    public class T5 : T1 { }
    public class T6 : T1 { }
    public class T7 : T1 { }
    public class T8 : T1 { }
    public class T9 : T1 { }
    public class T10 : T1 { }
}
```

Since all my tests take 10 seconds to complete and that I have 10 tests and that I limit to 2 threads, I would expect the tests to complete in about 50 seconds. Unfortunately, that's not what I see:

```
Starting test execution, please wait...

Test Run Successful.
Total tests: 10
     Passed: 10
 Total time: 11.1830 Seconds
```

Then, if I modify my `Test` function to be synchronous like this:

```csharp
[Fact]
public void Test()
{
    Thread.Sleep(10000);
}
```
I then have the expected behaviour:
```
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Test Run Successful.
Total tests: 10
     Passed: 10
 Total time: 51.2581 Seconds
```

My guess is that when we set `MaxParallelThreads` you simply limit the number of **threads** (as the name suggests) that are used to run the tests but you do not limit the number of **tests/collections** that are executed in parallel. So when the test starts, only 2 of them are started. Then, when they hit an `await`, other tests start as well. So I end up pretty fast with 10 tests running at the same time.

My real tests that did show this behaviour target an external services that don't behave nicely under too much load. I therefore wanted parallelism but not full blown parallelism. This is why I was intending to set `MaxParallelThreads=4` . But as the repros above show and considering that my real tests are `async`, I end up with all my tests that execute at the same time and I still have problem with the external service that fails under load.

Do you have a suggestion to limit the number of **tests/collections** that are executed at the same time (instead of trying to limit the number of threads)?

**Comment by bradwilson** [comment]
This is working as designed.

The thread pool limits how many threads are **executing** simultaneously. It is not a limitation of how many can be started. This is an attempt to limit contention on the CPU (you would ideally choose something which can keep the CPU pegged at 100% with little to no context switching).

Your tests effectively do nothing, yielding back the CPU for their entire run. They are "simulating" long-running async non-compute operations (for example, I/O like disk or network). The system then schedules the next test to run while it waits for the first to complete.

This is definitely the intended and desired behavior.

**Comment by mabead** [comment]
I understand that it works as designed. I have changed the title of the issue to better reflect my original question (sorry for the misleading title):

> Do you have a suggestion to limit the number of tests/collections that are executed at the same time (instead of trying to limit the number of threads)?

If there is nothing built-in, please consider this as a feature request for a future version of xunit ;)

Note that I tried to use a [Polly Bulkhead](https://github.com/App-vNext/Polly/wiki/Bulkhead) somewhere in my code but I ended with the same problem that my downstream service was still collapsing under load.

**Comment by bradwilson** [comment]
It's unlikely that we will implement the feature you want. Our feature is explicitly designed to try to limit the number of _actively executing_ tests so as to maximally utilize the compute resources of the box. Limiting the number of tests to be _started_ (whether executing or not) will dramatically reduce the performance of the framework.

**Comment by mabead** [comment]
I understand. Thanks for your input.

**Comment by APIWT** [comment]
@bradwilson Please consider the question that OP asks once again. Our issue is that we use an Xunit suite to run a very large acceptance test suite against an actual API that limits us, and we do not have an easy way to say "just run 2 tests max at a time". Do you have any suggestions?

**Comment by bradwilson** [comment]
There is no good answer here for code that uses `async`.

By design, code that uses `async`/`await` will return a worker thread to the thread pool while it waits for asynchronous operations to complete. The mechanism we use is a limited sized worker thread pool. When async code goes into a "wait" state and the thread pool thread is returned, then it's ready for an additional test to run on it. This is 100% by design, in an attempt to allow asynchronous code that is I/O bound to continue to maximize the use of the CPU with other tests that could be running, rather than just idling the CPU.

**Comment by mabead** [comment]
@bradwilson @APIWT I once tried to use the [bulk head policy of Polly](https://github.com/App-vNext/Polly/wiki/Bulkhead) to limit concurrency in my tests. I don't know how the code of xunit is structured, but I think that this could be an option to limit the number of tests that are running in parallel.

**Comment by bradwilson** [comment]
I don't think you're understanding what I'm trying to get across, which is: our code works the way we want it to work. I don't consider it broken. It properly limits the number of *actively running* tests.

When a test is blocked waiting for async operations to complete, it isn't running, and another test can and should have the opportunity to run. That's how you maximize the utilization of the CPU and finish running the most tests the quickest. That's the goal of the design, and it achieves that goal.

**Comment by mabead** [comment]
I don't think you're understanding what we are trying to get across, which is: 
* we completely understand the design that you have and we agree with it. Maximizing the CPU utilization is an essential concern and it's a very common need.
* there are scenarios when the goal is **not** to optimize the CPU utilization. We want tests to run "faster" but not "as fast as possible". When doing tests against a real service for example (ex: integration/component/system tests), if we run our tests "as fast as possible" it breaks the service under test because there is just too much load at the same time. A feature to throttle the speed of the tests would therefore be helpful.

So don't consider this issue as "we think your design is wrong". Please instead consider it as "we see a useful feature that could be added to xunit".

**Comment by stephenjg24-git** [comment]
If I am reading this incorrect, forgive me.   It sounds more like you wish to throttle the api tests as to to kill the web services.  



Stephen

**Comment by APIWT** [comment]
@mabead I could not agree more. I echo the fact that we completely understand the design philosophy. Simply suggesting a useful feature that could help people in the future.

Also, thank you for your suggestion of using bulkhead feature of `Polly` to essentially limit the requests. I will look into this, and I think it will work in my case.

**Comment by marcin-krystianc** [comment]
@bradwilson 

When I was reading docs I thought that `[assembly: CollectionBehavior(MaxParallelThreads = n)]` is a way to limit the number of tests that can run in parallel, but now I know that it is not. I think that it would be great that you extend the documentation with more detailed explanation on how it actually works.

Also it is unclear why a functionality to limit the number of threads to a fixed number exists in the first place. Test assembly doesn't have any control over the hardware on which tests are executed, so any fixed number used in the `MaxParallelThreads` attribute is by definition wrong (not optimal). Is there any valid use case for it ?

**Comment by ChrML** [comment]
We currently have a project with about 3000 tests, and roughly ~300 of are async and in some way test timing. Such as timeouts working correctly etc...

Unfortunately our pipeline currently fails 2 out of 3 times these days, because of too many tasks running in parallell. When 1000 tests are started simultaneously, there is simply not enough CPU to perform timing tests in a consistent manner, and a simple line such as `await Task.Delay(100);` quickly becomes 800 ms because too many pending tasks in the task queue. Hence test fails if it the purpose of the delay is to wait for a timeout that we expect to report before 500 ms.

Please reconsider implementing max concurrent async tests. It should be opt-in, and would not limit the performance of xUnit in normal use cases that do not depend so much on timing.

**Comment by Pasukaru** [comment]
We are experiencing the same issue.

In our case, we are running integration tests against our database.
Not being able to limit the number of concurrent tests leads to tests failing because they rapidly consume all available connections.

**Comment by two2tee** [comment]
We are also experiencing the same issue when we are using the framework for integration tests.
As with the others, not being able to limit the number of spawned tests would force us to disable TestParallelization all together which is a huge performance hit, while enabling it breaks the tests alltogether.

**Comment by berkeleybross** [comment]
We have the same feature request, since we are using XUnit as an integration test runner not a "unit" test runner.

We can implement a workaround such as Polly BulkHeads, but that then means the tests queue up and the reported execution time is misleading: `reportedExecutionTime = queueTime + executionTime`

Having the queuing being done natively in XUnit would help us identify actually slow tests. Ideally, it would be opt in since we only want this mode for integration tests

**Comment by bart-degreed** [comment]
Same here. We're running ~2000 integration tests against a PostgreSQL database during day-to-day development and in cibuild. Our only option today to make that work is to **turn off parallelism entirely**. I'd like tests to run in parallel, but after a few seconds where 70% has succeeded, the remaining ones fail with this message from the database:
```
53300 "sorry, too many clients already"
```
So the database properly has rate limiting in place. However, that does not help us. It would help us immensely to be able to configure "max 100 tests in parallel" instead of the current behavior.

In another project, I had to turn off parallelism too, because MongoDB (running in a docker container) couldn't handle the load caused by running all tests in parallel.

**Comment by StephanKirsch** [comment]
Same here - have the problem in using RavenDB (running into occasional time-out exceptions at arbitrary test cases) as soon as the build server has too many CPU ressources available. Really need a feature to control (throttle) that parallelism (e. g. MaxNumberCpuCoresUsed). But definitely cannot run all tests sequentially, takes too long.

**Comment by EklipZgit** [comment]
@bradwilson 
I'd just like to be very clear that this

> I don't think you're understanding what I'm trying to get across, which is: our code works the way we want it to work. I don't consider it broken. It properly limits the number of actively running tests.

> When a test is blocked waiting for async operations to complete, it isn't running, and another test can and should have the opportunity to run. That's how you maximize the utilization of the CPU and finish running the most tests the quickest. That's the goal of the design, and it achieves that goal.

seems to be looking at one side of a multi-dimensional problem. You have given users a single tool to solve a single dimension, _cpu utilization_, and completely ignored the fact that there are tons of other variables at play here.

I have 2500 tests.
Each test uses a test fixture https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-7.0 that runs my entire web api middleware effectively. Each test sets up a bunch of external mocks so that we're effectively unit testing our api+database at the api call level, mocking nothing internal to the service and database but mocking all external systems.
Each test sets up its own base environment config that the specific endpoint tests will act against.
I'm describing a pretty standard, solid, api level test harness, am I not? Nothing crazy.

A given test can maybe utilize half a core since it drops to DB (also running on same machine) and there are IO losses and whatnot, so optimally on an 8 core machine maybe 16-20 tests should be "running" whether blocked on IO or whatever, at any given moment in time. (8 active threads, sure).

I now have two options: Have my test run take 18 minutes instead of 3 minutes by utilizing half a core on an 8 core machine for 18 minutes, OR I can enable parallel test runs which (because test initialization is async) results in 
* like 2000 tests all trying to set up their base environment at once, 
* 2500 instances of the API being spun up in memory at once, 
* 2000 tests all blocking on database calls at once, 
* many tests timing out at the 1 minute DB query timeout because they just got unlucky due to the sheer volume of stuff XUnit allowed to spin up, 
* my machine having 17gb memory used by testhost because 2000 webapi instances is kind of a lot... You get the point. 

There isn't even a way with Fixtures that can prevent them all from spinning up in parallel when you await in the init async as far as I can tell. Though I would love to be wrong here? As a workaround I've thrown a semaphore super early in the async initialization to block as much memory consumption as possible and only let 20 tests enter at once (which solves the hundreds of tests hitting the 1min db timeout because too many active queries), but we still hit insane amounts of memory because the fixtures and all mocks and properties associated with them already exist by that point.

It feels like someone has made an architectural decision based on one dimension (low async unit tests) of testing's intersection with one dimension (cpu) of resource contention, and concluded that everyone in here complaining about not being able to throttle concurrent tests is wrong. Is your position then that XUnit is just not the right framework for integration tests? It is the wrong framework for high memory heavy async tests? It's the wrong framework for using Test Fixtures? Are we supposed to just make 16 different test projects and run them all serially to prevent spinning up 2500 instances and do 16 x 150 at a throughput hit?

From my perspective, there should be a setting to cap concurrent tests, separate from the setting to cap concurrent threads. There is no reason that my test project should ever have more than 30 instances of the webapi pipeline alive at once; if all 30 tests are waiting on IO, then they are waiting on SQL queries which are also eating CPU on my box _which is outside of XUnits awareness_ so all xunit is doing by spinning up more and more is throwing more gasoline on the resource contention fire and giving the SQL instance less and less cpu time to finish out the tests that are already blocked. I'd be interested to hear how to solve my scenario in some other way without any of the ad-absurdum ones above while still maintaining that there is no valid reason to cap concurrent tests.

Am I missing something?

**Comment by mabead** [comment]
@EklipZgit The problem that you face is very similar to the one that I described more than 3 years ago. I hope that you will be able to convince @bradwilson that a need exists... but I doubt that you'll succeed given his multiple push backs.

As a workaround, I think that it would be feasible to build on the idea of [Meziantou.Xunit.ParallelTestFramework](https://github.com/meziantou/Meziantou.Xunit.ParallelTestFramework). That nuget makes it possible to run **all** tests in parallel by creating one collection per test (each collection runs in parallel). I think that it could be possible to build on that idea by creating a fixed amount of collections (instead of one collection per test) and randomly assigning the tests in these collections. It is not perfect but it may be better than nothing...

**Comment by bradwilson** [comment]
@EklipZgit You are correct that our primary use case and design is based on unit testing. The fact that people use xUnit.net for other types of testing is something we wish to enable through third party extensibility as much as reasonably possible, but when there is a conflict between the needs of unit testing vs. everything else, we will always opt on the side of unit testing.

There is no way to achieve what you're after with what we ship today. As @mabead points out, there may be third party extensions that make it simpler to do what you're trying to achieve. We have no plans to do anything in this area.

**Comment by StephanKirsch** [comment]
Just to mention - some more unit tester here (app. same amount of tests) which would benefit from such a limit. I don't think this goes against unit testing. We have unit tests of code running async stuff (which does not mean that the CPU is idle, it is e. g. used by the database engine underneath in a different process) and code that depends on realtime behavior (e. g. putting timeouts to DB requests). Whenever you have that situation, which should be very common, it is a very valid idea to control the amount of tests runnning in parallel, I believe.

**Comment by EklipZgit** [comment]
@bradwilson 
> but when there is a conflict between the needs of unit testing vs. everything else, we will always opt on the side of unit testing.
What is the conflict? 
If I add a new, opt-in setting that does what we need in a PR to the xUnit source (which sounds far better than a throughput destroying hack based on randomly populating test collections in an extension), will it be rejected on principal because xUnit is not for integration testing?
Or are you implying that there is something core to the architecture of xUnit that prevents an optional flag for this from being added?
Serious question, implementing a solution in xUnit myself sounds like about as much work as cutting over to another test framework at this point, and our tests are just not reasonable to run anymore due to this issue so I need to do something.

**Comment by bradwilson** [comment]
> What is the conflict?

Changing the way parallelization works.

> If I add a new, opt-in setting that does what we need in a PR to the xUnit source (which sounds far better than a throughput destroying hack based on randomly populating test collections in an extension), will it be rejected on principal because xUnit is not for integration testing?

I will evaluate a PR that fixes this without breaking anything else (and does not overly complicate the usage of the framework). If you're unsure, perhaps more discussion on what the change would be, and how it would be surfaced, would be the next step before committing to the coding piece.

> Serious question, implementing a solution in xUnit myself sounds like about as much work as cutting over to another test framework at this point, and our tests are just not reasonable to run anymore due to this issue so I need to do something.

I understand, but I'm definitely not going to the one to implement this (for the aforementioned reasons). I appreciate the effort if you choose to do it, but it's also an entirely reasonable decision on your part to just move to a different framework when ours does not suit your needs.

**Comment by Ruud2000** [comment]
>...
> I have 2500 tests. Each test uses a test fixture https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-7.0 that runs my entire web api middleware effectively. Each test sets up a bunch of external mocks so that we're effectively unit testing our api+database at the api call level, mocking nothing internal to the service and database but mocking all external systems. Each test sets up its own base environment config that the specific endpoint tests will act against. I'm describing a pretty standard, solid, api level test harness, am I not? Nothing crazy.
>...

We're doing our integration tests exactly the same as you describe @EklipZgit and we run into similar issues. It would be absolute great to have control over the number of tests running in parallel in this scenario.

**Comment by Brokolis** [comment]
I had the same problem, found this thread and realized there is currently no solution to this, so I decided to make a solution myself.

[You can find my solution in this gist.](https://gist.github.com/Brokolis/8ca83b4516bb572760bd604b98991117)

Thanks to the xUnit team for making xUnit this customizable, which enables us to extend xUnit in our own ways!

**Comment by venkatr21** [comment]
@Brokolis Thanks for posting this solution, this works like a charm. However, an issue which I face during this implementation is the ordering of the tests.
Here is my scenario:
I have 10 collections in total, 8 collections have a single test class, while 2 collections have multiple test classes (which needs to run sequentially). But i see the order of test classes in the collection is not maintained. Is that something which we have control over?

**Comment by bradwilson** [comment]
By-default random ordering is a feature of xUnit.net.

To override this, you can implement a test orderer. Sample: https://github.com/xunit/samples.xunit/tree/main/TestOrderExamples

**Comment by venkatr21** [comment]
@bradwilson I did check this out, this has ordering for test cases, test collection.
How do i specify the test class ordering in the same collection?

**Comment by bradwilson** [comment]
The two orders work like this:

- TestCollectionOrderer is used to order collections against one another; it should be called once with all collections. You don't need this.
- TestCaseOrderer orders the test cases inside a test collection; it should be called once per collection with all the test cases in that collection (assuming it's an assembly- or collection-level test case orderer). This is what you need.

Because you're given all the test cases for a test collection at the same time and set the order, it's up to you whether class takes part in that decision or not.

The sample doesn't make this clear, so I'll update it. I'll also open an issue to create a documentation page for test ordering, since the samples are a sub-par way to learn how to do this.

**Comment by venkatr21** [comment]
@bradwilson Do you mean to say this:
under a particular test collection, let's say there are 3 test cases A, B, C. Each test case is defined under different classes let's say A,B,C.
So, the test suite looks like this:
one collection G,
under the collection G there are three test classes A, B and C
each of the class has a test case.

So, if I specify (assume less the number more the priority given)
TestPriority(1) for test case A
TestPriority(2) for test case B
TestPriority(3) for test case C

Do you mean to say irrespective of the classes the test steps will always run in the order A,B,C?

**Comment by venkatr21** [comment]
@bradwilson Got it, thanks for letting me know
> It would appear that you cannot do this via the test case orderer.

But yes, as @Brokolis mentioned, https://gist.github.com/Brokolis/8ca83b4516bb572760bd604b98991117 please do consider this to be a potential feature extension for x-unit. Would make this framework more powerful.

**Comment by bradwilson** [comment]
The reason I mis-remembered is that this is already an open feature request for v3: https://github.com/xunit/xunit/issues/1829

**Comment by jcracknell** [comment]
Yeah, I ran into this as well, I'm not sure why this isn't mentioned in [the "getting started with integration testing" guide][0], but at any kind of scale you'll have massive problems.

Dumping everything into the thread pool works fine if your tests are mostly synchronous as they never let go of the thread, but as soon as you have async tests, you'll start a transaction, lock some rows, release the thread, and get deadlocks because the scheduler has to cycle through thousands of other tasks before it gets back to continue the transaction.

@Brokolis's rewrite of the TestAssemblyExecutor works well to address this. In addition, I'll note that limiting the number of running tasks to something on the order of 4 x CPUs will have no effect on synchronous test performance (as you can only run one per core), and should probably improve performance for IO bound async tests, as you'll reduce access/lock contention. Obviously you'd need to tune this based on your test suite and environment.

The other trick you have available is CollectionBehavior.CollectionPerClass, which will cause (theoretically similar) tests defined in the same class to run serially, which may also reduce contention.

[0]: https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-7.0

**Comment by klinki** [comment]
I have also problems with too many tests running in parallel in integration testing scenario. Pretty much the same issue 
 as described in comment https://github.com/xunit/xunit/issues/2003#issuecomment-1423381563 .

I'm using TestContainers and MySQL container for integration testing.

I had so much trouble with tests so I had to opt-out of parallel execution completely. Tests started with spinning up 8 MySQL containers at the same time and waiting for them to initialize. As they all tried to initialize at the same time, it consumed massive amount of resources (CPU, memory) and lot of times it just crashed and didn't initialize properly.

**Comment by bradwilson** [comment]
@klinki Have you tried using 2.8.0 or later? We implemented a new parallelization algorithm. https://xunit.net/docs/running-tests-in-parallel#algorithms

**Comment by aomader** [comment]
@bradwilson We gave that ago but we noticed that the parallelization drops over time. For example, on my machine I could observe that it started out ambitious with 30 tests running in parallel (I configured "4x" via the `xunit.runner.json`, so I would have expect 40 as I have 10 logical cores), which than continuously dropped to finally running only one test at a time. Could you imagine a reason for such a behavior?

**Comment by bradwilson** [comment]
Parallelism is done hard on test collections (the default being one collection per test class), so maybe you were finishing test collections over time so the amount of collections left to run dropped.

**Comment by TristenFielding** [comment]
> We currently have a project with about 3000 tests, and roughly ~300 of are async and in some way test timing. Such as timeouts working correctly etc...
> 
> Unfortunately our pipeline currently fails 2 out of 3 times these days, because of too many tasks running in parallell. When 1000 tests are started simultaneously, there is simply not enough CPU to perform timing tests in a consistent manner, and a simple line such as `await Task.Delay(100);` quickly becomes 800 ms because too many pending tasks in the task queue. Hence test fails if it the purpose of the delay is to wait for a timeout that we expect to report before 500 ms.
> 
> Please reconsider implementing max concurrent async tests. It should be opt-in, and would not limit the performance of xUnit in normal use cases that do not depend so much on timing.

We had the same problem, here is how we solved it:
1. We use DI. 
2. We created a IClock interface which exposes a single property called `NowUtc`. Which all of our code uses.
3. In our tests, we implemented a simple `TestClock` and our tests refer to this clock as `CurrentVirtualTime`.
4. In our tests, we instantiate our ASP.NET WebAPI service, using `WebApp.Start<TestStartup>()`. Thus our tests, webAPI, business layer, etc. all use the same Clock instance and we control everything using virtual time. 
5. Our business services emit C# events (as a enum value) that our tests can record.
6. We created an EventRecorder class:
    1. The class has an event listener that records the actual events.
    2. The main method, `public Task WaitFor(params MyEventEnum[] expectedEvents)`, records the expected events, along with checking timeout, skipped events, unexpected events, and calls `Task.Delay(100)` in a loop. If all the expectedEvents have been accounted for, then the method returns, it the test timeout (which is captured in the `EventRecorder` ctor) then a timeout exception is thrown. 
    3. At the end of our test, we use eventRecorder.AllRecordEvents to write to our test ouput, all the events that was recorded. We support `List ExcludeEvents` to exclude events we don't care about thus we use `eventRecord.TrackedEvents` in our asserts, 
8. Thus, using a virtual clock and an event recorder that waits for actual events and not on real-time sleep, we have eliminated these issues.

Here's a real .NET FX example, we are testing a Windows service with EF 6.4.4 thus we have to use a real database backend:

Here's our TestClock implementation
```
public class TestClock : IClock
{
    /// <summary>
    /// Get or set the function that returns the test date/time as the current date/time.
    /// </summary>
    public Func<DateTimeOffset>? GetDateTimeOffset { get; set; }

    /// <summary>
    /// Get the current UTC time.
    /// </summary>
    public override DateTimeOffset UtcNow => GetDateTimeOffset?.Invoke() 
     ?? throw new ArgumentNullException($"Configure {nameof(GetDateTimeOffset)} before accessing {nameof(UtcNow)}.");
}
```

part of our test base class
```
public abstract class TestBase : IDisposable
{
    /// <summary>
    /// Used to set the current "virtual" time for testing purposes.
    /// Note each test get their own instance of <see cref="TestClock"/>.
    /// </summary>
    protected DateTimeOffset CurrentVirtualTime { get; set; }

    protected virtual void ConfigureContainer(Container container, bool useTestDevEnv = true)
    {
        container.Register<IClock>( () => new TestClock { GetDateTimeOffset = () => CurrentVirtualTime });
    }
}
```

Here's one of our tests:
```

    [Fact]
    public async Task Schedule_OnDataChangedEvent_Test()
    {
         // We use DateTimeOffset.UtcNow so that our virtual time start close to real-time, 
        // then we advance our CurrentVirtualTime when we choose.
        //
        var initialStart = (DateTimeOffset.UtcNow + TimeSpan.FromHours(1.0));
        var updatedStart = (initialStart + TimeSpan.FromHours(3.0));

        var schedule = await CreateDailyScheduleAsync(initialStart);
        try
        {
            var service = Task.Run(async () => await _schedulingService.StartAsync());
            await _recorder.WaitFor(SchedulingEvent.Starting, SchedulingEvent.Started);

            var updatedSchedule = await UpdateStartDateTimeAsync(schedule, updatedStart);
            CurrentVirtualTime = updatedSchedule.NextRunTime!.Value;

            await _recorder.WaitFor( SchedulingEvent.ScheduleChanged,
                SchedulingEvent.ExecutingSchedule,
                SchedulingEvent.ExecutingCallback, SchedulingEvent.ExecutedCallback, 
                SchedulingEvent.ExecutedSchedule);

            _schedulingService.Stop();
            await _recorder.WaitFor(SchedulingEvent.Stopping, SchedulingEvent.Stopped);

            await service;

            Write(_recorder.AllRecordedEvents);
            _recorder.TrackedEvents.Should().BeEquivalentTo(_recorder.ExpectEvents, o => o.WithStrictOrderingFor(x => x));

            var foundSchedule = await GetScheduleAsync(schedule.Key);
            foundSchedule.Should().NotBeNull();
            foundSchedule.LastRunTime.Should().Be(CurrentVirtualTime);
            foundSchedule.NextRunTime.Should().Be(CurrentVirtualTime.AddDays(1));
        }
        finally
        {
            await _scheduleCoordinator.DeleteScheduleAsync(schedule.Key);
        }
    }
```

Hope this helps.

**Comment by stevendarby** [comment]
I found this issue via the playwright documentation, where it mentions why xUnit isn't supported for parallel tests: https://playwright.dev/dotnet/docs/test-runners#xunit-support

I was looking at the notes for xUnit v3, and found this:

> `CollectionBehaviorAttribute` has a new property (`ParallelAlgorithm`) that can be used to set the parallel algorithm for the test assembly. This value can be overridden by a configuration file or a command line switch to the runner. If the value is not set, the default (`ParallelAlgorithm.Conservative`) is used.

The `ParallelAlgorithm` enum with XML comments can be found here: https://github.com/xunit/xunit/blob/main/src/xunit.v3.common/Options/ParallelAlgorithm.cs

The comments for Conservative (the default) are:
```
The conservative parallelization algorithm uses a semaphore to limit the number of started tests to be equal
to the desired parallel thread count. This has the effect of allowing tests that have started to finish faster,
since there are no extra tests competing for a chance to run, at the expense that CPU utilization will be lowered
if the test project spaws a lot of async tests that have significant wait times.
```

Am I right in understanding that this essentially delivers what this issue was requesting? And not only that, it'll be the default behaviour?

**Comment by bradwilson** [comment]
> Am I right in understanding that this essentially delivers what this issue was requesting? And not only that, it'll be the default behaviour?

That is correct.

**Comment by stevendarby** [comment]
FYI- https://github.com/microsoft/playwright-dotnet/issues/2977
