### ISSUE TITLE
Confusing assertion message when comparing floats.

### ISSUE THREAD

**Issue by marcin-chwedczuk** [xunit/xunit#2016]
Test that illustrates the problem:
```cs
        [Fact]
        public void demo() {
            var f1 = 6.00000048f;
            var f2 = 6.0f;

            Assert.Equal(f2, f1);
            /*
  Error Message:
   Assert.Equal() Failure
Expected: 6
Actual:   6
  Stack Trace: */
        }
```
Clearly format used to convert `float` to string in assertion message formatted is wrong. If values are not equal they should show up as such in the error message.

I am using
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.0.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
  </ItemGroup>
```
and dotnet core on ubuntu:
```
$ dotnet --version
2.2.300
```

**Comment by bradwilson** [comment]
I looked into this, and the issue is that the `Assert` this example uses is the generic version of [`Assert.Equal<T>`](https://github.com/xunit/assert.xunit/blob/4903ddf8e053d9abf0a1cb9bd3755a8caf9c3024/EqualityAsserts.cs#L50-L64). Instead, you should call the [`float`-specific `Assert`](https://github.com/xunit/assert.xunit/blob/4903ddf8e053d9abf0a1cb9bd3755a8caf9c3024/EqualityAsserts.cs#L168-L187) which requires a tolerance value (because comparing floating point values for exact equality is problematic given the imprecise nature of floating point values).

This is further exacerbated by the fact that the default `ToString()` for `float` does not print with full precision, thereby causing the issue you're seeing, because of your specific values. Here are some examples:

```csharp
[Fact]
public void SmallValues()
{
	Assert.Equal(6.0f, 6.00000048f);
}

[Fact]
public void LargeValues()
{
	Assert.Equal(6.0f, 6.1f);
}

[Fact]
public void SmallValues_WithTolerance()
{
	Assert.Equal(6.0f, 6.00000048f, 0.00000001f);
}
```

![image](https://user-images.githubusercontent.com/16944/124990302-0774aa80-dff5-11eb-8839-b43b08d6928c.png)

You can pass `0f` for the tolerance, although I wouldn't recommend this (for the precision reasons mentioned earlier).
