### ISSUE TITLE
Can't build a project referencing xunit.runner.utility

### ISSUE THREAD

**Issue by lejsekt** [xunit/xunit#2031]
Hi,
first of all, thank you for an awesome testing library!

I've run into the following issue while trying to create a custom test runner. I have a netstandard 2.0 library that references xunit.extension.runners 2.4.1 and that contains a class that uses a type from xunit.extension.runners. I've referenced that library from a netcoreapp2.2 console app. Once I've used a class defined in the library in the console app, the console app can't be built. It fails with the following error message:

error CS0012: The type 'TestPassedInfo' is defined in an assembly that is not referenced. You must add a reference to assembly 'xunit.runner.utility.netstandard15, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'

If I clone the current xunit repo, build nuget packages and use that version of xunit.runner.utility, the issue is gone. That package however targets netstandard 2.0 and version 2.4.1 does not, so I suspect this might be causing the issue. Looking at the git log, I've noticed netstandard 2.0 target has been removed. What were the reasons for doing that?
 
[xunitReferenceBug.zip](https://github.com/xunit/xunit/files/3707752/xunitReferenceBug.zip)

**Comment by bradwilson** [comment]
It was removed when it was discovered that netstandard2.0 broke people using older versions of .NET Framework.

That said. the problem with these libraries is that they don't actually support your library being a netstandard library; the netstandard support there is to support devices. Your library must target a specific platform; if you switch it from `netstandard2.0` to `netcoreapp2.2`, the build will succeed appropriately. If you need to support multi-platform, you must multi-target rather than relying on netstandard.

Sorry for this inconvenience; it's an unfortunate result of the design decisions in v2 (that were made long before netstandard was a thing, much less .NET Core) that are being fixed in v3.

**Comment by teddy108** [comment]
Thank you for a quick reply. Multi-targeting the library resolved the issue for now.
