### ISSUE TITLE
Autorollback doesn't work on .NET Core 3.0

### ISSUE THREAD

**Issue by MichalLechowski** [xunit/xunit#2043]
I haven't found a similar issue reported but Autorollback example from here:
[https://github.com/xunit/samples.xunit/blob/master/AutoRollbackExample/AutoRollbackAttribute.cs](url)

Doesn't work anymore after upgrading project from .NET Core 2.2 to .NET Core 3.0.
Dispose method is actually called and it looks like it's fine and working but it does nothing, db doesn't rollback at all.

Is there something to be changed because of using .NET Core 3.0 and EF 3.0 to make it work again or it's the actual issue to be resolved?

Greetings,
Mike

**Comment by bradwilson** [comment]
If it's only broken with EF Core 3.0, it sounds like it's a question to be asked of EF Core 3.0.

**Comment by MichalLechowski** [comment]
Thanks for quick response. Frankly speaking I have no idea where the issue really is. Maybe someone has a suggestion or an idea where to look for solution.

**Comment by TheArchitectIO** [comment]
Hi, I ran into this issue recently.

The auto rollback fails for DotNet Core 3.0 because it attempts to use Distribute Transactions in certain cases.

My problem was the TransactionScope in AutoRollback doesn't interact well with .BeginTransaction() that I use on DbConnection.

my solution was for SQL Server and I use 5 lines of SQL to basically reset all my tables. this is a very heavy handed approach I took and its not ideal for everyone or in all cases.

```
EXEC sp_MSForEachTable 'DISABLE TRIGGER ALL ON ?';
EXEC sp_MSForEachTable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL';'
EXEC sp_MSForEachTable 'DELETE FROM ?'
EXEC sp_MSForEachTable 'ALTER TABLE ? CHECK CONSTRAINT ALL';
EXEC sp_MSForEachTable 'ENABLE TRIGGER ALL ON ?';
EXEC sp_MSForEachTable 'DBCC CHECKIDENT (''?'', RESEED, 0)';
```

**Comment by NickFranceschina** [comment]
I am running into this right now...  `System.Transactions.Transaction.Current` is non-null in the test (TransactionScope is started in autorollback attribute as expected)  but inside the TestServer/Controller method, `Transaction.Current` is null.  I spent all day today trying to figure out where the difference is or how to work around it.  I may end up using DI to create some sort of connection factory where I can be more explicit about setting the outer-transaction (rather than relying on "Ambient Transactions")

**Comment by MichalLechowski** [comment]
I've just had the same problem again in another solution also with EF Core 3.x and xUnit and I can confirm that the solution mentioned in #18001 works just fine. The only thing you need to do is to set the PreserveExecutionContext = true in your testing environment configuration. This property is within TestServer class.

Example testing environment setup class:
`public class TestStartup : CustomWebApplicationFactory<Startup>
    {
        public HttpClient Client { get; private set; }

        public TestStartup()
        {
            Server.PreserveExecutionContext = true; //THIS MAKES AUTOROLLBACK WORK AGAIN
            Client = CreateHttpClient();
        }
}`

The only disadvantage I see is that you can't see the changes in the DB during debugging so I can create an entity in the test code and get it within a test using endpoints, too, but I can't query the DB when I set a breakpoint right after e.g. inserting the data, the new data is not there for some reason. But this is only the inconvenience while debugging. The feature itself works fine.
