### ISSUE TITLE
InlineData can't only take string array

### ISSUE THREAD

**Issue by bender2k14** [xunit/xunit#2060]
The `InlineData` attribute can accept a single `byte` array as well as a `string` array and a `string`, but it doesn't accept a single `string` array.  See the specific compiler error below.

I expected `InlineData` to be able to accept a single `string` array.

Is this the intended behavior (perhaps due to a limitation of the C# type system) or a bug?

## Screenshot
![2020-01-14_08-29-15_36_devenv](https://user-images.githubusercontent.com/34664007/72353307-7778cd80-36a9-11ea-9ab6-86608522a7eb.png)

## Code
```C#
[Theory]
[InlineData(new byte[] { 0 })]
public void ByteArray(
    byte[] array
)
{ }

[Theory]
[InlineData(new string[] { "foo" }, "bar")]
public void StringArray_String(
    string[] array,
    string s
)
{ }

[Theory]
[InlineData(new string[] { "foo" })]
public void StringArray(
    string[] array
)
{ }
```

## Compile error

CS0182
An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type

**Comment by bradwilson** [comment]
This is the compiler, and not us.

What you need is this:

```csharp
[InlineData(new object[] { new string[] { "foo" } })]
```

Why you need it: the signature for the `InlineData` attribute constructor is:

```csharp
public InlineDataAttribute(params object[] data);
```

Let's evaluate this example:

```csharp
[InlineData(new string[] { "foo" }, "bar")]
```

What the compiler is silently doing for you is actually this:

```csharp
[InlineData(new object[] { new string[] { "foo" }, "bar" })]
```

When you try to pass a the single `string[]`, rather than encapsulating it up into an `object[]` array for you, it assumes you're trying to pass the array yourself, and then it complains because the conversion from `string[]` to `object[]` is not a const value (which is a requirement for attribute constructor values).

As for why the single `byte[]` works here, I'm not sure; maybe @terrajobst has an idea (or knows who would).

As for what we can do? Nothing, unfortunately. It's just a quirk of the compiler/language that it helps you out most of the time, but not here.

**Comment by bender2k14** [comment]
Thanks @bradwilson for your quick and detailed reply :)

> This is the compiler, and not us.

I thought so.

> What you need is this:
> `[InlineData(new object[] { new string[] { "foo" } })]`
> ...
> As for what we can do? Nothing, unfortunately. It's just a quirk of the compiler/language that it helps you out most of the time, but not here.

Oh, yes.  Of course.  I should have considered that.  I like this workaround (...I was using workaround that includes an extra argument that my tested ignored, which I like less).

Sure, I wouldn't expect you to do the impossible! ;)

Thanks again :)

> As for why the single `byte[]` works here, I'm not sure; maybe @terrajobst has an idea (or knows who would).

I am still curious about this case.  One idea I had is that it might have something to do with `object` and `string` being references types and `byte` being a value type.

**Comment by bradwilson** [comment]
That's as good a guess as any. 😄

**Comment by bradwilson** [comment]
Closing as "external", since this is the compiler's doing and not ours.

**Comment by terrajobst** [comment]
Yeah, there isn't much you can do sadly :-(

**Comment by j0nimost** [comment]
Hello @terrajobst, is it possible we get a fix? Say in C# 12 or so?

**Comment by MisinformedDNA** [comment]
Another potential workaround/alternative:

```csharp
        [Theory]
        [InlineData("foo")]
        public void StringArray(
            params string[] array
        )
        { }
```

**Comment by terrajobst** [comment]
@j0nimost what would the suggested f change to the compile be?

The runtime and C# have array covariance, which was done to improve interop with Java.

That is, a method taking object[] can be called with a string[]. However, for attributes another constraint is that the expression must be considered a literal. That's why you need the manual object[] wrapping.

You don't need it for the byte[] case because there is no array covariance between arrays of value types and object[].
