### ISSUE TITLE
Sublte bug when missing unit argument in an F# fact

### ISSUE THREAD

**Issue by njlr** [xunit/xunit#2064]
Suppose I have a test like this:

```fsharp
module MyTests

open Xunit

[<Fact>
let ``this test always fails`` = 
  Assert.True(false)
```

Then I can build and run my tests successfully with:

```
dotnet test
```

This is because the test is actually defined incorrectly and gets silently ignored by the test runner!

It should be: 

```fsharp
module MyTests

open Xunit

[<Fact>
let ``this test always fails`` () = 
  Assert.True(false)
```

_(Notice that the test is now a function by adding `()`)_

This will compile and then fail as expected. 

Ideally, the first version should not compile at all, thus avoiding this very subtle bug. 

```
  nuget xunit 2.4.1
  nuget xunit.runner.console 2.4.1
  nuget xunit.runner.visualstudio 2.4.1
```

**Comment by bradwilson** [comment]
I don't know F# well enough to understand the difference.

In CLR terms, what does `let ``this test always fails`` =` translate to, if not a method?

**Comment by njlr** [comment]
Perhaps [this link](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfAtgexgV2AUwAQEEAjAY1wF4BYAKGt1xwBdcADZgQxNfN1rtwAcATgEsAdgzCjcAIgAW2YMFTTq1NJhy4AItjDdVVOoxbMYurgAoAlPsN8hYiVOkB3VIOAwVdoA==) helps?

```
module Abc =

  let ``abc`` = 
    printfn "hello"

module Def = 

  let ``def`` () = 
    printfn "world"
```

As far as I can tell, `abc` compiles to a statically initialized variable, whilst `def` compiles to a static function (with no arguments).

**Comment by bradwilson** [comment]
Unfortunately, there's nothing we can do about this.

Although these two look very similar in F#, the underlying code is dramatically different. What gets generated isn't even legal C#, using your supplied link, because it appears to be placing the `FactAttribute` onto a property definition, where it is most definitely _not_ legal. Regardless, the property definition that it attaches the attribute to is _not_ your test code:

```csharp
        [Fact]
        [CompilationMapping(SourceConstructFlags.Value)]
        public static Unit abc
        {
            get
            {
                return $_.abc@6;
            }
        }
```

Even if xUnit.net found this property getter method and ran it, there is no test code here; it merely returns a value, and thus none of your supposed test code is being run.

At best, this is a bug in the F# compiler for generating this incorrect code. At worst, this is just an oddity of the F# language that you're unfortunately being bitten by, but there's no way for xUnit.net to know that you wrote the wrong code here. I would consider opening a bug with the F# team to see what their response is, but there's nothing we can do about it on this side.

Sorry. 😞

**Comment by njlr** [comment]
I took a look at the xunit source code and the `[<Fact>]` attribute is only valid for methods. The `abc` does not compile to a method so the F# compiler should reject my source code. I think this is a bug in the F# compiler.

**Comment by njlr** [comment]
https://github.com/dotnet/fsharp/issues/8547

**Comment by bradwilson** [comment]
Resolving as external, since this appears to be an issue with F#.
