### ISSUE TITLE
AsyncTestSyncContext: Track `async void` exceptions

### ISSUE THREAD

**Issue by jzabroski** [xunit/xunit#2065]
Hi - Is this a potential issue with running `async void` tests?  The private `exception` gets over-written by arbitrary items that throw exceptions.  The last one "wins".

https://github.com/xunit/xunit/blob/9d10262a3694bb099ddd783d735aba2a7aac759d/src/xunit.execution/Sdk/AsyncTestSyncContext.cs#L62

Note: I don't have sophisticated knowledge of Xunit internals, so I apologize if this is a silly issue for a reason beyond my grasp.

**Comment by bradwilson** [comment]
The AsyncSyncContext is per-instance, per-test, so there's no cross-test contamination:

https://github.com/xunit/xunit/blob/3f3f6929c301db40e9d5d8ced2bb494084f57c82/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs#L237

The way that xUnit.net tracks test failures is by things that throw exceptions. The `Assert` methods all throw exceptions upon assertion failure. The code you linked is used to capture whatever _unhandled_ exception might be thrown by the test method (whether it's an assertion failure or not). Since a method cannot throw more than one unhandled exception, this code should only ever see the exception that caused test failure.

**Comment by jzabroski** [comment]
Thanks - sorry for the time waste.
