### ISSUE TITLE
xunit.console.exe does not declare support for Win10

### ISSUE THREAD

**Issue by Tratcher** [xunit/xunit#2076]
Run the following test on Win10
```
        [Fact]
        public void Test1()
        {
            Assert.Equal(10, Environment.OSVersion.Version.Major);
        }
```

Problem: You get different results depending on the runner used.

VS: The test passes
`dotnet test`: passes
xunit.console.exe fails with:
```
      Assert.Equal() Failure
      Expected: 10
      Actual:   6
```

This is because Windows lies about it's real version until you opt into supporting a specific version via the app.manifest file. VS and dotnet.exe already do this, but xunit.console.exe does not.

Change needed:
The xunit.console project needs to add an [app.manifest](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#supportedos) containing the following:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
      <application> 
        <!--This Id value indicates the application supports Windows Vista functionality -->
          <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/> 
        <!--This Id value indicates the application supports Windows 7 functionality-->
          <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
        <!--This Id value indicates the application supports Windows 8 functionality-->
          <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
        <!--This Id value indicates the application supports Windows 8.1 functionality-->
          <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
        <!--This Id value indicates the application supports Windows 10 functionality-->
          <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
      </application> 
  </compatibility>

</assembly>
```
With this added to the csproj:
```
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
```

Would you accept a PR for this?

Related: https://github.com/dotnet/extensions/pull/2927#issuecomment-594243348

**Comment by bradwilson** [comment]
This is useful information for v3, but is not necessary since the console runner as a "thing that loads your DLL and runs your tests" is going away.

**Comment by Tratcher** [comment]
Oh? What's replacing it?

**Comment by bradwilson** [comment]
Unit test projects will be directly executable. So you'll be able to add whatever app manifest makes sense for your own tests.

**Comment by ladipro** [comment]
@bradwilson any chance this could be revisited? The amount of code depending on Win10 / Win11 has increased and it cannot be easily tested because of this issue. v3 is still in Alpha, which I'm reading as "not yet production ready".

Here's where it's causing grief to MSBuild, for example: https://github.com/dotnet/msbuild/pull/8328#issuecomment-1398976569

**Comment by bradwilson** [comment]
The problem with things like this is that it will explode the combination of things we have to ship.

Today, we ship a matrix of:

- x86 vs. AnyCPU
- .NET Framework (4.5.2 through 4.7.2, which was latest as of our last official ship)

I'm reluctant to just "turn it on", because we may be breaking anybody who is depending on us _not_ declaring support for Windows 10. So, if we add a Win10 version to all of this, it **doubles the number of binaries we ship from 14 to 28**.

In addition, we have no current plans to ship another v2 version.

I believe the best solution for you is to probably pull our source, build the single exact console runner binary you need, and then make that available somewhere for your tests to pull and use.

**Comment by ladipro** [comment]
Fair enough, thank you.
