### ISSUE TITLE
xUnit under dotnet test does not use the correct .NET Framework runtime - report false test failures

### ISSUE THREAD

**Issue by TalAloni** [xunit/xunit#2081]
I have created a minimal xUnit test project demonstrating the problem (the test project use the SDK-style csproj, and target net472).
VSTest.Console works as expected.
when running the test with dotnet test, it will throw the following exception:
System.ArgumentException : The specified value is not valid in the 'SslProtocolType' enumeration.
This exception is not thrown by .NET Framework 4.7.2

dotnet SDK version: 3.1.200
Test Execution Command Line Tool Version 16.5.0

This issue does not occur with MSTest v2.

Project demonstrating the problem:
https://github.com/TalAloni/dotnettest-xunit

**Comment by bradwilson** [comment]
AFAIK, we don't control the version of .NET that's being consumed; that's VSTest that sets that (since they own the launching process). I would open the issue with VSTest at https://github.com/microsoft/vstest/issues

The workaround is to use the xUnit.net console runner. Add a NuGet reference to `xunit.runner.console`, then you get access to [the build properties](https://github.com/xunit/xunit/blob/v2/src/xunit.console/build/xunit.runner.console.props) that would allow you to set up a target to run the tests, like this:

![git diff and MSBuild output](https://user-images.githubusercontent.com/16944/77357673-c7a58900-6d05-11ea-8da2-eeb4ac6521b7.png)

Alternatively, you can find the runner in `~/.nuget/packages/xunit.runner.console/2.4.1/tools/net472/xunit.console.exe` and just invoke it by hand:

![xunit.console.exe output](https://user-images.githubusercontent.com/16944/77358008-5ca88200-6d06-11ea-9004-678c96a575dd.png)

/cc @clairernovotny

**Comment by TalAloni** [comment]
Thanks!
