### ISSUE TITLE
Assert failes for boxed numbers

### ISSUE THREAD

**Issue by Der-Kraken** [xunit/xunit#2118]
Assert.Equal((object)var1, (object)var2);Hi,

I realized that asserting a static typed integer and decimal ist working as expected but if I box that two values than asserting failes.
That seems like unexpected behaviour.

``` csharp
[Fact]
public void Test()
{
	int var1 = 1;
	decimal var2 = var1;

	Assert.Equal(var1, var2); // <- Working
	Assert.Equal((object)var1, (object)var2); // <- Failed
}
```

**Comment by bradwilson** [comment]
This is expected behavior.

Assert.Equal is generic (`Assert.Equal<T>(T var1, T var2)`), and if you call the version without a comparer, it gets a default comparer for you based on the type of T. The comparer for `object` is a reference equality comparer.

Your workarounds are:

- Unbox the values before the assert
- Call the version of Assert.Equal which allows you to pass a comparer which unboxes the values and compares them

https://github.com/xunit/assert.xunit/blob/3af483c3e851ef4f463a8ce8b9399b7bc8ab4dc0/EqualityAsserts.cs#L19-L45
