### ISSUE TITLE
Write an analyzer to catch things that should be nameof

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2141]
Today you can write things like:

```csharp
[MemberData("SomeMember")]
```

where that really should be:

```csharp
[MemberData(nameof(SomeMember))]
```

Part of this issue is to identify which attributes that might affect in addition to writing the necessary analyzers.

**Comment by TheBeardedLlama** [comment]
I'll try and have a look at this... :|

**Comment by andresrsanchez** [comment]
Hello, this analyzer already exists in [here](https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/UseNameofInPlaceOfString.cs). 
So instead of installing fxcop or microsoft.quality.analyzers nugets we should adapt UseNameofInPlaceOfString analyzer code for xunit.analyzers?

**Comment by stefannikolei** [comment]
I think this is already implemented in MemberDataShouldReferenceValidMember. 

It reports this diagnostic: Descriptors.X1014_MemberDataShouldUseNameOfOperator

**Comment by bradwilson** [comment]
Closing as fixed.
