### ISSUE TITLE
Assert.Equal Dictionary pretty printing

### ISSUE THREAD

**Issue by jzabroski** [xunit/xunit#2155]
This is a feature request for xunit.  Currently, `Assert.Equal` pretty prints dictionaries in ways that you can't easily copy-paste: copy the actual and paste it into the `Assert.Equal` expected.
 
```c#
Expected: Dictionary<String, Double> [[, 637975]]
Actual:   Dictionary<String, Double> [[PIB, 626615], [OGB, 11360]]
```

I would like it to pretty print as:

```c#
Expected: Dictionary<String, Double> [[""] = 637975]
Actual:   Dictionary<String, Double> [["PIB"] = 626615, ["OGB"] = 11360]
```

I'm incredibly impressed Assert.Equal handles Dictionaries at all, but this would put it over the moon for me.

Thank you.

**Comment by jzabroski** [comment]
It also prematurely trims the difference.  For a dictionary, I would rather it report on missing keys, and if keys match, different values.

**Comment by louis-z** [comment]
If that's alright, I'd like to take a crack at it.

**Comment by jzabroski** [comment]
I'm cool with that. Thanks, Louis!

**Comment by louis-z** [comment]
After some investigation, this is what I found:

The reason we get something like `[PIB, 626615]` is because each `Dictionary` entry (a `KeyValuePair`) ends up being converted to string by a call to `Convert.ToString(value, CultureInfo.CurrentCulture)`.

Now if we want to output something like `["PIB"] = 626615` instead, we would most likely need to
- treat a Dictionary's `KeyValuePair`s differently from other `KeyValuePair`s, outputting them as `[key] = value` rather than `[key, value]`
- detect when the key type is `string` and provide for it a special treatment where we enclose its value within quotes (i.e. `["key"]`).

But even then, we would face another problem: output truncation. For dictionaries containing more than a few items, `Assert.Equal` will output the first items followed by an ellipsis. So, with the said changes we would get something like

```
Dictionary<String, Int32> [["a"] = 1, ["b"] = 2, ["c"] = 3, ["d"] = 4, ["e"] = 5, ...]
```

This still wouldn't allow you to copy-paste Actual to Expected.

Maybe we could introduce some kind of "extended output" mode for dictionaries that would output all items for Actual and Expected, as well as the list of keys present in either dictionary but not in both and the list of values that differ for keys present in both dictionaries?

@bradwilson, what do you think?

**Comment by jzabroski** [comment]
I think it's OK to not show the full output for now.  The most likely use case for copy-paste is when you have a small typo in the expect side and just want to make a quick adjustment.  It's a minor convenience and probably shouldn't be too convenient (I'm sure those of us who have showed up to projects as consultants have all seen the code base where the Asserts basically do nothing but effectively return true and boost code coverage metrics).

**Comment by louis-z** [comment]
Just submitted a PR (Draft) with modified assert code. @jzabroski, let me know what you think?

I also added tests to xunit itself, to validate the modified assert code. I could submit another PR for that too (though it's not clear how I can refer a commit in my forked `assert.xunit` project).

**Comment by jzabroski** [comment]
Thanks, @Louis-z !

**Comment by louis-z** [comment]
Glad I could help @jzabroski. 😉
