### ISSUE TITLE
ClassData outputs do not get disposed if they implement IDisposable

### ISSUE THREAD

**Issue by jgowdy** [xunit/xunit#2162]
If my TestDataGenerators decorated with [ClassData] implement IDisposable, I would hope that they get Disposed after being used.

I have attached the following test project.

[XUnitTestProject1.zip](https://github.com/xunit/xunit/files/5318755/XUnitTestProject1.zip)

I have also created a pull request that attempts to fix the issue.

https://github.com/xunit/xunit/pull/2161

**Comment by bradwilson** [comment]
Note that we also need to make sure data rows (and class data) that implement `IAsyncDisposable` get properly async disposed, as well as validating that the default implementations of `GetData()` support `IAsyncLifetime` creation.

**Comment by JamesTerwilliger** [comment]
@bradwilson What about something like this?
https://github.com/xunit/xunit/pull/2801

**Comment by bradwilson** [comment]
Fixed by #2801.

Implementation of this feature requires that if the class pointed to be `[ClassData]` implements either `IDisposable` or `IAsyncDisposable`, that we disable data pre-enumeration. That's because otherwise we have no place to do the disposal of the data class itself (the only thing returned from discovery is test cases, and if you have more than one data row, you'll have more than one test case... so no one test case can own the lifetime of the class object).

The most visible result of this will be that tests using such data sources will not show up as "one test per data row" in Test Explorer, but rather as a single test for the test method (and running that test will run all data rows). This is identical to the behavior where we have non-serializable test data.

Available in v3 `0.1.1-pre.307`
