### ISSUE TITLE
QUESTION: In what assembly are defined SetUp and TearDown attributes?

### ISSUE THREAD

**Issue by gsscoder** [xunit/xunit#2166]
I would like to use attributes in the subject of the question, my I don't know what assembly to reference more than ones in xunit package.

Are these superseded by other mechanisms?

Thank you,
Giacomo S. S.

**Comment by bartelink** [comment]
These attributes are not present in xUnit.net. The documentation (and probably some blog articles) explain in more depth.
- in general, Teardown is handled via `IDisposable`
- in general, Setup lives in the constructor and/or in Collection Fixtures etc

The best way to get quick answers to these sorts of questions is to post questions on StackOverflow.com IMO

**Comment by bradwilson** [comment]
You can also use `IAsyncLifetime` if you need asynchronous versions of setup and teardown. In v2, this is supported by test classes and fixture classes, as documented here:

https://github.com/xunit/xunit/blob/v2/src/xunit.core/IAsyncLifetime.cs#L6-L11

For v3, we will support this in more places, as well introducing support for `IAsyncDisposable` (which is new since xUnit.net v2 shipped).

**Comment by gsscoder** [comment]
OK, thankyou @bradwilson!
