### ISSUE TITLE
Writing a unit test in xunit that passes if a function call takes too long

### ISSUE THREAD

**Issue by mattqs** [xunit/xunit#217]
I asked a question in stackoverflow http://stackoverflow.com/q/27220254/1109316 about passing a test after timeout.

Maybe there could be an attribute that makes writing these tests easier?

Instead of:

```
 [Fact]
 public void WrongServerKey()
 {
    bool flag = false;
    Task.Run(() =>
    {
        var result = CallServerWithWrongKey();
        flag = true;
    });
    Task.Delay(TimeSpan.FromSeconds(5)).Wait();
    Assert.False(flag);
 }
```

Something like:

```
 [Fact (Timeout = 8000,PassTimeout = true)]
public void WrongServerKey()
{
        var result = CallServerWithWrongKey();
}
```

This test should fail if it reaches the end before the timeout.

**Comment by mxa0079** [comment]
I agree with @Haacked comment. Even if the timeout is not accurate, I can tolerate a rough timeout value. As long as the library can guarantee an X% timeout variation, then this feature is effective for my needs.

**Comment by bradwilson** [comment]
It's impossible to guarantee _**any kind of accuracy at all**_.

**Comment by mxa0079** [comment]
Thanks for the prompt response, @bradwilson 

Could you please expand on why we could not guarantee any kind of accuracy? (or provide a link to educate myself on the issue).

Per the original suggestion, could we not leverage something like this:

```csharp
public static async Task TimeoutAfter(this Task task, int millisecondsTimeout)
{
    if (task == await Task.WhenAny(task, Task.Delay(millisecondsTimeout))) 
        await task;
    else
        throw new TimeoutException();
}
```

**Comment by bradwilson** [comment]
I don't think `Task.Delay` does what you think it does.

While it will wait _at least_ the amount of given time, there's no guarantee that it will not end up waiting longer, simply because there are no available threads on which to schedule the continuation to run. And this is the fundamental source of the problem: you cannot accurately measure how much time you've spent running (vs. the amount of time that has passed). You could ask for a 250ms delay, and after that delay is complete, the follow-on code doesn't have a chance to run until some indeterminate time later (seconds? minutes? hours?). Worse, when code is poorly written such that it blocks the thread it uses, any attempt to rely on this timeout is subject to a deadlock condition wherein it may _never_ get an opportunity to run the follow-on code.

**Comment by stijnherreman** [comment]
When using `await`, what is the recommended method to avoid a test being stuck due to the task never completing? Disable parallelisation and use a custom `FactAttribute` that does support a timeout?

**Comment by bradwilson** [comment]
That is an option, yes (though not one that's built in, obviously).

We support the notion of discovering that a test is running too long, without unilaterally terminating it (it just gets reported to the console), via the `longRunningTestSeconds` [configuration value](https://xunit.github.io/docs/configuring-with-json.html). This might be a good first place to start, if you're just looking for something that you can see interactively.

**Comment by dotMorten** [comment]
I don't this focus on accuracy of the timeout. The focus should be: Ensure hung tests doesn't prevent the entire test run to complete. A test taking way too long to complete is a test failure and should be treated as such. It's completely irrelevant if the timeout is a few milliseconds or even seconds off.

**Comment by bradwilson** [comment]
We added `Timeout` back into 2.4. However, if you use `Timeout` with any form of parallelism enabled, then the results are undefined (which typically means tests which should not have failed because of timeout, might fail simply because they were not given a chance to continue running before the timeout expired).

**Comment by adam-tran3946** [comment]
@bradwilson , I am consuming xunit.runner.console 2.4.1. What if we don't define the timeout value in Fact attribute. Does it have a default value for timeout?

**Comment by bradwilson** [comment]
There is no timeout by default.

**Comment by adam-tran3946** [comment]
Just clarify it a bit: does it mean that xunit will wait execution of a test forever OR depend on timeout value set in the test implementation before completing execution of the test? e.g: 

1. In our class, there is a statement that define execution timeout is 100s
2. A test consumes the class and invokes the statement
=> so by default, xunit could wait for 100s before completing execution of the test ( note: test triggered in parallel)

The reason that I asked the concern for is that I get an intermittent issue with the exception:
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.

OR sometime, the execution of the test suite containing that test is terminated quietly without completing its all tests.

**Comment by bradwilson** [comment]
It will wait forever. The fact that you have done code that times out isn't something xUnit knows (or cares) about.

**Comment by adam-tran3946** [comment]
thank @bradwilson so much.

**Comment by mcallaghan-bsm** [comment]
What is the CURRENT state of this? @bradwilson  ?

I just got burned by a test w/ a Fact timeout being silently ignored.
```
[Fact(Timeout = 10000)]
```
GOAL: if a test exceeds 10s, kill it

After enabling long running test detection (10s) and disabling parallelization of test collections, the test is still not killed.

https://xunit.net/docs/configuration-files

--
Where is the official documentation for Fact parameters? (where in which I would expect to find details about the `Timeout` parameter)

Also the "migration notes" mention timeout is dead, https://xunit.net/docs/test-migration ... but in 2.4 it was re-added

**Comment by bradwilson** [comment]
There is a current bug with Timeout that it only works with async tests. So this works:

```csharp
[Fact(Timeout = 1000)]
public async Task Passing()
{
    await Task.Delay(5000);
}
```

but this does not:

```csharp
[Fact(Timeout = 1000)]
public void Failing()
{
    Thread.Sleep(5000);
}
```

**Comment by mcallaghan-bsm** [comment]
> There is a current bug with Timeout that it only works with async tests
, bug/ticket ref? (so we can track it) thanks!

Also we are already using `async Task` test definitions; However in the code under test (deeper), they're doing `Thread.Sleep()`, ;; so presumably if those are switched to `await Task.Delay()` might start working. Will give that a go.

**Comment by darrenoakey** [comment]
this is painful 

- basically we use a build machine - so if someone has a test that goes long for some reason, it times out the build - which then kills the job - and guess what - collection of output happens _after_ the test job... if the job is killed - the docker container goes away, and any ability to work out _which_ thing took too long evaporates into the ether.  And the fun bit is, everything works fine and is fast locally.

We've had to make a Test attribute that defaults timeout to 10s - because even with parallelisation - if a test is 10s from start to end - that's pretty bad - but even then we've had to go through and make every test async - and then write a roslyn checker to make sure that it is async if it has a test wrapper. 

I was really excited when I saw the LongRunningTest setting - and then got equally depressed when I found it was just a message!?

Please, Please -
a) make a flag or config setting that allows you to say "kill any test that takes longer than x"
b) make Timeout work with non-async tests

Thanks!

**Comment by mcallaghan-bsm** [comment]
> There is a current bug with Timeout that it only works with async tests. So this works:
@bradwilson  - please advise/reference the ticket that tracks this? thank you

**Comment by Happypig375** [comment]
Well, NUnit has TimeoutAttribute, so I don't understand why xUnit doesn't want to have it. Seems backwards for the testing framework that is supposed to be better than NUnit.

**Comment by mcallaghan-bsm** [comment]
(do we need to submit a different ticket? or can we re-open this one?)

**Comment by bradwilson** [comment]
@mcallaghan-bsm Because of the history of this issue, it would be better to open a new one. Thanks!

**Comment by mcallaghan-bsm** [comment]
ALL: submitted #2222
