### ISSUE TITLE
[Feature] Inject Microsoft.Extensions.Logging.ILogger

### ISSUE THREAD

**Issue by hartmair** [xunit/xunit#2243]
I would love to see XUnit befriend with `Microsoft.Extensions.Logging` [1], i.e. allow to inject `ILogger<T>` and `ILoggerProvider` like `ITestOutputHelper` out of the box:
```CSharp
public class MyTests
{
  private readonly ILogger _logger;
  public MyTests(ILogger<MyTests> testOutput)
  {
    _logger = testOutput;
  }
  [Fact]
  public void TestWithLogging()
  {
    _logger.LogInformation("Hello, World!");
  }
}

public class MyDependencyInjectionTests
{
  private readonly ILogger _logger;
  public MyDependencyInjectionTests(IloggerProvider testOutput)
  {
    var services = new ServiceCollection()
      .AddLogging(logging => logging.AddProvider(testOutput))
      .BuildServiceProvider();
    _logger = services.GetRequiredService<ILogger<MyDependencyInjectionTests>>();
  }
  [Fact]
  public void TestWithLogging()
  {
    _logger.LogInformation("Hello, World!");
  }
}
```

[1] https://docs.microsoft.com/en-us/dotnet/core/extensions/logging

**Comment by bradwilson** [comment]
Seems like a subset/dup of https://github.com/xunit/xunit/issues/1738

**Comment by weitzhandler** [comment]
@bradwilson
I actually think #1738 is a separate issue concerning the actual DI, whereas here, I believe the OP referred solely to the logging aspect. Currently linking `ITestOutputHelper` and `ILoggingProvider` is super tedious and not-straightforward.

**Comment by bradwilson** [comment]
I have a few thoughts.

First, we generally trying to avoid shipping _any_ dependencies, but that would especially apply to a dependency that is not used by all users. Logging is definitely not something all users will use.

Second, your proposed solution does not work as there is no global `ITestOutputHelper` for you to use in your sample code. We create a fresh instance of it for each unit test. Instead, in v3 rather than having your AddXunit method take `ITestOutputHelper`, your logger provider could just call `TestContext.Current.TestOutputHelper?.Write` in response to logger usage. Or you could use the `ConsoleLoggerProvider` combined with `[assembly: CaptureConsole]`, and that would not require any new custom logger provider at all.

Third, what is the value of injecting the logger into the test, when the test already has access to `ITestOutputHelper`? I understand wanting _production code_ to get a logger which forwards its messages onto `ITestOutputHelper`, but I don't understand wanting _test code_ to use a logger rather than just using `ITestOutputHelper` directly.

**Comment by weitzhandler** [comment]
Thanks for your reply!

**Comment by seanterry** [comment]
@bradwilson Thanks so much for adding ambient access to the `ITestOutputHelper`. This has made getting log output from tests so much easier.

> your logger provider could just call TestContext.Current.TestOutputHelper?.Write in response to logger usage.

This is what I ended up doing. The console logger and attribute combo didn't seem to work for me, so I just made my own logger provider. Now any of my tests that hit the db with EF core will output the SQL it ran right into the test console. :chefs_kiss:
