### ISSUE TITLE
Running Xunit + selenium (grid) tests in Parallel is not working 

### ISSUE THREAD

**Issue by bhanu-pratap** [xunit/xunit#2281]
I have put following in the  xunit.runner.json to run the Xunit  + selenium test in parallel.

{
  "parallelizeAssembly": true,
  "parallelizeTestCollections": true,
  "maxParallelThreads": 2,
}

However when i am running them using "dotnet test" two browser window opens but both the test care running on the same browser window.

i also used selenium grid but same behavior.

**Comment by dtopuzov** [comment]
@bhanu-pratap most likely it should be issue with your code base and the way how you use Selenium API.
Behavior you described may be caused by using static browser driver or some other static things in your code.

I can confirm that I am are to run multiple browsers in parallel with Selenium and xunit.
