### ISSUE TITLE
System.ArgumentException for generic TheoryData

### ISSUE THREAD

**Issue by kopycol** [xunit/xunit#2315]
Hi
I created tests for my helpers library.
And for generic TheoryData one test is failed for null generic argument.
It tried to bind object but type of argument can be resolved:
a) from type of TheoryData
b) from type of the next Func argument.

[RemoveAnyTestsIssue.zip](https://github.com/xunit/xunit/files/6557178/RemoveAnyTestsIssue.zip)

```
[28.05.2021 01:01:21 Error] [xUnit.net 00:00:01.01]     XUnitTests.HelpersTests.RemoveAnyTest<String, Object>(list: ["aa", "bb", "cc", "cc", "bb", ...], sample: null, deltaCount: 0, predicate: Func`3 { Method = Boolean IsEqOrd(System.String, System.String), Target = null }) [FAIL]
[28.05.2021 01:01:21 Informational] [xUnit.net 00:00:01.01]       System.ArgumentException : Object of type 'System.Func`3[System.String,System.String,System.Boolean]' cannot be converted to type 'System.Func`3[System.String,System.Object,System.Boolean]'.
```

**Comment by bradwilson** [comment]
Unfortunately I can't get your repro to build, either from the command line (with .NET SDK 5.0.301) nor with VS 2019:

![image](https://user-images.githubusercontent.com/16944/121787069-df6e6480-cb78-11eb-9f1a-ae8eadf965ca.png)

**Comment by kopycol** [comment]
Excuse me, I am using VS 2017.
[RemoveAnyTestsIssue2.zip](https://github.com/xunit/xunit/files/6664425/RemoveAnyTestsIssue2.zip)

**Comment by bradwilson** [comment]
Sorry, I'm still getting the same compilation error, both from the command line and inside VS 2019.

**Comment by kopycol** [comment]
Hi, I've ported to Visual Studio 2019.  Please, look at it.
[RemoveAnyTestsIssue3.zip](https://github.com/xunit/xunit/files/7121785/RemoveAnyTestsIssue3.zip)

**Comment by bradwilson** [comment]
I've upgraded the projects to .NET 6 and xUnit.net 2.4.2 (with xunit.runner.visualstudio 2.4.5).

I cannot make any tests fail, either with `dotnet test` or with Visual Studio 2022's Test Explorer:

![image](https://github.com/xunit/xunit/assets/16944/c339308c-0605-4b62-8290-b7d1d1a0a27a)

![image](https://github.com/xunit/xunit/assets/16944/d0b638ce-dc54-4486-b453-6100521af1e8)

I am closing this issue because I cannot repro it. If you are still experiencing the issue, please open a new issue with a repro project. Thanks!
