### ISSUE TITLE
Integration with TeamCity sometimes does not work correctly

### ISSUE THREAD

**Issue by NikolayPianikov** [xunit/xunit#2415]
TeamCity service messages are misused for flows. This is why some tests can be skipped in reports and the TeamCity build logs can sometimes look messy. See [this page](https://www.jetbrains.com/help/teamcity/service-messages.html#Message+FlowId) for details. It is better to get the root _flowId_ from the _TEAMCITY_PROCESS_FLOW_ID_ environment variable if any.

Escaping may also not work correctly. See [this sample](https://github.com/JetBrains/TeamCity.ServiceMessages/blob/c2db4425c17bf8c34bc18ad9164220599fb22efb/TeamCity.ServiceMessages/ServiceMessageReplacements.cs#L33).

Related issues:
- #2385
- #2227
- [.NET xUnit - Parallelizing test assemblies in TeamCity may cause some tests to not be reported TW-70266](https://youtrack.jetbrains.com/issue/TW-70266)

**Comment by NikolayPianikov** [comment]
I can try fixing these issues and I have a few questions:
- Where is it better to fix it? I found several branches v2 and v3.
- Is it really needed to combine tests into collections?
- Is it possible to use NuGet dependencies to send TeamCity service messages?
- Do we want to stop publishing TeamCity service messages? Because users could use [TeamCity adapter](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter) for any test engines? And TeamCity does it automatically for .NET runner.

**Comment by bradwilson** [comment]
>Where is it better to fix it? I found several branches v2 and v3.

`v2` for a fix for 2.4.2, `main` for a fix for v3. So both.

>Is it really needed to combine tests into collections?

I'm not sure what you mean here by "combine tests into collections". Is this a question about TeamCity reporting, or about the architecture of xUnit.net itself?

>Is it possible to use NuGet dependencies to send TeamCity service messages?

Short answer: no.

Long answer: We take no dependencies other than .NET Framework/.NET Core itself in v2, because if we take a dependency and load our version before the tests get a chance to choose what version they want, and there is a conflict, our version always wins. So to avoid this problem, we take no dependencies at all.

>Do we want to stop publishing TeamCity service messages? Because users could use TeamCity adapter for any test engines? And TeamCity does it automatically for .NET runner.

These service message are not used with `dotnet test`, so the question isn't relevant for the .NET Runner. You are welcome to use the TeamCity adapter for `dotnet test` and avoid our console runner entirely, if that suits your needs best.

**Comment by bradwilson** [comment]
I have what I presume are fixes for all of this:

https://github.com/xunit/xunit/compare/2385-TeamCityLoggerUsesWrongFlowId

**Comment by bradwilson** [comment]
I'm going to close this in favor of #2385. Please followup there with any questions or comments.
