### ISSUE TITLE
[feature] test partitioning / parallel testing with multiple nodes  / seperate jobs

### ISSUE THREAD

**Issue by schmitch** [xunit/xunit#2426]
currently we mainly use gitlab-ci and gitlab-ci has a feature which can "parition" tests:
https://docs.gitlab.com/ee/ci/jobs/job_control.html#parallelize-large-jobs

at the moment xunit can only parallize tests within it's runner but it can't parallize it based on nodes.
it would be cool if there was a way to do it, so that tests can run on many many machines.

**Comment by bradwilson** [comment]
Since we have designed a system for unit tests which, by our definition, should be small and fast, we don't believe this kind of feature belongs in the core system itself. We leave that to third parties (like [NCrunch](https://www.ncrunch.net/)). If extra work is required from the test framework side to parallelize across multiple compute nodes, that a third party system will need to be put into place to make this happen. We simply do not have the time or desire to support this ourselves.
