### ISSUE TITLE
Argument formatting enigma

### ISSUE THREAD

**Issue by kkm000** [xunit/xunit#243]
I have a parametrized test (a "theory" in xUnit parlance) with quite a complex set of inputs. For this test, I have defined an argument class that includes all the test set up data. To describe and identify a particular instance of the test, I added a Name string field to the class, and overrode the class' `ToString()` method to return the name. xUnit never called it though, and instead printed the class in quite a puzzling format, naming all public fields and dumping the results of their respective `ToString()` invocations, which happened to be just class names, so each case was named almost identically:

![1](https://cloud.githubusercontent.com/assets/8228229/5517092/b329e620-8880-11e4-9a61-bbf807b4d3ff.png)

However, when I changed the class definition to be a struct, `ToString()` was suddenly called!

![2](https://cloud.githubusercontent.com/assets/8228229/5517093/dcc39e0e-8880-11e4-8258-5f055f7ba1fe.png)

Confused, I looked at the stack trace upon my ToString invocation and then the source, and discovered a mysteriously named method `FormatCompledValue` in class file `src/xunit.assert/Asserts/Sdk/ArgumentFormatter.cs`, that does the formatting. Indeed, the function is called on class types but not on value types, just a few lines above its definition:

``` C#
    if (type.GetTypeInfo().IsValueType)
        return Convert.ToString(value, CultureInfo.CurrentCulture);
    return FormatCompledValue(value, depth, type);
```

Is this intentional? Why are only structs allowed to be printed legibly, but classes are rather encoded into long confusing lines? Am I just missing something, and there is a different method of naming test instances? I am just worrying that if the described behavior will change in the release version of xUnit, my tests would suddenly all become unnamed, even if I use a struct as the argument.

And what is "compled" - compete? compiled? complicated? The function has not become less of a quandary even after I read its source, as I was still unable to express what it did in a few short words. I would not be surprised if the value becomes really compled, given what the function is doing 
with it... : )

**Comment by dklinger** [comment]
Hello, we are in the upgrade-process vom xUnit to xUnit2. Currently one-fifth of our tests are failing after the upgrade because this is a breaking change in xUnit, at least for us. We are talking of 1000 failing tests and more for every project. 
We are using xUnit, AutoFixture, NSubstitute and AutoFixture.NSubstitute.
In this scenario our tests look like this:
```csharp
        [Theory, AutoNSubstituteData]
        public void DoItNowAsProperty_UsingAutoNSubstitute(
            [Frozen] IRunSpeed runSpeed,
            GetToDaChoppa sut)
        {
            // Arrange
            runSpeed.Speed.Returns(49);

            //Act
            var x = sut.DoItNow;

            //Assert
            var tmp = runSpeed.Received(1).Speed;
            Assert.Equal(1, runSpeed.ReceivedCalls().Count());
        }
```
The failed test come from the ".Received()" and ".ReceivedCalls()" lines. The breaking change is, that xUnit2 is now calling all properties of the system under test - as the SUT is part of the test methods parameters - and therefore calling all of its properties once. As part of our test-methodology is to test the call count on those properties, all of our tests having either ".Received()" or ".Receivedcalls()" are now failing as the call count is +1 compared to xUnit v1. 

My feature request therefore is to have a global option which turns of the execution of the Value-retrieval-process of Complex test-method-parameters(this part of the ArgumentFormatter: https://github.com/xunit/assert.xunit/blob/2b70a9b0c5bb291f98472ec24cec437acf8d65c8/Sdk/ArgumentFormatter.cs#L156)

Besides the feature request: Do you have any suggestion for us on how to proceed with the upgrade process without changing thousands of test methods? Or is there no "easy" way?
