### ISSUE TITLE
Parallel test execution is incompatible with Micorsoft Fakes' shims

### ISSUE THREAD

**Issue by kkm000** [xunit/xunit#244]
I have 2 test classes using Microsoft Fakes with quite a similar setup. The following 3 lines shim a file load function and force loading of the set of fake files provided.
````C#
    var files = new Dictionary<string, string>() {  // Maps file name to contents
        { "1", "[142]\nv=0\n[143]\nv=0"},
. . . .
    using (ShimsContext.Create()) {
        ShimFile.LoadString = s => files[s];
        var ef = ExperimentFactory.Load(files.Keys, .......);
. . . .
````
Another test class uses a very similar setup, shimming the same `File.Load()` function. When both tests are run, files from one shim set up end up loaded in another test (I can clearly tell that from faked file names, which differ in the tests).

Is there a way to force sequential test execution?

EDIT: I tried adding 
````C#
[assembly:CollectionBehavior(DisableTestParallelization = true)]
````
to the test assembly, but that did not change anything.

EDIT2: But
````C#
[assembly:CollectionBehavior(MaxParallelThreads = 1)]
````
did it! Does `DisableTestParallelization` supposed to do what I think it supposed to do?

**Comment by wholroyd** [comment]
I can reproduce this issue without using Fakes. I have just short of 2000 tests and this causes about ~560 to fail, when switching to a single thread only leaves about 50 failing (which is what I should expect). Give me to mid next week to see if I can't create a sample project.

**Comment by wholroyd** [comment]
I figured it out. 

In my scenario through the use of AutoMapper and @kkm000's use of the Fakes framework, there are configuration settings held within a static variable in each of those frameworks. Tests within a single class aren't run parallelized to each other, but multiple classes are run asynchronously to each other (assuming I understand the xunit behavior correctly), which is where that static configuration gets out of sync between the multiple running classes' tests. Since statics are associated to the AppDomain, you would have to wrap each class' test execution in it's own AppDomain instance to absolve any cross-configuration in those frameworks.

I'll upload a sample project sometime this weekend.

**Comment by kkm000** [comment]
@wholroyd, I would appreciate if you do! I am swamped in other things, and I do not know when I could get back to building a minimum sample for @bradwilson.

**Comment by wholroyd** [comment]
@kkm000, no worries. The project is at https://github.com/wholroyd/xunit.parallelization-repro and you can see here the current state of the CollectionBehaviorAttribute with DisableTestParallelization enabled with multiple tests in current execution in the test explorer...

![xunit](https://cloud.githubusercontent.com/assets/147990/5791398/2ac6bc58-9ea2-11e4-88e2-97e52ab1e61a.png)

To me, it just seems that xunit would discover tests and stuff as it would today, feeding them into a queue that the test parallelization code would just feed from. The behavior I personally would expect to see for DisableTestParallelization being true would be the same as if I had set the thread count to 1. Otherwise DisableTestParallelization being false without dictating thread count would make it automatically choose (which the TPL calculates something roughly as one thread per core or two if hyperthreaded). Or if I just dictate the thread count for something it assumes parallel unless the value is 1, which obviously is not parallel.

One thought I had would be to remove the DisableTestParallelization flag altogether in favor of just the thread count option. 0 = automatic, 1 = synchronous/serialized, 2+ asynchronous/parallelized

**Comment by wholroyd** [comment]
@kkm000 - Xunit has a few different ways of performing parallelized unit tests. Parallelization boundaries are defined by collection attributes, where collections are performed in parallel to each other. However, tests within a collection are always guaranteed to occur synchronously.

If you don't utilize the collection attributes, a 'catch all' collection is used under the covers. By default, this collection is generated on a per-class basis. You can change that behavior by generating the collection at the assembly level through using this attribute instead...

**[assembly: CollectionBehavior(CollectionBehavior.CollectionPerAssembly)]**

This change is another option that you have if you don't want to completely de-parallelize everything and not bomb your tests. Every assembly in your solution will execute using the de facto standard of per-class, but then switch to per-assembly level collections when using this attribute on selected projects. Assemblies by default do not run in parallel to each other, but can be tweaked via Xunit config files on a per-assembly basis. I didn't see a way via attributes in code to allow this.

@bradwilson - What is the desired outcome for using DisableTestParallelization? The comments in the code say "Determines whether tests in this assembly are run in parallel.", but is only used in the context of the XunitTestAssemblyRunner. If the tests are already grouped at the assembly level, what is the purpose of this switch?

It looks like it's supposed to be used in a situation where the consumer makes use of collection attributes for some, but not all test classes and has already declared per-assembly level collection like above. And since collections are parallelized against each other, is this just a chicken-switch of toggling that parallelization within the assembly?

**Comment by bradwilson** [comment]
There's no bug here.

You're mutating shared state. That's never going to work with test parallelization. This isn't a bug with test parallelization; it's a bug with the fact that they're expecting it to work with mutable shared state. Unless you protect that mutable shared state (or get rid of it), you will be unable to parallelize tests.

I'm not sure whether this truly illustrates the problem with the Fakes support or not, since I don't have source for that. I will say that, given xUnit.net's heavy reliance on `Task`-based parallelization, that any code which mutates shared state, or attempts to use thread local storage, it bound to fail.

**Comment by wholroyd** [comment]
@kkm000 - Does this issue still occur after upgrading to RC2 or later? The repro I had posted above now works as expected in the change from #276 which shipped in RC2. So the weirdness I was seeing without even using Fakes is now gone.

I completely understand and agree with @bradwilson's stance on not supporting Fakes, but I'm personally just curious to see if your problem is now gone.
