### ISSUE TITLE
Misleading documentation, Performance losses

### ISSUE THREAD

**Issue by samtrion** [xunit/xunit#2453]
The [documentation](https://github.com/xunit/abstractions.xunit/blob/335cd98c6b63c1402d7116e589502d3e48a23b5d/src/xunit.abstractions/Reflection/IAttributeInfo.cs#L25-L32) for the `TValue GetNamedArgument<TValue>(string argumentName)` method states that if a property or field does not exist, `default(TValue)` is returned.

However, this is currently not the case, as can be seen from the following line.
https://github.com/xunit/xunit/blob/4747e938e14be895e636bfd24d25635f63d17019/src/xunit.execution/Sdk/Reflection/ReflectionAttributeInfo.cs#L122
This results in `ITraitDiscoverer` implementations being significantly more complex than necessary and execution is up to 4x slower in my setup.

Used NuGet package - `xunit.core` 2.4.1

**Comment by bradwilson** [comment]
Unfortunately, I'm reluctant to change behavior that's been in place for 7 years, even if it contradicts the documentation, because that would be a breaking change for anybody depending on the existing behavior.

**Comment by samtrion** [comment]
> Unfortunately, I'm reluctant to change behavior that's been in place for 7 years, even if it contradicts the documentation, because that would be a breaking change for anybody depending on the existing behavior.

I totally understand your point.

Would it be an option that we update the documentation for the existing method. So that the `ArgumentException` is shown. As well as provide a method `TValue GetNamedArgumentOrDefault<TValue>(string argumentName)` that implements the initial documented behavior.

**Comment by bradwilson** [comment]
I can update the documentation for v3, but I can't easily do so for v2 because it's in an assembly that is never updated (`xunit.abstractions`).

**Comment by bradwilson** [comment]
Circling back to this, I did update the behavior in v3 to return default instead of throw.

https://github.com/xunit/xunit/commit/d4808b28dcb5fe80cbf906984e2a2c7bb33e2cc8#diff-4dc3a1e3a82eb00d18bde5cd5e50f05971efb0d9fcbf001a6d06dd4c550fc4c8

Again, I'm reluctant to change the behavior in v2 because it would be breaking, but I'm going to consider this issue solved for now. Sorry for not closing it last year when the code got committed (I just overlooked it, as obviously I would've referenced the issue when resolving it had I been working on this explicitly).
