### ISSUE TITLE
Double width characters makes the formatting of the arrow slightly incorrect.

### ISSUE THREAD

**Issue by MageCoven** [xunit/xunit#2513]
Double width characters, such as あ, are treated as a normal character when positioning the arrow for indicating where the strings differ.

An example:
```
                  ↓ (pos 8)
Expected: åöäじゃぱねせ
Actual:   åöäじゃぱねせ\0\0\0\0\0\0\0\0\0
                  ↑ (pos 8)
```
Can easily be reproduced with:
```
Assert.Equal("aあ", "abcde");
```

**Comment by mrudang-vora** [comment]
@bradwilson : Could you please let me know more about this issue? In which file this issue is occurring?

**Comment by bartelink** [comment]
@mrudang-vora that's the question. You'll fare far better if you take a proper run at researching it first - the OP gives a full repo scenario, which is about as clean an issue as you're going to get!

**Comment by bradwilson** [comment]
@mrudang-vora There are the following locations that probably need to be looked at:

1. `Assert.Equal` for strings when you don't have access to `Span`: https://github.com/xunit/assert.xunit/blob/f125ad27d024cbf78b6f77b1c38d182731ab4e47/StringAsserts.cs#L314
2. `Assert.Equal` for strings when you do have access to `Span`: https://github.com/xunit/assert.xunit/blob/f125ad27d024cbf78b6f77b1c38d182731ab4e47/SpanAsserts.cs#L556

The code in both of these locations will look similar, because the logic is the same (except that one operates directly on strings, and the other operations on `ReadOnlySpan<char>`).

Since this repository is a Git submodule and doesn't have its own tests, there is documentation on the suggested workflow here: https://github.com/xunit/assert.xunit/#suggested-contribution-workflow

Once you have this working in for v3 and open the requisite PRs, I will also test to ensure that everything works in v2 (and may suggest and/or make changes to support v2).

Thanks!

**Comment by etherfield** [comment]
Are you sure it's not just a font issue? I've copied the string to Notepad++ with the font set to Courier New, 10px (it's monospaced) and it works fine.
Different fonts and sizes may produce different results though.

![Untitled2](https://github.com/xunit/xunit/assets/148793545/37306a5a-b8b8-40ef-922c-aa349d6c8f85)

**Comment by bradwilson** [comment]
@etherfield That's a good point.

I see different spacing based on font. The arrows should be pointing directly at the `c` on the top and the `b` on the bottom. None of them are correct, but they are all incorrect in slightly different ways.

Courier New:

![image](https://github.com/xunit/xunit/assets/16944/7bd8f548-35c7-40ed-b30c-5bd7d9f19213)

Consolas:

![image](https://github.com/xunit/xunit/assets/16944/fbb01825-2961-473d-8b5b-92ca1a02d272)

Cascadia Code/Cascadia Mono:

![image](https://github.com/xunit/xunit/assets/16944/de9e837f-cbb0-493d-b879-41a6b8d125ab)

...and some third party fonts I regularly use...

Input:

![image](https://github.com/xunit/xunit/assets/16944/cccc0d85-3295-45be-b2b5-00173d361b61)

Iosevka:

![image](https://github.com/xunit/xunit/assets/16944/a4e5f3c2-abe5-47f8-b40b-109d631ad9b6)

JetBrains Mono:

![image](https://github.com/xunit/xunit/assets/16944/b91c0641-bbaa-487c-b130-099f5faa0eb8)

My conclusion? The way Windows injects non-fixed pitch fonts for the foreign language into the output is to blame here. The only "fix" that would reliably place the arrow in the right place would involve escaping (thus, not actually printing) any of these non-Latin characters.

I think of the whole, balancing "arrow in the wrong place" vs. "not printing non-Latin characters", I prefer printing and letting the pointer be misplaced. As such I'm closing this issue.

**Comment by bradwilson** [comment]
It's also interesting to note that `dotnet test` cannot print the arrows nor the foreign language characters (and as a result, the "arrows" are pointing to the right place):

![image](https://github.com/xunit/xunit/assets/16944/c6147435-2c17-4db7-a9dc-76bbccdd2f3f)

This might be [rectified in the .NET 8 SDK](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/console-encoding), at which point I expect `dotnet test` to exhibit the same problem.
