### ISSUE TITLE
Add Explicit property to [Fact] and friends

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2518]
A test which is marked as explicit will normally not be run with a "run all" gesture, but will be run when asked for explicitly.

- For the SDK, we will need some metadata to indicate explicit tests (they should have a message, much like skipped tests do today) as well as an object model object which indicates a test which was skipped because of being marked as explicit (to differentiate from tests which are skipped because of being marked as skipped). The APIs to "run all" will not run explicit tests, but any API which takes a test case list will run explicit tests if they're requested. This means that runners should be careful to segregate explicit tests when filtering (give help here when possible with the existing filter classes).
- For theories, the theory data model in v3 has been extended to allow [skipping individual data rows](https://github.com/xunit/xunit/blob/c27a91f8cbcee37cb45699a3a81287bca225e876/src/xunit.v3.core/Sdk/TheoryDataRow.cs#L24). The theory data model should be extended to also allow the data row to be marked as explicit.
- For console runners, the default run all behavior will not run explicit tests (and we should add a reporting of explicit tests). A new option should be added (`-explicit`?) which will include explicit tests.
- For the MSBuild runner, the default run all behavior will not run explicit tests (and we should add a reporting of explicit tests). There is no equivalent to `-method` or `-class` in the MSBuild runner. A new option should be added (`Explicit=`?) which will include explicit tests.
- For the [VSTest runner](https://github.com/xunit/visualstudio.xunit), the ["run all" API](https://github.com/microsoft/vstest/blob/bfc7d83249b5097b9095dc1e3b89e4ccd76adcd5/src/Microsoft.TestPlatform.ObjectModel/Adapter/Interfaces/ITestExecutor.cs#L33) should skip explicit tests and report explicit tests with an outcome of [`TestOutcome.None`](https://github.com/microsoft/vstest/blob/bfc7d83249b5097b9095dc1e3b89e4ccd76adcd5/src/Microsoft.TestPlatform.ObjectModel/TestOutcome.cs#L16); the ["run some" API](https://github.com/microsoft/vstest/blob/bfc7d83249b5097b9095dc1e3b89e4ccd76adcd5/src/Microsoft.TestPlatform.ObjectModel/Adapter/Interfaces/ITestExecutor.cs#L25) should run any explicit test that's in the list.

I think there's some design work TBD yet. Some questions:

- Are the only options for `-explicit` something like `true`, `false`, etc.? Should there, for example, be a way to run only explicit tests (f.e., `-explicit only`)?
- Should `-class` run explicit tests in the given class? How is this impacted by `-explicit`?
- Should `-method` run an explicit test method? How is this impacted by `-explicit`? What about when the method is a theory, but only _some_ of the data has been marked as explicit?
- [Test filtering expressions](https://github.com/xunit/xunit/issues/1833) should be part of the consideration for explicit tests (and probably match the features available via `-explicit`).

Discussion: https://github.com/xunit/xunit/discussions/2483

**Comment by mu88** [comment]
> Are the only options for `-explicit` something like `true`, `false`, etc.? Should there, for example, be a way to run only explicit tests (f.e., `-explicit only`)?

I wouldn't even introduce a command line parameter, because it turns everything topsy-turvy: when a test method or class is marked `[Explicit]`, the only way to run this method or class should be by using `-class` or `-method`, as this is the explicit pendant on the CLI to the UI.  
An `-explicit` parameter would somehow water this explicitness.

> Should `-class` run explicit tests in the given class? How is this impacted by `-explicit`?  
> Should `-method` run an explicit test method? How is this impacted by `-explicit`? What about when the method is a theory, but only _some_ of the data has been marked as explicit?

It depends. Let me give some examples:
```c#
[Explicit]
public class ExplicitTests
{
    [Fact]
    public void RegularTest()
    {
    }
}

public class RegularTests
{
    [Fact]
    public void RegularTest()
    {
    }

    [Fact]
    [Explicit]
    public void ExplicitTest()
    {
    }
}
```

| Command | Result |
|-|-|
| `-class ExplicitTests` | executes `ExplicitTests.RegularTest()` |
| `-class RegularTests` | executes `RegularTests.RegularTest()`, but **not** `RegularTests.ExplicitTest()` |
| `-method RegularTests.ExplicitTest` | executes `RegularTests.ExplicitTest()` |

> [Test filtering expressions](https://github.com/xunit/xunit/issues/1833) should be part of the consideration for explicit tests (and probably match the features available via `-explicit`).

I agree. Based on the previous code sample, I'd like the following behavior:
| Command | Result |
|-|-|
| `-filter test==ExplicitTests` | executes `ExplicitTests.RegularTest()` |
| `-filter test==RegularTests` | executes `RegularTests.RegularTest()`, but **not** `RegularTests.ExplicitTest()` |
| `-filter test==RegularTests.ExplicitTest` | executes `RegularTests.ExplicitTest()` |
| `-filter category==Explicit` | executes `ExplicitTests.RegularTest()` **and** `RegularTests.ExplicitTest()` |

**Comment by bradwilson** [comment]
Yeah, I don't like a separate attribute. That's a failing of the design of NUnit, IMO, one that I'm not anxious to repeat ("floating" attributes which may end up applied in places they don't belong).

Assume the only way to mark something as explicit is via `[Fact(Explicit = true)]` or `[InlineData(1, 2, 3, Explicit = true)]` or the moral equivalent, and then re-frame whether you think `-explicit` is something that should be there or not.

**Comment by bradwilson** [comment]
Also, `-filter category==Explicit` seems to imply something I hadn't proposed (which is that explicitness is a category of some kind; we don't have categories, but trait name/value pairs, so what other things would you put under the list of 'category' in filters?)

**Comment by mu88** [comment]
I'm totally fine without `-filter category==Explicit` 🙂

And I also like your proposal `[Fact(Explicit = true)]` or `[InlineData(1, 2, 3, Explicit = true)]`, a dedicated attribute doesn't seem necessary to me.  
The only thing I'm not sure about is how to mark a complete class as explicit. Because it seems a little too verbose to me marking all tests within a class with `[Fact(Explicit = true)]`. But it's not a big issue for me, just a little bit inconvenient. What are you thoughts about this?

**Comment by markm77** [comment]
This seems a very nice proposal for handling known broken tests that are not immediately fixable but need to be able to be run "explicitly" to debug and fix. It will also be useful for special-purpose tests which should only run by request. To be honest these are the two reasons I use "skip" today so probably will convert uses of "skip" to "explicit". For me, if a test should never be run, I remove it or make sure it is not dynamically created via Theory data rather than "skip" it. I see "explicit" as an upgraded form of "skip".

It might be nice (as a secondary thing) to have the option to include "explicit" tests in a normal test run (e.g. to check status of broken tests) but I definitely would prefer explicit tests to be off by default. I guess from above there is a question about whether to make an exception to this when running tests for a class or method (including Theory data) that only has explicit tests. Not sure this is a great idea as means explicit tests could be run by accident (no longer fully opt-in) but don't feel that strongly about this.

**Comment by markm77** [comment]
Actually the more I think about it, I definitely don't want to accidentally run explicit tests just because e.g. I forgot I removed the only non-explicit test in a class and am testing using the command line. So yes I believe an "explicit" option or something like this should be required to run explicit tests. IDEs could then implement intelligent "Run Tests" behaviour on classes/methods only containing explicit tests because they can use icons to show all tests are explicit etc.

**Comment by mu88** [comment]
Could you please elaborate more on this, e. g. with the help of a code sample? I don't quite get it, sry

**Comment by markm77** [comment]
Hi @mu88 , no problem, let's take your class `RegularTests` above and let's imagine I run the tests in this class via a script.

If someone comments out the method `RegularTest` (perhaps wrongly) I don't want my script to suddenly start running the explicit test `ExplicitTest` when I have not asked to run explicit tests. This sort of behaviour is fine in an IDE where you have visual information about explicit tests (icons) and can then choose to run or not but at the command line I don't want explicit tests to be on or off unpredictably based on code I cannot see (perhaps edited by someone else).

That was the point I was trying to make.

**Comment by markm77** [comment]
Another way to explain is to say I'd rather not have explicit tests in a class/method run or not depending on what else is in the class/method when using scripts.

**Comment by mu88** [comment]
So in your example, you have a situation like this, right?
```c#
public class RegularTests
{
    // [Fact]
    // public void RegularTest()
    // {
    // }

    [Fact]
    [Explicit]
    public void ExplicitTest()
    {
    }
}
```

Now when running `-class RegularTests` (either from the GUI or CLI), I'd expect nothing to happen: `ExplicitTest` is explicit, so it shouldn't be executed. And since there are no non-explicit tests, that call will not run any tests. Only when executing `-method RegularTests.ExplicitTest`, a test gets executed.

**Comment by markm77** [comment]
> Now when running -class RegularTests (either from the GUI or CLI), I'd expect nothing to happen: ExplicitTest is explicit, so it shouldn't be executed. And since there are no non-explicit tests, that call will not run any tests.

Okay, but you also gave an example above where `[Explicit]` was defined on the class instead of the method and in that case you wanted the explicit test to run. To me the behaviour should be the same regardless of whether `[Explicit]` is applied at class or method level (if indeed such flexibility is supported).

> Only when executing -method RegularTests.ExplicitTest, a test gets executed.

I'm afraid I don't like this. If a Theory method has one non-explicit case which is removed do the explicit cases suddenly start to run without an "explicit" option? I'd rather an "explicit" option was required to run explicit tests in all cases. Like I've said though, I'm expecting this shouldn't restrict IDEs from silently adding an "explicit" option when only explicit tests are requested (so the "explicit" option is invisible to the user).

**Comment by bradwilson** [comment]
>The only thing I'm not sure about is how to mark a complete class as explicit.

There's no way to do this without introducing another attribute. I'm tempted to just say this isn't directly supported (you can only mark individual tests or test data as explicit).

>If a Theory method has one non-explicit case which is removed do the explicit cases suddenly start to run without an "explicit" option? I'd rather an "explicit" option was required to run explicit tests in all cases. Like I've said though, I'm expecting this shouldn't restrict IDEs from silently adding an "explicit" option when only explicit tests are requested (so the "explicit" option is invisible to the user).

Yeah, we should separate the GUI from the CLI from a usability standpoint.

In the GUI, you will see which tests were not run because of explicit, and you can select it/them to run them explicitly. I believe this is how other frameworks work today, so this should be fine.

In the CLI, the way I see it there are two potentially competing/complementary options (`-method` and `-explicit`). I believe that, for sure, `-explicit` is a necessary option, because ease of use would suggest you'd want options like `-explicit off` (default), `-explicit on`, and `-explicit only`. So then the remaining question is should `-method` run an explicit method in the absence of the `-explicit` option? (And how about explicit data rows in a test method?)

I'm currently leaning towards "from the CLI, the only way to run explicit tests is with `-explicit on` or `-explicit only`" regardless of usage of `-method`. This could be supplemented by logic which says if you've asked to run a filtered list of tests, and it ended up running nothing because everything you selected was explicit, it could say "Did you mean to add `-explicit on`?"

**Comment by markm77** [comment]
@bradwilson , makes a lot of sense to me, very much looking forward to xUnit v3!

**Comment by mu88** [comment]
Are there any considerations/discussions/clarifications missing? It seems to me that it has a relatively mature status

**Comment by bradwilson** [comment]
How the runners we build will handle explicit tests:

- Console runner (individual and meta): `-explicit <off|on|only>` with default of `off`
- MSBuild runner: `<xunit Explicit="<off|on|only>"> with default of `off`
- TDnet runner: Explicit is off for all run gestures except running an individual test method.
- VSTest runner: Explicit is off for "run all", and on for "run test" (meaning, if the user request to run a subset of tests, and that subset includes explicit tests, they will be run). In Visual Studio, not run tests will be shown as Not Run in their UI; in VS Code, using the "Run Test" or "Debug Test" to run an individual test that is explicit will run that test. _[Implementation details to be verified]_

**Comment by bradwilson** [comment]
From an extensibility point of view, the only thing that is marked as "explicit" is a test:

https://github.com/xunit/xunit/blob/8af64f2f810911ed8aefc3f19517ba78620e7827/src/xunit.v3.core/Sdk/v3/TestCases/_ITest.cs#L15-L18

Implementations of this are free to thread this through the system as they see fit. For `[Fact]` and friends, this gets surfaced on the test case:

https://github.com/xunit/xunit/blob/8af64f2f810911ed8aefc3f19517ba78620e7827/src/xunit.v3.core/Sdk/v3/Abstractions/IXunitTestCase.cs#L13-L16

https://github.com/xunit/xunit/blob/8af64f2f810911ed8aefc3f19517ba78620e7827/src/xunit.v3.core/Sdk/v3/TestCases/XunitTest.cs#L43-L44

This opens up extensibility opportunities to express explicit-ness at any layer, since `_ITest` is the lowest layer in the stack. I may later introduce `Explicit` as something you could set on an individual data row, and others could come and introduce class-level `[Explicit]` attributes that filter down into test cases and tests in the same way that `[Fact(Explicit)]` filters down from the test case into the test today.

**Comment by mu88** [comment]
Thx for your awesome work once again, @bradwilson! I'm happy to see this feature coming in `v3` :) any ideas when this version will be available?

And if you consider it useful, I'd be glad to assist you and the project with some coding work. It was not my intention that you have to do this bunch of work only on your own.

**Comment by bradwilson** [comment]
> any ideas when this version will be available?

At this point, not sure. I push alpha builds to MyGet but without VSTest support yet, it's still got limited usability. At the moment this is still just a "when I can find time" project, though that may change soon.

> And if you consider it useful, I'd be glad to assist you and the project with some coding work. It was not my intention that you have to do this bunch of work only on your own.

There are a bunch of issues marked with "help wanted". It may be helpful to consult the roadmap as well: https://github.com/xunit/xunit/issues/2133

**Comment by bradwilson** [comment]
FYI b54c11d51ef848e008d577aafa1806e04e116498 adds `Explicit` to `ITheoryDataRow` (which is something that will also be supported for `[InlineData]` in #2545):

https://github.com/xunit/xunit/blob/b54c11d51ef848e008d577aafa1806e04e116498/src/xunit.v3.core/ITheoryDataRow.cs#L10-L14

As you can see, this is a nullable-boolean with fallback, so this can override explicitness in both directions (on or off).

**Comment by CharlieDigital** [comment]
I feel like I'm doing something wrong (.NET 9) as I cannot get the `--explicit` flag to work in any scenario:

```
dotnet test --explicit only 

MSBUILD : error MSB1001: Unknown switch.
    Full command line: '/Users/cchen/.dotnet/sdk/9.0.304/MSBuild.dll -maxcpucount -verbosity:m -tlp:default=auto -nologo -restore --property:VsTestUseMSBuildOutput=true -target:VSTest -nologo --explicit only -property:VSTestArtifactsProcessingMode=collect -property:VSTestSessionCorrelationId=10679_30ab1df3-85b7-406c-8a03-51d012804ad3 -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/Users/cchen/.dotnet/sdk/9.0.304/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/Users/cchen/.dotnet/sdk/9.0.304/dotnet.dll'
  Switches appended by response files:
Switch: --explicit
```

As a pass through:

```
dotnet test -- --explicit only

Restore complete (0.3s)
  Motion.Common succeeded (0.1s) → /Users/cchen/code/motion/motion-net/src/Motion.Common/bin/Debug/net9.0/Motion.Common.dll
  Motion.Apps succeeded (0.2s) → /Users/cchen/code/motion/motion-net/src/Motion.Apps/bin/Debug/net9.0/Motion.Apps.dll
  Motion.Runtime succeeded (0.2s) → /Users/cchen/code/motion/motion-net/src/Motion.Runtime/bin/Debug/net9.0/Motion.Runtime.dll
  Motion.Apps.Tests succeeded (0.4s) → bin/Debug/net9.0/Motion.Apps.Tests.dll
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v3.1.4+50e68bbb8b (64-bit .NET 9.0.8)
[xUnit.net 00:00:00.29]   Discovering: Motion.Apps.Tests
[xUnit.net 00:00:00.42]   Discovered:  Motion.Apps.Tests
[xUnit.net 00:00:00.56]   Starting:    Motion.Apps.Tests
[xUnit.net 00:00:00.89]   Finished:    Motion.Apps.Tests
  Motion.Apps.Tests test succeeded (1.3s)

Test summary: total: 14, failed: 0, succeeded: 13, skipped: 0, duration: 1.3s
```

The explicit test is skipped (13/14 run)

**Comment by bradwilson** [comment]
@CharlieDigital For VSTest, you can't pass `--explicit` because VSTest doesn't understand that switch. You need to pass it like [a RunSettings configuration](https://xunit.net/docs/config-runsettings#Explicit) value, so the command line switch you're looking for is:

`dotnet test -- xUnit.Explicit=only`

(Note: RunSettings are actually implemented internally in VSTest as XML, as that's the format of the .runsettings file on disk, so be aware that the names are case sensitive!)

<img width="1964" height="1884" alt="Sample unit test with runs without/with explicit enabled" src="https://github.com/user-attachments/assets/f002728e-5215-4f03-9728-c2b9e4e6c5c2" />

**Comment by CharlieDigital** [comment]
Got it; much appreciated!
