### ISSUE TITLE
IClassFixture<T> strange behavior

### ISSUE THREAD

**Issue by Anakael** [xunit/xunit#2544]
`T` in `IClassFixture` seems to be reused for several test collections. Is that intended? Is there any way to force creating new fixture object for test class?

I create integration tests, which works against real database and I want to create new database for each test (collection) run and delete it after.

For that I have: 

```cs
public class TestClass : IClassFixture<ApplicationFactory>
{
  IRepository repository;
  public TestClass(ApplicationFactory app)
  {
    repository = app.GetRepo();
    /// Don't save app here
  }
  
  [Fact]
  public async Task TestSmth1()
  {
    // Write something to repository
    // Read something to repository
  }
}
```
```cs
public class ApplicationFactory : TastServerFixture, IDisposable
{
  private string connectionString;
  public ApplicationFactory()
  {
    connectionString = Server.Services.GetService<IConfiguration>.GetConnectionString("ContextName");
    InitDatabase(); // Create new instance of database
  }
  
  public void Dispose()
  {
    DeleteDatabase(); // Delete whole database
    base.Dispose();
  }
}
```

```cs
public abstract class TestServerFixture: IDisposable
{
  public TestServerFixture()
  {
    Server = CreateServer(); // Create IWebHostBuilder, update connectionString.
  }
  public TestServer Server { get; }
}
```
I add DateTime.Now and Guid to dabase name.

But when I run all tests (several test class), it fails with message that database already deleted. But for different test classes I have error message referenced to *the same database*. In case new instance of `ApplicationFactory` for test class it shouldn't happen, but there is seems to be sharing instance of `ApplicationFactory` for different test classes. But not for all, because not only one database created with test run.

As test runner I use `dotnet test`.

To solve the problem I put all test classes in one collection and disable parallelism for test collections.

**Comment by bartelink** [comment]
The point of of IClassFixture is to have something that's spun up before tests for a class are run and then disposed.
There is also ICollectionFixture etc which makes it live longer and be shared across all Test Classes that are in that collection

Aside: IMO this is question as opposed to a proven bug, so it should be logged either as a discussion here (tens of readers per day), or on stackoverflow (way more). Only repo watchers with time will ever see something like this. If this can be closed before it absorbs maintainer time, that's for the best.

If you have not read it recently, all the info is in https://xunit.net/docs/shared-context and the fixture management in xUnit is bullet proof in terms of its intended function, but I feel your pain - I've definitely spent time in a loop cursing why it wasn't Doing What I Mean...

**Comment by bartelink** [comment]
>What do you mean?

Have been using it for >10y. Have doubted it from time to time. I have always been wrong to do so.

> So, it supposed to call ctor/dispose for each test class, not for all classes, doesn't it? If so, it seems like bug. If not, it seems like something that should be mentioned in documentation.

If you can suggest a better wording that would have made you realise this from the off, that would help everyone (there is a repo for that site I linked - the ideal thing would be a PR, but an issue with a wording suggestion would be fine too).

For me it is implicit in that that there should not be hidden sharing going as there is in your case. Where that is the case, you get two choices:
1) use Collection Fixtures so usage is serialized (one test class at a time gets to use it)
2) explicitly manage it yourself in a way that they can can coexist - e.g. if you created a SCHEMA within the DB per instance of the Class Fixture and deleted that, they could co-exist

ASIDE: Another thing I'm not sure the docs make explicit is that 100% relying on test fixtures as a way to delete things is debatable - e.g. if spinning up term cloud resources, better to manage that outside rather than relying on a Dispose to guarantee cleanup. I tend to thus rely more on a fixture to guarantee a starting state than a final state. It's no harm to proactively clean up of course, but e.g. not at the price of destroying context for a failing tests if I can help it.

**Comment by Anakael** [comment]
-> rely more on a fixture to guarantee a starting state than a final state
I'm relying not on final state, but on fact that disposed objects should not be used, first of all.

Also, can parallelism and test runner (dotnet test) affect the way of fixture reusage? For example, create fixtures poll for test classes rather than one fixture for one test class?

**Comment by bartelink** [comment]
>I'm relying not on final state, but on fact that disposed objects should not be used, first of all.

Multiple classes, and class fixtures can be in flight concurrently, by design

If you are being handed a Disposed _instance_, that's a bug, but I doubt that's the case

>Also, can parallelism and test runner (dotnet test) affect the way of fixture reusage? For example, create fixtures poll for test classes rather than one fixture for one test class?

In general those settings override/constrain the default behavior. Sometimes that can be a good idea if you are migrating stuff and/or trying to pretend its NUnit/Junit etc in terms of semantics.

In general you'll just cause yourself pain if you go down the road of leaning on such things (i.e. if you are setting concurrency off, you might as well not bother using xUnit)

dotnet test in general is more about spinning up a host context than controlling any behavior as such - i.e. Rider/VS/dotnet test intentionally all drive the same basic high level scheduling/management

> For example, create fixtures poll for test classes rather than one fixture for one test class?

If I am correctly inferring what you mean, the answer is that xUnit does not have anything directly for such things - it falls in the "or you can write code yourself" split I mentioned earlier

i.e. the TL;DR is:
- Class Fixture - share state between tests for a test class. Does not influence concurrency so many can be in flight
- Collection Fixture - share state across multiple test classes. Forces max one test class in flight at a time.

Anything else is a matter of you either writing code in test class ctor/dispose, or using one of the two constructs above

i.e. there is nothing that xUnit does beyond that - its clear and simple. Sometimes its inadequate. But it would be a nightmare to troubleshoot if the semantics were actually more complex (and there would still be messy things that you'd want to do which would not be covered).

**Comment by bartelink** [comment]
>What I am trying to understand is:
>Can one instance of class fixtures be shared between multiple test classes or not? Or it's not defined?

If you used a Collection Fixture, yes. But the catch is that the other key thing that does is to guarantee that only one Test Class uses it at a time.

i.e. if you have 5 test classes and 2 use the collection fixture, there will be 4 collections of tests to run. They will run in parallel to the max degree possible, with that constraint of only one at a time for the ones using the Collection Fixture.

>I'll try to reproduce behavior with a more simple example to understand where exactly the problem.

👍 Makes sense - my instinct remains that SELECT is not broken - its just a misunderstanding as to the exact guarantees that the xunit constructs are providing (or not, in your case).

BTW this is great material for a high traffic self-answered SO question when you solve it...

**Comment by Anakael** [comment]
I've did more testing and it seems like everything is fine without `TestCollection`, but with `ParallelizeTestCollections: false` (it is expected that EF can not work with parallelizm).

Another instance of fixture created for test class.

Perhaps, while I was adding `TestCollection` I've also fixed some other error, which I can not reproduce now.

Thank you for your time and explanation! It was really helpfull!

**Comment by bartelink** [comment]
If you're happy, great.
If it was me, and I was trying to prevent test classes from running concurrently, I'd use a Test Collection for that rather than neutering all parallelism
Either way, a self-answered question on SO can be a good way to share a solution and/or become aware of better ones; I'm sure this is a pretty common thing people want to do.
