### ISSUE TITLE
SECURITY ISSUE:  XUnit 2.4.2 is vulnerable for CVE-2019-0820

### ISSUE THREAD

**Issue by neerajmathur** [xunit/xunit#2568]
Hi,

In our code scan, we have found that XUnit 2.4.2 is vulnerable to CVE-2019-0820, Please have a look at below dependency graph where it is using System.text.regularexpressions.4.3.0.nupkg which has CVE-2019-0820 vulnerability.

![image](https://user-images.githubusercontent.com/6531916/182855362-1e46f9b1-d63b-456f-bb6d-ddde9c20aefc.png)

Please let us know when you are planning to fix this issue.

Thanks,
neeraj

**Comment by alexmurari** [comment]
The `System.text.regularexpressions` [nuget package](https://www.nuget.org/packages/System.Text.RegularExpressions/4.3.0) is flagged as vulnerable and it has a [patch version (4.3.1)](https://www.nuget.org/packages/System.Text.RegularExpressions/4.3.1) from 2019 that fixes the vulnerability.

I wonder why the package resolver doesn't select the latest patch version available or at least one version that isn't flagged as vulnerable or obsolete.

**Comment by bradwilson** [comment]
This is a far downstream dependency from us. I don't believe we can fix this; this should be a matter to be fixed with `netstandard.library`.

**Comment by snakefoot** [comment]
Just downgrade to xUnit 2.4.0 (Supports NetStandard2.0), and wait for xUnit 3.0. See also https://github.com/xunit/xunit/issues/2470 and https://github.com/xunit/xunit/issues/2294 and https://github.com/xunit/xunit/pull/2529

**Comment by bdovaz** [comment]
> This is a far downstream dependency from us. I don't believe we can fix this; this should be a matter to be fixed with `netstandard.library`.

I don't understand this reasoning.

In 2.4.0 it was targeting .NET Standard 2.0:

https://github.com/xunit/xunit/blob/2.4/src/xunit.assert/xunit.assert.csproj

As of 2.4.1 it was changed to .NET Standard 1.1:

https://github.com/xunit/xunit/blob/2.4.1/src/xunit.assert/xunit.assert.csproj

https://github.com/xunit/xunit/blob/2.4.2/src/xunit.assert/xunit.assert.csproj

It is because of this change of target (to a much older one) that this vulnerability has been added.
