### ISSUE TITLE
Unusual Theory test names with double

### ISSUE THREAD

**Issue by JDCain** [xunit/xunit#2574]
Since updating to 2.4.2 theories which take a double generate unusual test names.

```
Test2(i: 2.1000000000000001)
Test2(i: 2.2000000000000002)
```
in 2.4.1 they display as
```
Test2(i: 2.1)
Test2(i: 2.2)
```

**Comment by daneelbester** [comment]
Was able to re-recreate the OP's issue.

Environment details:
OS: Windows 10
IDE: Visual Studio 2022

xUnit version 2.4.1
![image](https://user-images.githubusercontent.com/38572018/186904820-a12143df-aa52-4395-a3ea-3141dca279b7.png)

xUnit version 2.4.2
![image](https://user-images.githubusercontent.com/38572018/186904925-ea22480c-7646-42b6-b106-d7b5eef7da19.png)

Attempted to resolve the issue, but am not able to successfully build the project locally.

**Comment by zachspang** [comment]
I am working on this.

**Comment by bradwilson** [comment]
The decision to increase the precision in 2.4.2 was explicit. We are not planning to roll back that change.

FWIW, what you're experiencing is that double cannot represent a `.1` accurately because of the way floating points work. So you never actually have `2.1` in double form. In a sense, you were being lied to in 2.4.1.
