### ISSUE TITLE
Deadlock when synchronously awaiting an async method in GitHub Actions

### ISSUE THREAD

**Issue by YegorStepanov** [xunit/xunit#2587]
Deadlock in **Windows**/**Linux** when 2 tests wait the tasks in sync.
Deadlock in **Windows**/**Linux**/**macOS** when 3 tests wait the tasks in sync. (**macOS** has 3 threads in **GH Actions**)

I cannot reproduce it locally, but **GH Action** always falls.

Other test frameworks run fine. 

For 2 tests:
![image](https://user-images.githubusercontent.com/19392641/193124662-967ac349-a4a0-4c85-88d2-3811fb9f079a.png)
https://github.com/YegorStepanov/xunit-deadlock/actions/runs/3153937997

For 3 tests:
![image](https://user-images.githubusercontent.com/19392641/193129628-98f1ef73-6b27-46bd-9edb-0009be6d9196.png)
https://github.com/YegorStepanov/xunit-deadlock/actions/runs/3153957706

(I have set a 10 min timeout in GH Actions, without a timeout they fall after 6 hours)

### Code
```C#
[Fact]
public void Method1()
{
    Task<int> task = new BenchmarkClass1().Method();
    bool isAsyncMethod = TaskHelper.TryAwaitTask(task, out object result);

    Assert.True(isAsyncMethod);
    Assert.Equal(1, result);
}

[Fact]
public void Method2()
{
    Task<int> task = new BenchmarkClass2().Method();
    bool isAsyncMethod = TaskHelper.TryAwaitTask(task, out object result);

    Assert.True(isAsyncMethod);
    Assert.Equal(42, result);
}


public class BenchmarkClass1
{
    public async Task<int> Method()
    {
        await Task.Delay(1);
        return 1;
    }
}

public class BenchmarkClass2
{
    public async Task<int> Method()
    {
        await Task.Delay(1);
        return 42;
    }
}

public static class TaskHelper
{
    // we need await task in sync and return result.
    // returns true if task
    public static bool TryAwaitTask(object task, out object result)
    {
        result = null;

        if (task is null)
        {
            return false;
        }

        // ValueTask<T>
        var returnType = task.GetType();
        if (returnType.IsGenericType && returnType.GetGenericTypeDefinition() == typeof(ValueTask<>))
        {
            var asTaskMethod = task.GetType().GetMethod("AsTask");
            task = asTaskMethod.Invoke(task, null);
        }

        if (task is ValueTask valueTask)
            task = valueTask.AsTask();

        // Task or Task<T>
        if (task is Task t)
        {
            if (TryGetTaskResult(t, out var taskResult))
                result = taskResult;

            return true;
        }

        return false;
    }

    // https://stackoverflow.com/a/52500763
    private static bool TryGetTaskResult(Task task, out object result)
    {
        result = null;

        var voidTaskType = typeof(Task<>).MakeGenericType(Type.GetType("System.Threading.Tasks.VoidTaskResult"));
        if (voidTaskType.IsInstanceOfType(task))
        {
            task.GetAwaiter().GetResult();
            return false;
        }

        var property = task.GetType().GetProperty("Result", BindingFlags.Public | BindingFlags.Instance);
        if (property is null)
        {
            return false;
        }

        result = property.GetValue(task);
        return true;
    }
}
```

Repro: https://github.com/YegorStepanov/xunit-deadlock
Occurred in: https://github.com/dotnet/BenchmarkDotNet/pull/2114. Check comments/CI builds in PR, they can help.

If I add `[Collection("Dissable parallelisation")]` or move the tests to one class, there is no deadlock.

cc @timcassell

**Comment by YegorStepanov** [comment]
MacOS falling when 3 methods run in parallel (I will update issue):

![image](https://user-images.githubusercontent.com/19392641/193128999-7c544a17-fe73-4f0d-a0bf-de153d4adc3f.png)
https://github.com/YegorStepanov/xunit-deadlock/actions/runs/3153957706

**Comment by abelbraaksma** [comment]
Wow! I just spent two days investigating this, readily assuming it was own mistake in some race condition. But since I don’t have access to the GH actions machines, I couldn’t  do much but try (see https://github.com/abelbraaksma/TaskSeq/pull/27).

In my case, the issue popped up only after having a decent number of tests. 40 to 100 run fine, the number is different each time. 

One of the biggest issues in analysing this is that the XUnit runner **does not show a ‘test started’** line as other engines do. And using `ITestOutputHelper` didn’t help either as this info is only dumped **after** the test either succeeds or fails.

What’s more is that GH won’t show you the log (which is bug) in cases like this. It will show it when you keep it open. But once you click away you’ll never get it back, making analysis even harder.

Workaround for the latter was to use `dotnet test —blame-timeout`, which kills the whole test runner if any single test takes too long.

And no, `TimeoutAttribute` on the tests doesn’t help either. Not sure why, but docs say it’s non deterministic in parallel runs. But deterministic or not, it does nothing in this case. And like the OP I also saw runs take forever (until I added the blame timeout).

I’ll  try some older functions, or move back to NUnit. At least for the time being.

**Comment by abelbraaksma** [comment]
Btw, just a moment ago I created a mini runner that just takes all the tests of the assembly, and run them dozens of times in parallel. This showed me that the problem wasn’t with me, but with XUnit.

Locally this was easier, as NCrunch has a “run tests repeatedly until they fail” mode. After running for several hours, in parallel, all was still green. In other words, the issue really seems to be with XUnit itself.

**Comment by YegorStepanov** [comment]
> What’s more is that GH won’t show you the log (which is bug) in cases like this.

I've read that you can get output from the console if you run the tests through the cmd script, not directly `dotnet test`.

> And no, TimeoutAttribute on the tests doesn’t help either.

I meant `GH Action` timeout, not [Timeout]. I updated the issue.
https://github.com/YegorStepanov/xunit-deadlock/blob/365e75a4d7dbb0748cc539ab6ea98f0286d25a82/.github/workflows/tests.yml#L12

**Comment by abelbraaksma** [comment]
> I meant GH Action timeout, not [Timeout]. I updated the issue.

Ah, thanks, I wasn't aware of that option. Though I currently use `dotnet test --blame-hang-timeout 60s`, your option may be more idiomatic. 

I wonder if this issue is caused by thread starvation, as seemingly soft all the way back in 2015: https://github.com/xunit/xunit/pull/257.

**Comment by bradwilson** [comment]
This is because we limit the number of running tests by default to the number of cores available, and we do so via a [`SynchronizationContext`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.synchronizationcontext?view=net-7.0): https://github.com/xunit/xunit/blob/v2/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs

Synchronously waiting on Task objects will cause deadlocks in such situations.

You have two choices:

- Stop synchronous waits on Task and use async/await instead
- Raise the number of concurrent tests (or disable max concurrency entirely): https://xunit.net/docs/configuration-files#maxParallelThreads

**Comment by abelbraaksma** [comment]
> Stop synchronous waits on Task and use async/await instead

The deadlocks happen even if you have no synchronous waits at all. Max Parallel is interesting, though, I'll give that a whirl.

Ideally, the xUnit Runner should simply not deadlock itself. Not sure if it is possible (well, I haven't seen the issue in other testing libraries, and also running xUnit in NCrunch is seamless), but running tests, even if the code is bad, should never lead to a hanging runner. If anything, it should timeout instead, or raise something like `ThreadExhaustionException` (if that were a thing).

**Comment by bradwilson** [comment]
@abelbraaksma wrote:

> The deadlocks happen even if you have no synchronous waits at all.

If the analysis is correct that the deadlock is in the `MaxConcurrencySyncContext`, then this isn't possible. The only way to make that deadlock is to synchronously wait for some other bit of code to run that also runs on a thread in the same sync context.

The synchronous wait might not be in your unit test code; it may be in the code under test, or even buried somewhere in third party code that you're calling. (I will leave aside the judgment that any library which ships with synchronous waits of `Task` objects is fundamentally broken because there are lots of scenarios where synchronization context objects exist, and this is a surefire way to end up in a deadlock.)

The situation is likely being exacerbated in the Actions environment because you get very few logical processors, and our default maximum concurrency behavior is one thread per logical processor. The test is broken because of the deadlock, but you may never see its broken-ness in a normal run on a high-core-count developer machine.

FWIW, this is one of the reasons why our CI build artificially limits parallelism to a single thread, so we can discover if there are any self-inflicted deadlocks in our framework:

https://github.com/xunit/xunit/blob/4e6fc7ae07663ca770878b79d461a3c3f977b75f/tools/builder/models/BuildContext.cs#L175

https://github.com/xunit/xunit/blob/4e6fc7ae07663ca770878b79d461a3c3f977b75f/tools/builder/models/BuildContext.cs#L204-L206

(As the comment suggests, it also gives us more accurate test timing information. 😄)

It's also worth noting that, generally speaking, "logical processors" maps in CPU terms to "thread". My 12-core CPU is fully hyperthreaded, and as such has 24 "logical processors" according to Windows:

![image](https://user-images.githubusercontent.com/16944/214479215-0e246609-99f2-43d1-a3a8-5e4d624c8a5f.png)

Modern Intel CPUs have a mix of cores, some of which are hyperthreaded (two logical processors per core) and some which are not (one logical processor per core). Some older AMD and Intel CPUs don't support hyperthreading at all, so they have a single logical process per CPU core.

> Ideally, the xUnit Runner should simply not deadlock itself.

I agree with the assertion, and I disagree with the conclusion that we did this to ourselves. In fact, I'd say our test suite pretty much guarantees that if `MaxConcurrencySyncContext` is deadlocked, it's because of an incorrectly written test by the end user, and not because there is something broken with xUnit.net itself.

It's impossible to implement a feature like "maximum number of running threads" without blocking things. As to why running in a constrained environment is the default, it's because we found that typically just letting things run unconstrained means you will end up running slower, as you're subject to frequent and unnecessary thread context switches from the OS scheduler. Ideally you want one fully-utilized thread per logical processor in your CPU (logical thread/core), so our default behavior is this 1:1 mapping. We offer you a way to override this behavior, since your tests may not behave optimally (for example, if you frequently have synchronous waits).

If you cannot remove the synchronous code, then raising the number of threads (or removing the sync context entirely by disabling the thread limitation feature) is really the only other way to "fix" it. Note that both "fixes" hide the problem. In the former case, you may still end up deadlocked if you get unlucky with enough incorrectly written tests executing in the same way; in the latter case, you are guaranteed never to deadlock the sync context (since it's gone), but you will potentially end up paying the performance penalty associated with the excessive thread switches.

**Comment by bradwilson** [comment]
BTW, the quickest way to figure out which tests are deadlocking is to run with a single thread, and then enable long running test notifications. You could use a [configuration file](https://xunit.net/docs/configuration-files) like:

```json
{
  "$schema": "https://xunit.net/schema/current/xunit.runner.schema.json",
  "diagnosticMessages": true,
  "longRunningTestSeconds": 10,
  "maxParallelThreads": 1
}
```
