### ISSUE TITLE
xunit v3 unable to find on nuget

### ISSUE THREAD

**Issue by mufasalg0** [xunit/xunit#2614]
I am trying this website to get PackageReference:
https://www.myget.org/feed/xunit/package/nuget/xunit/2.4.3-pre.2#

`<PackageReference Include="xunit" Version="2.4.3-pre.2" />
`
When I put this on csproj I am getting an error as Unable to find package xunit with version (>=2.4.3-pre.2)

I have also tried this:
`<PackageReference Include="xunit" Version="2.4.3-pre.1" />
`I am also getting the same error on Error list

**Comment by Romanx** [comment]
This is because as you found the pre-release are not on nuget they're hosted on myget so the nuget restore needs to know the feed to ask for the package from.

Here are some docs for package sources: https://learn.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources

You'll need to add the following feed and the restore should work:
`https://www.myget.org/F/xunit/api/v3/index.json`

**Comment by bradwilson** [comment]
@mufasalg0 Also, those aren't v3 packages; they are CI builds of the `v2` branch. (There are no current plans for a 2.4.3 release, so these packages are likely to mean nothing.)

The v3 packages (also on MyGet, so use @Romanx's instructions) are named starting with `xunit.v3`.
