### ISSUE TITLE
AllAsync / XUNIT_VALUETASK not enabled in .NET 6 project

### ISSUE THREAD

**Issue by HappyRashair** [xunit/xunit#2648]
I'm using `2.4.2` version of xunit and as I see, the `XUNIT_VALUETASK ` is not enabled there for some reason, although I'm using .NET 6 project.

Coming back from this thread: https://github.com/xunit/xunit/discussions/2498

Project settings:
```
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Configurations>Debug;Release;Acceptance</Configurations>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>11</LangVersion>
  </PropertyGroup>


<ItemGroup>
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.1" />
      <PackageReference Include="xunit" Version="2.4.2" />
      <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
</ItemGroup>
```

Decompiled `CollectionAsserts`:
![image](https://user-images.githubusercontent.com/95406820/212700712-36b8bcee-9a89-4c5b-9e49-d75d291054f2.png)

**Comment by bradwilson** [comment]
The binary version of the assertion library for v2.4.2 is not built with `XUNIT_VALUETASK` because it targets `netstandard1.1`, which doesn't support `ValueTask`:

https://github.com/xunit/xunit/blob/93616f73fc2c5a1dca11963a41d52ce9e51f1bb3/src/xunit.assert/xunit.assert.csproj#L3-L8

As you can see, it only defines `XUNIT_NULLABLE`.

The [source code](https://github.com/xunit/assert.xunit) is shared via Git submodule between v2 and v3. For v3, we enable all flags:

https://github.com/xunit/xunit/blob/2b1f75b320b54edc364785d5d7634deff71784f8/src/Directory.Build.props#L13

If you want `ValueTask` support in v2, you must build the project yourself with a compatible target and compatible flags. In order to do this, you must:

1. Create a new .csproj file to compile the assertions privately for your own usage.
   1. Add a `<DefineConstants>` property group item like the one above that defines all the flags you wish to enable.
   2. Reference the `xunit.assert.source` NuGet package.
2. In each unit test project:
   1. Remove the `xunit` NuGet package reference, and replace it with `xunit.core` and `xunit.analyzers` references.
   2. Add a new project reference to the .csproj you created in step 1.

_As noted in the [annotations](https://github.com/xunit/assert.xunit#annotations), `XUNIT_SKIP` is not supported on v2. If you define this flag, the assertion will successfully compile, but any usage of `Assert.Skip`, `Assert.SkipUnless`, or `Assert.SkipWhen` will result in a failed test rather than a skipped one._

I've updated the samples project to include an example of this pattern: https://github.com/xunit/samples.xunit/tree/main/AssertSource

`AssertionLibrary` is the project that [brings in the source-based assertion library](https://github.com/xunit/samples.xunit/blob/main/AssertSource/AssertionLibrary/AssertionLibrary.csproj) (and also shows how you can [use this to extend the `Assert` class](https://github.com/xunit/samples.xunit/blob/main/AssertSource/AssertionLibrary/MyCustomAsserts.cs)), and `ExampleTests` shows [the updated imports](https://github.com/xunit/samples.xunit/blob/main/AssertSource/ExampleTests/ExampleTests.csproj) and [examples of using the assertions](https://github.com/xunit/samples.xunit/blob/main/AssertSource/ExampleTests/UnitTest1.cs)).

**Comment by HappyRashair** [comment]
Alright, thank you 👍, I think I will wait until v3 is released, I thought it was a bug
