### ISSUE TITLE
being able to execute static test method inherited from base class

### ISSUE THREAD

**Issue by pedrobsaila** [xunit/xunit#2704]
* Is this a question? no, it is a feature request
* Is this a bug with VSTest (aka Visual Studio Test Explorer, `dotnet test`, `dotnet vstest`,
  or `vstest.console.exe`)? no
* Did you search the docs @ https://xunit.net/ ? yes
* Did you search the issues list to see if someone already reported it? yes
* Did you create a simple repro for the problem? (see for examples dotnet/runtime#83617)

The dotnet runtime team detected in their codebase that static test methods inherited from base types do not run (see dotnet/runtime#83617). After further investigation, we think the reason is that xunit uses `Type.GetMethods(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)` aka `RuntimeReflectionExtensions.GetRuntimeMethods(this Type type)` to extract test methods, while we need an additional binding flag `BindingFlags.FlattenHierarchy` to be able to extract the base static ones. Can you evolve xunit to use the additional binding flag or do something equivalent that extracts base static methods ? If this is something that you don't agree to do, can you at least create an analyzer warning users that these kind of methods would not be executed ?

In case you need an external contributor for this one, I can work on it.

**Comment by bradwilson** [comment]
@pedrobsaila I have marked this as a bug open for help wanted.

Note: the `main` branch is for v3 work, and the `v2` branch is for v2 work. It will need to be fixed in both places. There currently is no plan for another release from the `v2` branch, so pulling this in for v2 usage will require moving to a pre-release MyGet-based package.

**Comment by bradwilson** [comment]
I looked at the solution for v3 and don't think I can port it to v2, because the ability to use `BindingFlags` to get a flattened hierarchy isn't available to us, since `BindingFlags` does not exist in .NET Standard 1.1: https://learn.microsoft.com/en-us/dotnet/api/system.reflection.bindingflags#applies-to

**Comment by bradwilson** [comment]
v2 fix: cc18546778719f7a2e0198e78c3901dfd502a36e
v3 fix: da319e0eeb6bbafc93ab2a2878c87ea6b40c6041
