### ISSUE TITLE
Can we Pass the complex type test method as parameter

### ISSUE THREAD

**Issue by surwasesandy** [xunit/xunit#2723]
TestCases.xlsx excel file has more than 10 records.

public class RegisterTest 
    {
        [Theory(DisplayName = nameof(Save))]
        [ExcelData<Register>(fileName: @"Data/TestCases.xlsx")]
        public async void Save(Register account)
        {
            ////mock Repositery
            Assert.NotNull(account);
        }
    }
    public class Register
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
    }

**Comment by bradwilson** [comment]
`ExcelData` hasn't been something we supported since v1.x (which is about 10 years old now).

We have a `SqlData` sample here, which is the closest analogue: https://github.com/xunit/samples.xunit/tree/main/SqlDataExample

You could adapt something like that to talk to Excel (via ADO.net) and then use it to create a structured object per row rather than one parameter per call. This is definitely not something that we've ever supported (or tried to support), but you could do it yourself.

That said, I don't think using actual Excel spreadsheets for your data is a great idea in 2023. A CSV file would be easier to read and interpret without requiring nearly as much infrastructure and library support as reading from Excel, and you could continue to update the data via Excel since it can read and write CSV files. This is likely the avenue I would pursue if I were in your situation.
