### ISSUE TITLE
Source for xunit.abstractions at 2.0.3?

### ISSUE THREAD

**Issue by mmitche** [xunit/xunit#2731]
Hello,

A number of the xunit v2 packages at 2.4.2 depend on xunit.abstractions at 2.0.3. https://github.com/xunit/abstractions.xunit seems to contain the source, but the newest tag is 2.0.1.

Can the source for 2.0.3 be pushed to the repo?

**Comment by bradwilson** [comment]
The source has not changed since 2.0, only the NuGet package target frameworks.

I will push up extra tags to make this clear.

**Comment by fviernau** [comment]
@bradwilson I'm also trying to find the source for 2.0.3. According to you comment I just can take the 2.0 tag.
However, could you tell whether in the codebase there is a variable holding the 2.0.3 value anywhere in a follow up commit. Or is the version not in the codebase at all?

Are you planning to add the missing 2.0.3 tag?

**Comment by bradwilson** [comment]
The tags are there: 

![image](https://github.com/user-attachments/assets/4af4ee47-fc95-4056-bbbe-d0f568939b40)

They all point to the same commit. That's because, as I've said previously, there has only ever been a single binary, built back in 2015. It has appeared in four different NuGet packages as target frameworks were evolved, .nuspec properties needed to be updated, and we also started signing our binaries and packages, but the binary is otherwise identical.
