### ISSUE TITLE
Certificate error occurred when opening v2.5.0 NuGet package with NuGetPackageExplorer

### ISSUE THREAD

**Issue by filzrev** [xunit/xunit#2747]
**Summary**
On NuGet packages page(https://www.nuget.org/packages/xunit).  
There is a link `Open in NuGet Package Explorer`.

When click this link, following page is opened. 
https://nuget.info/packages/xunit/2.5.0

NuGet Package Explorer shows `Health` checks are failed by following errors. 
> Validation Exception: Certificate Choices
![image](https://github.com/xunit/xunit/assets/103790468/452874b1-c61a-4da1-8c74-56aa520c789b)

Version `2.5.0-pre.11` or earlier packages has no errors. and `Digital Signatures` are displayed successfully.
https://nuget.info/packages/xunit.core/2.5.0-pre.11
![image](https://github.com/xunit/xunit/assets/103790468/deab2cd3-fc31-456d-80ee-fc667a657b47)

Additionaly This error occurred when using `nuget.info` only. If running [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) on local environment.  
These certificate errors are not displayed.

I don't know this certificate errors occurred by `xunit` nuget package signing process.
or occurred by ` nuget.info` side problems.

But recently updated packages that use `.NET Foundation` signing certificates
doesn't have this errors. it can be avoided by nuget package signing process.

**Example packages that using signing certificate issued by.NET Foundation**
https://nuget.info/packages/ReactiveUI/19.3.3

**Comment by bradwilson** [comment]
This is a known issue that can be fixed by updating your version of the .NET SDK.

https://fosstodon.org/@xunit/110672008182851610

> FYI: We've gotten a report of a user experiencing NU3003 ("The package signature is invalid") when trying to restore or verify the new 2.5.0 packages.
>
> It appears that this can be fixed by ensuring you are on the latest build of the .NET SDK that is appropriate for your build. Here are two screenshots showing the difference between 6.0.314 and 6.0.411 (both released at the same time, less than two weeks ago).
>
> ![image](https://github.com/xunit/xunit/assets/16944/c44e91ce-9b79-4d56-b032-2cdc46d12e49)
>
> ![image](https://github.com/xunit/xunit/assets/16944/0589f2f9-ee07-4b6e-978c-f001cb1af809)

https://fosstodon.org/@xunit/110672188455160116

> If you're curious what's going on here, [@bradwilson](https://fosstodon.org/@bradwilson@mastodon.social) discovered (via a diff of the 6.0.314 and 6.0.411 source) that there is a new certificate trust list for code signing that's shipped in the .NET SDK. The Microsoft Time Stamp service certificate that's in use by .NET Foundation is not inherently trusted by any OS, and prior SDK versions relied on the OS to validate code signing trust.
>
> The design and motivation for the new trust system is documented here: [https://github.com/dotnet/designs/blob/main/accepted/2021/signed-package-verification/re-enable-signed-package-verification.md](https://github.com/dotnet/designs/blob/main/accepted/2021/signed-package-verification/re-enable-signed-package-verification.md)

**Comment by filzrev** [comment]
Thanks for your explanation.
I didn't noticed already this problem discussed on Mastodon.

> The Microsoft Time Stamp service certificate that's in use by .NET Foundation is not inherently trusted by any OS, and prior SDK versions relied on the OS to validate code signing trust.

Is it impossible to change `timestamper` from `Microsoft Public RSA Time Stamping Authority` to `digiCert Timestamp 2022 - 2` for .NET `6.0.3x` SDK compatibility?

*xunit*
|{![image](https://github.com/xunit/xunit/assets/103790468/558d3488-a350-4e40-bb0d-2a2be034b270) 

As far as I tested on my environment (with self-signed certificate).  
`timestamper` can be changed with `--timestamper http://timestamp.digicert.com` option, when running `dotnet sign` commands.
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-sign#options

**Comment by bradwilson** [comment]
> Is it impossible to change timestamper from Microsoft Public RSA Time Stamping Authority to digiCert Timestamp 2022 - 2 for .NET 6.0.3x SDK compatibility?

The .NET Foundation has made this change for their new signing process, but not all projects have been converted over. Apparently ReactiveUI has not been converted, but xUnit.net has. Since the .NET Foundation controls the entire certificate chain as well as the time stamping service they use, I cannot change this (and I don't have the ability to revert back to the old process, because I moved to the new one when the one was broken for me, based on some changes they've done on the backend with authentication).

I have asked the .NET Foundation people to revert their change for the time being. Of course, that will not fix the problem for the 2.5.0 release.

All that said:

6.0.3xx will _never_ be compatible. Despite still being "released", it's considered out of date and shouldn't be used. There is a 6.0.4xx that is compatible, and you can match it up with whatever version of 6.0.3xx that you're currently using (for example, if you're using 6.0.314 to target .NET 6.0.19, then you can move to 6.0.411). See the complete [6.0 SDK download list](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) to validate what the correct download would be.

**Comment by filzrev** [comment]
> Since the .NET Foundation controls the entire certificate chain as well as the time stamping service they use, I cannot change this

I understand that existing code signing process can't changed from xunit project side.

Thank you for your clarification.

---
Following contents are personal notes. relating to this problem.

**.NET SDK Support policy**
> 6.0.3xx will never be compatible. Despite still being "released", it's considered out of date and shouldn't be used.

SDK 6.0.3xx is supported by Visual Studio 2022 `v17.2`. as described at SDK download page.
And it's  [LTSC (Long-Term Servicing Channel) version](https://learn.microsoft.com/en-us/visualstudio/productinfo/vs-servicing#enterprise-professional-and-build-tools-editions-support.).   It'll be updated & supported until `July 11, 2024`.

So it's reasonable to support `6.0.3xx`  to following .NET SDK support policy.

**Code Signing tools**
.NET Foundation replace signing tool to [dotnet/sign](https://github.com/dotnet/sign) tool. (https://github.com/dotnet-foundation/wg-maintainers/issues/90)

 [dotnet/sign](https://github.com/dotnet/sign) tool set default `timestamper` to `http://timestamp.acs.microsoft.com`.
And this settings is used when timestamper url is not explicitly specified.
https://github.com/dotnet/sign/blob/ef0e6b3ef8281dff1d62cea34445bd88fc3e6714/src/Sign.Cli/CodeCommand.cs#L37

It seems possible to override this settings to `http://timestamp.digicert.com` from command line.

**Comment by bradwilson** [comment]
I can't change the fact that 6.0.3xx will never be supported for xUnit.net 2.5.0, because I can't do anything about it. /shrug

**Comment by bradwilson** [comment]
I am re-opening (and then again re-closing as fixed 😁) this issue because the 2.5.1 builds have gone back to using the DigiCert time stamping service. I have thus far not been able to get any changes into the [official builds of .NET SDK 6.0.3xx]() nor [changing the default for all .NET Foundation projects](), but it's still early. I have hopes that one or both of these will end up eventually being resolved, hopefully before July of 2024 (at which point it stops being relevant, I suppose).

Here are the comparisons between `2.5.1-pre.6` and `2.5.1-pre.7`:

<img src="https://cdn.fosstodon.org/media_attachments/files/110/714/296/563/948/141/original/1ef79c3f49443dd2.png" />

<img src="https://cdn.fosstodon.org/media_attachments/files/110/714/299/783/424/733/original/2e450d9c050340ab.png" />
