### ISSUE TITLE
Make xUnit1031 opt-in

### ISSUE THREAD

**Issue by FLAMESpl** [xunit/xunit#2780]
So I have just updated my projects to xunit to 2.5.1 and what I have faced is a lot of nonsense analyzer issues "Test methods must not use blocking task operations, as they can cause deadlocks. Use an async test method and await instead.". 

The thing is, they are all awaited. Analyzer doesn't correctly recognize which task is awaited and I don't think it will ever be able to, just given few examples:

```csharp
public class Test
{
    [Fact]
    public async Task Method1()
    {
        var firstJob = AsyncJob();
        var secondJob = AsyncJob();
        await Task.WhenAll(firstJob, secondJob);

        Console.WriteLine(firstJob.Result + secondJob.Result);
    }

    [Fact]
    public async Task Method2()
    {
        Console.WriteLine(await AsyncJob().ContinueWith(x => x.Result.ToString()));
    }

    private static Task<int> AsyncJob() => Task.FromResult(1);
}
```

in both methods xunit complains about awaited tasks. Therefore my postulate is that it should be opt-in rule, I prefer it this way rather than having this rule manually turned off in every xUnit project I am going to ever use.

**Comment by bradwilson** [comment]
While we look for a fix, you can disable it by adding a `.editorconfig` file to your test project with the following content:

```ini
[*.cs]
dotnet_diagnostic.xUnit1031.severity = none
```

**Comment by marcinjahn** [comment]
I had a similar issue. A minor update of xUnit (2.5.0 -> 2.5.1) actually stops my project from building due to new analyzers being introduced.

**Comment by Leonardo-Ferreira** [comment]
similar here

**Comment by Ioana37** [comment]
Same for me. Our unit tests project is now having build errors.

**Comment by Playmountain710** [comment]
Same here

**Comment by bradwilson** [comment]
`1.4.0-pre.3` marks this as a Warning instead of an Error now: https://github.com/xunit/xunit.analyzers/commit/2c5f100d8068233a27987f909052e3552b4f4c98

**Comment by bradwilson** [comment]
I have fixed the two illustrated situations:

1. Calling `task.ContinueWith(t => ...)` marks the task into the lambda as safe
2. Calling `Task.WhenAll` marks all the passed tasks as safe

Additionally, I have fixed one other:

3. Calling `var t = task.WhenAny(...)` marks the returned task `t` as safe

Further, to reduce friction I have lowered this from Error to Warning and softened the language from "must not" to "should not". This means builds will not be broken by default.

All of these are part of `1.4.0-pre.7`.

-----

There are more conditions I'm aware of that I'm content to leave unsolved, because of both complexity and esoteric usage (especially in the context of a unit test).

1. Waiting for a task to complete with some mechanism other than `await`, like:

   ```csharp
   while (!task.IsCompleted)
   {
       // Do some busy work and delay
   }

   var result = task.Result;
   ```

   This one is not trivial because you need to ensure that referencing the task result is only done when you know it's completed, and I don't want to evaluate the code that strongly. The example here is purposefully simple, but it's not hard to come up with additional examples where following the logic becomes much more challenging.

2. Separating `GetAwaiter()` from `GetResult()`:

   ```csharp
   var awaiter = task.GetAwaiter();
   // ...
   var result = awaiter.GetResult();
   ```

   This is non-trivial because we'd have to back-track through the code to see where the awaiter came from (which I suspect is probably not as simple as it sounds).

3. Using the continuation methods on an awaiter can mark the tasks as complete in the same way that `ContinueWith` can (though with significantly less functionality, like not being able to wait for the completion of the continuation):

   ```csharp
   task.GetAwaiter().OnCompleted(() => task.Result);
   task.GetAwaiter().UnsafeOnCompleted(() => task.Result);
   ```

   This has the same problem with issue 2 (the awaiter itself might be a variable and not a direct call to `task.GetAwaiter()`). The complexity of the code here could also get a little bit out of control, including the idea that rather than just calling `task.Result` in the callback, I could be using `awaiter.GetResult()`, which is yet another variant of issue 2.

4. Using `WhenAny` without an intermediate variable:

   ```csharp
   var x = (await Task.WhenAny(task1, task2)).Result;
   ```

   This doesn't feel like a common usage to me, especially with `Task<T>` value coalescing, since there's no reason to actually call `.Result` in this case (you would much more commonly just `await` a second time), and there's no reason I can think of why someone would immediately call something like `.Wait()` on a task they know to be complete.

I am going to leave this issue open for a while to make it easier to find if anybody runs across these more esoteric cases, to make their arguments for why they should be supported.

**Comment by bradwilson** [comment]
There have been 3 months without comment, so I'm going to close this issue now.
