### ISSUE TITLE
Localization issue with xUnit when using [InlineData] on enum with negative values

### ISSUE THREAD

**Issue by boginw** [xunit/xunit#2796]
On a computer set with Faroese locale, negative numbers are `ToString`ed using the Unicode minus instead of a dash for the minus sign. This causes tests using `[Theory]` combined with `[InlineData]` for enum values with negative numbers to fail with a `System.ArgumentException`. I found it to be failing for around [182 locales](https://github.com/boginw/xunit-enum-bug/blob/main/failed.txt). Given the high number of failing locales, I suspect that this issue has been brought up before, but I was unable to find any previous issue.

The issue seems to arise due to the use of `value = Enum.Parse(argument.ArgumentType, value.ToString());` in [`ReflectionAttributeInfo.cs:46`](https://github.com/xunit/xunit/blob/c54cc52ffb275c81afed022521870193bbca6c39/src/xunit.execution/Sdk/Reflection/ReflectionAttributeInfo.cs#L46C81-L46C81), where `ToString` should likely be culture-invariant, i.e., `ToString(CultureInfo.InvariantCulture)`.

**Steps to Reproduce:** 
1. Set computer locale to Faroese.
2. Define an enum with a negative value.
3. Create a test using `[Theory]` and `[InlineData]` referring to the negative enum value.
4. Run the test.

**Expected Behavior:** 
The test should run without any localization-related issues.

**Actual Behavior:** 
Received a `System.ArgumentException` with the message `Requested value '−1' was not found`.

**Additional Details:**
- Suspected location of issue: In `ReflectionAttributeInfo.cs`, specifically the line `value = Enum.Parse(argument.ArgumentType, value.ToString());`
- Here's a link to a reproducible repository: https://github.com/boginw/xunit-enum-bug
- Perhaps related: https://github.com/xunit/xunit/issues/1605

**Comment by boginw** [comment]
Thank you for the swift response and for looking into the issue. I'm glad to hear that the bug is addressed in v3. I understand the challenges of backporting fixes to older versions like v2, but I appreciate your efforts in trying to address it there as well :)

**Comment by bradwilson** [comment]
I've ended up down a dark rabbit hole now. 🫤

I (belatedly) realized that interpolated strings are always done with the current culture, which is often not what I want (and interpolated strings don't trigger CA1305). The "support" for culture with interpolated strings (`string.Create(culture, $"...")`) isn't available everywhere that I'd need it, so for the moment I'm considering removing any interpolated string that isn't directly related to UI (the only place where I actually want current culture).

I have 925 matches for `$"` in the `main` branch and 657 in the `v2` branch.

!["ouch" GIF](https://github.com/xunit/xunit/assets/16944/8d90c5f3-7a1c-449c-b244-22ce8646bd1a)

I also discovered that there were places in the v3 source base that weren't triggered by your bug, but would end up triggering eventually with time. One example: I use an enum during serialization to map the type of the data:

https://github.com/xunit/xunit/blob/e889879ebeeabcc0c2bb248d2ee2a1fe5a1dd8c0/src/xunit.v3.common/Serialization/SerializationHelper.cs#L805-L835

and serialize it via its int value (inside of an interpolated string):

https://github.com/xunit/xunit/blob/e889879ebeeabcc0c2bb248d2ee2a1fe5a1dd8c0/src/xunit.v3.common/Serialization/SerializationHelper.cs#L430

Updating the serialization tests to use `[CulturedTheory("en-US", "fo-FO")]` caused all the `fo-FO` tests to fail because of the U+2212.

So, yeah. This will get fixed, but it's gonna take a little time.

**Comment by boginw** [comment]
Holy... that's a lot of strings! Seems like a lot of work. Since the issue seems to exist in around 182 locales, and nobody seems to have reported this issue, suggests that the issue is very rare. Might it make sense to only fix it in v3 and leave v2 be?

**Comment by 0xced** [comment]
FYI: there's an alternative way to use the invariant culture in interpolated strings, see https://learn.microsoft.com/en-us/dotnet/api/system.formattablestring.invariant#remarks

Maybe it could be used instead of `string.Create` ?

**Comment by bradwilson** [comment]
`string.Create` does not exist in .NET Framework (any version), so it's not an option.

The refactoring has been going quickly, and as it turns out a ton of it was in the assertion library (which is shared between v2 and v3, so only has to be done once).

**Comment by bradwilson** [comment]
Still plugging away. Turns out there is a second place where enums are parsed that might've been the problem all along.

If I switch from `InlineData` to `MemberData`, the problem disappears, which means the parsing here is likely to blame:

https://github.com/xunit/xunit/blob/94526f43f1f3d96d41a7d024c2fb47084c74ae89/src/xunit.execution/Sdk/Reflection/ReflectionAttributeInfo.cs#L46

**Comment by bradwilson** [comment]
It's probably working in v3 because of an unrelated change I made, where I swapped from the `Convert` function that I wrote in v2 to a new `Expression`-based conversion system in `Reflector`.

Change: https://github.com/xunit/xunit/commit/d4808b28dcb5fe80cbf906984e2a2c7bb33e2cc8

https://github.com/xunit/xunit/blob/2d0f499708cfdf3022a86911be9d38a9a5c9554d/src/xunit.v3.common/Reflection/Reflector.cs#L74-L85

Going to see if I can get a unit test to just isolate this problem, and then perhaps port over some or all of the change I made to v2.

**Comment by bradwilson** [comment]
Yep, this passes in `en-US` and fails in `fo-FO`: 🎉 

```csharp
public class ConstructorArgs
{
    [CulturedFact("en-US", "fo-FO")]
    public void CanConvertEnumArgs()
    {
        var method = typeof(ConstructorArgs).GetRuntimeMethod(nameof(UnusedFunction), new Type[0]);
        Assert.NotNull(method);
        var attributeData = method.GetCustomAttributesData();
        Assert.NotNull(attributeData);
        var attributeDatum = Assert.Single(attributeData);
        var attribute = new ReflectionAttributeInfo(attributeDatum);

        var ctorArgs = attribute.GetConstructorArguments();

        var ctorArg = Assert.Single(ctorArgs);
        var inlineArgData = Assert.IsType<object[]>(ctorArg);
        var inlineArgDatum = Assert.Single(inlineArgData);
        var enumValue = Assert.IsType<EnumWithNegativeValue>(inlineArgDatum);
        Assert.Equal(EnumWithNegativeValue.NegativeOne, enumValue);
    }

    enum EnumWithNegativeValue
    {
        NegativeOne = -1,
    }

    [InlineData(EnumWithNegativeValue.NegativeOne)]
    public void UnusedFunction() { }
}
```

I'm going to add this as a documentation test to v3 as well. 😄

**Comment by bradwilson** [comment]
Verified: `2.5.4-pre.3` (on feedz.io) does resolve the problem.

Results:

![image](https://github.com/xunit/xunit/assets/16944/2b02d4a0-ed69-493c-ad94-97838a492be1)

Diff: (I reverted it back to .NET 6 because I don't install .NET 7 on my Linux machines)

```diff
diff --git a/EnumBug.Tests/EnumBug.Tests.csproj b/EnumBug.Tests/EnumBug.Tests.csproj
index d3a6941..3aea4e3 100644
--- a/EnumBug.Tests/EnumBug.Tests.csproj
+++ b/EnumBug.Tests/EnumBug.Tests.csproj
@@ -1,7 +1,7 @@
 <Project Sdk="Microsoft.NET.Sdk">

     <PropertyGroup>
-        <TargetFramework>net7.0</TargetFramework>
+        <TargetFramework>net6.0</TargetFramework>
         <ImplicitUsings>enable</ImplicitUsings>
         <Nullable>enable</Nullable>

@@ -11,7 +11,7 @@

     <ItemGroup>
         <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0"/>
-        <PackageReference Include="xunit" Version="2.5.3"/>
+        <PackageReference Include="xunit" Version="2.5.4-pre.3"/>
         <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3">
             <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
             <PrivateAssets>all</PrivateAssets>
@@ -25,5 +25,5 @@
     <ItemGroup>
         <ProjectReference Include="../EnumBug/EnumBug.csproj" PrivateAssets="all"/>
     </ItemGroup>
-
+
 </Project>
diff --git a/EnumBug/EnumBug.csproj b/EnumBug/EnumBug.csproj
index 6836c68..eb2460e 100644
--- a/EnumBug/EnumBug.csproj
+++ b/EnumBug/EnumBug.csproj
@@ -1,7 +1,7 @@
 <Project Sdk="Microsoft.NET.Sdk">

     <PropertyGroup>
-        <TargetFramework>net7.0</TargetFramework>
+        <TargetFramework>net6.0</TargetFramework>
         <ImplicitUsings>enable</ImplicitUsings>
         <Nullable>enable</Nullable>
     </PropertyGroup>
```

**Comment by bradwilson** [comment]
Worth noting: I did these two targeted fixes (both of which I believe were necessary) before doing the string interpolation change in v2. I'm still planning to do that (as well as enabled CA1304 and CA1305), because I believe it will open up other issues along the way that need to be resolved.

**Comment by bradwilson** [comment]
(I seriously now just realized you pointed to the ReflectionAttributeInfo line in your bug report and I totally lost sight of that!)
