### ISSUE TITLE
Assert.Equal doesn't use comparer for sets

### ISSUE THREAD

**Issue by AndriySvyryd** [xunit/xunit#2831]
```C#
[Fact]
public void Test()
    => Assert.Equal(
        new HashSet<int> { 1 },
        new HashSet<int> { 2 },
        (int x, int y) => true);
```
v2.6.2

__Expected__
No exceptions

__Actual__
>   Assert.Equal() Failure: HashSets differ
Expected: [1]
Actual:   [2]

**Comment by bradwilson** [comment]
Actually, this is working as designed.

This is the equivalent of what we do with what you wrote:

```csharp
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Xunit;

namespace Empty;

public class MyComparer : IEqualityComparer<int>
{
	public bool Equals(int x, int y) => true;

	public int GetHashCode([DisallowNull] int obj) => obj.GetHashCode();
}

public class TestClass
{
	[Fact]
	public void TestMethod()
	{
		var comparer = new MyComparer();
		var set1 = new HashSet<int>(comparer) { 1 };
		var set2 = new HashSet<int>(comparer) { 2 };

		Assert.True(set1.SetEquals(set2));
	}
}
```

And this fails:

![image](https://github.com/xunit/xunit/assets/16944/494a08cd-ea2e-4086-9172-4cbbe22047fa)

Hash sets aren't linear containers. You would rightfully expect your test to pass with an array or a list, because we go in order to compare items. For hash sets, we rely on the inner implementation of set equality (because of previous bugs).

The problem lies in our default implementation of `GetHashCode()` (that we auto-generate when you pass us a comparer func). HashSets decide whether items are equal and where to put them based on the hash code. If two values have different hash codes, they're not considered to be the same value. If two values have the same hash code, then it relies on the `Equals()` function to determine if they're the same value or not. Because our `GetHashCode()` will give different hash codes for `1` and `2`, your equality function is never called.

As such, if I make a single change to return a constant value for the hash code, then your test passes:

```csharp
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Xunit;

namespace Empty;

public class MyComparer : IEqualityComparer<int>
{
	public bool Equals(int x, int y) => true;

	public int GetHashCode([DisallowNull] int obj) => 0;
}

public class TestClass
{
	[Fact]
	public void TestMethod()
	{
		Assert.Equal(new HashSet<int> { 1 }, new HashSet<int> { 2 }, new MyComparer());
	}
}
```

![image](https://github.com/xunit/xunit/assets/16944/61adb67d-273c-44df-a9ae-c9f87f748c04)

So the answer is: you need a full comparer implementation like the one above that obeys both rules required by the hash set. Our default implementation cannot be changed because we don't know that you're going to always return `true` for the `Equals()` function, so you're the only one who knows that the hash function needs to just return a constant value.

**Comment by AndriySvyryd** [comment]
The current design is not consistent in how it performs the comparison. The real test doesn't look like the above, but something like

```C#
Assert.Equal(
        GetExpectedCollection(...),
        GetActualCollection(...),
        (int x, int y) => DeepEquals(x, y))
```

So, statically I don't even know when both collections happen to be `HashSet<>` and suddenly the comparison rules become different from other collections.

Why can't the default implementation return a constant for `GetHashCode` when a func comparer is used? That would make the behavior consistent and predictable.

**Comment by bradwilson** [comment]
> The current design is not consistent in how it performs the comparison.

That's because HashSets are not like arrays or lists.

> So, statically I don't even know when both collections happen to be HashSet<> and suddenly the comparison rules become different from other collections.

That I can't help you with.

> Why can't the default implementation return a constant for GetHashCode when a func comparer is used? That would make the behavior consistent.

Returning a constant value for GetHashCode degrades the performance of HashSet to a linear container, and given how we must re-create HashSets to properly compare them, that would be a bad general purpose decision.

**Comment by AndriySvyryd** [comment]
> That I can't help you with.

At the very least this behavior should be clearly documented as it's counter-intuitive.

> Returning a constant value for GetHashCode degrades the performance of HashSet to a linear container, and given how we must re-create HashSets to properly compare them, that would be a bad general purpose decision.

So, basically you are saying that performance trumps consistency in this case.

**Comment by bradwilson** [comment]
> At the very least this behavior should be clearly documented as it's counter-intuitive.

Documented where? Having `Assert.Equal` call `SetEquals` when given hash sets does make sense. I think the problem is you're stuck believing that linear contains are the same as hash sets and they're just not.

> So, basically you are saying that performance trumps consistency in this case.

I disagree with your assessment about consistency, and yes performance is always a consideration.

**Comment by bradwilson** [comment]
Here's how you fix this:

```csharp
    Assert.Equal(
        GetExpectedCollection(...).ToArray(),
        GetActualCollection(...).ToArray(),
        DeepEquals)
```

**Comment by bradwilson** [comment]
Given this conversation, I'm consdering changing `Assert.Equal` to throw when given hash sets + a func because that's basically never what you want.

**Comment by bradwilson** [comment]
Here's a docs page: https://xunit.net/docs/hash-sets-vs-linear-containers

I think if I choose to throw, the exception will link to this page.

**Comment by AndriySvyryd** [comment]
Consider using linear comparison for `SortedSet<>`

**Comment by bradwilson** [comment]
I decided to throw an exception. Links to the source changes are here: https://github.com/xunit/xunit/issues/2838#issuecomment-1843634055

**Comment by bradwilson** [comment]
> Consider using linear comparison for SortedSet<>

This is a very minor edge case in my opinion, and again you can communicate your intent for "treat this like a linear collection" by ensuring that it's a linear collection. If you give us sets, we use `SetEquals`, end of story. If the end result of that (without a custom comparison function) is that sorted sets have the same results whether treated like sets or linear collections, then that also gets you what you want.

There is no amount of arguing that can convince me that (any kind of) set + a naked comparison function (without a corresponding implementation of `GetHashCode`) is a legitimate use case.

**Comment by AndriySvyryd** [comment]
> This is a very minor edge case in my opinion, and again you can communicate your intent for "treat this like a linear collection" by ensuring that it's a linear collection (with .ToArray())

In this case it is actually a matter of correctness, because the order is as important aspect to a `SortedSet` as to any linear collection. But xunit is ignoring this information by using set comparison.

This passes:
```C#
    [Fact]
    public void SetTest()
        => Assert.Equal(
            new SortedSet<int> { 1, 2 },
            new SortedSet<int>(new ReverseComparer()) { 1, 2 });

    public class ReverseComparer : IComparer<int>
    {
        public int Compare(int x, int y) => y - x;
    }
```

While this fails:
```C#
    [Fact]
    public void ListTest()
        => Assert.Equal(
            new SortedSet<int> { 1, 2 }.ToList(),
            new SortedSet<int>(new ReverseComparer()) { 1, 2 });
```

**Comment by bradwilson** [comment]
I'm done debating this with you. You have been given the work around over and over again.
