### ISSUE TITLE
Assert.Equal(hashset, hashset, comparerFunc) needs a fix

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2838]
Given the conversation in #2831, callers who call `Assert.Equal` with two hash sets and a comparer function are destined for failure. This is because of the way hash sets consider equality: they _first_ consult `GetHashCode`, and if the two hash codes are not equal, then the values are not equal. They do not call `Equals` until `GetHashCode` ends up return equality. As such, just providing a comparer function is not sufficient.

There are two possible solutions:

1. Throw. If you're in this situation, you need to provide `GetHashCode`; just a comparer isn't enough.

2. Implement `GetHashCode` in terms of the equality func: if you think the two values are equal, then they have to have the same hash code. However, as mentioned in the above-linked bug, just returning a constant value for `GetHashCode` will have potentially significant performance downsides, since the hash code is also used for distribution to ensure lookups/comparisons are closer to O(1) than O(n). It's also assumed that `GetHashCode` is faster than equality comparisons, though this is probably less of an issue.

I'm torn on which is better. I think option 1 is simpler, though offers unexpected runtime surprises. Option 2 gets us back into worse performance, because all calls to `GetHashCode` are assumed to have to call `Equals` first, and then the hash code computation for the two values needs to be resilient to ordering differences.

**Comment by bradwilson** [comment]
(FWIW, I'm not even sure option 2 is possible.)

**Comment by bartelink** [comment]
You know this but: Option 1 seems like a no brainer, and anything with bad perf should not be considered. An analyzer can provide guidance to ameliorate any pain, but life will go on.

**Comment by JamesTerwilliger** [comment]
@bartelink I think the original issue that raised this discussion was a situation where the arguments to the Assert were not known to be hashsets to begin with, so an analyzer would not help here.

I'm also wondering if we're thinking about it backwards. The intent isn't "do a fast thing, and when we can't, throw an error", it's "do what the user wants but do it as fast as possible", right? I had interpreted the original question to be "what does it mean to compare hashsets when a comparer is provided" and a workaround was provided in the original issue to convert both to arrays. In that case, it seems as if the "intent" of the user is to think of the two hashsets as enumerables. Xunit already encourages that thinking because the interface to `Assert.Equal` is not `Assert.Equal(HashSet<T>, HashSet<T>, comparer)` or `Assert.Equal(ISet<T>, ISet<T>, comparer)` but rather `Assert.Equal(IEnumerable<T>, IEnumerable<T>, comparer)`.

If `Assert.Equal` has a signature that is specific to sets, I would agree wholeheartedly with the error approach, but in that case, we wouldn't even offer an overload that takes a comparer. Having this one case where we throw an error and then tell the user to do a slow thing anyway to work around the problem feels like a non-optimal experience.

**Comment by bartelink** [comment]
>where the arguments to the Assert were not known to be hashsets to begin with,
Where they generic? Were they `Object`?
----
In my world, two IEnumerables and a comparer means you have a pair of arbitrarily long inputs and you want to feed them through a comparison function

If I so desire, I could render them lazily. Or one might be an array, and the other some other structure (my expected might be an array I precomputed; my actuals might be a List).

--- 
If there's special behavior for when both happen to be ISet, that's great. But I don't mind getting an exception if you believe it's not what I want.

Especially if there's a danger that the assertion will pass quickly, but later come back to me as a result of me:
a) getting lucky with the GetHashCode
b) getting lucky that the algorithm happened to have reasonable perf because I had a low number of items 
---
Chances are the horse has bolted but off the top of my head, I'd expected an `Assert.SetEqual` that makes the different semantics unambiguous.

In general, APIs that go off and do clever things based on type tests are not the first thing you want to do. But I've never thought about this deeply; Jim and Brad however have - and I trust they've made a lot of my tests do the right thing without me even considering some subtleties over time.

My mention of an Analyzer is based on the fact that I would hope/assume that at least one of the inputs can be inferred to be a _set_ based on implementing ISet. If that is the case, and the compiler can warn and/or tooling flag that you'll get an exception, then that's a win.
----

Finally, I'm not making any claim to having a deep understanding of the equality semantics of Xunit's `Assert`; I've been using [`unquote`](https://github.com/SwensenSoftware/unquote) for a long time as a replacement assertion library [from F#].

**Comment by JamesTerwilliger** [comment]
> Were they generic? Were they `Object`?

They were IEnumerable<T>

**Comment by bartelink** [comment]
OK, that makes sense. It would surprise me too.

But, unless Set comparison becomes an explicit thing with an explicit API, the basic issue Brad is trying to cover off is to stop people getting perf or semantic surprises in an obviously wrong scenario. That is something I'd want - throw me an exception, don't let it pass in an unsustainable way that will come back to bite the maintainer of my test later.

**Comment by JamesTerwilliger** [comment]
In that case, I would (personally) expect there to be some documentation for this case in the event of a perf issue but to prefer semantic consistency. If I pass two IEnumerable objects to `Assert.Equal`, and it throws an exception that tells me, "no, not that IEnumerable, use this other IEnumerable", so that I then need to convert my IEnumerable into another IEnumerable... it just feels off. If it said instead "use this other method or method overload", that would make sense, but that's not the case here I think.

**Comment by bradwilson** [comment]
I've written a documentation page which indicates why "do what the user wants" isn't possible with just a func: https://xunit.net/docs/hash-sets-vs-linear-containers

And I've decided that the solution is to throw.

Assertion library update: https://github.com/xunit/assert.xunit/commit/1dab747d384b6f1512df50f04cf2817864657f7a
v2 tests: https://github.com/xunit/xunit/commit/51851a64edb68040e8387f61c148b551a28b95e1
v3 tests: https://github.com/xunit/xunit/commit/ccf9d38953d295fd110a7d2ab243f38222bcb189

Now, onto the questions/comments.

-----

@JamesTerwilliger 

You have conflicting statements here:

> I think the original issue that raised this discussion was a situation where the arguments to the Assert were not known to be hashsets to begin with, so an analyzer would not help here.

> If Assert.Equal has a signature that is specific to sets, I would agree wholeheartedly with the error approach, but in that case, we wouldn't even offer an overload that takes a comparer.

If the analyzer doesn't know, neither does the compiler. And even if the compiler knew it, if you have hash sets and there isn't an overload for a func, the compiler will _still_ choose the version which is IEnumerable with the func comparer, because we aren't taking that version away.

> I would (personally) expect there to be some documentation for this case in the event of a perf issue but to prefer semantic consistency

See my link above about why a set != a linear collection, and why "just a comparer func" will never be sufficient for a set. You can continue to use the overloads that either compare things with the default behavior, or compare them will a full implementation of `IEqualityComparer<>`.

-----

@bartelink

> If there's special behavior for when both happen to be ISet, that's great.

There is. CollectionTracker is used to determine whether two collections are equal, and there is special handling for dictionaries, sets, and arrays: https://github.com/xunit/assert.xunit/blob/1dab747d384b6f1512df50f04cf2817864657f7a/Sdk/CollectionTracker.cs#L88-L92

> In general, APIs that go off and do clever things based on type tests are not the first thing you want to do.

This is pretty much the definition of how almost every assertion library works that I'm aware of. If you were forced to explicitly call specific functions for everything, you'd probably find that super tedious, wading through the dozens or hundreds of names of functions (not to mention the chore of naming them, like `Assert.EqualSetsButNotHashSetsWithComparerFunction()`. I like long names but that's just ludicrous. 😂 

> My mention of an Analyzer is based on the fact that I would hope/assume that at least one of the inputs can be inferred to be a set based on implementing ISet.

I'm not against having an analyzer, but in this case the operation is simply invalid (see my doc page link above). An analyzer would be something to be added on top of the runtime behavior, so that the user could discover their error at coding time (and leave the runtime error for either conditions where the container type is not strictly known and/or for developers who choose not to use the analyzers).

**Comment by JamesTerwilliger** [comment]
If Set != Linear Collection, what do we do if the left argument is a set and the right argument is a list?

**Comment by JamesTerwilliger** [comment]
> If the analyzer doesn't know, neither does the compiler

Indeed, but I was not suggesting that Xunit should have an overload of `Assert.Equal` that takes two sets and thus the compiler can pick the right one, I was attempting to point out that the signature doesn't take sets at the moment, it only takes enumerables. More that there was a suggestion above for maybe an `Assert.SetEqual` as an alternative.

**Comment by bradwilson** [comment]
> If Set != Linear Collection, what do we do if the left argument is a set and the right argument is a list?

They fall down to the default comparison, which treats them like a linear container, which almost assuredly fails because sets don't have prescribed order.

> a suggestion above for maybe an Assert.SetEqual as an alternative

This is a slippery slope towards turning one function (Assert.Equal) into dozens or hundreds of functions. There are already 44 overloads, and if each turned into a new function (plus several new ones to resolve ambiguities like you're suggesting), it becomes a complete nightmare (not to mention the problem of backward compatibility).

**Comment by JamesTerwilliger** [comment]
> plus several new ones to resolve ambiguities like you're suggesting

Not suggesting this, referring to another suggestion by not me. I don't think there should be that or more overloads or anything like it. Only trying to say that the inconsistency is odd and that I suspect many people don't think of Assert.Equal in the way that is being discussed.

> They fall down to the default comparison, which treats them like a linear container, which almost assuredly fails because sets don't have prescribed order.

Were this discussion ongoing, this would seem like a case for some research, but I don't think my point is coming across, and it's also not my call to make, so I'll move on.

**Comment by bradwilson** [comment]
We just shipped two new analyzers around set behavior in `xunit.analyzers` 1.9.0:

[xUnit2026](https://xunit.net/xunit.analyzers/rules/xUnit2026) detects when users pass two sets, and call the overload with the comparer func (i.e., the exact situation that this issue was raised about)

[xUnit2027](https://xunit.net/xunit.analyzers/rules/xUnit2027) detects when users pass one set + one linear container, and raise a warning that you should add a stabilizing sort to your set (like using LINQ's `OrderBy`). Note that we make a special case for [`SortedSet`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedset-1) since it has a stable order, so xUnit2027 won't raise if you have that specific concrete type for your set. Unfortunately there's no interface like `ISortedSet` so the detection of the specific concrete class is the best we can do, and as such xUnit2027 will still be raised for any custom set, whether it has an implied stable order or not. We considered that an edge case that a developer can disable the analyzer for.
