### ISSUE TITLE
Custom Data Attribute not reporting parameter values in xUnit >=2.5.0

### ISSUE THREAD

**Issue by NasC0** [xunit/xunit#2876]
I'm migrating some tests from xUnit 2.4.2 to the latest version and I've noticed that xUnit versions 2.5.0 and up don't report their passed in parameters correctly anymore:
![image](https://github.com/xunit/xunit/assets/3659723/d0e3b60a-0be9-4924-a658-f3091243c939)

Here's a screenshot from xUnit 2.4.2:
![image](https://github.com/xunit/xunit/assets/3659723/da27d557-d576-4e49-a694-476537b1a88d)

Both examples are using `xunit.runner.visualstudio` v. 2.4.5 so I don't think that's the culprit.
I'm using JetBrains Rider, but the same behavior can be observed in Visual Studio as well.

Please find attached a small solution that reproduces the described issue
[XUnit.CustomDataAttributeReporting.zip](https://github.com/xunit/xunit/files/14083469/XUnit.CustomDataAttributeReporting.zip)

**Comment by bradwilson** [comment]
This is expected behavior.

What's happening here is a result of an effort to eliminate multiple enumerations. We will only show the contents of `IEnumerable`s when we know they're safe to multiply enumerate. You are deserializing into the generic JSON format from `System.Text.Json`, and the arrays come back as `JsonArray`. We do not have any special knowledge of the types in `System.Text.Json` so we don't know whether `JsonArray` is safe to enumerate multiple times or not, so to be on the safe side, we show you the ellipses rather than the data elements.

My recommendation to restore the behavior you want is to use strongly typed objects rather than the generic JSON versions. If `nullOrEmptyProperties` were typed as an array or a `List<T>`, then we would know it's safe to multiply enumerate.

**Comment by NasC0** [comment]
Thank you for the clarification and quick reply, will implement your recommendation.
