### ISSUE TITLE
 xUnit includes vulnerability dependencies - System.Net.Http

### ISSUE THREAD

**Issue by borbiuk** [xunit/xunit#2908]
Our app comprises many projects with `xUnit` unit test projects dedicated to each project. However, each time when we scanned the app using `Snyk` (as per customer requirements) we consistently encountered reports rife with vulnerabilities stemming from the `xUnit` package.

Could you please confirm if it's feasible to update the `System.Net.Http` package within `xUnit`? If this is not possible, I would greatly appreciate an explanation.

NOTE: I have already seen similar issues that are already closed.

**Comment by bradwilson** [comment]
This `System.Net.Http` dependency isn't a direct dependency, it is a transient dependency from `NETStandard.Library`. I will say the next thing in bold, because you appear to have read several of my responses already and this has not gotten through yet: **NONE OF THE CODE IN XUNIT.NET USES SYSTEM.NET.HTTP.**

If you are using the latest version of xUnit.net (the 2.7.0 NuGet packages), you should not see any dependency on `NETStandard.Library` unless your code is being compiled against `netstandard1.1`+ (but not `netstandard2.0`+). This would be true if you are compiling directly against a 1.x version of `netstandard`, or against any unsupported older versions of .NET Core (anything prior to .NET 6, [which is the lowest currently supported version by Microsoft](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)).

An example of our dependencies, from `xunit.assert`:

https://github.com/xunit/xunit/blob/57af1d9f0b18181631cf6aa3d40a9f950468b1bc/src/xunit.assert.nuspec#L17-L24

If you are stuck for some reason compiling against .NET Standard 1.x, _you_ can take a dependency directly on a newer version of `System.Net.Http` to quell the security warning which is in fact not a security issue unless _you_ are using `System.Net.Http`.

I have zero experience with Snyk, so I have no idea what it does, and cannot vouch that it's actually giving you good information.

Closing this issue, because as has been repeated many, many, many times: this isn't our issue.

**Comment by apere170** [comment]
Good answer, when I updated my xunit version to `2.7.0` and xunit.runner.visualstudio to `2.8.0` in my test project the warning disappeared
