### ISSUE TITLE
Documentation/Sample for xUnit v2 tests programs as exes

### ISSUE THREAD

**Issue by davidmatson** [xunit/xunit#2909]
The v3 support for tests programs as exes is really useful - is there documentation or a sample for how to do this for v2?

Here's what I ended up doing, but I'm not sure if this anything close to a recommended approach:
```c#
using Xunit.Abstractions;
using Xunit;

class Program
{
    public static void Main()
    {
        // Change the following line if a different output format is needed:
        IRunnerReporter runnerReporter = new DefaultRunnerReporterWithTypes();
        IMessageSink messageSink = runnerReporter.CreateMessageHandler(new ConsoleRunnerLogger(true));

        using (IMessageSinkWithTypes executionMessageSink = MessageSinkWithTypesAdapter.Wrap(messageSink))
        using (ExecutionSink executionSink = new ExecutionSink(executionMessageSink, new ExecutionSinkOptions { DiagnosticMessageSink = messageSink }))
        using (XunitFrontController controller = new XunitFrontController(AppDomainSupport.IfAvailable, typeof(Program).Assembly.Location, diagnosticMessageSink: messageSink))
        {
            ITestFrameworkExecutionOptions executionOptions = TestFrameworkOptions.ForExecution();
            ITestFrameworkDiscoveryOptions discoveryOptions = TestFrameworkOptions.ForDiscovery();
            controller.RunAll(executionSink, discoveryOptions, executionOptions);
            executionSink.Finished.WaitOne();
        }
    }
}
```

This is code obviously limited in terms of harness functionality (doesn't support filtering or anything fancy - it just runs all the tests), but is this a reasonable approach, or could some documentation/a sample be added for getting "test as exe" for v2?

(Or maybe there's already something, and I just didn't find it.)

**Comment by bradwilson** [comment]
Yes, what you're doing is the core of what we do. Our version is 10-20x more complex mostly because of options that you aren't doing here (like reporter choice, support for output files, etc.).

This is the full version from the v2 console runner:

https://github.com/xunit/xunit/blob/57af1d9f0b18181631cf6aa3d40a9f950468b1bc/src/xunit.console/ConsoleRunner.cs#L342-L462

We haven't documented this because we don't expect average users to want to do this. We chose stand alone executables because it's impossible to rationalize linking in .NET Core (which is why we ended up abandoning `dotnet xunit`). The model where you load the unit test like it's a "plugin" into the actual runner was clever but wrong from the start in retrospect.

The complexity is why there is the new in-process console runner in v3. But there shouldn't be anything hidden away that you can't use, if you choose to dig into the code yourself.

**Comment by davidmatson** [comment]
Thanks, Brad.

Do you think that, once the v3 exe contract is settled, it would make sense to provide a one-line helper class for v2 that allows turning a v2 test project into an exe, so that some of those benefits are easily avaliable in v2 as well? (not that the helper would run the test internally as v3, just that it would support the overall similar command-line switches and output, perhaps compatible from the standpoint of an outside consumer)

If not, please feel free to close this issue.

**Comment by bradwilson** [comment]
I've given this some thought, and decided that I'll let a third party tackle this. I doubt it's going to come up, though, since right now we use references to determine what version of xUnit.net you use and therefore how to run you. If someone did this for v2, we'd still load you like a DLL into our process space and run you that way, because that's how v2 tests are run. Just because you became an executable doesn't mean we'd suddenly assume you're obeying v3's command line switches that we depend on (at least one of which is not documented at this time).

So, yeah. Closing it.

**Comment by davidmatson** [comment]
Makes sense. Thanks for following up, Brad!
