### ISSUE TITLE
Test runner now has an ambiguous call to AssemblyRunner.Start()

### ISSUE THREAD

**Issue by stonkie** [xunit/xunit#2922]
With the recent additional of the overload of Start with a ParallelAlgorithm parameter, upgrading the nuget in place makes the code below fail to compile.

```csharp
using var runner = AssemblyRunner.WithoutAppDomain(testAssembly.Location);
runner.Start(); // This is now an ambiguous call
```

Workaround is to use `runner.Start(parallelAlgorithm: null)`.

This is both...

- A regression since existing code stops building without code changes.
- An API degradation since we now need to add a disambiguating parameter to what used to be a parameterless method call.

# Solutions

Adding the new optional parameter on the previous method call (or removing the old method) would break the use case of dropping the new dll in place of the old one (because optional parameters are resolved by the caller), but I would consider this a lesser evil and an acceptable breakage for a minor version upgrade (not a patch)...

But that depends on how the project owners view backward compat :)

**Comment by bradwilson** [comment]
Bummer, I had hoped that marking the other one hidden would cause the compiler to prefer the new one. I may end up just replacing both with something that takes an options list, so that it can expand available options without breaking back compat.

**Comment by bradwilson** [comment]
New API is available in `2.8.1-pre.3` https://xunit.net/docs/using-ci-builds

There are no unit tests around this class, so I'll be doing some interactive testing soon to validate it. I did add one feature: you can specify more than one test class to run (previously it was "whole assembly" or "single type").

**Comment by albahari** [comment]
Will the fix appear in the NuGet release package soon? This issue breaks [LINQPad's xUnit support](https://forum.linqpad.net/discussion/3208/error-when-running-xunit-tests-assemblyrunner-start-ambiguous-method).

**Comment by bradwilson** [comment]
@albahari It should already be available in 2.8.1.

**Comment by albahari** [comment]
@bradwilson Are you certain? I'm referencing the 2.8.1 versions of the `xunit` and `xunit.runner.utility` packages - the following outputs "2.8.1+ba2ae9bc85"

    Console.WriteLine (FileVersionInfo.GetVersionInfo (typeof (Xunit.Runners.AssemblyRunner).Assembly.Location).ProductVersion);

And yet the following generates a compile-time error:

    using var runner = Xunit.Runners.AssemblyRunner.WithoutAppDomain (GetType().Assembly.Location);
    runner.Start();

`CS0121 The call is ambiguous between the following methods or properties: 'AssemblyRunner.Start(string, bool?, TestMethodDisplay?, TestMethodDisplayOptions?, bool?, bool?, int?, bool?)' and 'AssemblyRunner.Start(string, bool?, TestMethodDisplay?, TestMethodDisplayOptions?, bool?, bool?, int?, bool?, ParallelAlgorithm?)'`

**Comment by bradwilson** [comment]
You need to use the overload that takes `AssemblyRunnerStartOptions`. It's the only overload that should show in Intellisense, though the other older versions are still present (just hidden).

```csharp
assemblyRunner.Start(new AssemblyRunnerStartOptions());
```

**Comment by albahari** [comment]
Is that an ideal solution, though? Code that already calls runner.Start() without arguments is now broken, and it's not possible/easy to write code that works with both the old and new versions.

To elaborate, suppose I release a LINQPad update that patches the xUnit script such that runner.Start() is replaced with runner.Start(new AssemblyRunnerStartOptions()). This will break for end users that have an older version of the xUnit package. But if I don't do anything, the call is broken for users of the newer xUnit package.

I think you can fix this by changing one of the two obsolete overloads (the one without the `ParallelAlgorithm` parameter) such that its parameters are all mandatory. This won't break binary compatibility, nor will it break compile-time compatibility because you've got another obsolete overload that includes all of its parameters (plus one extra). This is how it's done in [CSharpCompilationOptions](https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Portable/CSharpCompilationOptions.cs) - whenever they add a new constructor whose parameters superset the parameters in an old one, the old one has its optional parameters changed to mandatory parameters.

**Comment by bradwilson** [comment]
Yep, that's what I'm doing. This will restore the "no parameter" use case, and the compiler will sort everybody else out. I will make sure the next release is versioned as 2.9.0 in deference to this breaking change.

**Comment by bradwilson** [comment]
The removal of the old APIs (and the new API offering a parameterless version, when no customization is needed) is available now.

v2 `2.8.2-pre.17
v3 `0.1.1-pre.487`

https://xunit.net/docs/using-ci-builds

**Comment by albahari** [comment]
Thanks. This will satisfy the LINQPad use-case, since the script calls `Start` without parameters, and binary compatibility is not needed.
