### ISSUE TITLE
Make having a public parameterless constructor for IXunitSerializable optional

### ISSUE THREAD

**Issue by Chasmical** [xunit/xunit#2935]
It'd be great if xUnit could create instances of serializable types without needing a public parameterless constructor. Not being able to use primary constructors, having to add empty public parameterless constructors, and annotating them with `[Obsolete]` as well as with some nullable analysis warning suppressions, is quite inconvenient.

There is a [`RuntimeHelpers.GetUninitializedObject(Type)`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimehelpers.getuninitializedobject?view=net-8.0) (or [`FormatterServices.GetUninitializedObject(Type)`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatterservices.getuninitializedobject?view=net-8.0) for older frameworks) method that can be used for this. It should be used only when there is no public parameterless constructor, so if the serializable class does declare such a constructor, it can still be used to set up whatever's necessary.

I would love to use custom fixtures with primary constructors like this:

```csharp
public abstract class CustomFixture : IXunitSerializable
{
    /* Base class uses Reflection to serialize/deserialize the object's fields */
    public void Deserialize(IXunitSerializationInfo info) { /* ... */ }
    public void Serialize(IXunitSerializationInfo info) { /* ... */ }
}
public class ParsingFixture(string source, NumberStyles styles = NumberStyles.Float) : CustomFixture
{
    public string Source => source;
    public NumberStyles Styles => styles;
    public double Expected { get; private set; }
    
    public ParsingFixture Returns(double expected) { Expected = expected; return this; }
    public void AssertResult(double result) => Assert.Equal(Expected, result);
}
public class SystemDoubleTests
{
    [Theory, MemberData(nameof(CreateParsingFixtures))]
    public void Parsing(ParsingFixture fixture)
    {
        fixture.AssertResult(double.Parse(fixture.Source, fixture.Styles));
    }
    public static TheoryData<ParsingFixture> CreateParsingFixtures()
    {
        TheoryData<ParsingFixture> data = new();
        data.Add(new ParsingFixture("1.234").Returns(1.234));
        data.Add(new ParsingFixture("9045", NumberStyles.Integer).Returns(9045));
        return data;
    }
}
```

**Comment by bradwilson** [comment]
Enabling such a feature feels like leading down a path of potential failure, rather than a path of success, because you're illegally creating instances of objects in ways that developers (other than you, of course) would not expect. Although your empty constructors might always tend to be empty, that's certainly not the case for all fixture objects, and asking the developer to consciously consider what the initialized state of the object should be before de-serialization feels like the correct behavior for us to encourage.

I understand it's not the most convenient scenario to have to add the second constructor, but we believe it is the architecturally correct one.
