### ISSUE TITLE
Duplicate 'Xunit.TestFramework' attribute

### ISSUE THREAD

**Issue by travbeamo** [xunit/xunit#2949]
When using both of the following packages:
* Meziantou.Xunit.ParallelTestFramework: Version=2.2.0
* Reqnroll.xUnit: Version=2.0.3

The following error is generated when trying to build project in Visual Studio:
> Duplicate 'Xunit.TestFramework' attribute

**Comment by bartelink** [comment]
That's not something that can be fixed in this repo; you need to analyze the dependency chain that's led to the conflict, and your conflicting dependencies need to converge on a single one. How to accomplish this is outside of the scope of this repo; if you provide more details, it's a good question ofr stack overflow...

**Comment by bradwilson** [comment]
And it's probably worse than you think, because it sounds like both are trying to declare that they will be "the custom test framework for this test assembly" and you only get to have one of those, not two.

Off the top of my head, the 'easiest' solution for that would be to put the tests that use `Meziantou.Xunit.ParallelTestFramework` into one test assembly and the tests that use `Reqnroll.xUnit` into a separate one.
