### ISSUE TITLE
Subscribe to unhandled exceptions and surface them as fatal errors

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2952]
All 1st party runners (including `xunit.runner.visualstudio`) should subscribe to `AppDomain.CurrentDomain.UnhandledException` and make sure any unhandled exceptions get surfaced as fatal errors.

Source: https://github.com/xunit/xunit/issues/2377#issuecomment-2173417460

**Comment by AArnott** [comment]
I think this should be under a switch (perhaps the same one that lets us turn off shadow copying), as otherwise this will be a breaking change for existing test that could slow down or prevent adoption of the new version.
Whether it's on or off by default, I'm mixed. But so long as the default can be changed, I can support it.

**Comment by bradwilson** [comment]
I agree, this seems like something that should probably be off by default and configurable to be turned on as needed.

**Comment by bradwilson** [comment]
This is handled today in v3 in the in-process runner, so I think I'm going to consider this done (as I don't think I'm going to back-port the behavior to v2).

**Comment by AArnott** [comment]
@bradwilson did this end up being made off by default? I haven't turned it on, but my test host is crashing.

**Comment by bradwilson** [comment]
Just searching across the whole code base now, I realize we have done this in the console runner since v1:

![Image](https://github.com/user-attachments/assets/6edca934-5705-411b-a945-76aab7d4c840)
