### ISSUE TITLE
Non-ANSI characters in display names are broken

### ISSUE THREAD

**Issue by estrizhok** [xunit/xunit#2961]
```
[Theory, InlineData("ы")]
public void StringCyrillic(string value) { }
```

is presented in Xunit v3 0.1.1-pre.485 as `StringCyrillic(value: "╤ï")`.

**Comment by bradwilson** [comment]
I cannot reproduce this, and I suspect your problem is related to your terminal misinterpreting the output. Here is what I see, both with VSTest and by running the test directly, when using Windows Terminal 1.20:

![image](https://github.com/xunit/xunit/assets/16944/b6673fed-4ad7-47a1-9fba-49f4d3acfabb)
