### ISSUE TITLE
Add a diagnostic suppressor for VSTHRD200

### ISSUE THREAD

**Issue by cremor** [xunit/xunit#2978]
Please add an analyzer diagnostic suppressor for the rule [VSTHRD200](https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD200.md) (Use Async suffix for async methods) from the Microsoft.VisualStudio.Threading.Analyzers package. That rule should not apply to test methods.

I've already opened an issue on that analyzer project directly, see https://github.com/microsoft/vs-threading/issues/1315. But MSTest added a suppressor for that rule in its last release (see https://github.com/microsoft/testfx/pull/2926) so I thought maybe xUnit could do the same.

**Comment by bradwilson** [comment]
Available in `1.16.0-pre.20` https://xunit.net/docs/using-ci-builds

**Comment by cremor** [comment]
Thanks!

Would it also be possible to create a suppressor for a [code-style naming rule](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules) that defines an "Async" suffix? It is reported as error code IDE1006, but that error code is shared with other naming rule violations. So maybe you'd have to suppress all naming rules for test methods.

**Comment by bradwilson** [comment]
Only Roslyn analyzers can be suppressed by Roslyn suppressors. If this isn't an analyzer, then there's nothing that I'm aware of that we can do about it.

Since .editorconfig files are inheritable, it appears your options look like this:

- If all your test projects share a common folder, and that common folder is only used for test projects, put a singular .editorconfig with the override in that folder.
- If the above is not true, then you will need to put an .editorconfig file with the override into every test project folder.

**Comment by cremor** [comment]
Thanks. I'm already using an .editorconfig file to suppress that naming rule. I just hoped that it could be done at the test method level like with the Roslyn suppressors. Because with the .editorconfig way you'll also lose the naming rule for non test methods in test projects.
