### ISSUE TITLE
Test methods with FsCheck.Xunit.PropertyAttribute throws MissingMethodException in version 2.9

### ISSUE THREAD

**Issue by erikljung** [xunit/xunit#2996]
Methods which uses `FsCheck.Xunit.PropertyAttribute`, throws `MissingMethodException` in xUnit version 2.9 when having `ITestOutputHelper` as a ctor dependency. Removing the ctor seems to solve the problem. This error is not present in 2.8.1. FsCheck version used is 2.16.6.

Exception:
```
System.MissingMethodException
Constructor on type 'Repro.Tests1' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at ReflectionAbstractionExtensions.<>c__DisplayClass0_0.<CreateTestClass>b__0() in /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs:line 42
   at Xunit.Sdk.ExecutionTimer.Aggregate(Action action) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 31
   at ReflectionAbstractionExtensions.CreateTestClass(ITest test, Type testClassType, Object[] constructorArguments, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs:line 42
   at <StartupCode$FsCheck-Xunit>.$PropertyAttribute.testExec@212(PropertyTestCase this, IMessageBus messageBus, Object[] constructorArguments, CancellationTokenSource cancellationTokenSource, XunitTest test, RunSummary summary, TestOutputHelper outputHelper, Unit unitVar0)
```

Repro:
```
public class Tests1
{
	public Tests1( ITestOutputHelper output ) { }

	[Property]
	public void Throws_in_xUnit_2_9( int i )
	{
	}

	[Fact]
	public void Works_in_xUnit_2_9_and_2_8_1() { }
}

public class Tests2
{
	[Property]
	public void Works_in_xUnit_2_9( int i )
	{
	}
}
```

https://github.com/fscheck/FsCheck/issues/682

**Comment by bradwilson** [comment]
I'm happy to help try to track down where the compatibility issue is, as the break may be unintentional.

**Comment by bradwilson** [comment]
It's also worth pointing out that there was a change related to ITestOutputHelper in 2.9.0, which is probably the first place someone should be looking:

![image](https://github.com/user-attachments/assets/f093e372-df58-4366-be85-da44e29f21e6)

https://xunit.net/releases/v2/2.9.0

**Comment by bradwilson** [comment]
The change for 2.9.0 for this lives in XunitTestClassRunner and XunitTestRunner: https://github.com/xunit/xunit/commit/1fac6f8d88992c29edc2bd916b28ad94d590638a

From looking at the source, it appears FsCheck.Xunit has its own test case object (derived from `XunitTestCase`) that implements its own `RunAsync` without using any of the existing infrastructure. It's possible (likely, even) that they're running afoul of our change in `XunitTestClassRunner` when trying to type match against `ITestOutputHelper` where we've munged the argument value to be an instance of `Func<ITestOutputHelper>` instead of an instance of `ITestOutputHelper`, because we're picking up on that in `XunitTestRunner` to make sure every test gets a fresh instance. This was a bit of a hack on my part to make this work (we do something similar in v3, but more formalized). It doesn't recognize this, so it doesn't do anything with it, and it ends up passing the `Func<TestOutputHelper>` on to `Activator.CreateInstance`, which says "I don't know what you wanted me to do with this". 😂 

I suspect the fix on `FsCheck.Xunit`'s side would be to also start looking for argument values of type `Func<TestOutputHelper>` and treating it just like it does when it sees arguments of type `ITestOutputHelper`.

**Comment by bradwilson** [comment]
@erikljung You should probably open an FsCheck.Xunit issue for this and point back here for a description of the likely problem and solution.

**Comment by bartelink** [comment]
Thanks @bradwilson for all the energy you continue to invest in this insane level of community service commitment

The FsCheck issue is already in place: https://github.com/fscheck/FsCheck/issues/682 re how it surfaces.

And thanks for the digging - this is a great start for whomever picks it up over there (it could be me). Feel free to close this if you're doing an issue list traversal but the update has lingered.

cc @kurtschelfthout I guess this is also related to https://github.com/fscheck/FsCheck/issues/415

**Comment by bradwilson** [comment]
Closing as External.
