### ISSUE TITLE
xunit incredibly slower after upgrading from 2.7.1

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [xunit/xunit#3004]
I am trying to upgrade xunit on https://github.com/MarkCiliaVincenti/AsyncKeyedLock/, currently on 2.7.1

The issue I have is that any version of xunit after 2.7.1 runs the tests considerably slower, both when I test locally on my dev machine as well as on Github Actions (here they usually take 2.5 to 3 mins to run with 2.7.1 but over 25 minutes to run on 2.8.0+).

I'm a bit at a loss at what I should do at this point.

**Comment by bradwilson** [comment]
This note in the [2.8.0 release notes](https://xunit.net/releases/v2/2.8.0) is probably the issue:

![image](https://github.com/user-attachments/assets/f95ac3ad-339f-4b80-9820-786cf554923c)

The link goes here: https://xunit.net/docs/running-tests-in-parallel#algorithms

**Comment by bradwilson** [comment]
I'm gonna make a guess and say that the majority of your tests are probably not CPU bound, but rather I/O bound and async. The parallelism change was to limit the number of _started_ tests vs. the number of _actively running_ tests, so if the majority of your tests are just spending time waiting (rather than computing), you'd get significantly less utilization out of the CPU as a result, and hence see this dramatic performance change.

**Comment by MarkCiliaVincenti** [comment]
Thank you @bradwilson, that fixes it!
