### ISSUE TITLE
`Assert.Equal` and `ILookup` pitfall

### ISSUE THREAD

**Issue by vc-74** [xunit/xunit#3028]
Not sure if this should be considered a bug but `Assert.Equal` compares `IEnumerable<T>` and `IReadOnlyDictionary<TKey, TValue>` correctly, so one could assume `ILookup<TKey, TValue>` are covered too. 

It is not the case, `Assert.Equal` sees lookups as collections of `IGrouping<TKey, TElement>` which implements `IEnumerable<TElement>` and therefore only compares values regardless of keys.

I don't think the `IReadOnlyDictionary<TKey, TValue>` case is explicitly covered, but comparing collections of `KeyValuePair<TKey, TValue>` compares both the key and the value which is not the case with `IGrouping<TKey, TElement>`.

As an example:
```chsarp
ILookup<bool, int> evens =
    Enumerable.Range(0, 10).ToLookup(
        i => ((i % 2) == 0),
        i => i);

ILookup<bool, int> odds =
    Enumerable.Range(0, 10).ToLookup(
        i => ((i % 2) == 1),
        i => i);

Assert.Equal(evens, odds);
```

succeeds because both lookups have the same values but the keys associated to these values are different.

**Comment by bradwilson** [comment]
These are all special cased (collections, KeyValuePair<>, etc.). We would need to special case ILookup<> as well, since it does not implement any form of comparability.

**Comment by vc-74** [comment]
Actually, only `IGrouping<>` needs to be handled, which would allow the `Assert.Equal` overload comparing `IEnumerable<T>` to work. Shall I create a PR or is it a minor corner case?

**Comment by bradwilson** [comment]
I'm going to do it myself today, because I'd like to get a 0.4.0 release out soon and I want to put this in.

**Comment by bradwilson** [comment]
Playing around with signatures, I'm not sure I can get Equal(IGrouping<>, IGrouping<>) to do the right thing in all cases. You want to be able to treat them _sort of_ like a dictionary, in that the ordering of the keys isn't important, but that isn't really easy to do right now. `Equal` really wants them to be in the same order. So if your two groupings are, for example, `{[true] = [1,3,5,7,9], [false] = [0,2,4,6,8]}` vs. `{[false] = [0,2,4,6,8], [true] = [1,3,5,7,9]}`, `Assert.Equal` wants them to be unequal because `true != false` (in the same way that `Assert.Equal([0,1], [1,0]);` would fail.

I'm going to start with `Assert.Equivalent`, since its a more relaxed kind of comparison, and see whether that feels better.

**Comment by bradwilson** [comment]
Support for `Assert.Equivalent` with groupings is available in:

v2 `v2.9.1-pre.14`
v3 `0.4.0-pre.19`

https://xunit.net/docs/using-ci-builds

After considering it, I don't believe I'm going to add support for Assert.Equal, because of the complexity involved in making it work correctly.

**Comment by vc-74** [comment]
OK thanks 
Does dictionary equality also mandate same entries order?

**Comment by bradwilson** [comment]
No, because dictionaries don't have an order. They are handled separately.

The problem isn't so much `IGrouping<>` as it is the fact that it's `IEnumerable<IGrouping<>>`. If you were to try to run `Assert.Equal` against `IEnumerable<KeyValuePair<>>` (how a dictionary would present if it weren't handled explicitly), then it too would be order sensitive, and then you would be best off using `Assert.Equivalent` rather than `Assert.Equal`.

This is really about how `IEnumerable<>` is handled rather than how `IGrouping<>` is handled.
