### ISSUE TITLE
xUnit1012 and `!` 

### ISSUE THREAD

**Issue by nrhoffmann** [xunit/xunit#3082]
```
public sealed class ReproClass
{
    [Theory]
    [InlineData(null!)]
    public void ReproMethod(string id)
    {

    }
}
```

The `!` operator suppress all null warnings. Is there a reason why this attribute doesn't respect that?

**Comment by bradwilson** [comment]
We don't look at the null suppression operator.

You could question whether that's a bug or not, but consider this scenario: You can use a non-nullable type like `int` rather than `string`, and then what would you expect to happen? The answer is that you'll get `0`, which is also not `null`.

I don't think we should fix this. If you want to pass `null`, you should provide a nullable type (reference or otherwise). The fact that you get unpredictable results is being clearly documented by the analyzer.

**Comment by nrhoffmann** [comment]
@bradwilson That is a good point.

**Comment by bradwilson** [comment]
I would also add: The null suppression operator is designed to be used when you have a value which _you_ know is not `null`, but for some reason the _compiler_ doesn't know is not `null`. That's not what you're doing. You're saying "this is `null` and I don't care that it's not compatible".

**Comment by nrhoffmann** [comment]
> To be fair, we routinely pass null! into APIs which are designed to be not nullable, just so that we can verify that we're still guarding against nulls for those users who have nullable reference types turned off. I consider that to be an edge case usage.

@bradwilson I was about to point out that this is my company's use case.

**Comment by nrhoffmann** [comment]
I worked around this by using a nullable parameter and suppressing the null warning when calling the system under test.

**Comment by bradwilson** [comment]
IMO this is how it should be done.

You aren't trying to trick the testing framework, you're trying to trick your API.
