### ISSUE TITLE
JSON schema for xunit.runner.schema.json not available for v3

### ISSUE THREAD

**Issue by karl-sjogren** [xunit/xunit#3085]
The "current" schema located at https://xunit.net/schema/current/xunit.runner.schema.json is still the 2.8.1 version.

The schema for 3.0 is kinda available via https://xunit.net/schema/v3.0-alpha-1/xunit.runner.schema.json, but it would be great if another one was added for just v3.0.

I couldn't find which repo this is handled in so if this is the wrong one then I'll gladly move the issue to the right place.

**Comment by bradwilson** [comment]
Thanks! It turns out `v3.0-alpha-1` wasn't completely up to date anyway, so I added `v3.0` with the two missing properties (`seed` and `showLiveOutput`), and updated `current` to point to `v3.0`.

https://xunit.net/schema/v3.0/xunit.runner.schema.json
https://xunit.net/schema/current/xunit.runner.schema.json

**Comment by bradwilson** [comment]
The doc site is handled in a branch of `xunit/xunit` named `gh-pages`, so the change was done here: https://github.com/xunit/xunit/commit/06abb9a78af6a10f3f100fc671d6399e8de2ca17
