### ISSUE TITLE
xunit1051 false positive for mocked methods (v3)

### ISSUE THREAD

**Issue by stevendarby** [xunit/xunit#3087]
If I use Moq to mock a method that takes a cancellation token, e.g.:

```C#
myMock
    .Setup(x => x.GetSomethingAsync(default))
    .ReturnsAsync(something);
```

I am getting the analyzer warning:

`Calls to methods which accept CancellationToken should use TestContext.Current.CancellationToken to allow test cancellation to be more responsive. (https://xunit.net/xunit.analyzers/rules/xUnit1051)`

This isn't code directly called in the test so I think it's a false positive, and being a unit testing framework I think it'll be a very common one.

I may be testing a method which doesn't take a cancellationToken, but internally calls a method that does, and only passes `default` to it (or nothing at all if it's optional). If mocking that call, then using `TestContext.Current.CancellationToken` in the setup for the mock could fail the test, as it wouldn't match the actual cancellation token used.

**Comment by bradwilson** [comment]
Fix available in `1.19.0-pre.5` https://xunit.net/docs/using-ci-builds

**Comment by campersau** [comment]
The analyzer does not trigger for this anymore:
```c#
[Fact]
public async Task Test()
{
    await Assert.ThrowsAsync<Exception>(() => Task.Delay(100));
}
```
I guess it is now expected.

**Comment by bradwilson** [comment]
That is true, for the moment.

I decided that the quick fix would be to "miss" some cases like `ThrowsAsync` for the time being. The problem comes down to identifying the intent of the lambda, and in my mind an inclusion-list of places where I know I want to check (like `Assert.ThrowsAsync`) is a better solution than trying to create an exclusion-list for what is essentially an open-ended list of places where lambdas are used and may or may not be reasonable for code under test to pass cancellation tokens.

This is really a personal philosophy for these analyzers: If I can help it, I never want them to report false positives, to the point where I'll prefer to have them do false negatives instead (because in the former case you're annoyed, and in the latter case you're no worse off than if we didn't have an analyzer). Writing an inclusion-list for acceptable places to check lambdas isn't a perfect solution, either: you should say, for example, that any callback that's being registered that will actually be called should follow the rules.

The flip side is that there are plenty of places we don't check at all (outside of the test method) where you maybe should be passing along cancellation tokens. One example might be that the API that you're creating and testing could benefit from piping through a cancellation token, but until you've done that, we can't see that you _should_ have been doing that, since we stop our detection at the test method level. (Another rule we follow is that, even for our rules which might be useful generally, like "always use cancellation tokens when you can", we strictly limit them to the context of tests. Generalized coding rules are better provided elsewhere, like from Microsoft. 😁)

In a world of where we're forced to choose from imperfect solutions, I have to follow my gut on what is the best experience for the end user. For now that means "no checking in lambdas" (with the unfortunate case of false negatives), and soon, I will pick the option that checks in lambdas where I know you should be following the rules (which will eliminate some, but not all, of those false negatives).

**Comment by bradwilson** [comment]
@campersau https://github.com/xunit/xunit.analyzers/commit/abfeef7c61b2086b8570773938982597c67750b0
