### ISSUE TITLE
Feature request: Add support to define custom Main entry point with  `GenerateTestingPlatformEntryPoint` setting

### ISSUE THREAD

**Issue by filzrev** [xunit/xunit#3106]
In the following MSBuild document. 
https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#generatetestingplatformentrypoint

`GenerateTestingPlatformEntryPoint` property is documented as supported on xUnit.
But it seems not works on xUnit v3. (And I thought it's not applicably to xUnit v2)

Is it able to add supports for `GenerateTestingPlatformEntryPoint` on xUnit v3?

**List of AutoGeneratedEntryPoints**

- XunitAutoGeneratedEntryPoint (default)
  - https://github.com/xunit/xunit/blob/main/src/xunit.v3.core/Package/content/EntryPoint-xunit.cs
- XunitAutoGeneratedEntryPoint (When using `Microsoft.Testing.Platform`)
  - https://github.com/xunit/xunit/blob/main/src/xunit.v3.core/Package/content/EntryPoint-mtp.cs

**Comment by filzrev** [comment]
I didn't noticed that already there is `XunitAutoGeneratedEntryPoint` for disable auto generated entry point.

Is it able to support `GenerateTestingPlatformEntryPoint` also for `Microsoft.Testing.Platform`.
or MSBuild document should be fixed?

**Comment by bradwilson** [comment]
I'll be completely honest, I have no idea who wrote that document section or what they're trying to imply with it. 🤷🏼‍♂️

We always support Microsoft.Testing.Platform. There's no flag to turn that support off. We do not document or support setting `XunitAutoGeneratedEntryPoint` to `false`; it is there as an escape hatch if we ever need it. We give users an alternative way to run code during startup and shutdown via `ITestPipelineStartup` as documented here: https://xunit.net/docs/getting-started/v3/whats-new#test-pipeline-startup

**Comment by filzrev** [comment]
Thank you for clarification.

> In addition, we do not document or support setting XunitAutoGeneratedEntryPoint to false; it is there as an escape hatch if we ever need it. 

On my use case (Tracking xUnit behaviors when using `Microsoft.Testing.Platform`)
It's sufficient to use `XunitAutoGeneratedEntryPoint` (Officially unsupported)

Close this issue. Because I've raised following documentation issue to `dotnet/docs` repository.
`https://github.com/dotnet/docs/issues/44090`

**Comment by bradwilson** [comment]
@Mad-Lynx It's not clear to me why you need this.

If you're writing a Microsoft.Testing.Platform extension that also uses xUnit.net extensibility points, then you should be using the `xunit.v3.extensibility.core` NuGet package, not `xunit.v3` or `xunit.v3.core`. This will completely bypass anything related to `Microsoft.Testing.Platform.MSBuild`, since that import comes from using `xunit.v3.core`.

> If you have the project that is non-test referencing the test one

This is not a supported scenario for xUnit.net. Test projects are stand-alone executables, not libraries. They are not designed to by referenced by other projects.

> Ideally generating entry point should not be unconditionally, it should be depending if we are really dealing with the test project

That is precisely the difference between these two packages:

* `xunit.v3.core` (referenced by `xunit.v3`) is _**only**_ for unit test projects
* `xunit.v3.extensibility.core` is _**only**_ for non-unit test projects
