### ISSUE TITLE
Package Source Changes

### ISSUE THREAD

**Issue by kentcb** [xunit/xunit#329]
Yesterday I was playing around with various XUnit projects and have wound up with different Package Sources:
![image](https://cloud.githubusercontent.com/assets/1901832/6423492/c8006924-bf36-11e4-88b2-f1945e2a367e.png)
What specifically made these changes? I just want to know so I can avoid the hassle in future...

**Comment by bradwilson** [comment]
This is unfortunately a HUGE problem with NuGet. (Well, my interpretation of how annoyed I get is "huge" :laughing:)

xUnit.net ships a `nuget.config` file in the repository, which contains overrides for that solution only. The problem is, if you edit your package sources while "under the influence" of this config file, then your personal settings (which are stashed in `%USERPROFILE%\AppData\Roaming\NuGet\NuGet.Config`).

The easiest way to fix this is to shut down all instances of Visual Studio, then launch one without opening any solution, then update your package sources to get you back to whatever known state you should be in.
