### ISSUE TITLE
v1 -> v2 tests performance

### ISSUE THREAD

**Issue by Muchiachio** [xunit/xunit#353]
Is it just me or running tests got a lot slower in visual studio runner?
In v1.9.2 ~770 tests passed in 10-11 seconds, and v2.0 they are running for 29-30 seconds.

Investigating this further I found out that the actual tests run only 10-20% slower, if at all. But their start is delayed quiet a bit on VS, compared to an instant start on 1.9.2 (when tests are already discovered).

Other than that, "xunit.runner.visualstudio 2.0.0" can be used together with "xunit 1.9.2" without any performance loss.

**Comment by Muchiachio** [comment]
Investigating this further I found out that the actual tests run only 10-20% slower if at all, but their start is delayed quiet a bit on VS, compared to an instant start on 1.9.2 (when tests are already discovered).

Other than that, "xunit.runner.visualstudio 2.0.0" can be used together with "xunit 1.9.2 " without any performance loss.

**Comment by bradwilson** [comment]
Thanks for the report.

Out of curiosity, have you done any testing with other runners like the console runner, or is the problem unique to the Visual Studio runner?

**Comment by Muchiachio** [comment]
The only other runner I tried was console one, and it was running fine (10-11 seconds).
It seems that the problem is in "xunit.runner.visualstudio 2.0.0" then combined with "xunit 2.0.0".

**Comment by bradphelan** [comment]
I see the same problem. Even when the solution is fully built and I right click in the test explorer and try to run a specific test it can take up to 20 seconds to re-run the test discovery stage. Shouldn't this be cached and only rebuilt if it is detected the solution has been rebuilt.

**Comment by Schaeri** [comment]
We have massive performance problems with XUnit 2.1. After migrating our unit tests form XUnit 1.9.2 to XUnit 2.1, a full test run takes 3 to 10 times longer than before. Our situation: We do TDD and have approximately 25000 unit tests. We try to reduce the test run time as much as possible to get a fast feedback from our build server. 

With XUnit 1.9.2 our average test run time was around 1 minute. The parallelization was done by MSBuild by having multiple unit test assemblies, each running on a separate cpu core. 
With Xunit2.1 we first tried to use the same approach by disabling parallelization in XUnit and by letting MSBuild do the parallelization. A test run then took with an average of 3 minutes 20 seconds more than 3 times longer than with XUnit 1.9.2.  
Then we tried to use the XUnit parallelization and disabled MSBuild parallelization. Our average test run time was 10 times slower then.  Around 10 minutes. 
In order to reproduce the issue we created a unit test project with 25000 tests (2500 test classes with 10 facts each). The fact only contains a simple Assert.Equal(true, true). We wrote a power shell script to execute the tests and measure the run time.
With XUnit 1.9.2:  around 26 seconds
With XUnit 2.1: -parallel none  around 11 minutes 
With XUnit 2.1: -parallel collections around 10 minutes
When you look at the CPU utilization, in the XUnit 2.1 parallel case we observe a maximum of 18%. Is there a reason for that?
Are there any plans to improve the performance of the XUnit runner? And when?

If more information is needed, please ask.
Thanks. 
[XUnit.zip](https://github.com/xunit/xunit/files/59089/XUnit.zip)

**Comment by bradwilson** [comment]
You should be doing assembly parallelization, not just collection parallelization, to get an "apples to apples" comparison to what you had before.

That said, we are aware of one particular component that causes the majority of the performance issues. We're planning to do some work with this in 2.2. One way to bypass this issue with 2.1 is to turn off app domains (and in fact, this will always be faster than what our planned performance improvements are).

**Comment by Schaeri** [comment]
Thanks for the feedback. The attached solution in the last post contains only one test project. I think that it not helps to also paralyze assemblies.  We tried with the noappdomain flag. This increases the test performance massively, but we still not reach the xunit 1.9.2 performance. 
 An in our real project we were not able to run the tests without the flag. Running into assembly load problems we have to analyze first. 
We are locking forward for xunit 2.2 and try then the migration again.

**Comment by bradwilson** [comment]
The performance of 2.2 with app domains will, by definition, perform worse than 2.1 without app domains, because the performance issue is tied to app domains.

**Comment by Shyam-Gupta** [comment]
We are also seeing performance issues in VS test runner in test discovery step during test execution in 2.2.0 Beta 5. It is taking 2 min 55 sec to run 1000 tests present in a single dll. Out of that 2 min 42 sec are spent in test discovery only. The tests just have a single line: Assert.Equal(1, 1);

Performance deteriorates a lot as number of tests increases. Any timeline on when this issue will get addressed ?

**Comment by smithkl42** [comment]
Agreed that this is a problem. We've got about 3500 tests, and discovery takes forever - both with the Visual Studio test runner, and the Resharper test runner (which I presume are largely calling the same code under the hood).

**Comment by asdfgasdfsafgsdfa** [comment]
Same problem here, any commet on that yet? :(

**Comment by bradwilson** [comment]
We believe we have done everything we can for this at this time.
