### ISSUE TITLE
Debug.Assert should throw exception rather than show modal dialog

### ISSUE THREAD

**Issue by citizenmatt** [xunit/xunit#382]
The xunit1 behaviour to capture output for `Trace.Write` and `Trace.WriteLine` was removed in v2 (threading), but so was the behaviour to throw an exception on `Debug.Assert`. Instead, v2 uses the default behaviour, which is to show a modal dialog, which is not very nice.

Should v2 throw an exception again?

**Comment by bradwilson** [comment]
Simply, no.

We want to leave the environment untouched as much as possible. Any changes we make to the environment mean that (a) your tests run differently from your production code, and (b) it makes it harder to test the use of that environment. (We heard this latter one a lot, actually, regarding people trying to test trace handlers.)

If people want to test that a `Debug.Assert` has been called, I would suggest writing a lambda-based assertion (like `Assert.Throws`) that temporarily changes the environment, runs the code and captures what needs to captured, and then reverts the environment.

Also, when changing shared resources like this, the developer needs to be aware of the implications with parallelization.

**Comment by davkean** [comment]
@bradwilson Would love for you to reconsider this, perhaps an opt-in via a headless mode? 

Here's what I'm looking at, in the Roslyn code base, we have:

~40,000 tests.
~40 test binaries

Since moving to xunit 2.1, we're hitting a lot a more asserts and failures, likely due to threading improvements in 2.x that exposed more bugs in our code/tests, that 1.x didn't expose. We want to use Debug.Assert and have it always throw when running on the build machine. We don't have a good way to control the entry points of each test project - although we can centralize the call to xunit itself.

Thoughts?

**Comment by jaredpar** [comment]
Have you considered a feature where we can control the `TraceListener` collection when xunit is running?  Essentially let the developer control how `Debug.Assert` is handled in a test run.  If there is an existing configuration option for this please let me know (looked around, couldn't find one).  

To be clear and expand on @davkean, we don't actually want to test that `Debug.Assert` is called.  The problem is that `Debug.Assert` by default pops up a blocking UI.  When running our suites on a headless server this blocks the job indefinitely and eventually leads to the entire process tree being killed when the overall job times out.  

This is causing us quite a headache at the moment.  It both kills our job throughput and leaves us with very little data to act on.  All we know is that a test hit a `Debug.Assert`.  We're forced to essentially run the tests in a loop in our box and hope we hit the same failure.  

We've looked into making Jenkins give us more data when this happens but it feels like we're working around the problem.  The problem is our tests are popping up blocking UI.  

I definitely understand the motivation for the original change.  Silently overriding `Debug.Assert` definitely feels like the wrong behavior.  But it also seems like it would be nice to let developers opt into changing it.

**Comment by bradwilson** [comment]
There are mechanisms for this kind of assembly-wide overriding of behavior: custom test frameworks. The implementation of [`ITestFramework`](https://github.com/xunit/xunit/blob/master/src/abstractions/xunit.abstractions/Frameworks/ITestFramework.cs) and friends can be mostly pass-thru to the existing code.

We resist the notion of having dozens of these one-off hooks in the framework itself because everybody's pet "thing I want to override" just bloats the framework. We ensure that our extensibility story allows user to do what they need to do so that the core framework stays leans and focused.

The [ObservationExample](https://github.com/xunit/samples.xunit/tree/master/ObservationExample) does more than you need/want, but should at least set you down the right path.

**Comment by davkean** [comment]
Thanks @bradwilson, I'll look into that.
