### ISSUE TITLE
Sealing Trait attribute lost a lot of functionality. 

### ISSUE THREAD

**Issue by Irtechie** [xunit/xunit#394]

**Comment by ghostsquad** [comment]
+1
http://tech.trailmax.info/2014/02/why-im-not-migrating-to-xunit-completely/

> NUnit has [Category()] attribute that marks the test(s) with some category. Usually these categories mark tests as “fast”, “slow”, “database”, “integration”, “smoke”, etc. So when you run these tests you can only include (or exclude) tests suitable for the environment. xUnit has Trait attribute which is a pair of strings. To create a category with Trait you’ll have to do this: [Trait("Category", "database")]. The key-value structure gives a bit more flexibility with categories. But I can’t come up with a scenario where I’d use other than “Category” for the trait key. Also, code examples shipped with xUnit 1.9.2 do have [Category("")] attribute which is inherited from Trait and placing the key to be "Category". But in xUnit v2 (which is in alpha just now) Trait attribute is sealed, so you can’t inherit it any more.

**Comment by bradwilson** [comment]
@ghostsquad: https://github.com/xunit/samples.xunit/tree/master/TraitExtensibility

**Comment by ghostsquad** [comment]
Oh, thanks for that. I didn't realize. I just saw in the latest code that TraitAttribute was still sealed. ITraitAttribute seems to be a good compromise.

**Comment by bradwilson** [comment]
The new design serves two purposes.

First, `ITraitAttribute` is more flexible, because it allows a single attribute to provide 0..n traits, whereas the old design of `TraitAttribute` only allowed (and mandated) a single trait from the attribute.

Second, the reason many of the new attributes are sealed (and use a discoverer) rather than using inheritance is because we wanted to be able to support test discovery from environments where the code may not even compile, so it's done with an abstract syntax tree (think: Resharper, CodeRush, even Roslyn in VS 2015). By being able to determine the intent of the code simply by looking it -- rather than having to run it -- means we can discern the user's intent earlier, before a compiler is invoked.

**Comment by ghostsquad** [comment]
Thank you for the explanation.

**Comment by wespday** [comment]
FYI, to make things simpler for my most common usage patterns I'm trying out this little NuGet package I created for test categories (e.g. UnitTest, IntegrationTest attributes):

https://github.com/wespday/CategoryTraits.Xunit2

One of the problems it solves is file locking issues I encountered when I originally had the ITraitDiscoverer implementation in the same solution as the tests.  The Test Explorer was loading and locking the same assembly that was being built.

Having this in place with xUnit 2 I'm definitely liking the ability to consolidate all test assemblies into one run and run tests in parallel and the console output is much prettier.
