### ISSUE TITLE
Test status

### ISSUE THREAD

**Issue by wziska** [xunit/xunit#398]
Is it possible to know status of currently executed test? Specifically I'd like to know in Dispose() method whether test failed or was successful.

**Comment by bradwilson** [comment]
Sorry, test run information is not available to the tests themselves.

**Comment by wziska** [comment]
Then, is it something possible to implement in the future? Or that was a design decision to not have such feature in the framework?

**Comment by bradwilson** [comment]
It was an explicit design decision that test information is available only to the runners, not to anything inside the test code.

**Comment by wziska** [comment]
Ok, it's not what I've expected, but thanks for the information.

**Comment by kenlefeb** [comment]
> It was an explicit design decision that test information is available only to the runners, not to anything inside the test code.

Why?

If the reason is expediency and priority of other work that needs to be done, that's perfectly valid, but I don't think that's really a _design_ decision.

If there's a genuine design flaw in exposing such context to the test code, I would love to understand this line of reasoning. It feels bad to have to fight against our infrastructure, and when I have to do this with infrastructure that I trust (as I trust xUnit) it makes me wonder if I'm trying to do the wrong thing.

**Comment by SimonCropp** [comment]
i needed this for a few of my projects. so i bundled it into my this https://github.com/SimonCropp/XunitContext#current-test
