### ISSUE TITLE
Add a version of BeforeAfterTestAttribute for ctor/Dispose

### ISSUE THREAD

**Issue by AlexanderSher** [xunit/xunit#401]
Right now, BeforeAfterTestAttribute.Before method is called before test method, but after class constructor. Sometimes, when constructor contains initialization logic, it is useful to be able to do some actions before class is instantiated.

There is an available workaround with IMessageBus, but it requires several things to be overriden.

**Comment by bradwilson** [comment]
After discussion, we decided not to do this feature.

**Comment by Shinkansens** [comment]
Hi Brad,

We love xUnit and appreciate many features xUnit team added. 

We're wondering if you know a workaround in xUnit for this situation. 

Like the title says, our test constructor have unique initialization logic that depends on common logic inside BeforeAfterTestAttribute. Today the constructor starts up before BeforeAfterTestAttribute, so the unique logic in the constructor fails. 

Is there a workaround to control the sequence of event so that BeforeAfterTestAttribute goes first, wait for BeforeAfterTestAttribute to finish, and then constructor do initialization? One guy mentioned using IMessageBus as a workaround, but we're not sure what that means. 

Any input welcome. Thank you Brad.

**Comment by bradwilson** [comment]
@Shinkansens There is no simple way to change this behavior today.
