### ISSUE TITLE
Xunit for 4.0 project

### ISSUE THREAD

**Issue by Gwynnbleid1** [xunit/xunit#407]
Hi!

Is it possible to use xunit for 4.0 project ? 
I'm developing apps for WIndows XP (I know it is not longer supported) and I would really like to use xunit for unit tests and integration tests.

Regards
Gwynnbleid1

**Comment by bradwilson** [comment]
You cannot use version 2.0 (or later) with a 4.0 project, because it requires 4.5.

If targeting 4.5 is not possible, then you must stick with version 1.9.2. If you need help with installing an older NuGet package, please see this StackOverflow article: http://stackoverflow.com/questions/5628689/download-old-version-of-package-with-nuget
