### ISSUE TITLE
Create a unit test for each line in memberdata

### ISSUE THREAD

**Issue by NPadrutt** [xunit/xunit#429]
Hi

I couldn't find an existing issue to this topic, aswell as there wasn't someone on StackOverflow who could give me a concret answer, so I create a new issue here.

When you use the Theory Attribute together with Inline Data it will create you a single test for each line of inline data. But if you use Member Data to pass a static property it will only create a single test and execute all data lines within this test.
Is there a specific reason that this works in a other way and would it be to make it adjustable via the app.config? Or are there specific limitations who prevents such an implementation?

**Comment by bradwilson** [comment]
What version of xUnit.net are you using?
What test runner (and what version) are you using?

**Comment by NPadrutt** [comment]
I have these versions:
- xUnit.net 2.0.0
- xUnit Visual Studio Runner 2.0.0
- Visual Studio 2013 Update 4
- .net 4.5

**Comment by bradwilson** [comment]
The problem very likely comes down to support for serialization.

When test cases are made for the Visual Studio runner, we need to be able to serialize that test case, because the discovery and execution phase take place in different processes (sometimes, as is the case with Windows Phone tests, inside a virtual machine). We can always serialize the test case without its parameters; whether we can serialize it with parameters depends on the parameters. We have support for several built-in types, but your own custom types will require implementation of serialization if you want to support this.

This method, given that it uses only simple types, works as you'd expect:

```csharp
public static TheoryData<object> CompatibleData
    = new TheoryData<object> { 42, 21.12, "Hello world!" };

[Theory]
[MemberData("CompatibleData")]
public static void ThisShowsIndividualRows(object x)
{
    Assert.NotNull(x);
}
```

This method, on the other hand, fails because it at least one of the data items is not serializable (the naked object):

```csharp
public static TheoryData<object> IncompatibleData
    = new TheoryData<object> { 42, new object() };

[Theory]
[MemberData("IncompatibleData")]
public static void ThisShowsASingleRow(object x)
{
    Assert.NotNull(x);
}
```

You can add serialization support for your custom test data if you want to enable the per-data row support:

```csharp
public static TheoryData<object> CustomSerializableData
    = new TheoryData<object> { 21.12, new CustomSerializable(42) };

[Theory]
[MemberData("CustomSerializableData")]
public static void ThisHasCompatibleSerializableData(object x)
{
    Assert.NotNull(x);
}

class CustomSerializable : IXunitSerializable
{
    public CustomSerializable() { }  // Needed for deserializer

    public CustomSerializable(int value)
    {
        Value = value;
    }

    public int Value { get; private set; }

    public void Deserialize(IXunitSerializationInfo info)
    {
        Value = info.GetValue<int>("Value");
    }

    public void Serialize(IXunitSerializationInfo info)
    {
        info.AddValue("Value", Value);
    }

    public override string ToString()
    {
        return "Value = " + Value;
    }
}
```

The override of `ToString` allows you to control what the data looks like in the test list (the default display is a JSON-like view of the object).

Here are all three test methods shown in Visual Studio 2013:

![Visual Studio discovery](https://cloud.githubusercontent.com/assets/16944/7952644/d1090c70-096d-11e5-8c9c-56d5f8e82282.png)

**Comment by NPadrutt** [comment]
So that would mean that if I want to use that with a custom object rather than an int that this object needs to implement the IXunitSerializable? As far as I see I cannot replace the int with my object in the CustomSerializable. Or at least not without to change the Serialize method.

**Comment by bradwilson** [comment]
Everything down the entire tree that's being serialized either needs to have built-in support, or has to implement `IXunitSerializable`.

**Comment by NPadrutt** [comment]
Alright, thank you for your answers.

**Comment by ghostsquad** [comment]
Wait, so what's the problem with @NPadrutt above example? Is it the `new []` or `new object[]` is not serializable?

**Comment by bradwilson** [comment]
The fact that `DataConverterParameter` is not serializable.

**Comment by aviita** [comment]
"Everything down the entire tree that's being serialized either needs to have built-in support, or has to implement IXunitSerializable."

Does all of this mean that all my types need to be serializable specifically with methods from IXunitSerializable and platform specific serialization is not supported (e.g. Serializable attribute in .net)?

**Comment by bradwilson** [comment]
> all my types

Anything that's a data member for a theory.

> platform specific serialization is not supported

Correct, serialization is not available in the PCL, which is why `IXunitSerializable` exists at all.

**Comment by ViktorHofer** [comment]
> Correct, serialization is not available in the PCL, which is why IXunitSerializable exists at all.

Sorry for bringing up a very old thread but as you already cross-compile for different .NET Core / .NET Standard versions, can't this easily solved now?

**Comment by bradwilson** [comment]
No, because there are target platforms that don't support serialization (like UWP).

**Comment by ViktorHofer** [comment]
Right, but that's what multi-targeting solves. Adding functionality to a (sub-)set of targets.

**Comment by bender2k14** [comment]
As I see it, the drawback with implementing `IXunitSerializable` is how it compromises my production types (by explicitly requiring mutability and [implicitly requiring a public default constructor](https://xunit.net/xunit.analyzers/rules/xUnit3001.html)).

Would it be possible to give xUnit this serialization functionality in a separate type?

As a comparison, I like how xUnit optionally provides its `ITestOutputHelper` to tests through constructor injection of the test class.  Using that, one can integrate with Serilog's logger [like this](https://github.com/trbenning/serilog-sinks-xunit).

As another comparison, [Microsoft.EntityFrameworkCore.DbContext](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext?view=efcore-2.1) has a [constructor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.-ctor?view=efcore-2.1#Microsoft_EntityFrameworkCore_DbContext__ctor_Microsoft_EntityFrameworkCore_DbContextOptions_) that (optionally, because there is also a [default constructor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.-ctor?view=efcore-2.1#Microsoft_EntityFrameworkCore_DbContext__ctor)) takes [DbContextOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptions?view=efcore-2.1) that can be used to configure many things.

Maybe the following would work.  Suppose there was a type like
```
public interface IXunitSerializer<T> {
  void Serialize(IXunitSerializationInfo info, T t);
  T Deserialize(IXunitSerializationInfo info);
}
```

Then a `Guid` implementation could be created...
```
public class GuidXunitSerializer : IXunitSerializer<Guid> {
  public void Serialize(IXunitSerializationInfo info, Guid guid) =>
    info.AddValue("key", guid.ToString("N"));
  public Guid Deserialize(IXunitSerializationInfo info) =>
    Guid.Parse(info.GetValue<string>("key"));
}
```

...and provided to xUnit though some constructor options:
```
public class TestClass {
  public TestClass(IXunitOptions optoins) =>
    options.AddXunitSerializer(new GuidXunitSerializer());

  // some Theory test using MemberData and Guid inputs
}
```

Would this work?  Does this give xUnit enough information to accomplish all its (de)serialization for all of its target platforms?

Furthermore, does this approach seem reasonable?

Thanks for your consideration :)

**Comment by bradwilson** [comment]
We should be able to support normal serialization in v3, since the target is `netstandard2.0`. Not sure if that's an open feature yet.

**Comment by bender2k14** [comment]
Oh, that is great.  I am looking forward to v3! :D

**Comment by douglasg14b** [comment]
Do the tests run off of the serialized data from discovery?

If I have non-serializeable properties in my model, are those not retrieved from my `GetTestData()` directly during test running?

It seems only the serializeable properties are being used in tests, all other properties are null.

I would expect that my actual test data is retrieved directly from my `GetTestData` static method for each test, not run through the serializer first?

**Comment by douglasg14b** [comment]
The behavior I'm seeing seems unexpected, and inconsistent:

* All tests run as  `[Theory]` with `[MemberData]` of type `MyTestObj`.
* `MyTestObj` contains:
  - A `Type TestingType {get; set;}` property
  - A `PropertyInfo TestingProp {get; set;}` property
  - A `string Name {get; set;}` property

**Scenario1:** :heavy_check_mark: 
- **`MyTestObj` does NOT implement `IXunitSerializable`**
- Only a single tests shows in test explorer :heavy_check_mark: 
- Test shows multiple results, one per member data :heavy_check_mark: 
- Tests run using all the data in  `MyTestObj`, the `Type` and `PropertyInfo` proerties are filled in and not null :heavy_check_mark: 

**Scenario2:**  :x: 
- **`MyTestObj` DOES implement `IXunitSerializable`**
- One test per member data shows in test explorer :heavy_check_mark: 
- Tests run using ONLY the serialized data in  `MyTestObj`, the `Type` and `PropertyInfo` properties are now null, and tests fail  :x:

**Comment by bradwilson** [comment]
That is actually the expected behavior. If you cannot fully serialize and deserialize your state, then you should not implement `IXunitSerializable`.

**Comment by xp44mm** [comment]
suggest each line support  array, tuple, record, union, list, set, map or their combines.(F#)
