### ISSUE TITLE
InlineData problem when using type conversion

### ISSUE THREAD

**Issue by row5is** [xunit/xunit#437]
When using InlineData with a parameter that is a short I had to coerce the numeric value to a short using (short). But this caused all the tests in the theory to become single test. i.e.
        [Theory]
        [InlineData(null, null, "N/A")]
        [InlineData(2, null, "#,##0.00")]
        [InlineData(1, (short)1, "N/A")]
        [InlineData(2,(short) 0, "#,##0.00")]
        [InlineData(2, (short)1, "#,##0")]

public void testcode(int? param1, short? param2, string param3)

This shows as one test not 5 in the test runner for visual studio.

**Comment by bradwilson** [comment]
Have you tried this with the latest pre-beta 3 builds from MyGet? I would think this would already be fixed.

**Comment by bradwilson** [comment]
I have verified that with `xunit` version `2.1.0-beta3-build3008` and `xunit.runner.visualstudio` version `2.1.0-beta3-build1065`, this works as expected:

![Visual Studio 2013 Test Explorer](https://cloud.githubusercontent.com/assets/16944/8196823/eaf071b4-1444-11e5-8889-8058b50045ba.png)

That means you should expect it to be fixed in the official Beta 3 release.

As for why you have to cast to `short` explicitly, it's because you're using `short?` for your parameter type. Inside the .NET framework itself, there is a registered conversion from `int` to `short` but not from `int` to `short?`. The compiler can do this when it has some clues, but the framework itself cannot. And of course, the worst part of all is that `short` does not have a constant suffix (unlike `L` for `long`, `M` for `decimal`, etc.). So you're stuck either using the `(short)` cast in the attribute, or switching the parameter from `short?` to `short`.

**Comment by row5is** [comment]
Thanks for the quick response. I'll grab beta 3 when it gets released.
