### ISSUE TITLE
Add a test context available to extensibility points

### ISSUE THREAD

**Issue by 82949712** [xunit/xunit#458]
Is there any docs on this? Cheers

**Comment by bradwilson** [comment]
The answer is "it depends on what you're trying to do".

There are several samples here that might point you in the right direction: https://github.com/xunit/samples.xunit

**Comment by lchong0412** [comment]
I am trying to figure out how to get the test status (pass/fail) at the end of running a test method, in the Dispose method. Could you please suggest a way to do it?

**Comment by bradwilson** [comment]
Given the design of xUnit.net as it stands today, a test does not have access to that information.

To make that information available to the running test would be... extensive surgery. I'm not 100% sure how you'd do it yet, though my first guess would be to introduce a constructor-provided test context object that held the information.

**Comment by kijanawoodard** [comment]
Is there a place to see "If you used to do this with ITestClassCommand, now you do ...."?
I've looked through the docs and searched, but not turning up much.

The project I'm working on has quite a few hooks into XUnit 1. Upgrading to Resharper 9 broke the display of failed test info. Kinda important LOL.

Right now I'm googling "Xunit 2 replacement for XYZ" and trying to get things compiling again. 
Nothing much comes up for ITestClassCommand. This issue was the best search result.

FWIW, I saw the migration guide, but that seemed to be about basic tests, not deep extensions.

Thanks for any guidance / doc pointers.

**Comment by kijanawoodard** [comment]
For anyone else who finds it, the answer was pretty simple.

I deleted most of the base class infrastructure [ITestClassCommand, TestCommand, etc] and replaced it with a constructor and IDisposable. 

Other than that, I converted IUseFixture to IClassFixture.
So far, everything's working well.

**Comment by alastairs** [comment]
I'm interested in how to access test metadata at runtime. In particular, I want to access the test name so that I can add it as a [Serilog](https://github.com/serilog/serilog) Property in the LogContext.

**Comment by bradwilson** [comment]
Subset of #621, closing as dup.
