### ISSUE TITLE
[Question] xUnit in VSO

### ISSUE THREAD

**Issue by XcoderTeam** [xunit/xunit#464]
Hi

I have mvc 6  project and host into VSO with xUnit 2.1.0-beta3-build3029.
In my VS i able to see the test in Test Explorer.
Question How can i setup and run the test in VSO Build.
Test add Visual Studio Test build step no matter I try to configure it, it not able to find the test case.

Below is the response from the build console.

```
2015-07-10T15:02:43.1230229Z Starting task: Test Assemblies **\*tests*.dll;-:**\obj\**

2015-07-10T15:02:43.1270229Z Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\tasks\VSTest\1.0.16\VSTest.ps1

2015-07-10T15:02:43.6280240Z ##[warning]No test assemblies found matching the pattern: C:\a\798feaf9\Wallet\**\*tests*.dll;-:**\obj\**

2015-07-10T15:02:43.6334717Z Finishing task: VSTest
```

**Comment by bradwilson** [comment]
Try following Donovan's directions:

http://www.donovanbrown.com/post/2015/06/15/how-to-run-xunit-test-with-vnext-build

(We have an open issue to get this documented on our site, based on Donovan's blog post)

**Comment by XcoderTeam** [comment]
Hi @bradwilson 

I setup following the article that you give, it not working.
Below screenshot is my configuration

![screen shot 2015-07-11 at 9 55 47 pm](https://cloud.githubusercontent.com/assets/1622986/8633971/c5736d7e-2817-11e5-85ee-4f6ba1fae15c.png)

may i know in which part is missing.

**Comment by bradwilson** [comment]
I'm sorry, I've never used VSO, so I'm not going to be able to be much help. :( 

Does it work if you don't check "Code Coverage Enabled"?

**Comment by XcoderTeam** [comment]
Hi @bradwilson 

Turn off Code Coverage, It the same not working.
No test assemblies found matching the pattern: C:\a\798feaf9\Wallet\**\*test*.dll;-:**\obj\**

**Comment by JacobSnyder** [comment]
I don't even think that this is an xunit issue because VSO isn't even finding any assemblies that match your search path.  If it weren't finding the xunit test runner, your error would be different (I've seen both these of these errors and they are sufficiently different).

One thing I notice from your screenshot is that it is trying to match `**\*test*.dll` whereas your logs are trying to match `**\*tests*.dll` (or at least I'm assuming the are, I think you're losing the `**\*` due to markdown, causing `**\*test*.dll` to appear as **\*test*.dll**).  But the "s" in test**s** might be important.

Secondly, make sure you're actually building your solution before running the test build step.  That's another thing that could cause your binaries to not be present.

For what it's worth, here's a screenshot of my settings, which are working for me.  I only compile and run Release, which is why that's present in my Test Assembly path.  You should tweak this to match your test assemblies.  You should ignore the value in "Other console options", that should safe to delete.
![Settings](http://i.imgur.com/mgrjtCL.png)

**Comment by bradwilson** [comment]
Added to documentation: https://xunit.github.io/docs/getting-test-results-in-vsts.html
