### ISSUE TITLE
Theory data with internal constructor should generate a failure

### ISSUE THREAD

**Issue by eroller** [xunit/xunit#465]
![1d59a956-2569-11e5-917c-75394a57bf4a](https://cloud.githubusercontent.com/assets/2440289/8622919/f87722fa-26e2-11e5-89e1-343371c4dbd5.png)

**Comment by eroller** [comment]
related to http://stackoverflow.com/questions/31279955/test-missing-when-using-autofixture-with-nsubstitute-auto-data-attribute

**Comment by eroller** [comment]
if the constructor is internal, those tests are ignored. If it's public, it runs.

**Comment by bradwilson** [comment]
There is a bug here, but it's not what you think it is.

The fix (for you) is simple: xUnit.net does not support test data attributes with internal constructors. Change the constructor to public, and the problem will go await.

The bug in xUnit.net is that it should be reporting an error for this test case because it violates the rule, but it does not; instead, it does not discover the test.

The secondary bug (which caused most of your confusion here, I think) is that the Resharper runner _**should never have discovered the test in the first place**_. Therefore, you should open an issue against the Resharper runner (at https://github.com/xunit/resharper-xunit) for this additional bug.

**Comment by bradwilson** [comment]
The fix for this is return a single test case with a failing theory that indicates the missing constructor. This may actually fix the Resharper issue, so you may not need to log an extra issue.
