### ISSUE TITLE
Add support for [BeforeAfterAttribute] classes on test collections

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#468]
I have a test fixture that manages AppDomain-wide state (it is state stored in statics in the product I am emulating for testing my extension). But some of that state should be reset for each test. 

Can my fixture implement some interface in order to receive notifications regarding when a test method is about to start or has stopped?

Or is there another supported way to do this?

**Comment by bradwilson** [comment]
No, fixtures do not have this capability. The closest thing we have is [`BeforeAfterTestAttribute`], whose scope today is limited to test method or test class. There is no collection equivalent to this.

I suppose we could extend this attribute to support test collections, if it was applied to the collection definition. That would need to be a feature request. I'm not sure if this is actually what you want, though, because what you lose by not being a fixture is finding out when the _first_ test starts and when the _last_ test ends.

**Comment by AArnott** [comment]
For this particular requirement, I don't need to know about the first and last tests (as I do for another requirement). For this one, I just need to ensure that each test starts with a clean slate in that shared state area.

But having test collections that can span assemblies is also important, both for this reason and the other one (#374)

**Comment by AArnott** [comment]
Ah, I just read your last comment on #374 about each assembly getting its own AppDomain. That's fantastic. So yes, having `[BeforeAfterTestAttribute]` support at the test collection level would satisfy the requirement.

How do I formalize the feature request?

**Comment by bradwilson** [comment]
^^ That's how :)

**Comment by AArnott** [comment]
Thanks!
