### ISSUE TITLE
How to debug individual test of a theory (example given)

### ISSUE THREAD

**Issue by vijayinvites** [xunit/xunit#479]
Consider the following example

```
public class TheoryTestClass
{
   [Theory, MemberData("GetIntValues")]
     public void TestTheory(ClassInt classInt)
    {
       Assert.True(classInt.intValue%2 == 0);
    }

    public static IEnumerable<ClassInt[]> GetIntValues()
    {
        var temp = new List<ClassInt[]>();
        for (int i = 0; i < 10; i++)
        {
            var c = new ClassInt();
            c.intValue = i;
            temp.Add(new []{c});
        }
        return temp;
    }
}

public class ClassInt
{
    public int intValue;
    public override string ToString()
    {
        return intValue.ToString();
    }
}
```

Test explorer shows only one test. I want to see all the 10 tests and if a test fails how do i run/debug only that particular test?

**Comment by bradwilson** [comment]
When the Visual Studio runner is used, test data needs to be able to be serialized, because the Visual Studio runner architecture is such that the tests are discovered in one process, and then run in a separate process. When the test discovery system finds theory data that it cannot serialize, it returns the single (parameterless) test case, so that it can do the discovery of the data later on in the second process.

Since the Visual Studio runner can run device tests (Windows & Windows Phone) in addition to desktop, we can't use the built-in serialization system (it's not supported on devices); instead, we have our own serialization system.

When something needs to be serialized (including test data), it needs to follow two rules:

- It must have a public, parameterless constructor (you're already okay here, because the compiler generates one implicitly for you);
- The class must implement `IXunitSerializable`.

Adding and implementing the interface gives you the behavior you want:

```csharp
public class ClassInt : IXunitSerializable
{
    public int intValue;

    public void Deserialize(IXunitSerializationInfo info)
    {
        intValue = info.GetValue<int>("intValue");
    }

    public void Serialize(IXunitSerializationInfo info)
    {
        info.AddValue("intValue", intValue);
    }

    public override string ToString()
    {
        return intValue.ToString();
    }
}
```

**Comment by xied75** [comment]
I have some simple inlinedata to feed into the test method:

```CSharp
[Theory]
[InlineData("7")]
[InlineData("7b")]
[InlineData("7b6")]
public virtual void TestPartial_FromString(string s)
```

Now when I right click on this test body and __run__, I got all tests in the file fired, not just this single test. But Debug on the test body does work.

**Comment by SuperJMN** [comment]
Is it possible to debug just only one test in a Theory?

**Comment by bradwilson** [comment]
Debugging individual data sets in a theory works, so long as your theory data is serializable.

**Comment by smetlov** [comment]
Adding `public Guid Id = Guid.NewGuid();` to the test case class did a trick for me.
