### ISSUE TITLE
Assert.Equals with IReadOnlyList<>

### ISSUE THREAD

**Issue by oliverjanik** [xunit/xunit#509]
This test:

``` c#
        [Fact]
        public void CanCompareEnumerables()
        {
            var array = new[] { 1, 2 };
            IReadOnlyList<int> list = new List<int> { 1, 2 };

            Assert.Equal(array, list);
        }
```

doesn't pick the IEnumerable<T> overload of Assert.Equal. Instead it just picks a T variant and it fails because the types don't equal.

Any slick way around it?

**Comment by bradwilson** [comment]
The compiler has decided that the `T` of `IReadOnlyList<int>` is of higher priority than the fact that both are `IEnumerable<T>`. The only simple fix for this would be to add a new method (like `CollectionEqual` or something) so that there were no ambiguity for the compiler to attempt to resolve.

The simplest work around for you right now is kinda ugly: explicitly saying `Assert.Equal<int>`. :frowning:

**Comment by oliverjanik** [comment]
I guess I'll stick to `Assert.Equal(array, list.AsEnumerable());` which is clearer IMO.
