### ISSUE TITLE
The missing manual -- is there documentation?

### ISSUE THREAD

**Issue by vamichael** [xunit/xunit#511]
Is there any *offiicial* documenation for xUnit?  How should one go about learning what various methods and attributes are for?  Unfortunately doing a Google/Stackoverflow search often misses the mark due to much of the sample code and tutorials are using deprecated functionality.

For example, what is DisplayName for?  `[Fact(DisplayName = "Foobar")]`   -- or to be more precise *where* is it used?  Command line runners?  Intellisense says *Gets the name of the test to be used when the test is skipped*.  What gets the name? And what does skipping have anything to do with it?  Where can I use it and what benefit would it provide?

**Comment by chester89** [comment]
Any reason [this] (http://xunit.github.io/) doesn't work for you?

**Comment by vamichael** [comment]
I'll give you a good example (in addition to the one above where I asked about DisplayName).

Is there documentation on how you assert an exception is thrown?  Any examples explaining the difference between Throws vs ThrowsAny?  I was very confused as to why Throws didn't catch an inherited exception until I was told about ThrowsAny.   Personally I think the convention is awkward.  Throws should behave like ThrowsAny, and ThrowsAny should be renamed ThrowsOnly.

There are probably hundreds of things missing from that page.  I'd volunteer to help start building documentation and matching samples if someone has a suggestion on how the whole thing could be organized.

**Comment by bradwilson** [comment]
The question of how `Assert.Throws` works was answered 8 years ago. We're not changing that now.

You're welcome to use any assertion library you want; ours is not required (it's a separate package). If you are so motivated, you can use our source package (`xunit.assert.source`) instead of the binary package, and make whatever changes you want to make the names work exactly how you expect. That's why we offer it as source.
