### ISSUE TITLE
Every unit test always run twice in Visual Studio 2015

### ISSUE THREAD

**Issue by regionbbs** [xunit/xunit#519]
Hi,
I use xunit as my unit testing solution, it works perfect in VS 2015.

After I upgraded my project to VS 2015, my Xunit Test always run twice, already tried to unistall xunit.runner.visualstudio and xUnit Test Extension for VS2015, this issue still exists.

How can I resolve this issue?
Thank you.

**Comment by bradwilson** [comment]
My guess? Your `packages` folder has two different versions of `xunit.runner.visualstudio` in it (either because you're referencing two different versions, or because one is leftover and failed to get cleaned up).

Try closing down Visual Studio, deleting your packages folder, then restart VS and re-build (which will cause a package restore), and then see how many Visual Studio runners are installed there. If it's just one, you should stop seeing this behavior.

**Comment by regionbbs** [comment]
OK, I will try it and report result here.
Thank you.

**Comment by regionbbs** [comment]
After I removed older of xunit.runner.visualstudio package and restarted IDE, it see work fine.
Thank you.

**Comment by zijianhuang** [comment]
thanks for the hint. In my case, the trigger of running the tests twice was that xunit.abstractions.2.0.0.0 is still there after updating the xUnit packages to 2.1. After removing it manually, tests run once as expected.
