### ISSUE TITLE
displayName value to only display simple class name and method

### ISSUE THREAD

**Issue by augusteiner** [xunit/xunit#524]
Some test libraries contains a few tests and the fully qualified class name and method option is too verbose in Test Explorer for example.

I think that a way of displaying only the simple class name and method would be nice in a small sized test library.

Another option would to allow a custom displayName.

My main problem resides in some base test class that has a generic arg, for instance:

``` csharp
namespace some.long.ns.str.here
{
    abstract class BaseGenericTest<T>
    {
        [Fact]
        public void SomeSharedTest()
        {
            Assert.False(false);
        }
    }

    class ConcreteTest : BaseGenericTest<Foo>
    {

    }
}
```

The test name reported is too long, and defining a displayName to every fact (would not report the current `ConcreteTest` class name) or overriding every base method to define a displayName would be too cumbersome.

Any ideas?

**Comment by bradwilson** [comment]
This will not be possible with our current design. Sorry.

**Comment by augusteiner** [comment]
Not even the SImpleClassNameAndMethod?

**Comment by bradwilson** [comment]
Our abstraction APIs do not separate class name from namespace name.

**Comment by DavidChenware** [comment]
Ditto this.

For example, if you follow a common naming convention for tests (taken from The Art of Unit Testing) UnitOfWork_StateUnderTest_ExpectedBehavior, and a common naming convention for namespaces, CompanyName.TechnologyName.Feature.Design - already the name in the Test Explorer is quite large.

In the test explorer it shows up as "CompanyName.TechnologyName.Feature.Design.FactClassName.UnitOfWork_StateUnderTest_ExpectedBehavior".

Even in the github comment entry box, it's longer than the max width. Adding or maintaining custom DisplayNames in the [Fact] attributes is both cumbersome and repetitive, since the method name is exactly what I would be used to seeing.

Would it be possible to be able to specify a tokenized displayName string?

**Comment by bradwilson** [comment]
The override today is to use the `DisplayName` property on `[Fact]`.

**Comment by DavidChenware** [comment]
Understood, it just is not feasible for thousands of unit tests, especially as Intellitests become more popular.

**Comment by yannduran** [comment]
I'm also having the same problem of only being able to see the namespace in VS Test Explorer due to the current way test names are formed.

In my search for a way to change this, I found an article that described a way of adding a keyname/value pair to app.config to set the display name to "method" only, but it didn't change the names, so I'm not sure if I just did something wrong.

I would regard this as an extremely useful feature if it was added to xUnit.

**Comment by wabirch** [comment]
The config setting is as follows: 

    <appSettings>
        <add key="xunit.methodDisplay" value="method" />
    </appSettings>

This works for me in a Visual Studio 2015 project targetting .NET 4.6 and referencing XUnit 2.1.0.

**Comment by yannduran** [comment]
@wabirch You're a legend! I don't know what I could have done wrong last time. But it works perfectly now. Thank you so much!

**Comment by ZodmanPerth** [comment]
UWP doesn't have these app settings.  Is there another way that works for UWP?

**Comment by cjprieb** [comment]
The suggestion by wabirch to edit the config doesn't work for .NET Core projects, but I found a workaround that should work for projects with access to System.Runtime.CompilerServices and .NET 4.5 (see https://stackoverflow.com/a/15738041/973678). It basically extends the FactAttribute from xUnit and sets the display name to the method name so you don't have to manually add it for every single method. 
```
    public class MyFactAttribute : FactAttribute
    {
        public MyFactAttribute([CallerMemberName] string memberName = null)
        {
            DisplayName = memberName;
        }
    }

**Comment by VMAtm** [comment]
@cjprieb For .Net Core you have to use the `JSON` config, not the `XML` one:
http://xunit.github.io/docs/configuring-with-json.html

**Comment by perlun** [comment]
> @cjprieb For .Net Core you have to use the `JSON` config, not the `XML` one:
> http://xunit.github.io/docs/configuring-with-json.html

In case anyone comes looking for this, here's an updated URL which works (the one above gives a 404 nowadays):  
https://xunit.net/docs/configuration-files

**Comment by Prasadnair** [comment]
I created an xunit Project in VS 2022 and targeting .NET 6.0 .  I can see only the method names without adding the xunit.runner.json file with key "methodDisplay" and value "method". I believe, by default Fact attribute would consider only the method name
