### ISSUE TITLE
BeforeAfterTestAttribute for DNX projects

### ISSUE THREAD

**Issue by sergeyzwezdin** [xunit/xunit#545]
I'm trying to implement custom `BeforeAfterTestAttribute` attribute in DNX project.

Once I override `Before` or `After` methods, I see following error during build:

> 'TestAttribute.After(MethodInfo)': no suitable method found to override	Tests.DNX 4.5.1
> 
> The type 'MethodInfo' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	

It's pretty obvious that xunit uses Reflection assembly. Ok, I'm adding this reference to `project.json` in this way:

```json
  "dependencies": {
    "System.Collections": "4.0.10-beta-23109",
    "System.Linq": "4.0.0-beta-23109",
    "System.Threading": "4.0.10-beta-23109",
    "System.Runtime": "4.0.10-beta-23109",
    "System.Reflection": "4.0.10-beta-23109",
    "Microsoft.CSharp": "4.0.0-beta-23109",
    "xunit": "2.1.0-*",
    "xunit.runner.dnx": "2.1.0-*"
  },

  "frameworks": {
    "dnx451": { }
  },

  "commands": {
    "test": "xunit.runner.dnx"
  }
```

Now when I build the project I see another error:
> The type 'MethodInfo' exists in both 'System.Reflection, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Could you advise how to use `BeforeAfterTestAttribute` in DNX projects?

**Comment by bradwilson** [comment]
What version of xUnit.net are you linked against?

What version of DNX are you using?

**Comment by sergeyzwezdin** [comment]
@bradwilson xunit.net − 2.1.0-beta4-build3109, dnx − 1.0.0-beta6

**Comment by bradwilson** [comment]
It's possible this issue is related to this: https://github.com/aspnet/dnx/issues/2387

**Comment by bradwilson** [comment]
IMO, the build process here is broken (as referenced in the previous issue).

For now, you still need to add appropriate framework references when targeting `dnx451`. The compiler error isn't super helpful here.

I used this as my project.json to get things to build:

```json
{
  "dependencies": {
    "xunit": "2.1.0-beta4-build3109",
    "xunit.runner.dnx": "2.1.0-beta4-build134"
  },
  "frameworks": {
    "dnx451": {
      "frameworkAssemblies": {
        "System.Reflection": ""
      }
    }
  },
  "commands": {
    "test": "xunit.runner.dnx"
  }
}
```

**Comment by ericstj** [comment]
DNX 4.5.1 doesn’t support System.Reflection 4.0.10.  System.Reflection 4.0.10 is only supported starting with .NET 4.6 and thus DNX 4.6.

The bug here is that DNX is choosing some reference assembly from a core framework (perhaps it is falling back to the DNXCORE50 reference assembly?).  Instead it should be throwing up an error on restore to tell you System.Reflection 4.0.10 isn’t supported by DNX 4.5.1.  If you examined the project.lock.json in the targets section DNX451 looking at asset selection for System.Reflection 4.0.10 it should reveal the mistake. /cc @anurse

The reason why adding an un-versioned framework assembly ref worked around the problem was that you told DNX to blindly add the system.reflection.dll from the targeting pack to the project.  This one happens to be the 4.0.0 and it satisfies your ref.

The reason why XUnit's dependency on System.Reflection 4.0.0 didn't work was that the inbox façade packages rely on the build system to automatically add references to all facades whenever a system.runtime based reference is added to the project.  In MSBuild this is handled by the ImplicitlyExpandDesignTimeFacades functionality in common.targets.  DNX is apparently missing this logic @davidfowl.

**Comment by bradwilson** [comment]
@ericstj It doesn't work on dnx46, either, at least not with `1.0.0-beta7-15019`. In both cases, it links against nothing.

**Comment by ericstj** [comment]
As I mentioned the reason it links against nothing is because DNX is missing the ImplicitlyExpandDesignTimeFacades functionality.

The version problem seemed to be causing the wrong asset selection for the unsupported contract.

2-bugs here, both in DNX.  We might be able to workaround the ImplicitlyExpandDesignTimeFacades problem in the framework packages if we special case DNX, we'll have to be careful though because if those assets become applicable for an msbuild based project ResolveAssemblyReferences will fail the build.

**Comment by ericstj** [comment]
So the root cause of the second issue (wrong asset selection) is happening because DNX didn't do the compat check for this package.  It's supposed to be doing a ref-lib comparison to determine if the package is supported and fail since the package has no matching lib for net451.  @bradwilson this failure is indeed related to https://github.com/aspnet/dnx/issues/2387 since the lack of runtime selection means DNX is not even currently building a runtime graph.  This is assuming that the DNX team will enable the same compatibility checking that was put into nuget as part of this fix.

**Comment by bradwilson** [comment]
@ericstj I'm not sure you can say that DNX (well, really,DNU) is doing the wrong thing, because the best matched framework for `dnx451` is `net45`, and it has an empty `lib` and `ref` folders. It has done exactly what that NuGet package asked. I agree that it's not the result I expected, but it definitely seems like its behavior is predictable, once you look at the NuGet package.

**Comment by onovotny** [comment]
@bradwilson the part that's missing isn't the blank ref/lib dir -- that's actually right. I believe all FX refs are added by the {} in the dnx451 framework. What *is* missing are the façade assemblies. When building a .NET 4.5/4.6 library in VS, MSBuild automatically adds all of those façade assemblies with the `ImplicitlyExpandDesignTimeFacades` mechanism. Once DNX includes the façade references in addition to the framework ones, things should work as expected.

**Comment by sergeyzwezdin** [comment]
@bradwilson ok, great! adding `System.Reflection` to `frameworkAssemblies` works for me. Thank you!
