### ISSUE TITLE
VisualStudio Runner does not properly display tests with member data

### ISSUE THREAD

**Issue by dealproc** [xunit/xunit#547]
I am unsure if this is an issue or not, so am reporting it to inquire.

When providing a MemberData attribute to a theory, if the member emits more than one item, it seems as if the Visual Studio runner is considering all items as a single test, instead of breaking them up into multiple tests.

Should a mock of this issue be created and posted for reference, or is it enough to just report this?

**Comment by bradwilson** [comment]
In Visual Studio, it can only show separate tests per data row when the data in the data row is serializable.

Serializable here is defined as the handful of intrinsics that we have built-in support for. You can see the actual list of things here: https://github.com/xunit/xunit/blob/4e39f2c784fae4e864c67743f825c5f811c04d42/src/common/XunitSerializationInfo.cs#L104-L176

MemberData is not on this list. When you have non-serializable data, then you get a single test case for the theory, and running it runs all the data. You are no longer able to run any individual data row.

**Comment by dealproc** [comment]
Ok.  Was mainly a curiosity.  So an anonymous type of intrinsic values cannot be split up.  No worries.  it just gets annoying because the test explorer is saying one thing, but the output in TeamCity is saying another.  I may be observing wrong, but will play a bit to verify.

**Comment by bradwilson** [comment]
@dealproc For your own custom types, you can implement [IXunitSerializable](https://github.com/xunit/xunit/blob/master/src/abstractions/xunit.abstractions/Serialization/IXunitSerializable.cs).

**Comment by Ausm** [comment]
@bradwilson
Does that mean, that there is no way to let xUnit call a theory method like
_public void TestSimpleExpression(string name, Expression<Func<MyClass, bool>> expression, int expectedCount)_

I tried it with a wrapper which implements [IXunitSerializable](https://github.com/xunit/xunit/blob/master/src/abstractions/xunit.abstractions/Serialization/IXunitSerializable.cs), and it worked as long as I used the wrapper class in the argument as well.
This one _public void TestSimpleExpression(string name, Wrapper<Expression<Func<MyClass, bool>>> expression, int expectedCount)_ worked, but when I remove the Wrapper<> type in the argument, a System.ArgumentException is thrown, and the implicit/explicite operator of the Wrapper<> was ignored.

I think it would help if the [TestInvoker](https://github.com/xunit/xunit/blob/4e39f2c784fae4e864c67743f825c5f811c04d42/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs) would call a function like this for all Testarguments
_static object Cast(object value, Type targetType) => Expression.Lambda<Func<object>>(Expression.Convert(Expression.Constant(value), targetType)).Compile()();_

Or is there any other way, I didn't get actually?

**Comment by bradwilson** [comment]
When **any of the theory data is not serializable**, it means we fallback to showing you just a single entry in the test method list for the theory, rather than an entry per theory data row. You won't be able to run an individual row of data; you'll have to run them all.

Here you can see that the theory with serializable data shows each individual data row, whereas the test with non-serializable data just show a single entry (which will run all the data):

![example](https://cloud.githubusercontent.com/assets/16944/12956466/0d51da96-cfdd-11e5-8b7b-7d3acf9bd24c.png)

**Comment by Ausm** [comment]
Sure, you are right, my fault, sorry for that stupid question...
Of course I can run them, but they appear as one test.
But I still have the problem, that I want an entry for each expression in my theory function ```TestExpression(Expression<Func<…>> exp)``` . I can’t make Expression<> implement IXunitSerializable because it’s provided by the Framework. So my idea was to write a class, which implements IXunitSerializable,  holds the expression object and has an explicit cast operator to convert to the expression object.
This all worked well, just the test runner doesn’t cast the given objects to the argument types. So I need to use the wrapper class in my test function, which I don’t want to.
My Idea is further to write a theory data class, which everyone can derive from, almost like the TheoryData<> class, but with the functionality, that it name the objects in it. Then you can use it, with complex, non serializable types, and the objects in the array are serializeable and appear as an test per entry in the theory data.

It’s difficult to explain, but much easier to show what the Problem is.
The following Test does not work.
```
public class ClassWithTheoryDataTypeDiffrentToArgumentType
{
	public class A { }

	public class B
	{
		public static explicit operator A(B value)
		{
			return new A();
		}

		public static explicit operator B(A value)
		{
			return new B();
		}
	}

	public static IEnumerable<object[]> Data = new[] { new object[] { new B() }, new object[] { new B() } };

	[Theory]
	[MemberData("Data")]
	public void Test(A x)
	{
	}
}
```
I forked the project, and made changes to fix this problem.
May I file a PR for that, or is this behaviour as designed?

**Comment by bradwilson** [comment]
I'm not 100% sure I know what problem you're solving here, so maybe the PR will help me understand what you're doing. :)

**Comment by Ausm** [comment]
I filed the PR, but some tests faild, so I dug deeper into.
Now I'm certain that it's a bug, and it's a bit apart from this issue.
So I will file a new one...

**Comment by Ausm** [comment]
@dealproc If you still have that problem, I maybe have a solution for you.
Have a look at this commit Ausm/ObjectStore@928e38f5d88182859160d5afda804feaff2f0f58
I implemented a ```IXunitTestCaseDiscoverer``` there which doesn't require discovered test case theory data to be serializeable.
The ```TheoryDiscoverer``` used the hash of the serialized arguments to determine the TestCase's UniqueID, my discoverer uses the key of the given data if ```Member/ClassData``` implements ```IDictionary<string, object[]>``` or the first parameters ```ToString()``` if it returns a unique string, or if both isn't the case then it uses the position of the datarow.
