### ISSUE TITLE
MissingMethodException on iOS/Android

### ISSUE THREAD

**Issue by onovotny** [xunit/xunit#556]
System.MissingMethodException: No constructor found for Xunit.Sdk.InlineDataDiscoverer::.ctor(Xunit.Sdk.TestFrameworkProxy+MessageS…

To repro, use the latest integration project and run everything on Devices.Android.

**Comment by bradwilson** [comment]
This is expected behavior.

We use `Activator.CreateInstance` when creating and caching all extensibility points in [ExtensibilityPointFactory.CreateInstance](https://github.com/xunit/xunit/blob/17f1ebc6ca93b4c6464e40dc37f1a4e8e6385eca/src/xunit.execution/Sdk/ExtensibilityPointFactory.cs#L17-L45). We call it twice: once with and once without a diagnostic message sink (since it's optional). What's being raised is the first innocuous failure, since InlineDataDiscoverer does not use the diagnostic message sink.

Since this is called from a PCL, we cannot use `Type.GetConstructor()` for us, so we rely on the implementation in `Activator`. You should be able to safely ignore this 1st chance exception.

**Comment by bitbonk** [comment]
This exception also occurs in a normal .NET 4.6 Desktop Environment (ReSharper runner). I think Xunit should never throw any first chance exceptions because it is getting very hard to debug unit tests when first chance exceptions are enabled in Visual Studio.

>System.MissingMethodException occurred
> HResult=-2146233069
>  Message=Constructor on type 'Xunit.Sdk.InlineDataDiscoverer' not found.
>  Source=mscorlib
>  StackTrace:
>            at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)

**Comment by bradwilson** [comment]
@bitbonk wrote:

>  I think Xunit should never throw any first chance exceptions

This is an impossible standard (for any library) and we have no intention of spending any time toward that goal. If you think you can solve particular problems, please send PRs.

**Comment by bitbonk** [comment]
Stupid me, I had "Enable Just My Code" disabled which caused exception notification for first chance excpetion outside of my code.
