### ISSUE TITLE
Can't use generic parameter type in Theory -- FormatTypeName null refs on generic parameters

### ISSUE THREAD

**Issue by nguerrera** [xunit/xunit#634]
Given the following, the 'Repro' test will fail due to a NullReferenceException in v2.1.0.

``` C#
public static readonly object[][] ReproData = new[] {
    new object[] { typeof(List<>).GetTypeInfo().GenericTypeParameters.First() },
};

[Theory]
[MemberData("ReproData")]
public static void Repro(Type type) {}
```

The issue appears to be here: https://github.com/xunit/xunit/blob/6c62c646ef19ae1fb938447805afd132fa90d966/src/xunit.assert/Asserts/Sdk/ArgumentFormatter.cs#L174

Regrettably, TypeInfo.FullName is null for type parameters.

**Comment by jongleur1983** [comment]
as far as I can see the problem is that `typeof(List<>).GetTypeInfo().GenericTypeParameters.First()`does return something like a Type placeholder, where TypeName is T, but FullName is null, as long as T is not set to a specific type.

Using `typeof(List<int>.GetTypeInfo().GenericTypeParameters.First()` works as expected of course.

I traced it down to an exception silently handled in TheoryDiscoverer.Discover, digging further now.

**Comment by jongleur1983** [comment]
MSDN agrees with the behaviour of https://github.com/xunit/xunit/blob/6c62c646ef19ae1fb938447805afd132fa90d966/src/xunit.assert/Asserts/Sdk/ArgumentFormatter.cs#L174 here: https://msdn.microsoft.com/de-de/library/system.type.fullname%28v=vs.110%29.aspx , describing the value of `TypeInfo.FullName` as
> The fully qualified name of the Type, [...]; or null if the current instance represents [...] a generic type that is not a generic type definition but contains unresolved type parameters.
This seems to be the case here, as `List<>` basically is `List<T>` with unresolved `T`.

Therefore the bug is in fact in the ArgumentFormatter that currently assumes the FullName to be set on any type it get's.

So how to deal with it?
I think `ArgumentFormatter.FormatTypeName(Type type)` should at least deal with this special case.

**Comment by jongleur1983** [comment]
locally I implemented tests covering that issue by directly invoking the ArgumentFormatter for unbound generic type arguments;
It would be easy to return the generic argument name in that case from `FormatTypeName()`; but as a result it would then return `typeof(T)` for a generic type argument that is named T, which seems not very useful at all.
So: what should be returned instead? anything like `typeof(?)` where `?` is replaced inside the brackets is easy to implement; but is it useful?

I'll open a pull request that does return typeof(T) for a generic argument named T for now.

any alternative solutions are welcome, and I'm fine with implementing them instead.
