### ISSUE TITLE
Launch Settings Environmental Variables for xunit dnx runner

### ISSUE THREAD

**Issue by aluitink** [xunit/xunit#643]
Hi, not sure if this is an xunit issue or a dnx issue.

With ASP.NET 5 xproj, you can use launchSettings.json to define env variables to be put in place during your tests.

I've not tried with any other test runners as xunit seems to be the only supported at this time.

``` json
{
  "profiles": {
    "test": {
      "commandName": "test",
      "environmentVariables": {
        "CassandraPassword": "yGCzwjw7x6GeUZN3",
        "CassandraEndpoints": "asdf",
        "CassandraUsername": "asdf"
      }
    }
  }
}
```

When a debug, a call to GetEnvironmentalVariable returns null, so it would seem like these EVs are not being set.

Is the runner responsible for setting these or is it DNX?

I would think DNX, but I'm able to get EVs when launching Kestrel, so maybe it is the host application that should be setting them.

Any thoughts?

Thanks.

**Comment by bradwilson** [comment]
I believe this to be an external bug (that is, one that should be logged against https://github.com/aspnet/Testing) since it's responsible for know about xproj files and launch conditions when tests are running inside of the Visual Studio test runner. The xUnit.net DNX runner should not have any Visual Studio-specific knowledge inside it.
