### ISSUE TITLE
Support running instances of the same data driven test (and I guess tests within the same test class) in parallel

### ISSUE THREAD

**Issue by johnlill** [xunit/xunit#648]
From http://stackoverflow.com/q/33072788/5357499 

As far as I can tell for the xUnit .net framework to run tests in parallel they must be in different test classes at a minimum, they must also be in separate test collections.

for example:

``` csharp
[Theory]
[InlineData(3)]
[InlineData(5)]
[InlineData(6)]
public void MyFirstTheory(int value)
{
    Assert.True(IsOdd(value));
}

bool IsOdd(int value)
{
    return value % 2 == 1;
}
```

This will run the test three times with the different data, but it will run in serial, I want the three tests to run in parallel.

**Comment by bradwilson** [comment]
Yes, this is a fundamental design decision in xUnit.net, that we don't plan to change.

**Comment by masaeedu** [comment]
So there is no way to work around this in xunit? Data driven tests are useful for cases where you have so many cases that it would be annoying to write a function for each. These are the very tests for which parallelism would be most useful, but you're saying it's an explicit design decision that these can't be paralellized, which doesn't make any sense to me.

Is there some other direction you might be willing to consider? Parallelization on static method tests perhaps?

**Comment by jnonce** [comment]
This is an issue for me as well.  I'm working in a system where I'm able to run about 50ish cases from data driven through a single function, but each test takes nearly 1sec.  Those, combined with a few other tests means that each run takes 60-70 sec.  My machine is mostly idle throughout.

Looking through the Core codebase I think I can appreciate how this would be difficult to address.  For my use cases though, it'd be worthwhile.  In general, the way parallelism works does seem to be the one blemish on an otherwise delightful framework.

@bradwilson could you comment on why this wouldn't be changed?  Is it not considered desirable?  Is it a backwards compatibility concern perhaps?  Or has it just not met the bar to be looked into right now (in favor of more pressing issues)?

**Comment by bradwilson** [comment]
This is never something we are going to support natively.

The extensibility APIs allow a third party to develop this capability and then ship and support it.

**Comment by jnonce** [comment]
Acknowledged.  I still don't understand why, but thanks for reading and responding.

For anyone else running against this, a workaround I'm trying out with some success so far is breaking the data into groups.  It's not clean, but seems to be enough for what I need right now.  General pattern shown below:

```cs
public abstract class DataScenario
{
    protected const int BatchSize = 20;

    public static TheoryData<string, string> Source =>
        new TheoryData<string, string>
        {
            // [Test data here]
        };

    public virtual Task Test(string input, string output)
    {
        // [Test code here]
    }

    public class GroupA : DataScenario
    {
        public new static IEnumerable<object[]> Source =>
            DataScenario.Source.Skip(BatchSize * 0).Take(BatchSize);

        [Theory, MemberData(nameof(Source))]
        public override Task Test(string input, string output) => base.Test(input, output);
    }

    public class GroupB : DataScenario
    {
        public new static IEnumerable<object[]> Source =>
            DataScenario.Source.Skip(BatchSize * 1).Take(BatchSize);

        [Theory, MemberData(nameof(Source))]
        public override Task Test(string input, string output) => base.Test(input, output);
    }

    // [and so forth]
}
```

(*I'll look into the extensibility APIs too, they're interesting.  Seems like there may be a way to get something here using a customized `TestFramework` + `XunitTestFrameworkExecutor` + `XunitTestAssemblyRunner` ...*)

**Comment by maxcherednik** [comment]
> Yes, this is a fundamental design decision in xUnit.net, that we don't plan to change.

Is it possible to read about this fundamental design decision? What was the reason behind, etc? Because to me, test methods are perfect candidates for a parallel execution - they share no state.
Or maybe there is a guideline which I am missing, something like one test method per test class?

Thank you

**Comment by bradwilson** [comment]
There is no documentation for this. These decisions were made between myself and @jnewkirk while developing.

**Comment by maxcherednik** [comment]
@bradwilson I see. Could you please share the thoughts you had that time? It's an interesting design decision - were you thinking it's going to be heavy to execute or something else? Some other place you mentioned that it was because a collection(test class with several test methods) share the state, but I don't quite see it, since a instance of the test class is created per test method.

Thank you

**Comment by bradwilson** [comment]
The design is such that parallelism happens on the "test collection" boundary, because that's where shared state happens. The smallest boundary we support for test collection by default is the class. It's documented here: https://xunit.github.io/docs/running-tests-in-parallel

As for why we designed it that way, the answer simply is: that's what we did. The decision was made half a decade ago, in the context of the best design for a unit testing framework.

**Comment by masaeedu** [comment]
@maxcherednik FWIW, I just switched to nunit, which now supports .NET Core and parallelism.

**Comment by janissimsons** [comment]
> As for why we designed it that way, the answer simply is: that's what we did. The decision was made half a decade ago, in the context of the best design for a unit testing framework.

Looks like it wasn't the best design choice after all.
Frankly, I don't understand how could you cripple the framework in such a way, the lack of parallelism for theories is a deal breaker. Data driven testing is impossible due to this - it is not feasible to run tens or hundreds of DD tests because they will take forever to finish and most of the time CPU will be just idling.

**Comment by chase-miller** [comment]
@bradwilson how do you recommend running data-driven tests in parallel with xunit? Is this possible today (either directly or via 3rd party extensions)?

**Comment by bradwilson** [comment]
There is nothing built-in that you can use. 3rd party solutions may exist, but I haven't researched them so I wouldn't know what to recommend.

**Comment by chase-miller** [comment]
> There is nothing built-in that you can use. 3rd party solutions may exist, but I haven't researched them so I wouldn't know what to recommend.

Thanks for getting back! I ended up using nunit. Using the `[FixtureLifeCycle(LifeCycle.InstancePerTestCase)]` attribute on a given test fixture class along with making it IDisposable makes nunit behave a bit more like xunit. Not exactly the same but getting there.
