### ISSUE TITLE
IAttributeInfo.GetNamedArgument throws ArgumentException instead of returning default(T)

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#668]
In an `IXunitTestCaseDiscoverer.Discover` method, when I call the `factAttribute`'s `GetNamedArgument<T>` method with an argument that cannot be found (as shown below) the method throws `ArgumentException`. It is documented to return `default(T)`, which would certainly be preferable in this case. 

```csharp
var skippingExceptions = factAttribute.GetNamedArgument<Type[]>("skippingExceptions");
```

In my particular repro, the attribute's constructor signature looks like this:

```csharp
public SkippableFactAttribute(params Type[] skippingExceptions)
```

**Comment by bradwilson** [comment]
This is working as designed, and is unfortunately confusing because of the naming xUnit.net used.

"Named argument" here refers specifically to the practice of setting properties via named arguments (i.e., `[MyAttribute(MyProperty = 42)]`). It was not meant to return constructor arguments, as it was used in the above example.

**Comment by AArnott** [comment]
Thanks.
