### ISSUE TITLE
Add support for dependency injection

### ISSUE THREAD

**Issue by inkadnb** [xunit/xunit#687]
It would be nice if xUnit natively supported constructor injection. I know there's [other projects](https://github.com/daniel-chambers/xunit.ioc) that extend xUnit to add support for constructor injection however there is a lot of extra setup. 

I believe it would be great if we could simply register an [IServiceProvider](https://msdn.microsoft.com/en-us/library/system.iserviceprovider_methods%28v=vs.110%29.aspx) with xUnit and have xUnit utilize that for constructor injection.

My current workaround is to use a Fixture to inject the DI container into the constructor, however it's less than ideal since I need to directly interact with the DI container in all my tests.

What's the teams opinion on supporting constructor injection?

**Comment by bradwilson** [comment]
We already use constructor injection for fixtures.

We have historically avoided full-fledged DI support inside the test framework itself, because it is a concern that is outside the framework. We feel this is better added via third party libraries like automatic mocking containers or automatic theory data providers.

**Comment by SharpNoiZy** [comment]
I also want to use Xunit with the new Microsoft DI system.
The only thing that should be supported is that I inject into the constructor of a CollectionFixture  IServiceCollection.

Would that be a hard one?

**Comment by SharpNoiZy** [comment]
The mentioned lib is outdated and just support xUnit 2.0.

**Comment by toddb** [comment]
@bradwilson I am back at this thread because I am wanting autofac support. I have looked at https://github.com/daniel-chambers/xunit.ioc/issues/6 that the RunWithAttribute is now obsolete. You talk about already having constructor injection for fixtures. Can you point me in the right direction on how in the new model/approach we would attain an equivalence to xunit.ioc. I am just trying to get a mental model of the direction and not work against it. When I get a solution, I will update this post and also cross reference to ioc thread! Cheers

**Comment by justsayno** [comment]
Am I correct in assuming if we want to do integration tests then we need to basically new up every dependency and its dependencies inside of a fixture? For example if I want to test e2e a function works WITH its dependencies then I cannot use any sort of dependency injection to avoid a whole lot of creation of the dependency tree's for each dependency?

**Comment by cherrydev** [comment]
No, you just need to create a fixture (I made an abstract one that can be customized for each DI scenario) that has a method on it that bootstraps your DI container.  Then make a base class for your tests that takes (as a generic type parameter that extends your abstract fixture class) your fixture as the constructor argument.  In your constructor, run the bootstrap method on your fixture and then you can either directly resolve your dependencies from the container root that you expose in your fixture, or have your container do property injection into your test class.  I'm using AutoFac, so in my base test class I call from my constructor:
```
this.Container = fixture.CreateComponentContext();
Container.InjectUnsetProperties(this);
```
Where `CreateComponentContext()` is a method that bootstraps your DI container and returns an `ILifetimeScope`.

The base test class then disposes the Container in its `Dispose()` method.

I do, however, think that it would be great if xunit directly supported the official MS DependencyInjection APIs in some manner, but strictly speaking it's not necessary.

**Comment by justsayno** [comment]
@cherrydev thanks heaps!

**Comment by inkadnb** [comment]
@cherrydev, agreed. I do not like property injection for various reasons
and would prefer constructor injection. I haven't seen any recent examples
of constructor injection using xunit.

Currently I'm using SimpleInjector but if the official Microsoft DI
containers are supported I'd be pleased with that too.

**Comment by mdissel** [comment]
any updates on supporting IOC?

**Comment by onovotny** [comment]
Couldn't IoC be done with a CollectionFixture to act as the bridge and supply the dependencies?

**Comment by veikkoeeva** [comment]
Cross-linking https://github.com/xunit/xunit/issues/988 since it might be of interest in this thread too.

**Comment by gitfool** [comment]
I do exactly what @cherrydev does with Autofac. I'd still prefer constructor injection though.

**Comment by veikkoeeva** [comment]
One way of achieving this would also be using the sample at https://github.com/xunit/samples.xunit/tree/master/AssemblyFixtureExample to create a single, assembly level fixture to hold the DI container and inject the dependencies in a like fashion from there, I suppose.

**Comment by gitfool** [comment]
A sample showing constructor DI for both test classes and fixtures would be really helpful. This is easier said than done since you need to know both the xUnit SDK quite well.

The container should be initialised once for the whole assembly and a new lifetime scope created and disposed per test (unit of work). ITestOutputHelper should also be registered such that a new instance can be resolved per test. Finally it should allow for full parallelisation of tests that support it.

It looks like @dennisroche is quite close with https://github.com/dennisroche/xunit.ioc.autofac, but in the Gitter channel he said he's abandoned this approach due to having issues.

**Comment by gitfool** [comment]
Oh and it needs it to work with different runners like the console runner and Resharper runner. 😜

**Comment by gitfool** [comment]
Finally, test classes and fixtures should be able to be oblivious to the container; i.e. the service locator anti-pattern should be avoidable, with dependencies being *injected* and not having to resolve them by interacting with the container. That said, the container should be available, again via injection, usually only needed to create nested lifetime scopes, but some containers like Autofac can still avoid this by using their awesome relationship zoo conventions.

**Comment by veikkoeeva** [comment]
@gitfool You are right and I set too an absolute tone on how I wrote my passage. This isn't that an easy thing to pull of. Maybe taking the assembly level sample and the assembly level fixture has a public property exposing the container from which one can resolved the dependency graphs explicitly (e.g. `container.Resolve<T>()`). Not ideal, but something to work with at least.

**Comment by SaltyDH** [comment]
I've been looking at DI with xunit for a little while now. My initial requirements were:

* Dependencies can be injected into the constructor of Test fixtures
* Dependencies can be injected into individual test methods
* Custom attributes are not necessary, [Fact] and [Theory] work like normal
* Works with dotnet test / dotnet xunit
* Works with R# test runner
* Works with dotnet core

I have an example of this working with xunit 2.3 beta with one caveat. I have an open pull request to give me the last bit of extensibility I need to make this happen. Its a non-functional change to xunit which provides a couple of virtual protected methods and members to make subclassing possible.

I was hoping if I posted here and got some traction behind the pull request, it might make it through :)

Xunit pull request: https://github.com/xunit/xunit/pull/1209

Example: https://github.com/SaltyDH/xunit/blob/example-autofac/samples/xunit.samples.autofac/UnitTest1.cs

**Comment by gitfool** [comment]
@SaltyDH Nice!! I presume it works with the popular containers including, my favourite, Autofac? 😉

I don't understand the need for method injection though. Test classes are created and destroyed for each test, which lines up nicely with ctor and property injection. What am I missing?

**Comment by SaltyDH** [comment]
@gitfool Hehe definitely early days. I haven't invested time in additional container support. Its really just a proof of concept at this stage. If the pull request goes through we can talk about multiple container support. For my team, Autofac is also our go-to DI container so that's been my primary (only) focus to date.

In terms of the method injection:-

At the time I dreamed up the requirements, I was considering a parent lifetime scope that would exist for the test class based on Type not instance with child lifetimes created for each individual test.

This would mean constructor injected dependencies are created once, the first time the test class is instantiated. While each test would create a new class instance (normal xunit behaviour), they would share a parent lifetime scope and thus can choose to share dependencies configured with the appropriate lifetime.

All of this is completely up in the air, very much open to thought and suggestion and completely dependent on the pull request being accepted :)

**Comment by gitfool** [comment]
@SaltyDH That's fairly twisted. xUnit has standard practices to use [Shared Context between Tests](https://xunit.github.io/docs/shared-context.html) and I wouldn't mess with that. Therefore, ctor / prop injection for class fixtures (for shared scope) and creating a lifetime scope per test with ctor / prop injection should be sufficient. Besides, method injection looks like and messes with parameterized theories!

**Comment by XdX-Software** [comment]
@gitfool No offence, but xunit DI system is bad, with attributes and empty fake classes...no, please real DI!

**Comment by bradwilson** [comment]
I will reiterate the point I made 18 months ago, which is still true today:

> We have historically avoided full-fledged DI support inside the test framework itself, because it is a concern that is outside the framework.

We have no plans of ever adding "full DI" to our unit test framework. We believe that this is a fundamental misunderstanding of the purpose of unit tests (in general) and unit test frameworks (in particular). If you want this, you should be using an auto-mocking system to create the class under test, which does not require any support from the unit testing framework.

**Comment by gitfool** [comment]
@bradwilson Fair enough. However, I think you're missing something.

We like xUnit to the degree that it made sense to leverage its familiar framework and runners to _also_ drive our _integration_ tests. Both Devs & QA love the consistency. As with unit tests we can drive them from within Visual Studio, with Resharper, and the commandline. This has been invaluable, but is obviously where we _heavily_ use DI.

For now we've got by with hacks, but I hope that you reconsider the _integration_ tests scenario one day.

**Comment by bradwilson** [comment]
We have consistently stated that, while integration testing is _**possible**_ with xUnit.net, it is not something we design for. Instead, we offer extensibility points which people can use to design an _**integration testing framework**_ that would be able to leverage the ecosystem of xUnit.net's test runner support.

**Comment by gitfool** [comment]
@bradwilson That sounds sufficient. If only someone with enough xUnit internals knowledge could help connect the dots.

**Comment by bradwilson** [comment]
There are examples of custom test frameworks out there, including:

https://github.com/xunit/samples.xunit/tree/master/ObservationExample
http://xbehave.github.io/

And I'm sure others...

**Comment by gitfool** [comment]
Thanks for the links. Maybe I'm asking for too much, but an "official" DI-specific example in [samples.xunit](https://github.com/xunit/samples.xunit) would be most helpful. (Others have been grappling with it for a while now.)

**Comment by SaltyDH** [comment]
@bradwilson could you please take a look at https://github.com/xunit/xunit/pull/1209 you mention existing extensibility points of xunit and this pull request only asks for some additional ones. DI is really only one use case this change would allow and the pull request doesn't specifically contain any DI related changes.

**Comment by SaltyDH** [comment]
Hi @bradwilson I realise that DI within a unit testing framework has some very polarising opinions and in a lot of ways I regret ever posting my solution here as I feel it has done an injustice to the hours spent coming up with a solution to our Integration testing needs. This will be my last post here on this GitHub issue. There are a number of other open issues which discuss the underlying problem I was trying to solve, hopefully the discussion can move there and focus on the merits of the pull requests changes detailed here:

https://github.com/xunit/xunit/issues/1119

> We have consistently stated that, while integration testing is possible with xUnit.net, it is not something we design for. Instead, we offer extensibility points which people can use to design an integration testing framework that would be able to leverage the ecosystem of xUnit.net's test runner support.

I would dearly love to develop an integration testing framework which leverages the xUnit ecosystem. To maintain maximum compatibility, I am requesting some visibility changes to certain members within the xUnit code base so that the appropriate extensibility hooks are present to allow for such a framework to be developed.

I'm hoping that I been able to communicate my perspective on this topic clearly enough that the pull request will be considered for its own merits and the specific discussion around dependency injection can be left at the door.

**Comment by weitzhandler** [comment]
I wish this is implemented.

**Comment by pete-restall** [comment]
I think this should do the trick, at least for xUnit 2:

[https://github.com/pete-restall/xunit.fixtureinjection/](https://github.com/pete-restall/xunit.fixtureinjection/)

And packaged:

[https://www.nuget.org/packages/xunit.fixtureinjection/](https://www.nuget.org/packages/xunit.fixtureinjection/)

Not the most elegant of solutions but it does what I need it to, anyway.  Enjoy.

**Comment by pengweiqhca** [comment]
https://www.nuget.org/packages/Xunit.DependencyInjection/

**Comment by Arash-Sabet** [comment]
@inkadnb Check this out as another solution: 
This open-source  project can help in leveraging Microsoft's DI in Xunit: https://github.com/Umplify/xunit-dependency-injection
