### ISSUE TITLE
Segfault under mono

### ISSUE THREAD

**Issue by stefansedich** [xunit/xunit#693]
I am currently working on getting the Akka.Net tests running under Mono, at the moment I am running this under Mono 4.3 as there are some things like IPAddress.MapToIPv4 that are not in the 4.2 release it seems (or I am just blind).

Now running the tests (using console runner version 2.1) it seems to get to the end of the test run and then segfault, output here: https://gist.github.com/stefansedich/bc8c1d3e9f88bc8d0f31

If I run the tests using -noappdomain it gets to the end of the test run and gives me the results as expected, is it expected that I need this option so that the tests run? Or is there something darker going on here? 

Happy to do what I can to help debug if this is the case, just wanted to see if I am missing something obvious here before I go digging too much further.

**Comment by mastoj** [comment]
I have a similar problem, but not sure if it is exactly the same. I thought I comment it here first instead of opening a new issue. I also added the output as a gist: https://gist.github.com/mastoj/1d6e03fa3b81da230c8b

My setup is a sample F# project where I use FAKE to build and test it. I'm using default FAKE params to xunit2, which should mean noappdomain. If you want to try it out you can clone this repo: https://github.com/mastoj/LibAAS and run `.\build.sh Ex4Done`.

**Comment by bradwilson** [comment]
You mention 2.1 of the console runner, but are you also running 2.1 of xUnit itself?

Also, if the repro is "this works on Microsoft .NET but not on Mono", then you should probably be posting the bug to the Mono team, not to us.

**Comment by stefansedich** [comment]
2.1 of both, I was mostly raising this to see if anyone was experiencing similar, as I am running happily using -noappdomain I will close this and if I ever get time look into it further and log a mono bug if it is indeed one.
