### ISSUE TITLE
Custom theory data attributes in PCL only work on desktop projects

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#705]
My Xunit.Combinatorial package doesn't work in UWP or WinRT test projects. I wonder if it only works on Desktop. It's just a simple portable project. Any idea why the tests aren't discovered when in a UWP context? https://github.com/AArnott/Xunit.Combinatorial/tree/uwptests

The Tests output window shows this, which mentions the tests that never show up in Test Explorer:
```
Test adapter sent back a result for an unknown test case. Ignoring result for 'UnitTest1.TestMethod1(hi: False)'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'UnitTest1.TestMethod1(hi: True)'.
```

The test cases produced by my attribute are quite stable. And desktop works fine, so even if they weren't stable, that may not explain why the problem only shows up for UWP.

**Comment by bradwilson** [comment]
You have two problems.

**First**, you have two versions of `xunit.runner.visualstudio` installed into your solution. The Visual Studio runner infrastructure cannot cope with this, and you get undefined discovery and execution behavior.

**Second**, your Xunit.Combinatorial project uses xUnit.net 2.0, but your UWP unit tests use xUnit.net 2.1 (which they must because of UWP support). UWP does not support binding redirects, and only places the 2.1.0 version of `xunit.core.dll` into the `.appxrecipe`, which means your extensions fail because they cannot load `xunit.core.dll` version 2.0.0.

If you update all projects to 2.1 all around, then everything works as expected.

![tests](https://cloud.githubusercontent.com/assets/16944/11610836/b7e8d88c-9b63-11e5-939a-a00408b90b47.png)

**Comment by AArnott** [comment]
Thanks, @bradwilson !
