### ISSUE TITLE
Test cases with discoverer in separate assembly are not executed unless test case inherits MarshalByRefObject

### ISSUE THREAD

**Issue by natemcmaster** [xunit/xunit#764]
Using xunit 2.2.0-beta1-build3239. 

Test cases using custom discoverers _in a different assembly_ are not recognized as discovered unless the test case inherits from `MarshalByRefObject`. Any test case that implements `IXunitTestCase` but fails to extend from `MarshalByRefObject` will disappear silently from discovery.

Setup:

```
X.Lib/
    CustomFactAttribute : FactAttribute
    CustomDiscoverer : IXunitTestCaseDiscoverer
    CustomTestCase : IXunitTestCase

X.Test/
    Test
         [CustomFact]
         ItWorks()
```

running xunit.runner.console on `X.Test.lib` will show no errors and not tests. The test case just disappears silently.

```
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: X.Test (app domain = on [shadow copy], method display = ClassAndMethod)
  Discovered:  X.Test (running 0 test cases)
=== TEST EXECUTION SUMMARY ===
   X.Test.dll  Total: 0
```

If CustomTestCase is changed in inherit from `MarshalByRefObject`, everything works:

```
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: X.Test (app domain = on [shadow copy], method display = ClassAndMethod)
  Discovered:  X.Test (running 1 test case)
  Starting:    X.Test (parallel test collections = on, max threads = 12)
   X.Test: Fake run
  Finished:    X.Test
=== TEST EXECUTION SUMMARY ===
   X.Test  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.098s
```

Repro here: [repro.zip](https://github.com/xunit/xunit/files/119926/dotnet-xunit.zip)

**Comment by bradwilson** [comment]
This is not a bug; this is a requirement for test cases.

https://github.com/xunit/xunit/blob/10ac1bc821b28f9cc310a9c448f173760f9b05d6/src/xunit.execution/Sdk/Frameworks/TestMethodTestCase.cs#L16

If you are really providing an implementation of `IXunitTestCase`, I would strongly recommend you use [`XunitTestCase`](https://github.com/xunit/xunit/blob/10ac1bc821b28f9cc310a9c448f173760f9b05d6/src/xunit.execution/Sdk/Frameworks/XunitTestCase.cs) as your base class rather than attempting to re-implement from scratch. There are a lot of extensibility points already available through that and `TestMethodTestCase`, including the required support for serialization of test cases.

**Comment by natemcmaster** [comment]
I understand the requirement for `MarshalByRefObject`. It's the silent, no-error disappearance of test cases that should be a bug.

**Comment by bradwilson** [comment]
Sorry, that wasn't clear. :)

**Comment by natemcmaster** [comment]
No worries. :)

**Comment by bradwilson** [comment]
Covered by #1492
