### ISSUE TITLE
By some reason the execution is failed.

### ISSUE THREAD

**Issue by xtrmstep** [xunit/xunit#782]
The project has tests that were correctly running. After updating to 2.1 the execution of some [Fact]s cause an error in the engine and the process fails with the message in output:

> The active Test Run was aborted because the execution process exited unexpectedly. The test execution process crashed while running the tests. To investigate further, open file:///C:/Users/.../vstest.executionengine.x86.exe.152.dmp file in Visual Studio and choose "Debug in mixed mode".
> The dump [vstest.executionengine.x86.exe.152.zip](https://github.com/xunit/xunit/files/146625/vstest.executionengine.x86.exe.152.zip)
> What can be a workaround? What has caused such effect?

**Comment by xtrmstep** [comment]
Found the issue. The code raises stack overflow exception. The exception is not propagated to VS and because of that there is no information about real cause.

**Comment by aboo** [comment]
We have the same problem as well. If we somehow change the grouping of the tests which I assumes changes the order of them running then all the tests will pass. This issue is very annoying and is causing us a lot of problems. 

Is there any fix for this? Or any way to find more information about what is causing the test runner to crash? /cc @bradwilson

**Comment by aboo** [comment]
FYI, I've upgraded to 2.3.0 beta 3 build 3705 and the issue is still there. Originally we developed the tests on 2.2 and had no issues until we crossed 800 unit tests. 

I downgraded to 2.1 and 2.0 and the issue didn't go away.

**Comment by bradwilson** [comment]
There's nothing we can do about stack overflows in your tests, so I'm not sure what you're asking for.

**Comment by aboo** [comment]
Is that a stack overflow? how can we be sure?

The unit tests run fine when run individually but if you couple two of them together the adapter will crash. The tests still show as passed. 

In that project we have over 900 unit tests and this problem only happens between 10 of them. It's very strange.

Any hint you could provide in terms of being able to diagnose the issue further is appreciated.

**Comment by bradwilson** [comment]
> We have the same problem as well. If we somehow change the grouping of the tests which I assumes changes the order of them running then all the tests will pass. This issue is very annoying and is causing us a lot of problems.

We run tests in random order, precisely for this reason: unit tests should be independent of one another, and therefore be able to be run in any order.

**Comment by bradwilson** [comment]
> Any hint you could provide in terms of being able to diagnose the issue further is appreciated.

Using a [configuration file](https://xunit.github.io/docs/configuring-with-json.html), you could disable parallelization to "fix" the problem. As for tracking down stack overflow problems, I honestly don't know what to recommend for that.

**Comment by aboo** [comment]
Thanks @bradwilson for the hints. Will look into the configuration. We've already disabled the parallelization by using CollectionAttribute.

One question,  could this potentially break the test executor/engine if a single unit test (a Fact) is very large (6 to 7 seconds to run including fire up the test server)? 

The reason I'm asking this is because we've used [PACT](https://github.com/SEEK-Jobs/pact-net) which is a BDD/CDD framework. Our Server test is basically one giant Fact with lots of assertions inside it. Using that technique our devs only need to write one unit test which will read a collection of requests and assert the responses. So basically that big Fact has lots of Shimming, Mocking, Shim.Reset, Re-Shim, Action, Assert (Header, Body, Status Code, etc.) and write the logs to files inside it. In my tests sometimes (very rare) even one of those tests will cause the test runner to crash. Any experience there?

**Comment by bradwilson** [comment]
> One question, could this potentially break the test executor/engine if a single unit test (a Fact) is very large (6 to 7 seconds to run including fire up the test server)?

No. There is no time limit for tests.

> In my tests sometimes (very rare) even one of those tests will cause the test runner to crash. Any experience there?

Is the test async? In my experience, a mocking framework which is not async-safe will cause all kinds of weird crashing...and no, thread-safe is not necessarily good enough, because after each `await` statement, your test may be running on a different thread. A mocking framework which uses thread locals for "thread safety" is not async safe.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by soeron** [comment]
@aboo Have you found the cause of this behavior since I am experiencing it too. Strangely installing W10 on VM with fresh VS2017 doesn't gives me any problems.
