### ISSUE TITLE
Ability to force color output on xunit.console

### ISSUE THREAD

**Issue by Eibwen** [xunit/xunit#783]
I have xunit.console running as part of a much longer build process.  Therefore i would like to output it as it runs (instead of seeing zero output for 1 minute) in color, but also pipe the output to a variable (that supports the color codes) to be displayed later.

When redirecting the output, the console runner defaults to `nocolor`.  I tried adding the flag `-nocolor=false` but it doesn't recognize that format at least.

**Comment by bradwilson** [comment]
You've asked for two things, neither of which is under our control.

1. When you pipe output in Windows, it is buffered by the system. We have no control over this behavior.

2. When you pipe output in Windows, it ignores/strips all color, because the Windows console system does not use character output to control control; therefore, it has no way to preserve the color in a meaningful way once you've decided to pipe the output.

**Comment by Eibwen** [comment]
I'm actually using it inside a rake script, so ruby is doing the piping, which i presume would preserve it, when binary reading is enabled:

      IO.popen("#{testsCommand}", "rb") {
        |io| while (line = io.gets) do
          puts line
        end
      }

I presumed it was your detection of build servers that was doing it... it could be the `puts` command i suppose

**Comment by bradwilson** [comment]
On Linux, colors are typically done with ANSI codes, which are printed to the output.

On Windows, colors are a direct feature of the console window. They are NOT part of the output stream, and therefore not captured during any form of redirection.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by mvestergaard** [comment]
@bradwilson I know this issue has been closed, but I'm wondering whether there may be a way to make this work.

In my team we're running builds through GitLab CI, which requires ANSI coloring for colored log output. It would be nice to easily be able to find the test failure in the log by color.

The MSBuild output works because of the `/clp:forceconsolecolor` flag, which appears to toggle ANSI coloring on https://github.com/Microsoft/msbuild/blob/master/src/Build/Logging/ConsoleLogger.cs#L144

Couldn't xunit do something similar?

**Comment by mvestergaard** [comment]
Yea exactly, that's why it seemed pretty easy to implement, by introducing a flag. Our CI servers are on windows, so they don't use it.

Too bad that it has to wait till 3.0. I can imagine it is quite a ways off, based on prior release cadence.

**Comment by perlun** [comment]
@mvestergaard Did you investigate this further? I am using xUnit.net using GitHub Actions, running the tests on Linux - I would _love_ to be able to force color there. It's really very boring to see the test outputs in black and white when it e.g. uses nice, red colors for failures when running locally.

If not for anything else, it could be worth putting this on the v3 roadmap: https://github.com/xunit/xunit/issues/2133

**Comment by SuperJMN** [comment]
Any news on this?

**Comment by bradwilson** [comment]
@SuperJMN Honestly, it's been closed for a long time, but given how quick it would be to change, I'm going to go ahead and add a switch to the console runner.

**Comment by bradwilson** [comment]
Available in v2 `2.7.2-pre.21`
Available in v3 `0.1.1-pre.404`

https://xunit.net/docs/using-ci-builds

I've captured some output both to file and piped through `less -R` to ensure that the colors are showing up, and they do.

Sample output without the new switch:

`xunit.console.exe test.xunit.assert.dll | less -R`

![image](https://github.com/xunit/xunit/assets/16944/96e8e240-d0e8-49eb-912e-998ea1b2f2b5)

Sample output with the new switch:

`xunit.console.exe test.xunit.assert.dll -useansicolor | less -R`

![image](https://github.com/xunit/xunit/assets/16944/6755ba6d-2ec4-430c-86b4-39a07079318a)

Using the flag in a CONHOST-hosted command prompt, you'll see the raw ANSI codes, since CONHOST does not support that; Windows Terminal, on the other hand, will properly handle ANSI color codes. The above two screenshots were taken in Windows Terminal, whereas this one was taken in CONHOST:

![image](https://github.com/xunit/xunit/assets/16944/bea465c1-9753-405a-a61a-c69a09f69574)
