### ISSUE TITLE
Culture and async behavior in .NET 4.6

### ISSUE THREAD

**Issue by mono-software** [xunit/xunit#789]
The sample from this article (section "How a Thread's Culture Is Determined")

https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.currentculture(v=vs.110).aspx

runs successfully in the console app. When the same sample is run from the xUnit test (target framework also .NET 4.6), the culture is not preserved.

**Comment by bradwilson** [comment]
From the linked site:

> In the .NET Framework 4.5.2 and earlier versions, the CurrentCulture property is read-only; that is, you can retrieve the property value, but you cannot set it. To change the current culture, you assign the CultureInfo object that represents the new culture to the Thread.CurrentThread.CurrentCulture property. Starting with the .NET Framework 4.6, the CurrentCulture property is read-write; you can both set and retrieve the property's value. If you do set the property value to a CultureInfo object that represents a new culture, the value of the Thread.CurrentThread.CurrentCulture property also changes.

Inasmuch as xUnit.net uses culture at all, it does so via the 4.5 APIs. We have no control over the 4.6 behavior since we're not written against 4.6.

Please provide a repro and I'll see if there's anything we can do.

**Comment by onovotny** [comment]
This UseCultureAttribute might help?

https://github.com/Humanizr/Humanizer/blob/dev/src/Humanizer.Tests.Shared/UseCultureAttribute.cs

**Comment by mono-software** [comment]
Consider the following two samples:

SAMPLE 1:
```cs
Theory]
[InlineData("en-US")]
[InlineData("en-GB")]
public async void Should_culture_be_propagated_accross_async_await_as_in_dotnet_4_6(string culture)
{
	Thread.CurrentThread.CurrentCulture = new CultureInfo(culture);
	await Task.Run(() =>
	{
		Assert.Equal(culture, Thread.CurrentThread.CurrentCulture.Name);
	});
}
```

SAMPLE 2:
```cs
Theory]
[InlineData("en-US")]
[InlineData("en-GB")]
public async void Should_culture_be_propagated_accross_async_await_as_in_dotnet_4_6(string culture)
{
	Thread.CurrentThread.CurrentCulture = new CultureInfo(culture);
	await Task.Run(() =>
	{
		//run some task
	});
	Assert.Equal(culture, Thread.CurrentThread.CurrentCulture.Name);
}
```

Assuming that the "en-US" is the default culture, both samples will currently fail for the "en-GB" culture. They should both work in .NET 4.6.

There are workarounds and no, the suggested UseCultureAttribute is not one of them, it does the same thing as setting the culture manually at the beginning of the test, it doesn't propagate it.

The workarounds I've found are:

1) Setting CultureInfo.DefaultThreadCurrentCulture instead of Thread.CurrentThread.CurrentCulture - both samples will work, but this is not compatible with running series of tasks with different cultures at the same time. As long as a single culture is required during a single test, this may be good enough.

2) Using custom synchronization context like the one here http://stackoverflow.com/a/30665384. This will however work with sample 2, but not with sample 1, so it will propagate the culture only to the continuation code, which again may be good enough if only true async is used.

I can live with the workarounds, but just wanted to see if in the future I'll be able to rely on xUnit tests producing the same behavior as if the code was executed in, for example, a .NET 4.6 console app.

**Comment by jasmh** [comment]
Hi, I think I found what's wrong and how to fix it, but I still don't understand why it happens. From .NET 4.6 mscorlib viewed in reflector - `System.Threading.Thread.CurrentCulture` property setter:

```
...
if (!AppContextSwitches.NoAsyncCurrentCulture)
		{
			if (Thread.s_asyncLocalCurrentCulture == null)
			{
				Interlocked.CompareExchange<AsyncLocal<CultureInfo>>(ref Thread.s_asyncLocalCurrentCulture, new AsyncLocal<CultureInfo>(new Action<AsyncLocalValueChangedArgs<CultureInfo>>(Thread.AsyncLocalSetCurrentCulture)), null);
			}
			Thread.s_asyncLocalCurrentCulture.Value = value;
			return;
		}
...
```

This means that culture flows with async context only if the `AppContextSwitches.NoAsyncCurrentCulture` is set to false. That class is internal , but further investigation shows that the `AppContext` static constructor populates several internal .NET framework switches and `NoAsyncCurrentCulture` is one of them. The key logic is in another internal class `AppContextDefaultValues` and its `PopulateDefaultValues` method. It determines envirnment framework version and if it's lower or equal to 40502, then it disables the async culture behavior. Here's the part that I don't understand:

1) My library project's target framework is 4.6
2) My xUnit test project which tests the library has its target framework also as 4.6
3) The framework reported during the test's runtime is 4.5, which causes that invalid culture behavior switch

The fix is easy, one just has to put this in the test or the test fixture:

```
AppContext.SetSwitch("Switch.System.Globalization.NoAsyncCurrentCulture", false);
```

I still don't understand the incorrect reported version, but I suspect it may have something to do with the xUnit Visual Studio runner and the fact that it is compiled against the 4.5 framework. If one wants to test the internal code which reports the compiled framework version, it can be achieved with this code:

```
delegate void ParseTargetFrameworkName(out string identifier, out string profile, out int version);
ParseTargetFrameworkName parseTargetFrameworkName;

public void SomeMethod()
{
	string platformIdentifier;
	string profile;
	int version;
	var type = typeof(AppContext).Assembly.GetType("System.AppContextDefaultValues");
	parseTargetFrameworkName = (ParseTargetFrameworkName)Delegate.CreateDelegate(typeof(ParseTargetFrameworkName), null, type.GetMethod("ParseTargetFrameworkName", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic));
	parseTargetFrameworkName(out platformIdentifier, out profile, out version);
	...
```

I hope this helps and also that it will be fixed when xUnit is compiled in 4.6. When is that expected btw?

**Comment by bradwilson** [comment]
The incorrect reported version is almost assuredly because it's based on the entry process, not on your unit test library. The xUnit.net runners are all built against 4.5, not 4.6.

**Comment by stefanhendriks** [comment]
I have multiple tests running against multiple `CultureInfo` settings, they each set the CultureInfo, but because they run in parallel they conflict with each other. Using the stackoverflow reference that @mono-software gave I was able to fix this. It would be very nice if somehow this would work out of the box somehow.

**Comment by bradwilson** [comment]
Closed for age.
