### ISSUE TITLE
Is there a way to skip an entire test class in v2

### ISSUE THREAD

**Issue by gdennie** [xunit/xunit#791]
My tests are organized into classes. One particular class is devoted to exploring and confirming the behaviour of the infrastructure. Some of these tests are very expensive and I would like to perform them sparingly. Consequently, I would like to exclude that class from normal test runs.

Making the test class constructor `private` does not work. The test methods report as failed tests with the message: **A test class may only define a single public constructor.**

**Comment by bradwilson** [comment]
Sorry, this feature doesn't exist today.

**Comment by Schaeri** [comment]
We also have the need to skip a whole test class. Because we use xUnit not only as unit test framework. We use xunit also as a integration test framework. When writing the test code before the productive code it is sometimes helpful to ignore a whole test. There are workarounds for the missing feature like a custom test discovery (with own fact attribute) or the exclude via trail attribute. But this workarounds have all disadvantages. 

@bardwilson if I would implement a way to set the fact skip reason via a class attribute and create a pull request for this feature. Does it have a change to be included in a next xunit release?

Thanks for the help.

**Comment by matkoch** [comment]
@bradwilson I think a dedicated `SkipAttribute` would be nice to have. I know that there exists a property on the `FactAttribute`, but what is really an issue here I think, is that you can't configure coverage tools to exclude those tests from their analysis.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by leo-ridgewood** [comment]
I too have some test classes that are very expensive to run and are normally disabled but which I occasionally enable and run manually.

My workaround used to be to be to comment out the "public" in the class definition. This is no longer possible: https://xunit.github.io/xunit.analyzers/rules/xUnit1000

My workaround is now to comment out "using xunit" and create an nested class "FactAttribute". I don't want to disable in the pre-processor because I want to ensure they keep compiling.

**Comment by marcind** [comment]
Have you considered putting these expensive tests in a different project? Assemblies are a supported way of dividing and grouping tests.

**Comment by r-pankevicius** [comment]
I found a hack for Fact-s: https://stackoverflow.com/a/48282025/1175698

**Comment by ReneCode** [comment]
today there is a solution:

     [Fact(Skip="reason")]

**Comment by gdennie** [comment]
Unit testing facility has broad utility including experimentation, production environment setup or verification, reporting, etc. Things quite separate from target program requirements and which you would want to selectively exclude or include in a test run independent of performance hit.

Consequently, it seems one approach could be to simply provide a test categorizing system and the ability to invoke test belonging to one or more categories. That is, each test method and test class may be associated with one or more categories such as by a space or comma delimited list of words to the SKIPPABLE property wherein each unique word is implicitly a distinct category. 

Presently, we might regard the existing testing system as being able to assign tests to only three categories: specification, runnable, not_runnable. Additionally, all tests belong to specification.

**Comment by ilya-chumakov** [comment]
I still miss this short and simple feature because R# ignores "Skip tests from categories" settings (and it has been doing that for years).

**Comment by niwrA** [comment]
I also don't understand why I have to manually do this for every test in a test class ...

**Comment by lauxjpn** [comment]
As far is I know, the simplest way to dynamically skip a whole xUnit test class at runtime is to use the `TestFrameworkAttribute` at the assembly level, to point to a class that implements the `ITestFramework` interface (or inherits from `XunitTestFramework`, which is simpler) and which overrides the `CreateDiscoverer()` method to return another class, that implements the `ITestFrameworkDiscoverer` interface (or inherits from `XunitTestFrameworkDiscoverer`, which is simpler), where you can finally override the `IsValidTestClass()` method, to decide whether a class should be skipped or not.

Here is some sample code:

```c#
[assembly: TestFramework("MyNamespace.Xunit.MyTestFramework", "MyAssembly")]

namespace MyNamespace.Xunit
{
    public class MyTestFramework : XunitTestFramework
    {
        public MyTestFramework(IMessageSink messageSink)
            : base(messageSink)
        {
        }

        protected override ITestFrameworkDiscoverer CreateDiscoverer(
            IAssemblyInfo assemblyInfo)
            => new MyTestFrameworkDiscoverer(
                assemblyInfo,
                SourceInformationProvider,
                DiagnosticMessageSink);
    }

    public class MyTestFrameworkDiscoverer : XunitTestFrameworkDiscoverer
    {
        public MyTestFrameworkDiscoverer(
            IAssemblyInfo assemblyInfo,
            ISourceInformationProvider sourceProvider,
            IMessageSink diagnosticMessageSink,
            IXunitTestCollectionFactory collectionFactory = null)
            : base(
                assemblyInfo,
                sourceProvider,
                diagnosticMessageSink,
                collectionFactory)
        {
        }

        protected override bool IsValidTestClass(ITypeInfo type)
            => base.IsValidTestClass(type) &&
               FilterType(type);

        protected virtual bool FilterType(ITypeInfo type)
        {
            // Insert your custom filter conditions here.
            return true;
        }
    }
}
```

Tested with xUnit `2.4.1`.

**Comment by FelixDamrau** [comment]
Thanks for the suggestion lauxjpn. This works in principle, but then the tests no longer appear in the test explorer as "skipped". Therefore I find the solution not perfect. 
But better than manually marking n tests as "skipped".

**Comment by NonlinearFruit** [comment]
Here is my work-around. It isn't at the class level (and doesn't easily work for Theories), but it does:
- Skip the tests when TDD-ing in the IDE and
- Allows you to run the tests in your CI/CD pipeline and
- Is pretty minimal

It is a custom FactAttribute that checks an environment variable. If true, skip

```csharp
public class ContinuousIntegrationOnlyFactAttribute : FactAttribute {
    private const string IncludeContinuousIntegrationTests = "IncludeContinuousIntegrationTests";

    private static readonly bool ShouldIncludeContinuousIntegrationTests =
        bool.Parse(Environment.GetEnvironmentVariable(IncludeContinuousIntegrationTests) ?? $"{false}");

    public ContinuousIntegrationOnlyFactAttribute() {
        Skip = ShouldIncludeContinuousIntegrationTests
            ? null
            : $"Run with `dotnet test -e {IncludeContinuousIntegrationTests}={true}`";
    }
}
```

When you want to run the tests in the IDE, add the environment variable to the [Test Runner Settings](https://www.jetbrains.com/help/rider/Reference__Options__Tools__Unit_Testing__Test_Runner.html#environment-variables) (Rider) or [modify the .runsettings(?)](https://stackoverflow.com/a/65667188/4769802) (VS)

**Comment by lauxjpn** [comment]
@FelixDamrau For a more elaborate implementation, that dynamically controls what is skipped and what isn't, see the 
 [implementation](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/tree/fa6f54caa487f0d7635229b9984d474f2836ad15/test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit) we use in our test suite (that will even decide after running a test, whether it should be considered skipped or not).

**Comment by belav** [comment]
It is unfortuante that I need to add custom code to easily skip a whole class of tests. There are plenty of reasons we have needed to do this.

1. When starting to multitarget our project, the tests weren't passing in net8 yet, so we wanted to skip them for now and come back to them later.
2. Something makes it into the main branch and causes tests to fail, we want to quickly skip the tests in a class, merge that change and come back to them later.
3. The tests that were implemented work just fine locally, but for some reason aren't working in our GH action, we want to skip running them for now and come back to them later.

The custom XunitTestFramework + a custom Attribute is what I went with. But it would be nice if this was just build in, and trying to run the skipped test would show the reason that was added for why we are skipping. This feature has been in nunit for as long as I can remember.

**Comment by bradwilson** [comment]
> It is unfortuante that I need to add custom code to easily skip a whole class of tests.

I have two answer for why this is the case.

1. As a framework that is "unit tests first, everything else second" in design, we don't believe that unconditionally skipped tests are a good thing; they should be temporary. Adding functionality for that scenario isn't a high priority. I am shocked to discover that this has been such a huge problem for you on so many occasions (where you couldn't just, say, comment out of the test class instead) that it makes me wonder why.

2. We don't have any kind of attribute on test classes by default. There's nowhere to attach a Skip property off of. Creating an entirely new [Skip] attribute, even if answer 1 above wasn't true, would be something we would definitely not want to do, because it would create a dichotomy between skipping tests vs. test classes.

**Comment by belav** [comment]
>  I am shocked to discover that this has been such a huge problem for you on so many occasions (where you couldn't just, say, comment out of the test class instead) that it makes me wonder why.

I didn't say it is a huge problem. Someone in this issue was asking for reasons why someone would skip an entire class worth of tests and I provided some of the reasons that I've run into. 

Commenting out the entire class is a poor workaround.

If I use single line comments it would be easy to do in the IDE, but the diff on that file would be obnoxious. If I use multiline comments and the file already has multiline comments then it is going to be a pain in the ass. 

Not to mention devs may be changing the codebase in ways that introduce compilation errors in the commented out code. There is also no visibility into tests that are skipped because they are commented out. All the test runners I know of provide information for skipped tests. And you can also search your codebase to find skipped tests based on the attribute/property that skips them.

I added a custom skip attribute which solves my problem except that it doesn't provide the skip reason to any test runners. And because it is non-standard other devs on my team won't know about it unless it is communicated or they run into it existing.

> Creating an entirely new [Skip] attribute, even if answer 1 above wasn't true, would be something we would definitely not want to do, because it would create a dichotomy between skipping tests vs. test classes.

I don't see the issue with a skip attribute for a class. If a test is in a class with the skip attribute, then it is skipped. If the test has a skipped property set, then it is skipped. If it has both then I assume the reason provided by the skip property would show up in a test runner as opposed to the skip reason on the class. Or maybe both reasons show up. Either way it is still skipped.

I can understand it not being priority, but there doesn't seem to be a good reason to say "no we won't do this" when there is clearly interest in it, and are valid use cases for it.

**Comment by bradwilson** [comment]
> there doesn't seem to be a good reason to say "no we won't do this" when there is clearly interest in it

This truth is, we say this all the time. We consider xUnit.net to be opinionated: we have design goals in mind, and priorities to consider when evaluating feature requests. This is not a design we would ever encourage (long term skipping of an entire test class), so enabling it is not something we would do. This what the crux of my first point in the reply. I suppose it's my fault adding a second point when I do not ever anticipate being moved off my first point.

**Comment by belav** [comment]
> This truth is, we say this all the time. 

Yeah thinking about it after I sent the response my thought was "really, the reason can just be 'We don't want to do this' " because at the end of the day it is your project.

Are you opposed to a contribution that adds the ability to skip classes? I was poking around in the source and I don't think it would be straightforward to do. Plus I feel that if it is added then it should support everything like `SkipUnless` and `SkipWhen`, and not just be a basic attribute like I added to our code base. Which then leads to questions such as "what if SkipUnless is set on the class and SkipWhen is set on the method"

So...... I don't know that I'd actually find the time to do it.

**Comment by bradwilson** [comment]
FWIW, you can do this in v3 just by doing `Assert.Skip()` in your test class constructor.

**Comment by webczat** [comment]
so what's a normal way of splitting unit and integration tests? I have a project for the latter. but they're in same solution, so they would actually run.

**Comment by bradwilson** [comment]
In the xUnit.net codebase itself, we don't split them.

In the past, I have had teams split them into separate assemblies, then use the mechanism in the IDE to unload the integration test assemblies so that they wouldn't build and wouldn't show up in the test list.

I think with v3 I'd suggest keeping them together but marking the integration tests with `Explicit = true`, and then using command line switches when running tests to ensure that both explicit and non-explicit tests are run (`-explicit on` for `xunit.v3.runner.console`). In the IDEs, without a command line, we use a simple heuristic to determine when to run explicit tests (we only run explicit tests when the entire list of tests to run only contains explicit tests, since we assume the most common gesture would be to run a single explicit test explicitly). That may make it difficult to run them all together in the IDE (depending on how easily you can isolate the integrate tests with Test Explorer's groupings, like putting all integration tests into a single namespace), so I think it's a balancing decision to use combined + explicit vs. separated + unloading.

**Comment by webczat** [comment]
first, I can isolate by project there. If I load all projects, vscode test explorer and vs test explorer too I think group tests by project first.
My problem here though: how to make all tests in assembly explicit? or at least the easiest way to make a fact/theory attribute that just does it for me so that i can't forget.

**Comment by webczat** [comment]
also is that specific to ides? if I use a filter in cmdline so that only tests  that are explicit get selected, then run that without -explicit on/only, which will be run? explicit or none? would be a very useful shortcut.

**Comment by bradwilson** [comment]
> also is that specific to ides?

The "guessing" for explicit tests lives in [`xunit.runner.visualstudio`](https://github.com/xunit/visualstudio.xunit/blob/50e68bbb8b9ddd4b1bbb95d062b62010caf99909/src/xunit.runner.visualstudio/VsTestRunner.cs#L384) (for VSTest) and [`xunit.v3.runner.inproc.console`](https://github.com/xunit/xunit/blob/9214bef1544142cc520bf37a9b4f655aaabfdb0f/src/xunit.v3.runner.inproc.console/Utility/ProjectAssemblyRunner.cs#L272-L299) (for MTP). It is never does when running projects directly or with first party runners like `xunit.v3.runner.console` or `xunit.v3.runner.msbuild`.

Technically, this isn't specific to IDEs, but rather to running things with VSTest or MTP, so you can put yourself into a situation where you've used `dotnet test` and filters that end up only picking explicit tests, and they should run in that situation; I've never tested this scenario, but I don't see why it wouldn't work, since it doesn't matter to the runners how the list of tests were arrived at (via the Test Explorer UI or via a filter).

> if I use a filter in cmdline so that only tests that are explicit get selected, then run that without -explicit on/only, which will be run?

The answer is "it depends on the runner", as mentioned above. For a first party runner, filtering does not change the explicit run behavior. The reason we "infer" when using VSTest or MTP is because _there is no UI gesture in Test Explorer nor command line switch for `dotnet test` that supports explicit tests_, so we have to guess on your intent based on what you asked to run.

Our first party runners don't have this problem. We have `-explicit <option>` (`xunit.v3.runner.console`) or `Explicit='<option>'` (`xunit.v3.runner.msbuild`) options for:

* `off` (only run non-explicit, the default)
* `on` (allow both explicit and non-explicit)
* `only` (only run explicit)

If you're using one of these first party runners and want to only run explicit tests, you don't need a filter; you just use the `only` option and it will not run any non-explicit tests.

**Comment by webczat** [comment]
I potentially have more than one category of explicit tests. I mean I am building a library and want to test things that require actual user interaction like something that starts with oauth flow which can't be fully automated. Unsure how to do it except another category of explicit tests or making a separate project just for myself that's a test app. So that's why I asked.
