### ISSUE TITLE
Adding Trait to CollectionDefinition

### ISSUE THREAD

**Issue by xmedeko** [xunit/xunit#799]
In xUnit and Visual Studio, I would like to group tests marked with the `[Collection("DB")]` attribute in the _Test Explorer_. I can group test by the `[Trait("Collection", "DB")]` attribute only. Is there any way how to assign a specific `Trait` to all tests with the `[Collection("DB")]` attribute?
(I have also [asked on SO](http://stackoverflow.com/questions/35936671/xunit-adding-trait-to-collectiondefinition)).

**Comment by jchannon** [comment]
This is something I now need, I have some tests in my project split into those that have state and those that don't. These are marked with the Collection attribute. It would be nice to run them such as `xunit.console.exe My.dll -collection mycollection`

**Comment by zwcloud** [comment]
One implementation I found: http://mac-blog.org.ua/xunit-category-trait/

**Comment by xmedeko** [comment]
@zwcloud it's a bit simplification of the problem, but does not solve that. Now, I have to mark a method
```c#
[Trait("Collection", "DB")] 
[Collection("DB")]
```
With your solution, I would do
```c#
[Category("DB")] 
[Collection("DB")]
```
But I would like to use `[Collection("DB")]` only and have it automatically added to a `Trait`.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by TheConstructor** [comment]
@bradwilson this is still not possible, right? To me it would also be ok, to just have the collection-name added as collection trait

**Comment by bradwilson** [comment]
@TheConstructor That is correct, this is not a feature.

If someone wanted to create a PR for this, I wouldn't want to add an automatic trait for every collection, because you potentially run afoul of someone already using a trait named `Collection` (or whatever name you chose), and some people wouldn't want the additional noise of the extra trait.

I would be willing to accept a PR that adds traits to tests based on putting trait attributes on the collection definition class itself. That would allow people to add whatever traits that wanted (names and values) in a central location.
