### ISSUE TITLE
xunit.console.exe in .xproj

### ISSUE THREAD

**Issue by justinyoo** [xunit/xunit#809]
Hi, Team.

I have an ASP.NET Core library targeting DNX451, DNXCORE50 and NET451. Within command-line prompt, I'm able to run `dnx test` to target DNX451 and DNXCORE50. Unfortunately, as NET451 is not DNX, I can't run `dnx test` for it.

Instead, I run `xunit.console.exe MyProject.Test.dll` for NET451 from my `.xproj`. Of course it can't be run as it requires all package dependencies. Basically `.csproj` copies all relevant .dll files into `/bin/Debug/net451` so that `xunit.console.exe` can run without an issue. On the other hands, `.xproj` doesn't copy all package dependencies into `/artifacts/bin/MyProject/Debug/net451` so I can't run `xunit.console.exe`.

Is there any way to copy all dependencies so that `xunit.console.exe` can run as expected, or another way to run test runner targeting NET451 on .xproj in command-line?

Cheers,

**Comment by bradwilson** [comment]
This is not a supported scenario.

The .xproj build system does not correctly copy the dependency DLLs when it does a build (like the old build system did), so the DLL that's left on disk cannot be correctly loaded because it's missing all of it's dependencies (not to mention we can't find the xunit.execution.* DLLs that are required to run correctly). This isn't an issue in DNX because they have their own loader which will load the dependencies from a different location other than the bin folder, but this behavior by definition cannot be made to work on the desktop console runner, which knows nothing about .xproj or dependency resolution.

**Comment by justinyoo** [comment]
@bradwilson Thanks for the clarification.

What I understood from your comment is that basically there's no way to run the test runner (`xunit.console.exe`) on `.xproj` targeting `NET451`.

Actually, I succeeded in executing `xunit.console.exe` once I manually copied all dependencies from `%USERPROFILE%\.dnx\packages\` to the directory `\artifacts\bin\MyProject.Tests\Debug\net451\` where my `MyProject.Tests.dll` is located. Therefore, once we have a tool that copies all dependencies into the artifacts directory, I suspect that it wouldn't be an issue.

**Comment by bradwilson** [comment]
> What I understood from your comment is that basically there's no way to run the test runner (xunit.console.exe) on .xproj targeting NET451.

That is correct (today). The ability of .xproj to target non-DNX things is a bit of a degenerate case; that is, they sort of made it work, but it's nothing like the normal MSBuild-based project system, and has many caveats, this being one of them.

Note that UWP has the same problem (.csproj + project.json) as .xproj, except in that case, there are flags you can add to the .csproj file that will make the reference copies happen. AFAIK, there is no such capability available to .xproj. /cc @davidfowl @onovotny

> Therefore, once we have a tool that copies all dependencies into the artifacts directory, I suspect that it wouldn't be an issue.

It's not clear to me whether "dotnet compile" will do this in the future, since we haven't had a stable release yet, but from what I've seen so far, reference copying is nothing something that's being done by default. Maybe they'll have a project.json-flag or a command-line flag to get references copied.

**Comment by justinyoo** [comment]
@bradwilson Yep, that perfectly makes sense to me.

If your `.xproj` targets both DNX and non-DNX, how do you test it on the non-DNX side, by the way? When I see Json.Net repo, it uses a different approach - xUnit for DNX and NUnit for non-DNX. But I'm not convinced this is a right(or proper at least) way. Sorry for mentioning a different testing framework here.

**Comment by bradwilson** [comment]
I honestly never do that, for just this reason. I only use .xproj for DNX. I use shared code and standard .csproj class libraries when I need to target multiple frameworks (or a PCL).

**Comment by justinyoo** [comment]
Thanks!
