### ISSUE TITLE
Should be able to Cancel ordered tests collection run on first fail

### ISSUE THREAD

**Issue by DmitriySokhach** [xunit/xunit#856]
### Description:

I'm using AlphabeticalOrderer from AlphabeticalOrderExample.cs. My test collection runs perfectly in alphabetical order as expected.
### Issue:

After failing test in the middle of the run it is meaningless to continue running ordered tests within same collection.
So my tests are chunks of the huge test, that is why I cannot avoid ordering those chunks.
### Example:

TestA
TestB (depends on TestA)
TestC (depends on TestB)
TestD...etc.

If TestB fails it is meaningless to run next tests in collection. I need to be able mark this collection as "Cancel Run on first fail"
### Analogy

This feature reminds me Visual Studio's "Cancel build on first error", which I can control. I would like to control this behaviour for Test Collection as well.

**Comment by bradwilson** [comment]
The only way to do precisely what you want is to use an extensibility point which adds this behavior. A generalized "stop running all test in a collection when one fails" doesn't make sense with the traditional definition of a test collection.

There are generalized requests for this feature already (#23, #24) that would stop running all tests (not just the tests in a single collection).

**Comment by DmitriySokhach** [comment]
Brad, thanks for prompt reply!
I've read about extensibility points and wonder if it will be sufficient to have custom **BeforeAfterTestAttribute** and in it's _override After_ perform cancelling the run.

Would you please point me on how do I tell framework to _cancel_ the run? (maybe some sort of special exception)
Or maybe detect that fail occurred and some way to _skip other methods_? (which is quite similar to me)

**Comment by bradwilson** [comment]
My first thought is: it's a custom test framework, which is not simple. (I'll keep thinking if there's something simpler.)

We have a [Observation Example](https://github.com/xunit/samples.xunit/tree/master/ObservationExample) which shows complete test framework extensibility. What I think I would do is reuse the existing framework infrastructure (specifically, the `XunitXxxRunner` classes), but override at specific points to help stop the run. For example, if you look at [TestCollectionRunner.RunTestClassesAsync](https://github.com/xunit/xunit/blob/2991566dc1f1303a040f0b2fa72f655e483bb96d/src/xunit.execution/Sdk/Frameworks/Runners/TestCollectionRunner.cs#L124-L136), you'll see that it simply runs each test class in order. You could replicate this behavior, but insert a check after each test class to see if the [RunSummary](https://github.com/xunit/xunit/blob/2991566dc1f1303a040f0b2fa72f655e483bb96d/src/xunit.core/Sdk/RunSummary.cs) has any failures, and stop running if so. You'll need to follow similar behavior down the execution stack (the collection runner [calls the test class runner](https://github.com/xunit/xunit/blob/2991566dc1f1303a040f0b2fa72f655e483bb96d/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunner.cs#L123-L124), which in turn [calls the test method runner](https://github.com/xunit/xunit/blob/2991566dc1f1303a040f0b2fa72f655e483bb96d/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestClassRunner.cs#L151-L152), and so on) because at each point, you'll want to be able to bail early to stop any further execution.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by pouladpld** [comment]
I also try to do the same. [Our tests](https://github.com/TelegramBots/telegram.bot/tree/develop/test/Telegram.Bot.Tests.Integ) have an assembly fixture and run sequentially.

Has anyone found a way to stop test execution completely upon first test case failure?

**Comment by bradwilson** [comment]
There is a new switch on the console runner and `dotnet xunit` (`-stoponfail`) which stops running after the first failure. The MSBuild runner has a similar property (`StopOnFail`).

**Comment by pouladpld** [comment]
@bradwilson Is there any way to call it using .NET Core CLI's run settings?
similar to:
```bash
$ dotnet test -- StopOnFail=true
```

**Comment by bradwilson** [comment]
No, there's no way to do that today. The RunSettings that we support are listed here (some of them are automatic settings from Visual Studio and not intended to be set by end users):

https://github.com/xunit/xunit/blob/1953782eac3d537fbf6826df7b62b308bf456567/src/xunit.runner.visualstudio/Utility/RunSettings.cs#L69-L98

**Comment by admin-simeon** [comment]
Is this ever going to be supported via dotnet test?

**Comment by svermeulen** [comment]
> Is this ever going to be supported via dotnet test?

Based on what is posted here:
https://github.com/xunit/xunit/issues/2133#issuecomment-674344404

It sounds like it will be supported in v3 at least

**Comment by PrimeHydra** [comment]
This would be great to have, as our CI builds will keep running after a test fails. It would save a lot of time (we have many tests) if we could fail the test run immediately.
