### ISSUE TITLE
vstest.console doesn't discover tests in UWP appx

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [xunit/xunit#863]
Hi, I've been facing an issue that can't step over:
when using UWP test project + xunit in VS it works like a charm. Tests are discovered and run successfully.
But when I try to do the same with vstest.console.exe targeting appx - it never discoveres tests, even though the appx application is started it always says 
**Warning: No test is available in *.appx. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.**

And at the same moment I do have logs like:
Information: [xUnit.net 00:00:07.9963796]   Starting:    WinRTXamlToolkit
Information: [xUnit.net 00:00:07.9992463]   Finished:    WinRTXamlToolkit
Information: [xUnit.net 00:00:08.0000109]   Starting:    xunit.abstractions
Information: [xUnit.net 00:00:08.0034515]   Finished:    xunit.abstractions

By the way, running TestWindow>vstest.console.exe /ListExecutors /ListDiscoverers /TestAdapterPath:"./Extensions" /UseVsixExtensions:true never shows any xunit related dlls,even if you put them there directly

**Comment by DerGary** [comment]
I currently have the same issue. MSTests are working with vstest.console.exe but I tried everything and I can't get xUnit to work. I want to run the tests through the Console because we want to execute them on the build server.

when I use this command:
```vstest.console.exe /TestAdapterPath:C:\vs_uwp_ws\BuildTestProject\App1\UnitTestProject1\bin\x86\Debug /ListExecutors```
 I get the following output:
```
Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Warning: The Test Executor Add-Ins installed through a VSIX installation are ignored. Use the /UseVsixExtensions parameter to include them, if your installation supports vsix extensions. Example: vstest.console.exe /ListExecutors /UseVsixExtensions:true

The following Test Execution Add-Ins are available:
Microsoft.VisualStudio.TestPlatform.Extensions.GenericTestAdapter.GenericTestExecutor
                Uri: executor://GenericTestAdapter/v1
Microsoft.VisualStudio.TestPlatform.Extensions.MSAppContainerAdapter.MSAppContainerTestExecutor
                Uri: executor://MSAppContainerTestAdapter/v1
Microsoft.VisualStudio.TestPlatform.Extensions.MSAppContainerAdapter.DummyUwpExecutor
                Uri: executor://uapexecutoridentifier/
Microsoft.VisualStudio.TestPlatform.Extensions.MSAppContainerAdapter.MSPhoneTestExecutor
                Uri: executor://MSWPTestAdapter/v1
Microsoft.VisualStudio.TestPlatform.Extensions.OrderedTestAdapter.OrderedTestExecutor
                Uri: executor://OrderedTestAdapter/v1
Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MSTestExecutor
                Uri: executor://MSTestAdapter/v1
Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension.TestExecutor
                Uri: executor://CppWPUnitTestExecutor/v1
Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension.TestExecutor
                Uri: executor://CppUnitTestExecutor/v1
Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension.DummyUWPCppTestExecutor
                Uri: executor://UAPCppExecutorIdentifier
Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner
                Uri: executor://xunit/VsTestRunner2
```
which means that vstest.console.exe finds the testexecutor, great.
Then I tried if it also finds the TestDiscoverer with the following Command:
```vstest.console.exe /TestAdapterPath:C:\vs_uwp_ws\BuildTestProject\App1\UnitTestProject1\bin\x86\Debug  /ListDiscoverers```
with the output:
```
Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Warning: The Test Discovery Add-Ins installed through a VSIX installation are ignored. Use the /UseVsixExtensions parameter to include them, if your installation supports vsix extensions. Example: vstest.console.exe /ListDiscoverers /UseVsixExtensions:true

The following Test Discovery Add-Ins are available:
Microsoft.VisualStudio.TestPlatform.Extensions.GenericTestAdapter.GenericTestDiscoverer
                Default Executor Uri: executor://generictestadapter/v1
                Supported File Types: .generictest
Microsoft.VisualStudio.TestPlatform.Extensions.MSAppContainerAdapter.MSAppContainerTestDiscoverer
                Default Executor Uri: executor://msappcontainertestadapter/v1
                Supported File Types: .appx, .dll, .exe
Microsoft.VisualStudio.TestPlatform.Extensions.MSAppContainerAdapter.MSPhoneTestDiscoverer
                Default Executor Uri: executor://mswptestadapter/v1
                Supported File Types: .xap, .appx, .dll, .exe
Microsoft.VisualStudio.TestPlatform.Extensions.OrderedTestAdapter.OrderedTestDiscoverer
                Default Executor Uri: executor://orderedtestadapter/v1
                Supported File Types: .orderedtest
Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MSTestDiscoverer
                Default Executor Uri: executor://mstestadapter/v1
                Supported File Types: .dll, .exe
Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension.TestDiscoverer
                Default Executor Uri: executor://cppwpunittestexecutor/v1
                Supported File Types: .dll
Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension.TestDiscoverer
                Default Executor Uri: executor://cppunittestexecutor/v1
                Supported File Types: .dll, .exe
Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner
                Default Executor Uri: executor://xunit/VsTestRunner2
                Supported File Types: .appx, .dll, .exe
```
Which means it also finds the discoverer which is also great.
But when I run the command to execute the tests:
```vstest.console.exe /TestAdapterPath:C:\vs_uwp_ws\BuildTestProject\App1\UnitTestProject1\bin\x86\Debug "C:\vs_uwp_ws\BuildTestProject\App1\UnitTestProject1\AppPackages\xUnitTestProject_1.0.6.0_x86_Debug_Test\xUnitTestProject_1.0.6.0_x86_Debug.appx" /InIsolation```
It produces the following output (the output is a bit long so I put it on pastebin):
http://pastebin.com/2HYZ0VSW

So its searching for tests in different Namespaces but the Namespace that my tests are in (UnitTestProject1) is not listed in the Output and therefore It doesn't found tests and ends with the Warning:
```Warning: No test is available in C:\vs_uwp_ws\BuildTestProject\App1\UnitTestProject1\AppPackages\xUnitTestProject_1.0.6.0_x86_Debug_Test\xUnitTestProject_1.0.6.0_x86_Debug.appx. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.```

I hope someone can help me I'm sitting here several days now and I'm trying to figure out why it is not working and I tried everything that I could think of.

Best Regards
Gary

**Comment by slycote** [comment]
Got same issue.  I need to make this work to be able to run tests on build server.  I did mostly all Gary did.  Does someone been able to make this work.

Regards

**Comment by tfarris07** [comment]
When running against an .appx VsTestRunner will not discover tests in an exe.  It only discovers tests in *.dll.

The problem is in xunit.runner.visualstudio.desktop\VsTestRunner.cs.  The method ITestExecutor.RunTests(IEnumerable<string> sources, IRunContext runContext, IFrameworkHandle frameworkHandle), searches the appx install path for only *.dll.  It also needs to search for *.exe.

Also, specifing /TestAdapterPath when invoking vstest.console.exe on an appx causes (or would cause once exe's are checked for tests) vstest.console.exe to use the desktop runner, which won't work with UWP.  Leaving /TestAdapterPath off will cause vstest.console.exe to use the UWP runner, which is included in the appx.

**Comment by onovotny** [comment]
This is a fundamental issue in the VSTest Platform. It tries to do discovery on the desktop, which simply doesn't work for xUnit. It "sort of" works in VS, but that's a huge hack there too and doesn't cover all cases.

I recommend using the Device Runner for UWP tests, but automating that in CI is difficult currently.

Really what needs to happen is that vstest does whatever "magic" it does - during execution to execute tests in an AppContainer - for Discovery as well. It's critical that discovery execute within the AppContainer as well.

MSTest isn't affected by this because that test framework is not extensible by users at runtime. Instead, they can do a reflection-only load to discover tests. xUnit cannot do that; it must execute code within the test project itself to properly discover tests.

/cc @codito

**Comment by tfarris07** [comment]
I understand the issue with the way Visual Studio is doing discovery with vstest.discoveryengine.exe and then executing vstest.executionengine.exe.  That's the reason that the project references the desktop runner, but the appx has the uwp runner.  That's not the bug.

The bug is that when an appx is passed in sources to ITestExecutor.RunTests(IEnumerable sources, IRunContext runContext, IFrameworkHandle frameworkHandle), that method opens the appx's installed location and only runs discovery on *.dll files.  VsTestRunner.cs lines 111-113 gathers only dlls.  If  *.exe files were added, then when that list of files that get passed to discovertests, tests in UWP unit tests (which are exe's) would be found.

**Comment by tfarris07** [comment]
Just to be clear, I'm not asking for this to be investigated.  It's a simple 3 line fix (on of which is white space).  I want this to be an accepted up for grabs up bug, so I can send this tiny change in pull request.  

It would make running UWP tests in CI so much easier.

[Here are the 3 lines I'm suggesting be added](https://github.com/tfarris07/visualstudio.xunit/commit/4f959da9a3bac852bfdca2b09fa961e203bcef79)

**Comment by bradwilson** [comment]
Closed for age.
