### ISSUE TITLE
Consider supporting netstandard

### ISSUE THREAD

**Issue by javiercn** [xunit/xunit#872]
Right now the libraries support "dotnet" as a platform. This forces people to trick nuget into restoring by using imports. Are there any plans to publish a netstandard version?

**Comment by javiercn** [comment]
Thanks! If you publish a CI build I will be happy to try it out.

**Comment by reisenberger** [comment]
@bradwilson We would also be keen to see this. See [Polly#132](https://github.com/App-vNext/Polly/issues/132): because dot-net-runners target only .NET Core at this time, not .NET Standard, we are in the position of providing a .NET Standard Polly library tested by a test assembly with a different tfm (.NET Core).

Appreciate also how much extra hoop-jumping the moving targets on .NET Core tooling are making us all do: this is a tough one.  Thanks for the great test framework!

**Comment by hughbe** [comment]
This is fixed right @bradwilson?

**Comment by bradwilson** [comment]
Closed for age.
