### ISSUE TITLE
'test-xunit' returned '-2147450749'.

### ISSUE THREAD

**Issue by hovsepm** [xunit/xunit#890]
Could someone give me a hint what could be wrong with my solution?

```
Discovering tests in 'Authorization\Authorization.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "Authorization\Authorization.Tests\project.json" --output "Authorization\Authorization.Tests\bin\Debug\netcoreapp1.0" --port 10701 --parentProcessId 10048 --no-build]
'test-xunit' returned '-2147450749'.
```

the error message is really useless. This happens after build in VS 2015 update 3 when I open Test Explorer window.

**Comment by praseetht** [comment]
@hovsepm I got a similar error message `'test-xunit' returned '-532462766'` (VS 2015 Update 2). 

Now when I opened command prompt and executed `dotnet test` it gave me a detailed error message 

> 
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Xunit.Runner.DotNet.Program.Run(String[] args)
   at Xunit.Runner.DotNet.Program.Main(String[] args)

To fix the error I added `Newtonsoft.Json": "8.0.3"` to `project.json` and then the error went away.

Btw, I'm using `"dotnet-test-xunit": "1.0.0-rc2-build10025"`

**Comment by bradwilson** [comment]
@hovsepm That error code is not one returned by us. You should take this issue up with one of the .NET teams at Microsoft.

**Comment by hovsepm** [comment]
@praseetht @bradwilson Thanks for info. Indeed doing `dotnet test` from the cmd provides more details. For me it is 
>The targeted framework { 'Microsoft.NETCore.App': '1.0.0' } was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0-rc2-3002702
  - Alternatively, install the framework version '1.0.0'.

This seems like a conflict between Windows/Ubuntu configuration.

**Comment by bradwilson** [comment]
No, it looks like your framework version # is wrong. It should be `1.0.0-rc2-3002702.`

See the suggested `project.json` from our [Getting Started with xUnit.net and .NET Core](http://xunit.github.io/docs/getting-started-dotnet-core.html#add-xunit-ref) documentation.

**Comment by hovsepm** [comment]
@bradwilson that what I mean by Windows/Ubuntu configuration issues. If I put `1.0.0-rc2-3002702` Ubuntu builds fail with
>Project HttpRecorder.Tests (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc2-3002702' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
  - Alternatively, install the framework version '1.0.0-rc2-3002702'.

**Comment by hovsepm** [comment]
@bradwilson https://github.com/dotnet/cli/issues/3657 FYI

**Comment by praseetht** [comment]
@bradwilson Do you think the VS tooling should display the detailed error message? As of now it's not very useful.

**Comment by hovsepm** [comment]
@praseetht +1 for better message in VS tooling.

**Comment by peterorjeff** [comment]
I'm getting a similar message: `'test-xunit' returned '-1073741819'.`
This only occurs once I've added the reference to the project I'd like to test.
If I remove the project I get a different error: `'test-xunit' returned '-532462766'.`

I don't get any additional info when running `dotnet test` from the command line, and I can't see anything useful in the Event Viewer.

My `project.json` is exactly what's suggested in the getting started guide with the addition of a dependency to my project.

Any ideas would be greatly appreciated.

**Comment by kidchenko** [comment]
I have the same problem, but when I updated xunit it worked! I am using: `"dotnet-test-xunit": "2.2.0-preview2-build1029"`, and `"xunit": "2.2.0-beta2-build3300"`

**Comment by fletchsod-developer** [comment]
Really!  That one doesn't work for me.  :-(  

The actual issue from what I can see with that `-2147450749` error code is the output never display the actual error of whatever packages or projects you're using.   If you go into powershell command prompt and run `dotnet test` or `dotnet build` or `dotnet run`, you can see the error message there.  For some reasons, it never bubbled up to Visual Studio output.

Attached is this few days ago GitHub solution for DotNetCore Cache.  Reason for this attached is due to changing code on GitHub, so we want the one that produce the bug here.

[Caching-dev.zip](https://github.com/xunit/xunit/files/556848/Caching-dev.zip)

Hope this help you to find the bug better & fix it.   I'm pretty much stuck on this GitHub solution.

**Comment by bradwilson** [comment]
Those negative return codes from the .NET CLI, rather than from the test runner (we only ever return positive return codes), so I'd start looking in that direction

**Comment by fletchsod-developer** [comment]
Can it returned the error messages from .NET Core CLI instead of negative codes?   I was thinking if test runner do that error messages instead of error codes then I think there'll be fewer GitHub issues tickets, as it could make developers look elsewhere.   Just a thought here.

**Comment by bradwilson** [comment]
@fletchsod-developer The error happens before we're even called, so we have no control over what's being displayed.

**Comment by ehsomma** [comment]
Adding the following dependency into the test projects on project.json fixed it for me:
"Microsoft.DotNet.InternalAbstractions": "1.0.1-beta-003206"
[Source](https://github.com/dotnet/cli/issues/3759)

**Comment by zchpit** [comment]
In my situation problem was in "Newtonsoft.Json" version. After fix i project.json I also needed to 
delete /bin and /obj folder worked.

**Comment by DanGSabin** [comment]
My problem was the same as the original issue mentioned at the top of this chain:  _**Discovering tests in ...'test-xunit' returned '-2147450749'.**_ .  As a result, no tests were appearing in the the Test Explorer panel (VS 2015 Update 3).  Weird thing was that the same apparent environment, same exact code and settings, worked fine on another development machine I used the day before, as well as on my other teammates' machines.   After lots of searching and troubleshooting, I discovered the fix for my problem buried at the bottom of this StackOverflow post:  https://stackoverflow.com/questions/38085430/the-library-hostpolicy-dll-was-not-found .   I only came across that post after following another suggestion to attempt running the test project(s) through the Developer Command Prompt (_dotnet test_), which resulted in a the error 'A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found'.   At the end of the day, adding the following to the test project's project.json file fixed my problem.

 **"runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.0.0"
    }
  },**

Other members of my development team do not seem to require this setting.  My guess is that is has something to do with the order in which I installed .NET Core runtime, SDK and VS 2015.  I was forced to install an older version of .NET Core SDK in order to match some of the preexisting settings for this project.
