### ISSUE TITLE
Unable to update xunit.abstractions

### ISSUE THREAD

**Issue by godrose** [xunit/xunit#968]
This is the error message that's displayed upon updating xunit.abstractions to 2.0.1 version:
Attempting to resolve dependencies for multiple packages.
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'xunit.abstractions 2.0.0'
Unable to resolve dependencies. 'xunit.abstractions 2.0.1' is not compatible with 'xunit.extensibility.core 2.1.0 constraint: xunit.abstractions (= 2.0.0)'.

**Comment by bradwilson** [comment]
You don't need this package. Please don't update it.

**Comment by bradwilson** [comment]
Dup #939

**Comment by GaTechThomas** [comment]
To quote #939 (since it is locked), "This behavior is by design. Complain to the @nuget team for creating a UI that encourages you to upgrade something that you didn't even ask for in the first place. ¯\_(ツ)_/¯".

That's nice and all, but it would be helpful to recognize that you're wasting the time of those of us who are stuck using NuGet and xUnit. 

I searched numerous times over the past few days to try to fix this. Only now did I find these comments in all the search result noise. It would be much appreciated if, when the xUnit team knows that it is making updates that will cause its consumers to have unexpected behavior, then the team document it SOMEWHERE.

Thank you.

**Comment by bradwilson** [comment]
There is *literally* nothing I can do about this. We're not doing anything wrong.

**Comment by nicka-cme** [comment]
@bradwilson  So if we do not need this package anymore what it the correct way capture output? According to the documentation here: https://xunit.github.io/docs/capturing-output.html using the ITestOutputHelper interface is the correct which I'm sure your are aware relies on the 'abstraction' package.
Thx

**Comment by bradwilson** [comment]
You get the dependency implicitly, not explicitly. That's why updating it on its own makes no sense.

It doubly makes no sense because the DLL is literally identically in 2.0.0 and 2.0.1; the only thing that has changed is the NuGet package, so that it supports the new `netstandard` target frameworks without needing any `imports` statements.
