### ISSUE TITLE
Fluent Assertion (Question, not Issue)

### ISSUE THREAD

**Issue by maroonedsia** [xunit/xunit#970]
Hi,

Sorry if I'm asking this in a wrong place, I didn't find a place to post a question to you.

Do you already have, or will you have a fluent assertion syntax for xUnit.net? I'm talking about something like this: https://lukewickstead.wordpress.com/2013/02/09/howto-nunit-fluent-assertions/ 

I believe this is a very nice feature, and since xUnit is the more modern framework, having this will make it even better. 

Thanks,
Cheers,
Sia

**Comment by bradwilson** [comment]
We do not intend to ship fluent assertions. There are third party libraries (like [Fluent Assertions](http://www.fluentassertions.com/)) which already support xUnit.net.

We keep our assertions in a separate NuGet package, so that people using third party libraries like FA do not need to include them. When installing NuGet packages, choose `xunit.core` rather than `xunit`, as the latter automatically includes the built-in assertion library.

**Comment by maroonedsia** [comment]
Wow, that’s very great! 

 

Thanks for the explanation.

 

Cheers,

Sia

**Comment by maroonedsia** [comment]
BTW, I’m not finding documentations on this important feature, here https://xunit.github.io/#documentation 

Maybe I’m missing it, but that would be really great to read about the custom assertion packages for xUnit.net.

 

Thanks again,

Sia

 

From: Siavash Mortazavi [mailto:smortazavi@hotmail.com] 
Sent: Monday, September 12, 2016 10:48 AM
To: 'xunit/xunit' <reply@reply.github.com>; 'xunit/xunit' <xunit@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [xunit/xunit] Fluent Assertion (Question, not Issue) (#970)

 

Wow, that’s very great! 

 

Thanks for the explanation.

 

Cheers,

Sia

**Comment by bradwilson** [comment]
Closed for age.
