### ISSUE TITLE
Unseal TestFrameworkAttribute

### ISSUE THREAD

**Issue by asgerhallas** [xunit/xunit#976]
Hi, 

would it be possible to unseal TestFrameworkAttribute, so that I could make a convinience attribute for users of my extension, like `UseTheoryWithInjectionInCtorAttribute : TestFrameworkAttribute` with no need to manually refer to the framework and assembly by string?

Or is there a reason for it being sealed? :)

**Comment by bradwilson** [comment]
We can't, because of the way our reflection abstraction works.

You'll find that almost all of our attributes are sealed, for this reason. We need to be able to find the test framework without being able to run any code associated with that attribute. We need to be able to look at the constructor arguments and know exactly what they mean (this is also why, if you look at the implementation, we don't actually do anything with the ctor arguments, because it's irrelevant).

You can implement `ITestFrameworkAttribute` instead, and decorate it with `TestFrameworkDiscovererAttribute`. Look at the existing classes ([TestFrameworkAttribute](https://github.com/xunit/xunit/blob/master/src/xunit.core/TestFrameworkAttribute.cs), [TestFrameworkTypeDiscoverer](https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/TestFrameworkTypeDiscoverer.cs)) for guidance on how to do this.

**Comment by asgerhallas** [comment]
Great, thank you, that just works! :)
