### ISSUE TITLE
dotnet-test-xunit only passes output to host for failures

### ISSUE THREAD

**Issue by citizenmatt** [xunit/xunit#986]
The `dotnet test` command line tool only shows output when a test fails. It's doing the same with the API for other test runners - only passing the output to the host if a test fail. It should always pass the output, and allow the host to decide what to do with it.

**Comment by niemyjski** [comment]
I agree, it would be great to see messages in real time as it makes for a great debugging experience.

**Comment by citizenmatt** [comment]
Real time messages require a change in the test API protocol. See dotnet/cli#4249.

**Comment by bradwilson** [comment]
To be clear: real-time messages are available in xUnit.net itself, just not in the protocol defined by `dotnet-test-xxx` in Visual Studio/.NET Core.

**Comment by sstublic** [comment]
@bradwilson Can you please clarify what's the final state for this now? I'm trying to get output messages to work when tests pass, but have been unsuccessful. 

Issues I'm having: you fixed this issue in "dotnet-test-xunit": "2.2.0-preview3-build1047", however I can't get any of my tests discovered with any build > "build1030", no matter which xunit version I try.

I can't figure out what broke the compatibility with what. I've also noticed that since "build1031" --designtime problem referenced in #934 is occurring.

Is it a problem with my lack of basic understanding how xUnit works in the VS/.NETCore environment or is there a specific problem causing this issue?

**Comment by bradwilson** [comment]
Preview 3 isn't public yet. If you want to try to use it, you must pull the package from MyGet, not NuGet.

https://www.myget.org/gallery/xunit

**Comment by sstublic** [comment]
@bradwilson Yes, I'm pulling from myget already...using this:
    "dotnet-test-xunit": "2.2.0-preview3-build1047",
    "xunit": "2.2.0-beta4-build3419"

No tests are discovered. If I move dotnet-test-xunit to 2.2.0-preview3-build1030,  everything works, even with xunit being the latest myget build.

**Comment by sstublic** [comment]
Ok, I've narrowed down the problem. It occurs when I target net451 framework in project.json.

When following getting started at https://xunit.github.io/docs/getting-started-dotnet-core.html, everything works if you target framework "netcoreapp1.0". If you do as is described in the second part of the page and target "net451", tests do NOT get discovered anymore if using dotnet-test-xunit build > build1030.

Simple example:

1. Create Class Library (.NET Core)
2. Use this project.json
  
  ```
{
   "version": "1.0.0-*",
  "testRunner": "xunit",
  "dependencies":
  {
    "xunit": "2.2.0-beta4-build3419",
    "dotnet-test-xunit": "2.2.0-preview3-build1031"
  },
  "frameworks":
  {
    "net451":
    {
      "dependencies":
      {
        "Microsoft.NETCore.Platforms": "1.0.1"
      }
    } 
  }
}
```
3. Add  a class1.cs with a [Test] method inside. 

**It won't get discovered**.

Lower dotnet-test-xunit to build1030 and everything works again.

Any build higher than 1030 (even the latest 1047) behaves the same.

If I run `dotnet test --list --designtime` from command line, builds above 1030 won't discover tests. That's why i mentioned #934 before.

Any help would be appreciated.

btw. to what module am I passing those --designtime --list parameters? I just stole them from other issue.

**Comment by bradwilson** [comment]
Is the problem limited to Visual Studio? (meaning, if you run `dotnet test` from the command line, does that work?)

**Comment by bradwilson** [comment]
> to what module am I passing those --designtime --list parameters? I just stole them from other issue.

https://github.com/xunit/dotnet-test-xunit/blob/4b9cc80571265c212e7788018c7299a9a11372e7/src/dotnet-test-xunit/CommandLine.cs#L297-L335

**Comment by sstublic** [comment]
> Is the problem limited to Visual Studio? (meaning, if you run dotnet test from the command line, does that work?)

It is not limited to Visual Studio from what I can gather. I described what happens from command line in a comment above.

**Comment by bradwilson** [comment]
Right, okay, that helps narrow it down.

**Comment by bradwilson** [comment]
Sorry, didn't mean to re-open this.

**Comment by sstublic** [comment]
I think this might help:

```
FlamingoLoyalty.Tests>dotnet test --list
Project FlamingoLoyalty.Tests (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
xUnit.net .NET CLI test runner (64-bit Desktop .NET win10-x64)
  Discovering: FlamingoLoyalty.Tests
FlamingoLoyalty.Tests.Class1.NowYouSeeMe
SUMMARY: Total: 1 targets, Passed: 1, Failed: 0.

FlamingoLoyalty.Tests>dotnet test --list --designtime
Project FlamingoLoyalty.Tests (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
xUnit.net .NET CLI test runner (64-bit Desktop .NET win10-x64)
  Discovering: FlamingoLoyalty.Tests
{"MessageType":"TestRunner.TestCompleted","Payload":null}
SUMMARY: Total: 1 targets, Passed: 1, Failed: 0.'
```

This was using build1047

**Comment by bradwilson** [comment]
Let's move any further conversation over to #934, since that's the actual bug in question. :)
