### ISSUE TITLE
InvalidOperationException thrown in string.Join running MemberData tests

### ISSUE THREAD

**Issue by hughbe** [xunit/xunit#987]
The following throws an `InvalidOperationException` when running tests, with the stack trace attached
![stacktrace](https://cloud.githubusercontent.com/assets/1275900/18843304/193c3f1c-8410-11e6-8267-ca46b9647454.png)

```
using System.Json;
public static IEnumerable<object[]> TestData()
{
    yield return new object[] { new JsonValue[] { new JsonPrimitive(true) } };
}

[Theory]
[MemberData(nameof(TestData))]
public void Test(JsonValue[] items)
{
    JsonArray array = new JsonArray(items);
}
```

This is a bug in xunit I think, as the error doesn't seem to be coming from my code - there is no mention of `string.Join` anywhere.
The reason why an `InvalidOperationException` is thrown is that `JsonValue` throws this exception when `GetEnumerator` is called.

/cc @stephentoub  FYI

**Comment by bradwilson** [comment]
Are you sure about that? The very top of the stack trace is your code (`JsonValue.cs`).

**Comment by hughbe** [comment]
Right, the exception is thrown from the `GetEnumerator` method in `JsonValue.cs`.

But my issue is that this code is being called from `xunit`, specifically some kind of `string.Join` call

**Comment by bradwilson** [comment]
Can you point to the implementation of `JsonValue`?

**Comment by hughbe** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Json/src/System/Json/JsonValue.cs

**Comment by bradwilson** [comment]
Curious: Why are you implementing `IEnumerable`, only to throw `InvalidOperationException`?

**Comment by stephentoub** [comment]
> But my issue is that this code is being called from xunit, specifically some kind of string.Join call

Presumably this is by design, and xunit is attempting to serialize any IEnumerable as part of the name of a theory?  It might be nice if it caught exceptions from enumeration and ignored them, assuming this is part of name generation or something similarly non-fatal.  That said, this doesn't seem like a bug to me.

> Curious: Why are you implementing IEnumerable, only to throw InvalidOperationException?

I ported this code, and I'm wondering the same thing ;)  I need to go dig up an old copy of the Silverlight library to see what it was doing here.  This is a straight port of Mono's implementation, which we brought to corefx for compat with code that's using it there.

**Comment by hughbe** [comment]
It's probs not a bug, I was incorrect in identifying it as such. I just wanted to identify this as a limitation. I agree that catching the IOE would be nice but not essentiab
